receivers:
  otlp:
    protocols:
      http:
        endpoint: 127.0.0.1:15418
        max_request_body_size: 1048576
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64
  batch:
    timeout: 1s
    send_batch_size: 128
    send_batch_max_size: 256
exporters:
  otlphttp/jaeger:
    endpoint: http://127.0.0.1:15419
    timeout: 2s
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 128
    retry_on_failure:
      initial_interval: 1s
      max_interval: 5s
      max_elapsed_time: 30s
  prometheus:
    endpoint: 127.0.0.1:15464
    metric_expiration: 2m
    translation_strategy: UnderscoreEscapingWithSuffixes
    without_scope_info: true
extensions:
  health_check:
    endpoint: 127.0.0.1:15333
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
  telemetry:
    logs:
      level: warn
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 127.0.0.1
                port: 15888
