import type {S3Client} from "bun";
import {existsSync,lstatSync,mkdirSync,readFileSync,realpathSync,renameSync,rmSync,writeFileSync} from "node:fs";
import {dirname,resolve,sep} from "node:path";
import {audioPcmHash} from "../../generator/src/audio-delivery";
import {inspectSoundWav,verifySoundWav} from "../../generator/src/sound-audio";
import {MAX_SOUND_UPLOAD_BYTES,soundAssetKey,soundAssetObjectKey,soundFail,validateSoundAsset,type SoundAsset} from "../../planner/src/sound-assets";
export async function boundedSoundBody(stream:ReadableStream<Uint8Array>|null,limit:number,signal:AbortSignal):Promise<Buffer>{const reader=stream?.getReader();if(!reader)soundFail("Choose a WAV recording.");const parts:Uint8Array[]=[];let bytes=0;const abort=()=>{void reader.cancel().catch(()=>{});};signal.addEventListener("abort",abort,{once:true});try{for(;;){signal.throwIfAborted();const next=await reader.read();signal.throwIfAborted();if(next.done)break;bytes+=next.value.length;if(bytes>limit)soundFail("The sound recording exceeds its allowed size.");parts.push(next.value);}}finally{signal.removeEventListener("abort",abort);await reader.cancel().catch(()=>{});reader.releaseLock();}return Buffer.concat(parts);}
export async function soundUploadBody(request:Request):Promise<Buffer>{if(Number(request.headers.get("content-length"))>MAX_SOUND_UPLOAD_BYTES)soundFail("Choose a WAV recording up to 128 MiB.");return boundedSoundBody(request.body,MAX_SOUND_UPLOAD_BYTES,AbortSignal.any([request.signal,AbortSignal.timeout(60000)]));}
/** Immutable original and normalized recordings are scoped to their owning project. */
export class SoundBlobStore {
  private root:string;
  constructor(root:string,private client?:S3Client){mkdirSync(root,{recursive:true});this.root=realpathSync(root);}
  private path(asset:SoundAsset,kind:"original"|"audio"):string{const path=resolve(this.root,soundAssetKey(asset,kind));if(!path.startsWith(this.root+sep))soundFail("Sound media escaped its workspace.");return path;}
  private verify(asset:SoundAsset,kind:"original"|"audio",bytes:Buffer):void{validateSoundAsset(asset,asset.projectId);if(bytes.length!==asset[kind].bytes||audioPcmHash(bytes)!==asset[kind].sha256)soundFail("The sound recording failed checksum verification.");if(kind==="audio")verifySoundWav(bytes,asset.audio.frames,asset.audio.sha256);else{const m=inspectSoundWav(bytes);for(const key of ["sampleRate","channels","frames","encoding"] as const)if(m[key]!==asset.original[key])soundFail("The original recording format changed.");}}
  async put(asset:SoundAsset,kind:"original"|"audio",bytes:Buffer):Promise<void>{this.verify(asset,kind,bytes);if(this.client){await this.client.file(soundAssetObjectKey(asset,kind)).write(bytes,{type:"audio/wav",partSize:8*1024**2,queueSize:2});await this.read(asset,kind);return;}const path=this.path(asset,kind);mkdirSync(dirname(path),{recursive:true});if(!realpathSync(dirname(path)).startsWith(this.root+sep))soundFail("Sound media escaped its workspace.");if(existsSync(path)){await this.read(asset,kind);return;}const pending=path+"."+crypto.randomUUID()+".pending";writeFileSync(pending,bytes,{flag:"wx",mode:0o600});try{renameSync(pending,path);}finally{if(existsSync(pending))rmSync(pending);}}
  async read(asset:SoundAsset,kind:"original"|"audio"):Promise<Buffer>{validateSoundAsset(asset,asset.projectId);let bytes:Buffer;if(this.client)bytes=await boundedSoundBody(this.client.file(soundAssetObjectKey(asset,kind)).stream(),asset[kind].bytes,AbortSignal.timeout(60000));else{const path=this.path(asset,kind),stat=lstatSync(path);if(stat.isSymbolicLink()||!stat.isFile()||stat.size!==asset[kind].bytes||!realpathSync(path).startsWith(this.root+sep))soundFail("The sound recording is not a valid owned file.");bytes=readFileSync(path);}this.verify(asset,kind,bytes);return bytes;}
}
