import {afterAll,beforeAll,expect,test} from "bun:test";
import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {StudioDatabase} from "../src/database";
import {PostgresJobStore} from "../src/jobs";
import {PostgresAudioLedger,type AudioInvoice} from "../src/audio-ledger";
import {PostgresCostLedger} from "../src/ledger";
import {PostgresReviewQueue} from "../src/reviews";
import {PostgresRetention} from "../src/retention";
import {PostgresArtifactStore,objectClient} from "../src/artifacts";
import {exportStateSnapshot,importStateSnapshot} from "../src/snapshots";
import {createApiServer,type ApiServer} from "../../api/src/server";
import {processNextJob} from "../../queue/src/worker";
import {LeaseError} from "../../queue/src/index";
import {CartesiaAudioProvider} from "../../generator/src/cartesia-audio";
import {contentHash} from "../../generator/src/capabilities";
import {verifyAudioMedia} from "../../generator/src/audio-media";
import {CAST_INPUT} from "../../../test/fixtures/casting";
import {AUDIO_POLICY,AUDIO_PCM,audioSse,audioIntent} from "../../../test/fixtures/audio";
const enabled=Boolean(process.env.HV_PG_ADMIN_URL&&process.env.HV_API_DATABASE_URL&&process.env.HV_WORKER_DATABASE_URL&&process.env.HV_S3_ENDPOINT&&process.env.HV_S3_FLEET_TEST_BUCKET),pgtest=enabled?test:test.skip;
let admin:StudioDatabase,worker:StudioDatabase,restored:StudioDatabase,server:ApiServer,root:string,wire:ReturnType<typeof Bun.serve>,calls=0,provider:CartesiaAudioProvider;
const ids:string[]=[],objectKeys=new Set<string>(),name="hv_audio_test_"+crypto.randomUUID().replaceAll("-",""),policies=[AUDIO_POLICY],oldSecret=process.env.HV_TOKEN_SECRET;
const replica=()=>objectClient({...process.env,HV_S3_BUCKET:process.env.HV_S3_FLEET_TEST_BUCKET});
beforeAll(async()=>{if(!enabled)return;
  process.env.HV_TOKEN_SECRET="audio-pg-fixture-secret-at-least-thirty-two-characters";root=mkdtempSync(join(tmpdir(),"hv-audio-pg-"));
  admin=new StudioDatabase(process.env.HV_PG_ADMIN_URL!);worker=new StudioDatabase(process.env.HV_WORKER_DATABASE_URL!);await admin.migrate();
  await admin.sql.unsafe('CREATE DATABASE "'+name+'"');const url=new URL(process.env.HV_PG_ADMIN_URL!);url.pathname="/"+name;restored=new StudioDatabase(url.href);await restored.migrate();
  server=createApiServer({port:0,hostname:"127.0.0.1",storage:"postgres",artifactStorage:"s3",databaseUrl:process.env.HV_API_DATABASE_URL,artifactRoot:join(root,"api"),audioPolicies:()=>policies,rateLimit:{api:{limit:10000,windowMs:60000}}});
  wire=Bun.serve({port:0,hostname:"127.0.0.1",async fetch(request){calls++;const body=await request.json() as any;return audioSse(body.context_id);}});
  provider=new CartesiaAudioProvider({apiKey:"fixture-not-a-real-key",fetchImpl:(async(_url,init)=>fetch(wire.url,init)) as typeof fetch});
});
afterAll(async()=>{if(!enabled)return;await server?.stop(true);await wire?.stop(true);
  for(const id of ids){for(const row of await admin.sql`select object_key from hv_artifacts where project_id=${id}`)objectKeys.add(row.object_key);
    await admin.sql`delete from hv_reservations where job_id in (select job_id from hv_provider_attempts where project_id=${id} union select id from hv_jobs where project_id=${id})`;
    for(const table of ["hv_cost_events","hv_provider_attempts","hv_outbox","hv_operator_reviews","hv_artifacts","hv_jobs","hv_reviews"])await admin.sql.unsafe("delete from "+table+" where project_id=$1",[id]);await admin.sql`delete from hv_projects where id=${id}`;}
  for(const key of objectKeys){await objectClient().file(key).delete();await replica().file(key).delete();}
  await worker?.close();await restored?.close();if(!/^hv_audio_test_[a-f0-9]{32}$/.test(name))throw new Error("Unexpected fixture database");await admin.sql.unsafe('DROP DATABASE "'+name+'"');await admin.close();rmSync(root,{recursive:true,force:true});
  if(oldSecret===undefined)delete process.env.HV_TOKEN_SECRET;else process.env.HV_TOKEN_SECRET=oldSecret;
});
const call=(path:string,method="GET",body?:unknown,token?:string)=>fetch(new URL(path,server.url),{method,headers:{"content-type":"application/json",...(token?{authorization:"Bearer "+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
async function owner(){
  const owner=await(await call("/api/projects","POST")).json() as any;ids.push(owner.projectId);const base="/api/projects/"+owner.projectId,actorId=crypto.randomUUID(),character={...CAST_INPUT,name:"Marla",aliases:[]};
  await call(base+"/script","PUT",{text:"INT. GARDEN - DAY\n\nMarla waves.\n\nMARLA\nHello."},owner.token);await call(base+"/rights","POST",{attested:true},owner.token);
  expect((await call(base+"/cast/"+actorId,"PUT",{character,expectedVersion:0},owner.token)).status).toBe(200);
  const quote=await(await call(base+"/audio-takes","GET",undefined,owner.token)).json() as any;expect(quote.enabled).toBe(true);
  const body={idempotencyKey:"audition",generationApproved:true,sceneIndex:0,lineIndex:0,sourceHash:quote.lines[0].source.hash,characterId:actorId,voiceId:AUDIO_POLICY.voiceId,policyRevision:AUDIO_POLICY.revision,controls:{emotion:"calm"},beforeMs:250,afterMs:500};
  return {...owner,base,actorId,character,body};
}
const invoice=(attempts:{attemptId:string;usd:number}[],documentSha256="a".repeat(64)):AudioInvoice=>{
  const data={schema:"hv-audio-invoice-allocation/1" as const,documentSha256,accountRevision:AUDIO_POLICY.accountRevision,totalUsd:Number(attempts.reduce((n,a)=>n+a.usd,0).toFixed(6)),allocations:attempts,at:new Date().toISOString()};return {...data,revision:contentHash(data)};
};
pgtest("one RLS admission and provider dispatch survive S3 worker recovery, archive restore and invoice settlement",async()=>{
  const o=await owner(),path=o.base+"/audio-takes",ledger=new PostgresAudioLedger(worker),operator=new PostgresAudioLedger(admin),first=new PostgresJobStore(worker),next=new PostgresJobStore(worker),cacheA=join(root,"first"),cacheB=join(root,"next"),artifactsA=new PostgresArtifactStore(worker,cacheA),artifactsB=new PostgresArtifactStore(worker,cacheB),policy=(id:string)=>policies.find(p=>p.voiceId===id);
  const context={ledger,reviewQueue:new PostgresReviewQueue(worker),audio:{provider,ledger,policy}};
  const admitted=await Promise.all(Array.from({length:2},async()=>{const response=await call(path,"POST",o.body,o.token);expect(await response.clone().text()).not.toContain('"error"');expect(response.status).toBe(202);return await response.json() as any;}));expect(new Set(admitted.map(j=>j.jobId)).size).toBe(1);
  expect((await call(path,"POST",{...o.body,controls:{emotion:"angry"}},o.token)).status).toBe(409);
  expect((await call(path,"POST",{...o.body,idempotencyKey:"stale",sourceHash:"f".repeat(64)},o.token)).status).toBe(409);
  expect((await call(path,"POST",{...o.body,idempotencyKey:"forged",policy:AUDIO_POLICY},o.token)).status).toBe(400);
  const checkpoint=artifactsA.checkpointAudio.bind(artifactsA);artifactsA.checkpointAudio=async(...args)=>{await checkpoint(...args);throw new LeaseError(args[0].id,"lease_expired",args[1]);};
  const before=calls,partial=(await processNextJob(first,cacheA,{...context,artifacts:artifactsA,workerId:"interrupted"}))!;artifactsA.checkpointAudio=checkpoint;
  expect(partial.failureReason??partial.cancelReason).toBeUndefined();expect(partial.status).toBe("running");expect(partial.audioCheckpoint).toBeTruthy();expect(calls-before).toBe(1);
  const done=(await processNextJob(next,cacheB,{...context,artifacts:artifactsB,workerId:"resumed",now:()=>Date.now()+600000}))!;
  expect(done.failureReason??done.cancelReason).toBeUndefined();expect(done.status).toBe("done");expect(done.audioOutput).toEqual(partial.audioCheckpoint);expect(calls-before).toBe(1);
  await expect(first.completeAudio(done.id,"interrupted",done.audioOutput!)).rejects.toThrow("fence_changed");
  const attempt=(await ledger.audioAttempt(done.id))!;expect(attempt.status).toBe("unknown");expect(attempt.actualUsd).toBeNull();expect((await admin.sql`select remaining_usd from hv_reservations where job_id=${done.id}`)[0].remaining_usd).toBe("0.250000");
  await expect(new PostgresCostLedger(worker).finishAttempt(attempt.id,"succeeded")).rejects.toThrow("Audio");
  await expect(ledger.recordForJob({projectId:o.projectId,jobId:done.id,at:new Date().toISOString(),shotId:"audio-line",provider:"cartesia",model:attempt.audio.intent.model,total_cost_usd:0,prompt_tokens:0,output_frames:0,gpu_seconds:0})).rejects.toThrow("invoice");
  const view=await(await call("/api/jobs/"+done.id,"GET",undefined,o.token)).json() as any;expect(view.audioBilling.actualUsd).toBeNull();expect(JSON.stringify(view)).not.toContain("licenceEvidenceSha256");
  const wav=await fetch(new URL(view.output.audioUrl,server.url)),bytes=Buffer.from(await wav.arrayBuffer());expect(wav.status).toBe(200);expect(bytes.readUInt32LE(24)).toBe(48000);expect(bytes.subarray(44+12000*2,44+60000*2)).toEqual(AUDIO_PCM);
  const foreign=await owner();expect((await call("/api/jobs/"+done.id,"GET",undefined,foreign.token)).status).toBe(404);
  const snapshot=await exportStateSnapshot(admin,o.projectId);expect(snapshot.ledger.audioAttempts?.[0]?.actualUsd).toBeNull();await importStateSnapshot(restored,snapshot,.1);
  const restoredLedger=new PostgresAudioLedger(restored);expect(await restoredLedger.reservedUsd()).toBe(.25);await expect(restoredLedger.reserve(crypto.randomUUID(),"audio-take",.01,.1)).rejects.toThrow("capacity");
  await artifactsB.restoreCheckpoint(done);verifyAudioMedia(done,done.audioOutput!,cacheB);
  const copied=new PostgresArtifactStore(restored,cacheB,replica());await copied.importCompletedJob(done,done.audioOutput!.files.map(f=>join(cacheB,f.path)));
  const downloaded=new PostgresArtifactStore(restored,join(root,"archive-reader"),replica());await downloaded.restoreCheckpoint(done);verifyAudioMedia(done,done.audioOutput!,join(root,"archive-reader"));
  for(const row of await restored.sql`select object_key from hv_artifacts where project_id=${o.projectId}`)objectKeys.add(row.object_key);
  const bill=invoice([{attemptId:attempt.id,usd:.12}]);await expect(ledger.settleAudioInvoice(bill)).rejects.toThrow("operator database role");
  await Promise.all([operator.settleAudioInvoice(bill),operator.settleAudioInvoice(bill)]);await restoredLedger.settleAudioInvoice(bill);
  expect((await operator.audioAttempt(done.id))!.actualUsd).toBe(.12);expect(await restoredLedger.reservedUsd()).toBe(0);expect(await admin.sql`select id from hv_reservations where job_id=${done.id}`).toHaveLength(0);
  expect(await admin.sql`select id from hv_cost_events where job_id=${done.id}`).toHaveLength(1);
  await expect(operator.settleAudioInvoice(invoice([{attemptId:attempt.id,usd:.13}]))).rejects.toThrow("different");
  const settled=await exportStateSnapshot(admin,o.projectId);expect(settled.ledger.events[0]!.total_cost_usd).toBe(.12);expect(JSON.stringify(settled.ledger)).not.toContain('"allocations"');
  expect((await call(o.base+"/cast/"+o.actorId,"PUT",{expectedVersion:1,character:{...o.character,permission:{...o.character.permission,status:"revoked"}}},o.token)).status).toBe(200);
  expect((await fetch(new URL(view.output.audioUrl,server.url))).status).toBe(404);
},60000);
pgtest("a crash after intent never redispatches; late outcomes and scoped invoice receipts survive content purge",async()=>{
  const o=await owner(),other=await owner(),ledger=new PostgresAudioLedger(worker),operator=new PostgresAudioLedger(admin),store=new PostgresJobStore(worker),next=new PostgresJobStore(worker),policy=()=>AUDIO_POLICY;
  expect((await call(o.base+"/audio-takes","POST",o.body,o.token)).status).toBe(202);
  const job=(await store.claimNext(Date.now(),{},{workerId:"original"}))!,intent=audioIntent(job.audioTake!.line),journal=ledger.journal(job,"original",policy),held=await journal.authorize(intent,job.audioTake!.line);
  await expect(journal.authorize(audioIntent(job.audioTake!.line),job.audioTake!.line)).rejects.toThrow("already dispatched");
  const before=calls,failed=(await processNextJob(next,join(root,"ambiguous"),{ledger,reviewQueue:new PostgresReviewQueue(worker),audio:{provider,ledger,policy},artifacts:new PostgresArtifactStore(worker,join(root,"ambiguous")),workerId:"recovery",now:()=>Date.now()+600000}))!;
  expect(failed.status).toBe("failed");expect(failed.failureReason).toContain("already dispatched");expect(calls).toBe(before);
  expect((await ledger.audioAttempt(job.id))!.actualUsd).toBeNull();expect((await exportStateSnapshot(admin,o.projectId)).ledger.reservations).toHaveLength(1);
  await admin.sql`update hv_projects set taken_down_at=now() where id=${o.projectId}`;expect(await new PostgresRetention(admin).purgeProject(o.projectId)).toBe(true);
  await journal.recordOutcome({schema:"hv-audio-attempt-outcome/1",intent,reservation:held,dispatched:true,providerState:"unconfirmed",deliveryState:"withheld",httpStatus:null,providerRequestId:null,billing:{state:"unreconciled",actualUsd:null},deliveryRevision:null});
  expect((await ledger.audioAttempt(job.id))!.audio.outcome!.billing.actualUsd).toBeNull();
  expect((await call(other.base+"/audio-takes","POST",other.body,other.token)).status).toBe(202);
  const otherJob=(await store.claimNext(Date.now(),{},{workerId:"other"}))!,otherIntent=audioIntent(otherJob.audioTake!.line);
  await ledger.journal(otherJob,"other",policy).authorize(otherIntent,otherJob.audioTake!.line);await store.fail(otherJob.id,"other","fixture dispatch interrupted");
  const bill=invoice([{attemptId:intent.attemptId,usd:.09},{attemptId:otherIntent.attemptId,usd:.11}],"b".repeat(64));await operator.settleAudioInvoice(bill);await ledger.release(otherJob.id);
  expect((await operator.audioAttempt(job.id))!.actualUsd).toBe(.09);expect(await admin.sql`select id from hv_reservations where job_id=${job.id}`).toHaveLength(0);
  const scoped=await exportStateSnapshot(admin,other.projectId);expect(JSON.stringify(scoped)).not.toContain(intent.attemptId);expect(scoped.ledger.events[0]!.total_cost_usd).toBe(.11);
  await expect(operator.settleAudioInvoice({...bill,accountRevision:"f".repeat(64)})).rejects.toThrow();
},60000);
