import {afterAll,beforeAll,expect,test} from "bun:test";
import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {StudioDatabase} from "../src/database";
import {PostgresJobStore} from "../src/jobs";
import {PostgresCostLedger} from "../src/ledger";
import {PostgresReviewQueue} from "../src/reviews";
import {PostgresArtifactStore,objectClient} from "../src/artifacts";
import {createApiServer,type ApiServer} from "../../api/src/server";
import {processNextJob} from "../../queue/src/worker";
import {LeaseError} from "../../queue/src/index";
import {CAST_INPUT} from "../../../test/fixtures/casting";
const enabled=Boolean(process.env.HV_PG_ADMIN_URL&&process.env.HV_API_DATABASE_URL&&process.env.HV_WORKER_DATABASE_URL&&process.env.HV_S3_ENDPOINT),pgtest=enabled?test:test.skip;
const envKeys=["HV_TOKEN_SECRET","HV_NARRATION","HV_ANIMATIC_CAPTIONS","HV_ANIMATIC_PROVIDER_POOL"],old=Object.fromEntries(envKeys.map(k=>[k,process.env[k]]));
let admin:StudioDatabase,worker:StudioDatabase,root:string,server:ApiServer;const ids:string[]=[];
beforeAll(async()=>{if(!enabled)return;Object.assign(process.env,{HV_TOKEN_SECRET:"postgres-dialogue-test-at-least-thirty-two-characters",HV_NARRATION:"1",HV_ANIMATIC_CAPTIONS:"0",HV_ANIMATIC_PROVIDER_POOL:'["mock"]'});
  root=mkdtempSync(join(tmpdir(),"hv-dialogue-pg-"));admin=new StudioDatabase(process.env.HV_PG_ADMIN_URL!);worker=new StudioDatabase(process.env.HV_WORKER_DATABASE_URL!);await admin.migrate();
  server=createApiServer({port:0,hostname:"127.0.0.1",storage:"postgres",artifactStorage:"s3",databaseUrl:process.env.HV_API_DATABASE_URL,artifactRoot:join(root,"api"),rateLimit:{api:{limit:10000,windowMs:60000}}});
});
afterAll(async()=>{if(!enabled)return;await server?.stop(true);
  for(const id of ids){for(const row of await admin.sql`select object_key from hv_artifacts where project_id=${id}`)await objectClient().file(row.object_key).delete();
    await admin.sql`delete from hv_reservations where job_id in (select id from hv_jobs where project_id=${id})`;
    for(const table of ["hv_cost_events","hv_provider_attempts","hv_outbox","hv_operator_reviews","hv_artifacts","hv_jobs","hv_reviews"])await admin.sql.unsafe("delete from "+table+" where project_id=$1",[id]);await admin.sql`delete from hv_projects where id=${id}`;}
  await worker?.close();await admin?.close();rmSync(root,{recursive:true,force:true});for(const [key,value]of Object.entries(old)){if(value===undefined)delete process.env[key];else process.env[key]=value;}
});
const call=(path:string,method="GET",body?:unknown,token?:string)=>fetch(new URL(path,server.url),{method,headers:{"content-type":"application/json",...(token?{authorization:"Bearer "+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
pgtest("RLS dialogue admission is atomic; another worker resumes S3 media with exact PCM and rejects an obsolete fence",async()=>{
  const owner=await(await call("/api/projects","POST")).json() as any;ids.push(owner.projectId);const base="/api/projects/"+owner.projectId;
  await call(base+"/script","PUT",{text:"INT. GARDEN - DAY\n\nMarla welcomes Kevin.\n\nMARLA\nWelcome to the garden.\n\nKEVIN\nThank you."},owner.token);await call(base+"/rights","POST",{attested:true},owner.token);
  const actorId=crypto.randomUUID(),character={...CAST_INPUT,name:"Marla",aliases:[],voice:{rateWpm:110,voice:"en-us+f3"}};
  expect((await call(base+"/cast/"+actorId,"PUT",{character,expectedVersion:0},owner.token)).status).toBe(200);
  const first=new PostgresJobStore(worker),next=new PostgresJobStore(worker),cacheA=join(root,"first"),cacheB=join(root,"next"),artifactsA=new PostgresArtifactStore(worker,cacheA),artifactsB=new PostgresArtifactStore(worker,cacheB);
  const ledger=new PostgresCostLedger(worker),context={ledger,reviewQueue:new PostgresReviewQueue(worker)};
  expect((await call(base+"/jobs","POST",{idempotencyKey:"source"},owner.token)).status).toBe(202);
  const source=(await processNextJob(first,cacheA,{...context,artifacts:artifactsA,workerId:"source"}))!;expect(source.failureReason??source.cancelReason).toBeUndefined();expect(source.status).toBe("done");
  const path=base+"/dialogue/"+source.id,quote=await(await call(path,"GET",undefined,owner.token)).json() as any;expect(quote.error).toBeUndefined();
  const body={idempotencyKey:"replacement",generationApproved:true,sourceRevision:quote.sourceRevision,sourceFilesRevision:quote.sourceFilesRevision,engineVersion:quote.engineVersion,edits:[{shotId:quote.lines[0].shotId,index:0,sourceHash:quote.lines[0].sourceHash,text:"Welcome home.",voice:{...quote.lines[0].voice,rateWpm:250}}]};
  const admitted=await Promise.all(Array.from({length:2},async()=>{const response=await call(path,"POST",body,owner.token);expect(await response.clone().text()).not.toContain('"error"');expect(response.status).toBe(202);return await response.json() as any;}));expect(new Set(admitted.map(j=>j.jobId)).size).toBe(1);
  const checkpoint=artifactsA.checkpointDialogue.bind(artifactsA);artifactsA.checkpointDialogue=async(...args)=>{await checkpoint(...args);throw new LeaseError(args[0].id,"lease_expired",args[1]);};
  const partial=(await processNextJob(first,cacheA,{...context,artifacts:artifactsA,workerId:"interrupted"}))!;artifactsA.checkpointDialogue=checkpoint;expect(partial.status).toBe("running");expect(partial.dialogueCheckpoint).toBeTruthy();
  const rows=await admin.sql`select body from hv_reservations where job_id=${partial.id}`;expect(rows[0].body.amountUsd).toBe(0);
  const done=(await processNextJob(next,cacheB,{...context,artifacts:artifactsB,workerId:"replacement",now:()=>Date.now()+600000}))!;
  expect(done.failureReason??done.cancelReason).toBeUndefined();expect(done.status).toBe("done");expect(done.output).toEqual(partial.dialogueCheckpoint);expect(done.resumedCount).toBe(1);
  await expect(first.complete(done.id,"interrupted",done.output!)).rejects.toThrow("fence_changed");
  expect(await admin.sql`select id from hv_provider_attempts where job_id=${done.id}`).toHaveLength(0);expect(await admin.sql`select id from hv_cost_events where job_id=${done.id}`).toHaveLength(0);
  const view=await(await call("/api/jobs/"+done.id,"GET",undefined,owner.token)).json() as any,wav=await fetch(new URL(view.output.audioUrl,server.url));expect(wav.status).toBe(200);expect((await wav.arrayBuffer()).byteLength).toBe(44+done.output!.dialogue!.report.totalSamples*2);
  const foreign=await(await call("/api/projects","POST")).json() as any;ids.push(foreign.projectId);expect((await call("/api/jobs/"+done.id,"GET",undefined,foreign.token)).status).toBe(404);
  expect((await call(path,"POST",{...body,idempotencyKey:"revoked"},owner.token)).status).toBe(202);
  expect((await call(base+"/cast/"+actorId,"PUT",{expectedVersion:1,character:{...character,permission:{...character.permission,status:"revoked"}}},owner.token)).status).toBe(200);
  const revoked=(await processNextJob(next,cacheB,{...context,artifacts:artifactsB,workerId:"revoked"}))!;expect(revoked.status).toBe("failed");expect(revoked.failureKind).toBe("policy_refusal");expect(revoked.output).toBeUndefined();
},60000);
