import {expect,test,spyOn} from "bun:test";
import {existsSync,mkdirSync,mkdtempSync,readFileSync,readdirSync,realpathSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join,sep} from "node:path";
import {dubStudio} from "../../../test/fixtures/dub-studio";
import {StudioDatabase} from "../src/database";
import {PostgresProjectService} from "../src/projects";
import {PostgresJobStore} from "../src/jobs";
import {PostgresCostLedger} from "../src/ledger";
import {PostgresReviewQueue} from "../src/reviews";
import {PostgresArtifactStore,objectClient} from "../src/artifacts";
import {exportProjectArchive,importProjectArchive} from "../src/archives";
import {exportStateSnapshot,importStateSnapshot,readStateSnapshot,validateSnapshot,type StateSnapshot} from "../src/snapshots";
import type {PersistedProject} from "../../api/src/index";
import {DeterministicMockProvider,type VideoClip} from "../../generator/src/index";
import {contentHash} from "../../generator/src/capabilities";
import {inspectEditSource} from "../../generator/src/edit-source-media";
import {bindOriginalEditSource} from "../../planner/src/edit-jobs";
import {deriveEditAssemblyParent} from "../../planner/src/edit-assembly-parent";
import {compileEditScriptSource} from "../../planner/src/edit-script-source";
import {projectEditScriptNavigation} from "../../planner/src/edit-script-projection";
import {compileLivingScriptPatch} from "../../planner/src/living-script-patch";
import {compileLivingScriptGenerationImpact} from "../../planner/src/living-script-generation";
import {compileLivingScriptSourceMap} from "../../planner/src/living-script-source-map";
import {createLivingScriptJobPlan,type LivingScriptJobPlan} from "../../planner/src/living-script-jobs";
import {createLivingScriptPreviewReview,validateLivingScriptOutput} from "../../planner/src/living-script-job-context";
import {currentCasting,castingSnapshot} from "../../planner/src/casting";
import {currentDirection} from "../../planner/src/direction";
import {renderShots} from "../../planner/src/shot-reuse";
import {LeaseError,type Job,type JobInput} from "../../queue/src/index";
import {processNextJob} from "../../queue/src/worker";

const enabled=Boolean(process.env.HV_PG_ADMIN_URL&&process.env.HV_API_DATABASE_URL&&process.env.HV_WORKER_DATABASE_URL&&process.env.HV_S3_ENDPOINT&&process.env.HV_S3_BUCKET&&process.env.HV_S3_FLEET_TEST_BUCKET);
function databaseName(name:string):string{if(!/^hv_pending_jobs_[a-f0-9]{32}$/.test(name))throw new Error("Unsafe pending job fixture database");return name;}
function databaseUrl(value:string,name:string):string{const url=new URL(value);url.pathname="/"+databaseName(name);return url.href;}
function files(root:string):string[]{return readdirSync(root,{withFileTypes:true}).flatMap(entry=>{if(entry.isSymbolicLink())throw new Error("Fixture media cannot contain links");const path=join(root,entry.name);if(entry.isDirectory())return files(path);if(!entry.isFile())throw new Error("Fixture media must be regular files");return [path];});}
function cleanup(root:string):void{if(!root.startsWith(realpathSync(tmpdir())+sep+"hv-pending-pg-")||realpathSync(root)!==root)throw new Error("Unsafe pending job fixture cleanup");rmSync(root,{recursive:true,force:true});}
async function clearObjects(client:ReturnType<typeof objectClient>,projectId:string):Promise<void>{const prefix="v1/"+projectId+"/";for(let page=0;page<100;page++){const entries=(await client.list({prefix,maxKeys:1000})).contents??[];if(!entries.length)return;for(const entry of entries){if(!entry.key.startsWith(prefix))throw new Error("Fixture object escaped its project");await client.file(entry.key).delete();}}throw new Error("Fixture object cleanup exceeded its bound");}
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(error:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};}
function input(plan:LivingScriptJobPlan,original:Job,preview?:Job,at?:string):JobInput{return {id:crypto.randomUUID(),idempotencyKey:plan.inputs.projectId+":"+crypto.randomUUID(),...plan.inputs,livingScript:plan,shotReuse:plan.shotReuse,totalFrames:renderShots(plan.inputs).reduce((total,shot)=>total+Math.round(shot.durationSec*30),0),retryPolicy:{maxRetries:1,backoffMs:0},timeoutMs:120000,costCapUsd:original.costCapUsd,budgetReservedUsd:0,...(plan.inputs.stage==="animatic"?{providerSpec:plan.inputs.providerPlan!.pool[0]!.spec}:{}),rightsAttestedAt:original.rightsAttestedAt,animaticJobId:preview?.id??null,animaticApprovedAt:at??null};}

(enabled?test:test.skip)("PostgreSQL pending generation serializes admission approval and dispatch, resumes S3 checkpoints and restores schema eleven without committing its screenplay",async()=>{
  const root=realpathSync(mkdtempSync(join(realpathSync(tmpdir()),"hv-pending-pg-"))),originName=databaseName("hv_pending_jobs_"+crypto.randomUUID().replaceAll("-","")),restoreName=databaseName("hv_pending_jobs_"+crypto.randomUUID().replaceAll("-",""));
  const oldPool=process.env.HV_PROVIDER_POOL,sourceBucket=process.env.HV_S3_BUCKET,control=new StudioDatabase(process.env.HV_PG_ADMIN_URL!),created:string[]=[],sourceClient=objectClient(),destinationClient=objectClient({...process.env,HV_S3_BUCKET:process.env.HV_S3_FLEET_TEST_BUCKET});
  let studio:Awaited<ReturnType<typeof dubStudio>>|undefined,admin:StudioDatabase|undefined,api:StudioDatabase|undefined,worker:StudioDatabase|undefined,restored:StudioDatabase|undefined,projectId:string|undefined;
  try{
    process.env.HV_PROVIDER_POOL='["mock"]';expect(sourceBucket).not.toBe(process.env.HV_S3_FLEET_TEST_BUCKET);const studioRoot=join(root,"studio");mkdirSync(studioRoot);studio=await dubStudio(studioRoot);projectId=studio.owner.projectId;
    expect((await studio.call(studio.base+"/animatic/decision","POST",{animaticJobId:studio.film.id,decision:"approved"},studio.owner.token)).status).toBe(201);
    expect((await studio.call(studio.base+"/jobs","POST",{idempotencyKey:"pending-pg-original",stage:"final",animaticJobId:studio.film.id},studio.owner.token)).status).toBe(202);
    const originalFilm={...(await studio.worker())!,leaseVersion:0},originalPreview={...studio.film,leaseVersion:0};expect(originalFilm.failureReason??originalFilm.cancelReason).toBeUndefined();expect(originalFilm.status).toBe("done");
    await control.sql.unsafe('CREATE DATABASE "'+databaseName(originName)+'"');created.push(originName);admin=new StudioDatabase(databaseUrl(process.env.HV_PG_ADMIN_URL!,originName));await admin.migrate();
    const initial:StateSnapshot={schema:"hv-state/11",projects:studio.projects.snapshot(),jobs:[originalPreview,originalFilm],ledger:JSON.parse(readFileSync(studio.paths.costLedgerPath,"utf8")),reviews:[]};validateSnapshot(initial);await importStateSnapshot(admin,initial,500);
    const originals=new PostgresJobStore(admin).forProject(projectId),original=(await originals.get(originalFilm.id))!,seedMedia=new PostgresArtifactStore(admin,studio.paths.artifactRoot,sourceClient);
    // A raw worker result contains optional own-undefined fields which JSONB omits.
    // That transport difference is allowed; an actual changed value must fail without
    // publishing an artifact index, even when all copied files themselves are valid.
    expect(Object.hasOwn(originalPreview,"failureReason")).toBe(true);expect(originalPreview.failureReason).toBeUndefined();
    const previewFiles=files(join(studio.paths.artifactRoot,projectId,originalPreview.id));
    await expect(seedMedia.importCompletedJob({...originalPreview,failureReason:"altered import"},previewFiles)).rejects.toThrow("private execution job changed");
    expect(Number((await admin.sql`select count(*) as count from hv_artifacts where job_id=${originalPreview.id}`)[0].count)).toBe(0);
    expect(original).toEqual(originalFilm);for(const job of [originalPreview,original]){const uploaded=await seedMedia.importCompletedJob(job,files(join(studio.paths.artifactRoot,projectId,job.id)));expect(uploaded.files).toBeGreaterThan(0);expect(uploaded.bytes).toBeGreaterThan(0);}
    const source=await inspectEditSource(original,"Retained final screenplay",studio.paths.artifactRoot,async()=>{},undefined,seedMedia,path=>seedMedia.fileInfo(projectId!,original.id,path)),binding=bindOriginalEditSource(source),carrier={binding,current:original},originalHash=contentHash(original),originalBytes=readFileSync(join(studio.paths.artifactRoot,original.output!.mp4Path));
    api=new StudioDatabase(databaseUrl(process.env.HV_API_DATABASE_URL!,originName));worker=new StudioDatabase(databaseUrl(process.env.HV_WORKER_DATABASE_URL!,originName));const projects=new PostgresProjectService(api),ledger=new PostgresCostLedger(worker),owner=studio.owner;
    const editorial=(await projects.createEditSequence(owner.token,[source],"parent","Original saved cut",source.facts.id,320,180,0,Date.now(),[binding]))!,parent=deriveEditAssemblyParent(projectId,editorial,"parent"),index=compileEditScriptSource(source),line=index.entries.find(entry=>entry.kind==="dialogue")!,navigation=projectEditScriptNavigation(parent.sequenceId,parent.historyRevision,parent.timeline,[index]);
    const patch=compileLivingScriptPatch(source,{entryId:line.id,indexRevision:index.revision,currentScript:{version:original.scriptVersion,text:original.scriptText},replacement:"Welcome back to the garden."}),impact=compileLivingScriptGenerationImpact(source,patch,{...original,scriptVersion:patch.after.version,scriptText:patch.after.text}),current=(await projects.peekProject(projectId))!;
    const proposal=(await projects.createLivingScriptProposal(owner.token,{id:"pending-line",label:"Review the greeting",sequenceId:parent.sequenceId,historyRevision:parent.historyRevision,editorialRevision:editorial.revision,navigationRevision:navigation.revision,patch,candidate:impact.candidateInputs,baseline:{casting:currentCasting(projectId,current.castingHistory),direction:currentDirection(projectId,current.directionHistory)}},0,[carrier]))!.proposal;
    const previewPlan=createLivingScriptJobPlan(proposal,binding,{role:"preview",providerPlan:originalPreview.providerPlan!}),renderPlan=createLivingScriptJobPlan(proposal,binding,{role:"render"}),previewInput=input(previewPlan,original);
    const row=async()=>{const value=(await admin!.sql`select body,version from hv_projects where id=${projectId!}`)[0];return {body:value.body as PersistedProject,version:Number(value.version)};};
    const counts=async()=>{const value=(await admin!.sql`select (select count(*) from hv_jobs where project_id=${projectId!}) as jobs,(select count(*) from hv_cost_events where project_id=${projectId!}) as costs,(select count(*) from hv_provider_attempts where project_id=${projectId!}) as attempts,(select count(*) from hv_reservations where job_id in (select id from hv_jobs where project_id=${projectId!})) as holds`)[0];return [value.jobs,value.costs,value.attempts,value.holds].map(Number);};
    const before=await row(),beforeCounts=await counts(),carrierFile=binding.files[0]!;
    const baseline=currentCasting(projectId,before.body.castingHistory);
    for(const body of [{...before.body,rightsAttestedAt:null},{...before.body,versions:[...before.body.versions,{...before.body.versions.at(-1)!,version:patch.after.version,text:patch.after.text}]},{...before.body,castingHistory:[...before.body.castingHistory!,castingSnapshot(projectId,baseline.version+1,baseline.characters)]}]){
      await admin.sql`update hv_projects set body=${body}::jsonb where id=${projectId}`;await expect(ledger.admit(projectId,previewInput,500)).rejects.toThrow();expect(await counts()).toEqual(beforeCounts);
    }
    await admin.sql`update hv_projects set body=${before.body}::jsonb where id=${projectId}`;
    await admin.sql`update hv_artifacts set bytes=bytes+1 where project_id=${projectId} and job_id=${original.id} and key=${carrierFile.path}`;await expect(ledger.admit(projectId,previewInput,500)).rejects.toThrow("source artifact changed");expect(await counts()).toEqual(beforeCounts);await admin.sql`update hv_artifacts set bytes=${carrierFile.bytes} where key=${carrierFile.path}`;
    // The admission waits for the actual carrier row, then sees its withdrawal rather than
    // trusting the unchanged receipt supplied by this caller.
    const locked=deferred<number>(),release=deferred<void>(),withdrawal=admin.sql.begin(async tx=>{const pid=Number((await tx`select pg_backend_pid() as pid`)[0].pid);await tx`select id from hv_jobs where id=${original.id} for update`;locked.resolve(pid);await release.promise;await tx`update hv_jobs set body=${{...original,status:"cancelled"}}::jsonb,status='cancelled' where id=${original.id}`;}).catch(error=>{locked.reject(error);throw error;});
    const blocker=await locked.promise,waiting=ledger.admit(projectId,previewInput,500).then(value=>({value,error:null}),error=>({value:null,error}));
    try{let observed=false;const deadline=Date.now()+10000;while(Date.now()<deadline){observed=Boolean((await admin.sql`select exists(select 1 from pg_stat_activity where ${blocker}::int=any(pg_blocking_pids(pid))) as blocked`)[0].blocked);if(observed)break;await new Promise(resolve=>setTimeout(resolve,20));}expect(observed).toBe(true);}finally{release.resolve();await withdrawal;await waiting;}
    expect((await waiting).error).toBeInstanceOf(Error);expect(await counts()).toEqual(beforeCounts);await admin.sql`update hv_jobs set body=${original}::jsonb,status='done' where id=${original.id}`;
    const admissions=await Promise.all([ledger.admit(projectId,previewInput,500),ledger.admit(projectId,{...previewInput,id:crypto.randomUUID()},500)]);expect(admissions[0]!.id).toBe(admissions[1]!.id);const previewId=admissions[0]!.id;
    expect((await counts())[0]).toBe(beforeCounts[0]!+1);expect((await counts())[3]).toBe(beforeCounts[3]!+1);expect(await row()).toEqual(before);
    const admittedCounts=await counts();await expect(ledger.admit(projectId,{...previewInput,timeoutMs:previewInput.timeoutMs+1},500)).rejects.toThrow("different reviewed plan");expect(await counts()).toEqual(admittedCounts);
    const firstRoot=join(root,"first"),firstMedia=new PostgresArtifactStore(worker,firstRoot,sourceClient),context={projects,ledger,reviewQueue:new PostgresReviewQueue(worker)};
    const preview=(await processNextJob(new PostgresJobStore(worker).forProject(projectId),firstRoot,{...context,artifacts:firstMedia,workerId:"pending-preview"}))!;expect(preview.id).toBe(previewId);expect(preview.failureReason??preview.cancelReason).toBeUndefined();expect(preview.status).toBe("done");validateLivingScriptOutput(preview,preview.output!);expect(await row()).toEqual(before);
    await firstMedia.restoreCheckpoint(preview);expect(readFileSync(join(firstRoot,preview.output!.captionsPath),"utf8")).toContain(patch.replacement);expect(preview.scriptText).toBe(patch.after.text);
    const review=createLivingScriptPreviewReview(preview),reviewCounts=await counts(),decision=()=>projects.recordLivingScriptDecision(owner.token,preview,review,"approved","Use this pending performance",carrier),decisions=await Promise.all([decision(),decision()]);expect(decisions.map(value=>value!.replayed).sort()).toEqual([false,true]);expect(decisions[0]!.approval).toEqual(decisions[1]!.approval);
    const approved=await row();expect(approved.version).toBe(before.version+1);expect(approved.body.versions).toEqual(before.body.versions);expect(approved.body.editLibrary).toEqual(before.body.editLibrary);expect(approved.body.animaticApprovals.find(value=>value.animaticJobId===preview.id)!.livingScriptReview).toEqual(review);expect(await counts()).toEqual(reviewCounts);
    expect((await decision())!.replayed).toBe(true);expect(await row()).toEqual(approved);expect(await projects.recordLivingScriptDecision("invalid",preview,review,"approved","Use this pending performance",carrier)).toBeNull();expect(await row()).toEqual(approved);
    const foreign=await projects.createAnonymousProject();await expect(projects.recordLivingScriptDecision(foreign.token,preview,review,"approved","Use this pending performance",carrier)).rejects.toThrow();expect(await row()).toEqual(approved);
    const previewFile=Object.values(preview.output!.shotRenders![0]!.files)[0]!;await admin.sql`update hv_artifacts set bytes=bytes+1 where key=${previewFile.path}`;try{await expect(decision()).rejects.toThrow("preview shot artifacts changed");expect(await row()).toEqual(approved);}finally{await admin.sql`update hv_artifacts set bytes=${previewFile.bytes} where key=${previewFile.path}`;}
    const request=input(renderPlan,original,preview,decisions[0]!.approval.at),unapproved={...approved.body,animaticApprovals:approved.body.animaticApprovals.filter(value=>value.animaticJobId!==preview.id)};
    await admin.sql`update hv_projects set body=${unapproved}::jsonb where id=${projectId}`;await expect(ledger.admit(projectId,request,500)).rejects.toThrow("saved approval");expect(await counts()).toEqual(reviewCounts);await admin.sql`update hv_projects set body=${approved.body}::jsonb where id=${projectId}`;
    const finalAdmissions=await Promise.all([ledger.admit(projectId,request,500),ledger.admit(projectId,{...request,id:crypto.randomUUID()},500)]);expect(finalAdmissions[0]!.id).toBe(finalAdmissions[1]!.id);const finalId=finalAdmissions[0]!.id,firstStore=new PostgresJobStore(worker).forProject(projectId);
    const generate=DeterministicMockProvider.prototype.generate,calls:string[]=[],provider=spyOn(DeterministicMockProvider.prototype,"generate").mockImplementation(function(this:DeterministicMockProvider,...args:Parameters<typeof generate>){calls.push(args[2].shotId!);return generate.apply(this,args);});
    const begin=ledger.beginAttempt.bind(ledger);let attempted=false,checkpointed=false,completedFence=false;
    const dispatch=spyOn(ledger,"beginAttempt").mockImplementation(async(...args:Parameters<typeof begin>)=>{const attempt=args[0];if(attempt.jobId!==finalId||attempted)return begin(...args);attempted=true;const beforeAttempt=await counts();await expect(begin({...attempt,leaseVersion:attempt.leaseVersion+1})).rejects.toBeInstanceOf(LeaseError);
      await admin!.sql`update hv_artifacts set bytes=bytes+1 where key=${carrierFile.path}`;try{await expect(begin(...args)).rejects.toThrow("source artifact changed");expect(await counts()).toEqual(beforeAttempt);}finally{await admin!.sql`update hv_artifacts set bytes=${carrierFile.bytes} where key=${carrierFile.path}`;}
      const attempts=await Promise.allSettled([begin(...args),begin(...args)]);expect(attempts.filter(value=>value.status==="fulfilled")).toHaveLength(1);expect(attempts.filter(value=>value.status==="rejected")).toHaveLength(1);expect((await counts())[2]).toBe(beforeAttempt[2]!+1);
    });
    const checkpoint=firstMedia.checkpoint.bind(firstMedia),interrupt=spyOn(firstMedia,"checkpoint").mockImplementation(async(...args:Parameters<typeof checkpoint>)=>{if(args[0].id===finalId&&!checkpointed){await expect(checkpoint({...args[0],leaseVersion:args[0].leaseVersion!+1},...args.slice(1) as [string,VideoClip[],number,number,AbortSignal?])).rejects.toBeInstanceOf(LeaseError);await checkpoint(...args);checkpointed=true;throw new Error("Injected interruption after durable pending S3 checkpoint");}await checkpoint(...args);});
    let interrupted:Job,done:Job;
    try{
      try{interrupted=(await processNextJob(firstStore,firstRoot,{...context,artifacts:firstMedia,workerId:"pending-interrupted"}))!;}finally{interrupt.mockRestore();}
      expect(interrupted!.id).toBe(finalId);expect(interrupted!.status).toBe("queued");expect(interrupted!.checkpointShots).toBe(1);expect(checkpointed).toBe(true);expect(attempted).toBe(true);expect(calls).toEqual(renderPlan.shotReuse.forceShotIds);expect(existsSync(join(firstRoot,projectId,finalId))).toBe(false);await expect(exportStateSnapshot(admin,projectId)).rejects.toThrow("drained");
      const secondRoot=join(root,"resumed"),secondMedia=new PostgresArtifactStore(worker,secondRoot,sourceClient),secondStore=new PostgresJobStore(worker).forProject(projectId);
      await expect(secondMedia.restoreCheckpoint({...interrupted!,checkpointFrame:interrupted!.checkpointFrame+1})).rejects.toThrow("exact shot prefix or frame count");
      await secondMedia.restoreCheckpoint(interrupted!);const prefix=JSON.parse(readFileSync(join(secondRoot,projectId,finalId,"clips/manifest.json"),"utf8")) as VideoClip[],prefixBytes=readFileSync(prefix[0]!.path),attemptCount=(await counts())[2];
      const complete=secondStore.complete.bind(secondStore),completion=spyOn(secondStore,"complete").mockImplementation(async(...args:Parameters<typeof complete>)=>{const beforeFinish=(await originals.get(finalId))!;await admin!.sql`update hv_artifacts set bytes=bytes+1 where key=${carrierFile.path}`;try{await expect(complete(...args)).rejects.toThrow("source artifact changed");expect(await originals.get(finalId)).toEqual(beforeFinish);}finally{await admin!.sql`update hv_artifacts set bytes=${carrierFile.bytes} where key=${carrierFile.path}`;}
        const results=await Promise.allSettled([complete(...args),complete(...args)]);expect(results.filter(value=>value.status==="fulfilled")).toHaveLength(1);expect(results.filter(value=>value.status==="rejected")).toHaveLength(1);completedFence=true;const result=results.find(value=>value.status==="fulfilled");if(!result||result.status!=="fulfilled")throw new Error("Pending completion did not commit");return result.value;});
      try{done=(await processNextJob(secondStore,secondRoot,{...context,artifacts:secondMedia,workerId:"pending-resumed"}))!;}finally{completion.mockRestore();}
      expect(done!.failureReason??done!.cancelReason).toBeUndefined();expect(done!.status).toBe("done");expect(done!.id).toBe(finalId);expect(completedFence).toBe(true);expect((await counts())[2]).toBe(attemptCount);expect(calls).toEqual(renderPlan.shotReuse.forceShotIds);validateLivingScriptOutput(done!,done!.output!);
      await secondMedia.restoreCheckpoint(done!);expect(readFileSync(prefix[0]!.path)).toEqual(prefixBytes);const generated=await inspectEditSource(done!,"Pending final",secondRoot,async()=>{},undefined,secondMedia,path=>secondMedia.fileInfo(projectId!,done!.id,path)),mapping=compileLivingScriptSourceMap(source,patch,impact,generated);expect(mapping.shots.filter(shot=>shot.treatment==="unchanged")).toHaveLength(renderPlan.shotReuse.shots.length);
      for(const record of done!.output!.shotRenders!.filter(record=>record.reusedFrom)){const old=renderPlan.shotReuse.shots.find(value=>value.shotId===record.shotId)!;expect(record.reusedFrom!.revision).toBe(old.revision);for(const [kind,file]of Object.entries(record.files))expect(readFileSync(join(secondRoot,file.path))).toEqual(readFileSync(join(studio.paths.artifactRoot,old.files[kind as keyof typeof old.files]!.path)));}
      await expect(firstStore.complete(finalId,"pending-interrupted",done!.output!)).rejects.toBeInstanceOf(LeaseError);
    }finally{interrupt.mockRestore();dispatch.mockRestore();provider.mockRestore();}
    expect(await row()).toEqual(approved);expect(contentHash((await originals.get(original.id))!)).toBe(originalHash);expect(readFileSync(join(studio.paths.artifactRoot,original.output!.mp4Path))).toEqual(originalBytes);expect(await ledger.monthSpend()).toBe(0);
    // Historical exact retries neither admit again nor renew permission. A fresh worker must
    // still reject a withdrawn carrier before an attempt, charge or checkpoint is created.
    const rejectedInput=input(previewPlan,original);rejectedInput.retryPolicy.maxRetries=0;const rejectedJob=await ledger.admit(projectId,rejectedInput,500);await admin.sql`update hv_jobs set body=${{...original,status:"cancelled"}}::jsonb,status='cancelled' where id=${original.id}`;
    const withdrawnCounts=await counts(),withdrawnRow=await row();expect((await ledger.admit(projectId,{...rejectedInput,id:crypto.randomUUID()},500)).id).toBe(rejectedJob.id);expect(await counts()).toEqual(withdrawnCounts);expect(await row()).toEqual(withdrawnRow);
    const noDispatch=spyOn(DeterministicMockProvider.prototype,"generate");try{const rejected=(await processNextJob(new PostgresJobStore(worker).forProject(projectId),join(root,"withdrawn"),{...context,artifacts:new PostgresArtifactStore(worker,join(root,"withdrawn"),sourceClient),workerId:"pending-withdrawn"}))!;expect(rejected.id).toBe(rejectedJob.id);expect(rejected.status).toBe("failed");expect(rejected.checkpointShots).toBe(0);expect(noDispatch).not.toHaveBeenCalled();expect((await counts()).slice(1,3)).toEqual(withdrawnCounts.slice(1,3));}finally{noDispatch.mockRestore();await admin.sql`update hv_jobs set body=${original}::jsonb,status='done' where id=${original.id}`;}
    const snapshot=await exportStateSnapshot(admin,projectId);expect(snapshot.schema).toBe("hv-state/11");expect(snapshot.jobs.filter(job=>job.livingScript)).toHaveLength(3);expect(snapshot.jobs.find(job=>job.id===preview.id)!.executionCheckpoints).toEqual(preview.executionCheckpoints!);expect(snapshot.projects.projects[0]!.versions).toEqual(before.body.versions);expect(snapshot.projects.projects[0]!.livingScriptAcceptances).toBeUndefined();expect(()=>validateSnapshot({...snapshot,schema:"hv-state/10"})).toThrow("schema 11");
    const archive=join(root,"pending.zip"),prepared=join(root,"prepared"),unpacked=join(root,"unpacked"),exported=await exportProjectArchive(admin,projectId,prepared,archive);expect(exported.jobs).toBe(5);expect(readStateSnapshot(prepared)).toEqual(snapshot);
    await control.sql.unsafe('CREATE DATABASE "'+databaseName(restoreName)+'"');created.push(restoreName);restored=new StudioDatabase(databaseUrl(process.env.HV_PG_ADMIN_URL!,restoreName));await restored.migrate();
    let imported:Awaited<ReturnType<typeof importProjectArchive>>;try{process.env.HV_S3_BUCKET=process.env.HV_S3_FLEET_TEST_BUCKET;imported=await importProjectArchive(restored,archive,unpacked,500);}finally{process.env.HV_S3_BUCKET=sourceBucket;}
    expect(imported.archiveSha256).toBe(exported.archiveSha256);expect(imported.mediaFiles).toBeGreaterThan(0);expect(imported.mediaBytes).toBeGreaterThan(0);expect(readStateSnapshot(unpacked)).toEqual(snapshot);expect(readFileSync(join(prepared,"state/projects.json"))).toEqual(readFileSync(join(unpacked,"state/projects.json")));
    await clearObjects(sourceClient,projectId);expect((await sourceClient.list({prefix:"v1/"+projectId+"/",maxKeys:1})).contents??[]).toHaveLength(0);
    const independentRoot=join(root,"independent"),independent=new PostgresArtifactStore(restored,independentRoot,destinationClient),restoredJobs=new PostgresJobStore(restored).forProject(projectId);expect(existsSync(join(independentRoot,projectId))).toBe(false);
    for(const expected of [original,preview,done!]){const job=(await restoredJobs.get(expected.id))!;expect(job).toEqual(expected);await independent.restoreCheckpoint(job);for(const shot of job.output!.shotRenders!)for(const file of Object.values(shot.files)){expect(await independent.fileInfo(projectId,job.id,file.path)).toEqual(file);expect(readFileSync(join(independentRoot,file.path))).toEqual(readFileSync(join(unpacked,"artifacts",file.path)));}if(job.livingScript)validateLivingScriptOutput(job,job.output!);}
    expect(readFileSync(join(independentRoot,original.output!.mp4Path))).toEqual(originalBytes);expect(readFileSync(join(independentRoot,done!.output!.captionsPath),"utf8")).toContain(patch.replacement);
    const restoredProjects=new PostgresProjectService(restored),retained=(await restoredProjects.authorize(owner.token))!;expect(retained.versions.history()).toEqual(before.body.versions);expect(retained.editLibrary).toEqual(before.body.editLibrary!);expect(retained.animaticApprovals.find(value=>value.animaticJobId===preview.id)!.livingScriptReview).toEqual(review);expect((await exportStateSnapshot(restored,projectId)).schema).toBe("hv-state/11");
  }finally{
    if(sourceBucket===undefined)delete process.env.HV_S3_BUCKET;else process.env.HV_S3_BUCKET=sourceBucket;if(oldPool===undefined)delete process.env.HV_PROVIDER_POOL;else process.env.HV_PROVIDER_POOL=oldPool;
    if(projectId)for(const client of [sourceClient,destinationClient])await clearObjects(client,projectId);await api?.close();await worker?.close();await admin?.close();await restored?.close();for(const name of created)await control.sql.unsafe('DROP DATABASE "'+databaseName(name)+'" WITH (FORCE)');await control.close();await studio?.close(false);cleanup(root);
  }
},300000);
