import {afterAll,afterEach,beforeAll,expect,test} from "bun:test";
import {mkdtempSync,readFileSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join,resolve,sep} from "node:path";
import {StudioDatabase} from "../src/database";
import {PostgresJobStore} from "../src/jobs";
import {PostgresCostLedger} from "../src/ledger";
import {PostgresReviewQueue} from "../src/reviews";
import {PostgresArtifactStore,objectClient} from "../src/artifacts";
import {SoundBlobStore} from "../src/sound-assets";
import {PostgresRetention} from "../src/retention";
import {exportProjectArchive,importProjectArchive} from "../src/archives";
import {exportStateSnapshot,validateSnapshot} from "../src/snapshots";
import {createApiServer,type ApiServer} from "../../api/src/server";
import {processNextJob} from "../../queue/src/worker";
import {LeaseError} from "../../queue/src/index";
import {soundFixture,soundCue,SOUND_RIGHTS} from "../../../test/fixtures/sound";
import {soundAssetObjectKey} from "../../planner/src/sound-assets";
import {verifySoundMedia} from "../../generator/src/sound-media";
import {outputRevision} from "../../planner/src/dialogue-selection";
import {PostgresProjectService} from "../src/projects";
import {inspectEditSource} from "../../generator/src/edit-source-media";
import {editHistoryState} from "../../planner/src/edit-history";
import {createEditPlan,bindOriginalEditSource,bindRetainedEditSource,editRenderReview} from "../../planner/src/edit-jobs";
import {soundRuntimeRevision} from "../../generator/src/sound-audio";
import {contentHash} from "../../generator/src/capabilities";
import type {JobInput} from "../../queue/src/index";
import {verifyEditMedia} from "../../generator/src/edit-media";
import {decodePreviewPage} from "../../planner/src/edit-preview-protocol";
const enabled=Boolean(process.env.HV_PG_ADMIN_URL&&process.env.HV_API_DATABASE_URL&&process.env.HV_WORKER_DATABASE_URL&&process.env.HV_S3_ENDPOINT&&process.env.HV_S3_FLEET_TEST_BUCKET),pgtest=enabled?test:test.skip;
const envKeys=["HV_TOKEN_SECRET","HV_NARRATION","HV_ANIMATIC_CAPTIONS","HV_ANIMATIC_PROVIDER_POOL","HV_S3_BUCKET"],old=Object.fromEntries(envKeys.map(k=>[k,process.env[k]])),name="hv_sound_"+crypto.randomUUID().replaceAll("-","");
let admin:StudioDatabase,worker:StudioDatabase,restored:StudioDatabase,root:string,server:ApiServer;const ids:string[]=[],keys=new Set<string>();
const replica=()=>objectClient({...process.env,HV_S3_BUCKET:process.env.HV_S3_FLEET_TEST_BUCKET});
afterEach(async()=>{if(!enabled||!restored)return;for(const id of ids){
  for(const row of await restored.sql`select object_key from hv_artifacts where project_id=${id}`)keys.add(row.object_key);
  await restored.sql`delete from hv_reservations where job_id in (select id from hv_jobs where project_id=${id})`;
  for(const table of ["hv_outbox","hv_artifacts","hv_archives","hv_reviews","hv_operator_reviews","hv_cost_events","hv_provider_attempts","hv_jobs","hv_projects"])await restored.sql.unsafe('delete from "'+table+'" where '+(table==="hv_projects"?'id':'project_id')+'=$1',[id]);
}for(const key of keys)await replica().file(key).delete();});
beforeAll(async()=>{if(!enabled)return;root=mkdtempSync(join(tmpdir(),"hv-sound-pg-"));Object.assign(process.env,{HV_TOKEN_SECRET:"postgres-sound-test-at-least-thirty-two-characters",HV_NARRATION:"1",HV_ANIMATIC_CAPTIONS:"0",HV_ANIMATIC_PROVIDER_POOL:'["mock"]'});
  admin=new StudioDatabase(process.env.HV_PG_ADMIN_URL!);worker=new StudioDatabase(process.env.HV_WORKER_DATABASE_URL!);await admin.migrate();await admin.sql.unsafe('CREATE DATABASE "'+name+'"');const url=new URL(process.env.HV_PG_ADMIN_URL!);url.pathname="/"+name;restored=new StudioDatabase(url.href);await restored.migrate();
  server=createApiServer({port:0,hostname:"127.0.0.1",storage:"postgres",artifactStorage:"s3",databaseUrl:process.env.HV_API_DATABASE_URL,artifactRoot:join(root,"api"),rateLimit:{api:{limit:10000,windowMs:60000}}});
});
afterAll(async()=>{if(!enabled)return;await server?.stop(true);
  for(const db of [admin,restored])if(db)for(const id of ids)for(const row of await db.sql`select object_key from hv_artifacts where project_id=${id}`)keys.add(row.object_key);
  for(const key of keys){await objectClient().file(key).delete();await replica().file(key).delete();}
  for(const id of ids){await admin.sql`delete from hv_reservations where job_id in (select id from hv_jobs where project_id=${id})`;for(const table of ["hv_outbox","hv_artifacts","hv_archives","hv_reviews","hv_operator_reviews","hv_cost_events","hv_provider_attempts","hv_jobs","hv_projects"])await admin.sql.unsafe('delete from "'+table+'" where '+(table==="hv_projects"?'id':'project_id')+'=$1',[id]);}
  await worker?.close();await restored?.close();await admin.sql.unsafe('DROP DATABASE "'+name+'" WITH (FORCE)');await admin.close();for(const [k,v]of Object.entries(old)){if(v===undefined)delete process.env[k];else process.env[k]=v;}
  if(!resolve(root).startsWith(resolve(tmpdir())+sep+"hv-sound-pg-"))throw new Error("Unexpected sound test root");rmSync(root,{recursive:true,force:true});
});
const call=(path:string,method="GET",body?:unknown,token?:string)=>fetch(new URL(path,server.url),{method,headers:{"content-type":"application/json",...(token?{authorization:"Bearer "+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
pgtest("editorial renders resume owned S3 checkpoints, retain flat source carriers and restore without earlier jobs",async()=>{
  const owner=await(await call("/api/projects","POST")).json() as any;ids.push(owner.projectId);const base="/api/projects/"+owner.projectId;
  expect((await call(base+"/script","PUT",{text:"INT. GARDEN - DAY\n\nMarla waves at the gate."},owner.token)).status).toBe(200);expect((await call(base+"/rights","POST",{attested:true},owner.token)).status).toBe(200);
  const queue=new PostgresJobStore(worker).forProject(owner.projectId),ledger=new PostgresCostLedger(worker),projects=new PostgresProjectService(admin),aRoot=join(root,"edit-first"),bRoot=join(root,"edit-resumed"),a=new PostgresArtifactStore(worker,aRoot),b=new PostgresArtifactStore(worker,bRoot),context={ledger,reviewQueue:new PostgresReviewQueue(worker)};
  expect((await call(base+"/jobs","POST",{idempotencyKey:"source"},owner.token)).status).toBe(202);const film=(await processNextJob(queue,aRoot,{...context,artifacts:a,workerId:"edit-source"}))!;expect(film.failureReason??film.cancelReason).toBeUndefined();expect(film.status).toBe("done");await a.restoreCheckpoint(film);
  const receipt=await inspectEditSource(film,"Retained original",aRoot,async()=>{}),sequenceId=crypto.randomUUID();let library=(await projects.createEditSequence(owner.token,[receipt],sequenceId,"Short assembly",film.id,640,360,0))!;
  const frames=editHistoryState(library.sequences[0]!.history).timeline.frames;
  if(frames>30)library=(await projects.changeEditSequence(owner.token,sequenceId,{kind:"edit",label:"Keep opening second",operation:{kind:"trim",clipId:"initial-0",linked:true,edge:"out",delta:30-frames,ripple:true}},library.version,library.sequences[0]!.history.revision))!;
  library=(await projects.changeEditSequence(owner.token,sequenceId,{kind:"edit",label:"Split retained original",operation:{kind:"split",clipId:"initial-0",linked:true,at:15,rightIds:{"initial-0":"right-picture","initial-1":"right-mix","initial-2":"right-captions"},rightLink:"right"}},library.version,library.sequences[0]!.history.revision))!;
  library=(await projects.changeEditSequence(owner.token,sequenceId,{kind:"edit",label:"Crossfade retained performances",operation:{kind:"crossfade",leftId:"initial-0",rightId:"right-picture",linked:true,frames:6,alignment:"center",ids:{"initial-0":"picture-fade","initial-1":"audio-fade"}}},library.version,library.sequences[0]!.history.revision))!;
  expect(editHistoryState(library.sequences[0]!.history).timeline.transitions).toHaveLength(2);
  expect((await call(base+"/jobs","POST",{idempotencyKey:"later-source"},owner.token)).status).toBe(202);const later=(await processNextJob(queue,aRoot,{...context,artifacts:a,workerId:"edit-later-source"}))!;expect(later.failureReason??later.cancelReason).toBeUndefined();expect(later.status).toBe("done");await a.restoreCheckpoint(later);const laterReceipt=await inspectEditSource(later,"Later retained original",aRoot,async()=>{}),binding=bindOriginalEditSource(laterReceipt),beforeAddition=editHistoryState(library.sequences[0]!.history).head;
  await admin.sql`update hv_jobs set body=jsonb_set(body,'{linkExpiresAt}',to_jsonb(${new Date(Date.now()-3600000).toISOString()}::text)) where id=${later.id}`;try{await expect(projects.admitEditSource(owner.token,sequenceId,binding,library.version,library.sequences[0]!.history.revision)).rejects.toThrow();}finally{await admin.sql`update hv_jobs set body=jsonb_set(body,'{linkExpiresAt}',to_jsonb(${later.linkExpiresAt}::text)) where id=${later.id}`;}
  const artifacts=await admin.sql`select object_key,sha256 from hv_artifacts where job_id=${later.id} and key=${binding.files[0]!.path}`;expect(artifacts).toHaveLength(1);const artifact=artifacts[0]!;await admin.sql`update hv_artifacts set sha256=${"0".repeat(64)} where job_id=${later.id} and object_key=${artifact.object_key}`;try{await expect(projects.admitEditSource(owner.token,sequenceId,binding,library.version,library.sequences[0]!.history.revision)).rejects.toThrow("artifact changed");}finally{await admin.sql`update hv_artifacts set sha256=${artifact.sha256} where job_id=${later.id} and object_key=${artifact.object_key}`;}
  const additions=await Promise.allSettled([projects.admitEditSource(owner.token,sequenceId,binding,library.version,library.sequences[0]!.history.revision),new PostgresProjectService(admin).admitEditSource(owner.token,sequenceId,binding,library.version,library.sequences[0]!.history.revision)]);expect(additions.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect(additions.filter(r=>r.status==="rejected")).toHaveLength(1);library=(await projects.authorize(owner.token))!.editLibrary;
  library=(await projects.changeEditSequence(owner.token,sequenceId,{kind:"cursor",reason:"undo",target:beforeAddition,label:"Return to earlier original"},library.version,library.sequences[0]!.history.revision))!;
  const sequence=library.sequences[0]!,timeline=editHistoryState(sequence.history).timeline,bindings=[bindOriginalEditSource(receipt),binding].sort((a,b)=>a.source.facts.id.localeCompare(b.source.facts.id)),plan=createEditPlan(sequence,bindings,soundRuntimeRevision(),"s3",contentHash("edit-pg"),editRenderReview(timeline));expect(timeline.sources).toHaveLength(1);expect(plan.bindings).toHaveLength(2);
  const input:JobInput={id:crypto.randomUUID(),projectId:film.projectId,idempotencyKey:crypto.randomUUID(),tier:"free",stage:"picture-edit",scriptVersion:film.scriptVersion,scriptText:film.scriptText,rightsAttestedAt:film.rightsAttestedAt,animaticJobId:null,animaticApprovedAt:null,totalFrames:timeline.frames,costCapUsd:0,budgetReservedUsd:0,retryPolicy:{maxRetries:0,backoffMs:0},timeoutMs:180000,pictureEdit:plan};
  const admitted=await Promise.all([ledger.admit(film.projectId,input,500),ledger.admit(film.projectId,input,500)]);expect(admitted[0]!.id).toBe(admitted[1]!.id);await expect(ledger.admit(film.projectId,{...input,pictureEdit:{...plan,revision:"0".repeat(64)}},500)).rejects.toThrow("different editorial plan");
  const checkpoint=a.checkpointEdit.bind(a);a.checkpointEdit=async(...args)=>{await checkpoint(...args);throw new LeaseError(args[0].id,"lease_expired",args[1]);};
  const partial=(await processNextJob(queue,aRoot,{...context,artifacts:a,workerId:"edit-interrupted"}))!;a.checkpointEdit=checkpoint;expect(partial.failureReason??partial.cancelReason).toBeUndefined();expect(partial.status).toBe("running");expect(partial.editCheckpoint).toBeTruthy();
  for(const original of [film,later]){for(const row of await admin.sql`select object_key from hv_artifacts where job_id=${original.id}`){keys.add(row.object_key);await objectClient().file(row.object_key).delete();}for(const table of ["hv_outbox","hv_artifacts"])await admin.sql.unsafe('delete from "'+table+'" where job_id=$1',[original.id]);await admin.sql`delete from hv_jobs where id=${original.id}`;}
  const done=(await processNextJob(new PostgresJobStore(worker).forProject(owner.projectId),bRoot,{...context,artifacts:b,workerId:"edit-resumed",now:()=>Date.now()+600000}))!;expect(done.failureReason??done.cancelReason).toBeUndefined();expect(done.status).toBe("done");expect(done.output).toEqual(partial.editCheckpoint);expect(done.resumedCount).toBe(1);await expect(queue.complete(done.id,"edit-interrupted",done.output!)).rejects.toThrow("fence_changed");
  expect(await admin.sql`select id from hv_provider_attempts where job_id=${done.id}`).toHaveLength(0);expect(await admin.sql`select id from hv_cost_events where job_id=${done.id}`).toHaveLength(0);expect(await admin.sql`select job_id from hv_reservations where job_id=${done.id}`).toHaveLength(0);
  await expect(ledger.recordForJob({projectId:owner.projectId,jobId:done.id,stage:"animatic",provider:"fixture",shotId:"edit",model:"fixture",prompt_tokens:0,output_frames:0,gpu_seconds:0,total_cost_usd:.01,at:new Date().toISOString()})).rejects.toThrow("provider costs");
  const continued=createEditPlan(sequence,sequence.sourceRevisions.map(revision=>bindRetainedEditSource(done,revision)),plan.engineVersion,"s3",contentHash("edit-pg-continued"),editRenderReview(timeline));
  await ledger.admit(film.projectId,{...input,id:crypto.randomUUID(),idempotencyKey:crypto.randomUUID(),pictureEdit:continued},500);const next=(await processNextJob(queue,bRoot,{...context,artifacts:b,workerId:"edit-continued"}))!;expect(next.failureReason??next.cancelReason).toBeUndefined();expect(next.status).toBe("done");expect(next.output!.editorial!.conform.pictureFrames).toEqual(done.output!.editorial!.conform.pictureFrames);expect(next.output!.editorial!.plan.bindings[0]!.source.job.pictureEdit).toBeUndefined();
  for(const row of await admin.sql`select object_key from hv_artifacts where job_id=${done.id}`){keys.add(row.object_key);await objectClient().file(row.object_key).delete();}for(const table of ["hv_outbox","hv_artifacts"])await admin.sql.unsafe('delete from "'+table+'" where job_id=$1',[done.id]);await admin.sql`delete from hv_jobs where id=${done.id}`;
  expect((await call(base+"/dialogue-selection","PUT",{jobId:next.id,sourceJobId:sequenceId,expectedVersion:0,expectedOutputRevision:outputRevision(next)},owner.token)).status).toBe(200);
  const retainedSequence=await call(base+"/editorial/sequences","POST",{id:crypto.randomUUID(),label:"Recovered alternate assembly",sources:[{jobId:next.id,sourceRevision:receipt.revision}],firstSourceId:film.id,width:640,height:360,expectedVersion:library.version},owner.token);expect(await retainedSequence.clone().text()).not.toContain('"error"');expect(retainedSequence.status).toBe(201);library=(await projects.authorize(owner.token))!.editLibrary;
  const retainedQuote=await call(base+"/editorial/sequences/"+sequenceId+"/renders","GET",undefined,owner.token);expect(retainedQuote.status).toBe(200);expect((await retainedQuote.json() as any).sources[0].jobId).toBe(next.id);
  const previewId=crypto.randomUUID(),previewPath=base+"/editorial/sequences/"+sequenceId+"/preview",previewBody={id:previewId,historyRevision:sequence.history.revision,from:0,frames:60};
  const previewStarted=await call(previewPath,"POST",previewBody,owner.token);expect(await previewStarted.clone().text()).not.toContain('"error"');expect(previewStarted.status).toBe(202);let preview=await previewStarted.json() as any;const previewQuery="?historyRevision="+sequence.history.revision,previewEnd=Date.now()+60000;
  while(preview.state!=="ready"){if(Date.now()>previewEnd)throw new Error("Retained S3 preview did not finish preparing.");await Bun.sleep(100);const status=await call(previewPath+"/"+previewId+previewQuery,"GET",undefined,owner.token);expect(status.status).toBe(200);preview=await status.json();if(preview.state==="failed")throw new Error(preview.error);}
  for(const [suffix,key]of [["audio/0",preview.audio.sourceKey],["picture/"+film.id+"/0",preview.sources[0].sourceKey]]){const response=await call(previewPath+"/"+previewId+"/"+suffix+previewQuery+"&sourceKey="+key,"GET",undefined,owner.token);expect(response.status).toBe(200);const packet=await decodePreviewPage(new Uint8Array(await response.arrayBuffer()),{sourceKey:key,from:0,sha256:response.headers.get("x-hv-preview-sha256")!});expect(packet.header.frames).toBeGreaterThan(0);expect(packet.header.sourceRevision).toBe(suffix.startsWith("audio")?timeline.revision:receipt.facts.revision);}
  expect((await call(previewPath+"/"+previewId+previewQuery,"DELETE",undefined,owner.token)).status).toBe(200);
  const archive=join(root,"editorial.zip");expect((await exportProjectArchive(admin,owner.projectId,join(root,"editorial-portable"),archive)).jobs).toBe(1);
  const bucket=process.env.HV_S3_BUCKET;process.env.HV_S3_BUCKET=process.env.HV_S3_FLEET_TEST_BUCKET;try{expect((await importProjectArchive(restored,archive,join(root,"editorial-unpacked"),500)).jobs).toBe(1);}finally{process.env.HV_S3_BUCKET=bucket;}
  const restoredJob=(await new PostgresJobStore(restored).get(next.id))!,restoredRoot=join(root,"editorial-restored"),reader=new PostgresArtifactStore(restored,restoredRoot,replica());await reader.restoreCheckpoint(restoredJob);await verifyEditMedia(restoredJob,restoredJob.output!,restoredRoot,async()=>{});expect(restoredJob.output).toEqual(next.output);expect((await new PostgresProjectService(restored).authorize(owner.token))!.editLibrary).toEqual(library);
  // A frozen version can also prepare picture/audio through the restored owner API,
  // with an empty local cache and only the archive's independent S3 bucket available.
  const restoredUrl=new URL(process.env.HV_API_DATABASE_URL!);restoredUrl.pathname="/"+name;const previousBucket=process.env.HV_S3_BUCKET;process.env.HV_S3_BUCKET=process.env.HV_S3_FLEET_TEST_BUCKET;let restoredApi:ApiServer|undefined;
  try{
    restoredApi=createApiServer({port:0,hostname:"127.0.0.1",storage:"postgres",artifactStorage:"s3",databaseUrl:restoredUrl.href,artifactRoot:join(root,"editorial-restored-api"),rateLimit:{api:{limit:10000,windowMs:60000}}});
    const versionBase=base+"/editorial/versions/"+next.id,versionRevision=outputRevision(next),versionCall=(path:string,method="GET",body?:unknown)=>fetch(new URL(versionBase+path,restoredApi!.url),{method,headers:{authorization:"Bearer "+owner.token,"content-type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});
    const metadata=await versionCall("?outputRevision="+versionRevision);expect(metadata.status).toBe(200);expect((await metadata.json() as any).timeline).toEqual(timeline);
    const windowId=crypto.randomUUID(),query="?historyRevision="+sequence.history.revision+"&outputRevision="+versionRevision;expect((await versionCall("/preview","POST",{id:windowId,historyRevision:sequence.history.revision,outputRevision:versionRevision,from:0,frames:60})).status).toBe(202);
    let ready:any;const end=Date.now()+60000;do{if(Date.now()>end)throw new Error("Archived version preview did not prepare.");await Bun.sleep(100);const response=await versionCall("/preview/"+windowId+query);expect(response.status).toBe(200);ready=await response.json();if(ready.state==="failed")throw new Error(ready.error);}while(ready.state!=="ready");
    for(const [suffix,key]of [["audio/0",ready.audio.sourceKey],["picture/"+film.id+"/0",ready.sources[0].sourceKey]]){const response=await versionCall("/preview/"+windowId+"/"+suffix+query+"&sourceKey="+key);expect(response.status).toBe(200);const page=await decodePreviewPage(new Uint8Array(await response.arrayBuffer()),{sourceKey:key,from:0,sha256:response.headers.get("x-hv-preview-sha256")!});expect(page.header.sourceRevision).toBe(suffix.startsWith("audio")?timeline.revision:receipt.facts.revision);}
    expect((await versionCall("/preview/"+windowId+query,"DELETE")).status).toBe(200);
  }finally{await restoredApi?.stop(true);if(previousBucket===undefined)delete process.env.HV_S3_BUCKET;else process.env.HV_S3_BUCKET=previousBucket;}
  const snapshot=await exportStateSnapshot(restored,owner.projectId);expect(snapshot.schema).toBe("hv-state/11");expect(snapshot.jobs).toHaveLength(1);expect(receipt.job.executionCheckpoints!.length).toBeGreaterThan(0);expect(()=>validateSnapshot({...snapshot,schema:"hv-state/10"})).toThrow("schema 11");
},240000);
pgtest("sound sessions resume verified S3 checkpoints, conserve admission, restore alone and enforce library revocation",async()=>{
  const owner=await(await call("/api/projects","POST")).json() as any;ids.push(owner.projectId);const base="/api/projects/"+owner.projectId;
  expect((await call(base+"/script","PUT",{text:"INT. GARDEN - DAY\n\nMarla waves.\n\nMARLA\nWelcome home. We saved a place for you in the garden, beside the old apple tree."},owner.token)).status).toBe(200);expect((await call(base+"/rights","POST",{attested:true},owner.token)).status).toBe(200);
  const queue=new PostgresJobStore(worker).forProject(owner.projectId),ledger=new PostgresCostLedger(worker),aRoot=join(root,"first"),bRoot=join(root,"resumed"),a=new PostgresArtifactStore(worker,aRoot),b=new PostgresArtifactStore(worker,bRoot),context={ledger,reviewQueue:new PostgresReviewQueue(worker)};
  expect((await call(base+"/jobs","POST",{idempotencyKey:"source"},owner.token)).status).toBe(202);const source=(await processNextJob(queue,aRoot,{...context,artifacts:a,workerId:"sound-source"}))!;expect(source.failureReason??source.cancelReason).toBeUndefined();expect(source.status).toBe("done");
  const fixture=soundFixture(owner.projectId),uploaded=await fetch(new URL(base+"/sounds",server.url),{method:"POST",headers:{authorization:"Bearer "+owner.token,"content-type":"audio/wav","x-hv-sound-record":encodeURIComponent(JSON.stringify({label:"Synthetic ambience",rights:SOUND_RIGHTS,expectedVersion:0}))},body:Buffer.from(fixture.wav)});expect(uploaded.status).toBe(201);const asset=(await uploaded.json() as any).asset;for(const kind of ["original","audio"] as const)keys.add(soundAssetObjectKey(asset,kind));
  const conflicts=await Promise.all([call(base+"/sounds/"+asset.id,"PUT",{expectedVersion:1,available:false},owner.token),call(base+"/sounds/"+asset.id,"PUT",{expectedVersion:1,available:false},owner.token)]);expect(conflicts.map(r=>r.status).sort()).toEqual([200,409]);expect((await call(base+"/sounds/"+asset.id,"PUT",{expectedVersion:2,available:true},owner.token)).status).toBe(200);
  const path=base+"/sound-mixes/"+source.id,quote=await(await call(path,"GET",undefined,owner.token)).json() as any;expect(quote.error).toBeUndefined();expect(quote.durationSec).toBeGreaterThanOrEqual(3);const {asset:_receipt,...cue}=soundCue(asset),body={idempotencyKey:crypto.randomUUID(),generationApproved:true,sourceRevision:quote.sourceRevision,engineVersion:quote.engineVersion,session:{reviewed:true,finishing:{schema:"hv-sound-finishing/1",mode:"normalize",targetLufs:-23,ceilingDbtp:-2,rangeLu:7},restoration:{schema:"hv-sound-restoration/1",tracks:[{track:"dialogue",amountDb:3,noiseFloorDb:-65,tracking:false,smoothing:3}]},dialogueGainDb:0,narrationGainDb:0,cues:[{...cue,assetId:asset.id,assetRevision:asset.revision,gainDb:-12,duckDb:-18,loop:true,frames:Math.round(quote.durationSec*48000)}]}};
  const replies=await Promise.all([call(path,"POST",body,owner.token),call(path,"POST",body,owner.token)]);expect(replies.map(r=>r.status)).toEqual([202,202]);const values=await Promise.all(replies.map(r=>r.json() as Promise<any>));expect(values[0].jobId).toBe(values[1].jobId);const id=values[0].jobId;
  const checkpoint=a.checkpointSound.bind(a);a.checkpointSound=async(...args)=>{await checkpoint(...args);throw new LeaseError(args[0].id,"lease_expired",args[1]);};
  const partial=(await processNextJob(queue,aRoot,{...context,artifacts:a,workerId:"sound-interrupted"}))!;a.checkpointSound=checkpoint;expect(partial.failureReason??partial.cancelReason).toBeUndefined();expect(partial.status).toBe("running");expect(partial.soundCheckpoint).toBeTruthy();
  const done=(await processNextJob(new PostgresJobStore(worker).forProject(owner.projectId),bRoot,{...context,artifacts:b,workerId:"sound-resumed",now:()=>Date.now()+600000}))!;expect(done.failureReason??done.cancelReason).toBeUndefined();expect(done.status).toBe("done");expect(done.output!.sound!.report.finishing?.settings.mode).toBe("normalize");expect(done.output!.sound!.report.restoration?.tracks[0]!.settings.track).toBe("dialogue");expect(done.output!.sound!.files.some(f=>f.path.endsWith("/finishing/master.wav"))).toBe(true);expect(done.resumedCount).toBe(1);expect(done.output).toEqual(partial.soundCheckpoint);await expect(queue.complete(id,"sound-interrupted",done.output!)).rejects.toThrow("fence_changed");
  expect(await admin.sql`select id from hv_provider_attempts where job_id=${id}`).toHaveLength(0);expect(await admin.sql`select id from hv_cost_events where job_id=${id}`).toHaveLength(0);expect(await admin.sql`select job_id from hv_reservations where job_id=${id}`).toHaveLength(0);
  await expect(ledger.recordForJob({projectId:owner.projectId,jobId:id,stage:"sound-mix",provider:"fixture",shotId:"sound",model:"fixture",prompt_tokens:0,output_frames:0,gpu_seconds:0,total_cost_usd:.01,at:new Date().toISOString()})).rejects.toThrow("provider costs");
  await b.restoreCheckpoint(done);await verifySoundMedia(done,done.output!,bRoot);const view=await(await call("/api/jobs/"+id,"GET",undefined,owner.token)).json() as any;expect((await fetch(new URL(view.output.mixStemUrl,server.url))).status).toBe(200);
  expect((await call(base+"/dialogue-selection","PUT",{jobId:id,sourceJobId:source.id,expectedVersion:0,expectedOutputRevision:outputRevision(done)},owner.token)).status).toBe(200);
  // Remove the disposable mock source and its mock accounting. The archive must own every required source byte.
  for(const row of await admin.sql`select object_key from hv_artifacts where job_id=${source.id}`)keys.add(row.object_key);
  await admin.sql`delete from hv_reservations where job_id=${source.id}`;for(const table of ["hv_cost_events","hv_provider_attempts","hv_outbox","hv_artifacts"])await admin.sql.unsafe('delete from "'+table+'" where job_id=$1',[source.id]);await admin.sql`delete from hv_jobs where id=${source.id}`;
  const editorial=new PostgresProjectService(admin),sourceReceipt=await inspectEditSource(done,"Finished source",bRoot,async()=>{}),sequenceId=crypto.randomUUID();
  const library=(await editorial.createEditSequence(owner.token,[sourceReceipt],sequenceId,"First picture assembly",done.id,640,360,0))!;
  const edit={kind:"edit" as const,operation:{kind:"marker" as const,marker:{id:"first",frame:1,label:"First read"}},label:"Mark first read"};
  const writes=await Promise.allSettled([editorial.changeEditSequence(owner.token,sequenceId,edit,1,library.sequences[0]!.history.revision),new PostgresProjectService(admin).changeEditSequence(owner.token,sequenceId,edit,1,library.sequences[0]!.history.revision)]);expect(writes.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect(writes.filter(r=>r.status==="rejected")).toHaveLength(1);
  let journal=(await editorial.authorize(owner.token))!.editLibrary;
  journal=(await editorial.changeEditSequence(owner.token,sequenceId,{kind:"cursor",reason:"undo",target:0,label:"Undo marker"},journal.version,journal.sequences[0]!.history.revision))!;
  journal=(await editorial.changeEditSequence(owner.token,sequenceId,{kind:"cursor",reason:"redo",target:1,label:"Restore marker"},journal.version,journal.sequences[0]!.history.revision))!;
  const snapshot=await exportStateSnapshot(admin,owner.projectId);expect(snapshot.schema).toBe("hv-state/11");expect(snapshot.jobs).toHaveLength(1);expect(done.soundMix!.source.base.executionCheckpoints!.length).toBeGreaterThan(0);expect(()=>validateSnapshot({...snapshot,schema:"hv-state/10"})).toThrow("schema 11");expect(()=>validateSnapshot({...snapshot,schema:"hv-state/3"})).toThrow("schema 11");
  const archive=join(root,"sound.zip"),exported=await exportProjectArchive(admin,owner.projectId,join(root,"portable"),archive);expect(exported.jobs).toBe(1);
  const bucket=process.env.HV_S3_BUCKET;process.env.HV_S3_BUCKET=process.env.HV_S3_FLEET_TEST_BUCKET;try{const imported=await importProjectArchive(restored,archive,join(root,"unpacked"),500);expect(imported.jobs).toBe(1);}finally{process.env.HV_S3_BUCKET=bucket;}
  const restoredJob=(await new PostgresJobStore(restored).get(id))!,readerRoot=join(root,"restored"),reader=new PostgresArtifactStore(restored,readerRoot,replica());await reader.restoreCheckpoint(restoredJob);await verifySoundMedia(restoredJob,restoredJob.output!,readerRoot);expect(restoredJob.output).toEqual(done.output);
  const recoveredEdits=(await new PostgresProjectService(restored).authorize(owner.token))!.editLibrary;expect(recoveredEdits).toEqual(journal);expect(editHistoryState(recoveredEdits.sequences[0]!.history).head).toBe(1);
  const blobStore=new SoundBlobStore(readerRoot,replica());expect(await blobStore.read(asset,"original")).toEqual(fixture.wav);expect((await exportStateSnapshot(restored,owner.projectId)).projects.projects[0]!.soundLibrary!.events).toHaveLength(3);
  const retention=new PostgresRetention(admin);await retention.collectOrphans(Date.now()+2*86400000);expect(await objectClient().file(soundAssetObjectKey(asset,"audio")).exists()).toBe(true);
  expect((await call(base+"/sounds/"+asset.id,"PUT",{expectedVersion:3,available:false},owner.token)).status).toBe(200);expect((await fetch(new URL(view.output.mixStemUrl,server.url))).status).toBe(404);expect((await call(base+"/dialogue-selection","PUT",{jobId:id,sourceJobId:source.id,expectedVersion:1,expectedOutputRevision:outputRevision(done)},owner.token)).status).toBeOneOf([400,409]);
  const retainedBytes=readFileSync(join(readerRoot,restoredJob.output!.mp4Path));expect(retainedBytes.length).toBeGreaterThan(0);await admin.sql`update hv_projects set taken_down_at=now() where id=${owner.projectId}`;expect(await retention.purgeProject(owner.projectId)).toBe(true);expect((await exportStateSnapshot(admin,owner.projectId)).projects.projects).toHaveLength(0);
},120000);
