/**
 * HV-024-12: the studio's own ambience beds. A small fixed catalogue of named presets, each a
 * deterministic FFmpeg graph (seeded noise sources, fixed filters and, for one, a tone), chosen per
 * scene from its heading -- INT or EXT, the location's words, and the time of day where that is
 * plain -- and overridable per scene by the creator. No vendor, recording, sample or model output is
 * involved, so a bed costs nothing and its rights record says it was generated by the studio.
 *
 * This module is the pure half: the catalogue, the choice, and the ambience cues laid under a cut's
 * scenes. `generator/src/sound-ambience.ts` renders a preset; the API saves it to the sound library.
 */
import {parseFountain} from "../../parser/src/index";
import {SOUND_RATE,soundFail} from "./sound-assets";

/** Everything that decides a bed's bytes besides the preset itself. Same recipe, preset and FFmpeg runtime: the same bytes. */
export const AMBIENCE_RECIPE={schema:"hv-ambience/1",sampleRate:48000,channels:2,encoding:"pcm_s24le",loopFrames:20*48000,crossfadeFrames:48000,crossfade:"equal-power-tail-over-head",peakDbfs:-18,sourceAmplitude:0.5} as const;

/** How a bed sits in the mix: under the voices, ducked a little when anyone speaks. */
export const AMBIENCE_MIX={gainDb:-6,duckDb:-6,duckAttack:4800,duckRelease:19200,edgeFadeFrames:48000,sceneFadeFrames:12000} as const;

export interface AmbienceTone {hz:number;filter:string;weight:number}
/** `trimDb` (never above 0) lowers a bed below the recipe peak where its spectrum would otherwise read louder than the others. */
export interface AmbiencePreset {id:string;label:string;description:string;color:"white"|"pink"|"brown";seed:number;channel:string;bed:string;trimDb:number;tone?:AmbienceTone}

/**
 * The catalogue. Every periodic part (tremolo rates, the tone) completes a whole number of cycles
 * in the 20-second loop, so the crossfaded seam joins in phase.
 */
export const AMBIENCE_PRESETS:readonly AmbiencePreset[]=Object.freeze([
  {id:"room-tone",label:"Room tone",description:"The quiet air of an interior.",color:"brown",seed:1101,channel:"highpass=f=30,lowpass=f=500",bed:"",trimDb:-2},
  {id:"wind",label:"Wind",description:"Open-air wind with slow gusts.",color:"pink",seed:2203,channel:"highpass=f=80,lowpass=f=1200",bed:"tremolo=f=0.15:d=0.5",trimDb:-0.5},
  {id:"rain",label:"Rain",description:"Steady rain.",color:"white",seed:3307,channel:"highpass=f=400,lowpass=f=4000",bed:"",trimDb:-6},
  {id:"traffic",label:"Traffic hum",description:"A city street's distant traffic.",color:"brown",seed:4409,channel:"highpass=f=25,lowpass=f=350",bed:"tremolo=f=0.1:d=0.4",trimDb:0},
  {id:"surf",label:"Surf",description:"Waves breaking on a shore.",color:"pink",seed:5503,channel:"highpass=f=60,lowpass=f=2500",bed:"tremolo=f=0.1:d=0.85",trimDb:0},
  {id:"crowd",label:"Crowd murmur",description:"A busy room's indistinct murmur.",color:"pink",seed:6607,channel:"highpass=f=250,lowpass=f=2500",bed:"tremolo=f=2.5:d=0.25",trimDb:-3.5},
  {id:"night",label:"Night air",description:"Still night air with distant insects.",color:"pink",seed:7703,channel:"highpass=f=100,lowpass=f=800",bed:"",trimDb:-1.5,tone:{hz:4500,filter:"tremolo=f=15:d=1,tremolo=f=0.5:d=1",weight:0.15}},
]);
export type AmbiencePresetId=string;
export const AMBIENCE_NONE="none";

export function ambiencePreset(id:unknown):AmbiencePreset{const preset=AMBIENCE_PRESETS.find(value=>value.id===id);if(!preset)soundFail("Choose an ambience from the studio's catalogue: "+AMBIENCE_PRESETS.map(value=>value.id).join(", ")+", or none.");return preset;}

// Unicode-aware word edges: `\\b` without the u flag treats É as a boundary, so CAFÉ would never match (review of HV-024-12).
const word=(pattern:string)=>new RegExp("(?<![\\p{L}\\p{N}_])(?:"+pattern+")(?![\\p{L}\\p{N}_])","iu");
/** Location words, strongest first. The first rule a heading matches chooses its bed. */
const LOCATION_RULES:readonly {preset:string;words:RegExp;exterior?:true}[]=[
  {preset:"rain",words:word("RAIN|RAINING|RAINY|STORM|STORMY|DOWNPOUR|DRIZZLE")},
  {preset:"surf",words:word("BEACH|SHORE|SHORELINE|SEASHORE|COAST|OCEAN|SEA|SURF|PIER|HARBOU?R|DOCKS?|BOARDWALK|CLIFFS?")},
  {preset:"crowd",words:word("BAR|PUB|RESTAURANT|CAFE|CAFÉ|DINER|CANTEEN|CAFETERIA|MARKET|STATION|AIRPORT|TERMINAL|PARTY|CLUB|NIGHTCLUB|STADIUM|MALL|LOBBY|BALLROOM|CASINO|CONCOURSE")},
  {preset:"traffic",words:word("STREET|CITY|ROAD|HIGHWAY|FREEWAY|AVENUE|BOULEVARD|PARKING|ALLEY|SIDEWALK|DOWNTOWN|INTERSECTION|CROSSWALK|TRAFFIC|CAR|TAXI|CAB|BUS")},
  {preset:"wind",words:word("FOREST|WOODS|FIELD|FIELDS|MOUNTAIN|MOUNTAINS|DESERT|HILL|HILLS|MEADOW|PRAIRIE|ROOFTOP|CANYON|MOOR|CLEARING|VALLEY"),exterior:true},
];
const INTERIOR=/^\s*\.?\s*(INT|I\/E|INT\.?\/EXT)\b/i,EXTERIOR=/^\s*\.?\s*(EXT|EST)\b/i,NIGHT=word("NIGHT|MIDNIGHT|LATE NIGHT");

/**
 * The bed a scene heading asks for. Weather and the strongest location word win; an exterior with
 * no telling word is wind, or night air when the heading says NIGHT; an interior is room tone. A
 * heading that says neither INT nor EXT is treated as an interior. Never throws, never returns none:
 * silence is the creator's choice, not the studio's.
 */
export function ambienceForHeading(heading:string):AmbiencePreset{
  const text=typeof heading==="string"?heading.slice(0,1000):"",exterior=EXTERIOR.test(text)&&!INTERIOR.test(text),mixed=/^\s*\.?\s*(I\/E|INT\.?\/EXT)\b/i.test(text);
  for(const rule of LOCATION_RULES){if(rule.exterior&&!(exterior||mixed))continue;if(rule.words.test(text))return ambiencePreset(rule.preset);}
  if(exterior)return ambiencePreset(NIGHT.test(text)?"night":"wind");
  return ambiencePreset("room-tone");
}

export interface AmbienceScene {sceneNumber:number;heading:string;start:number;frames:number;preset:string|null;chosenBy:"heading"|"creator"}

/**
 * The cut's scenes as 48 kHz sample spans, from its shots in cut order (`shot-<scene>-<n>`, each
 * `frames` long at 48 kHz) and the screenplay's headings. Consecutive shots of one scene make one
 * span. Overrides map a scene number to a preset id or "none"; an unknown scene or preset is refused
 * rather than ignored. When the shots cannot be read as scenes, the whole cut is one span under the
 * first heading, so the film still gets a bed.
 */
export function ambienceScenes(scriptText:string,shots:readonly {shotId:string;frames:number}[],totalFrames:number,overrides:unknown={}):AmbienceScene[]{
  if(!Number.isSafeInteger(totalFrames)||totalFrames<1||totalFrames>SOUND_RATE*3600)soundFail("The cut's sound timeline is out of range.");
  if(!overrides||typeof overrides!=="object"||Array.isArray(overrides))soundFail("Give ambience overrides as scene numbers mapped to a preset or none.");
  const headings=parseFountain(typeof scriptText==="string"?scriptText:"").scenes.map(scene=>scene.heading);
  const spans:{sceneNumber:number;start:number;frames:number}[]=[];let offset=0,readable=shots.length>0;
  for(const shot of shots){const match=/^shot-([1-9][0-9]{0,3})-[1-9][0-9]*$/.exec(shot.shotId),sceneNumber=match?Number(match[1]):0;
    if(!match||!Number.isSafeInteger(shot.frames)||shot.frames<1||sceneNumber>headings.length){readable=false;break;}
    const last=spans.at(-1);if(last&&last.sceneNumber===sceneNumber)last.frames+=shot.frames;else spans.push({sceneNumber,start:offset,frames:shot.frames});offset+=shot.frames;}
  if(!readable||offset!==totalFrames){spans.length=0;spans.push({sceneNumber:1,start:0,frames:totalFrames});}
  const choices=new Map<number,string>();
  for(const [key,value]of Object.entries(overrides as Record<string,unknown>)){const sceneNumber=Number(key);
    if(!/^[1-9][0-9]{0,3}$/.test(key)||!spans.some(span=>span.sceneNumber===sceneNumber))soundFail("Scene "+key.slice(0,12)+" is not in this cut, so its ambience cannot be chosen.");
    choices.set(sceneNumber,value===AMBIENCE_NONE?AMBIENCE_NONE:ambiencePreset(value).id);}
  return spans.map(span=>{const heading=headings[span.sceneNumber-1]??"",chosen=choices.get(span.sceneNumber);
    return {...span,heading,preset:chosen===undefined?ambienceForHeading(heading).id:chosen===AMBIENCE_NONE?null:chosen,chosenBy:chosen===undefined?"heading" as const:"creator" as const};});
}

export interface AmbienceAssetRef {id:string;revision:string;frames:number}
export interface AmbienceCueRequest {id:string;assetId:string;assetRevision:string;role:"ambience";start:number;frames:number;trimIn:number;trimOut:number;loop:true;gainDb:number;balance:number;fadeIn:number;fadeOut:number;duckDb:number;duckAttack:number;duckRelease:number}

/**
 * The ambience cues for a sound-mix session, in the shape the sound-mix route takes. Neighbouring
 * scenes with the same bed share one cue, so a cut between them does not dip. A bed fades in over a
 * second at the film's start, out over a second at its end, and over a quarter-second at a scene
 * boundary where the bed changes; no fade is longer than a quarter of its cue. Cue ids are derived
 * from `idSeed` (a UUID) so a retried request asks for the same session.
 */
export function ambienceCues(scenes:readonly AmbienceScene[],assets:ReadonlyMap<string,AmbienceAssetRef>,totalFrames:number,idSeed:string):AmbienceCueRequest[]{
  const runs:{preset:string;start:number;frames:number}[]=[];
  for(const scene of scenes){if(!scene.preset)continue;const last=runs.at(-1);if(last&&last.preset===scene.preset&&last.start+last.frames===scene.start)last.frames+=scene.frames;else runs.push({preset:scene.preset,start:scene.start,frames:scene.frames});}
  if(runs.length>63)soundFail("This cut has more scene beds than one sound session can hold; choose the same ambience for neighbouring scenes or none for some.");
  if(!/^[a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12}$/.test(idSeed))soundFail("Invalid ambience cue identity.");
  return runs.map((run,index)=>{const asset=assets.get(run.preset);if(!asset)soundFail("The "+run.preset+" ambience is not in the sound library.");
    const edgeIn=run.start===0?AMBIENCE_MIX.edgeFadeFrames:AMBIENCE_MIX.sceneFadeFrames,edgeOut=run.start+run.frames===totalFrames?AMBIENCE_MIX.edgeFadeFrames:AMBIENCE_MIX.sceneFadeFrames,quarter=Math.floor(run.frames/4);
    return {id:idSeed.slice(0,24)+(index+1).toString(16).padStart(12,"0"),assetId:asset.id,assetRevision:asset.revision,role:"ambience" as const,start:run.start,frames:run.frames,trimIn:0,trimOut:asset.frames,loop:true as const,
      gainDb:AMBIENCE_MIX.gainDb,balance:0,fadeIn:Math.min(edgeIn,quarter),fadeOut:Math.min(edgeOut,quarter),duckDb:AMBIENCE_MIX.duckDb,duckAttack:AMBIENCE_MIX.duckAttack,duckRelease:AMBIENCE_MIX.duckRelease};});
}

/** The rights record a generated bed carries. Its credit is the honest one: the studio made it. */
export function ambienceRights(preset:AmbiencePreset){
  return {basis:"original" as const,attested:true as const,credit:"Ambience generated by the studio",
    source:`Generated by this studio from ambience preset ${preset.id} (recipe ${AMBIENCE_RECIPE.schema}, seed ${preset.seed})`,
    terms:"Generated by the application's own code with FFmpeg's seeded noise and tone sources and fixed filters; no third-party recording, sample, vendor or model output."};
}
