import type {Job,JobInput} from "../../queue/src/index";
import type {Project,PersistedProject} from "../../api/src/index";
import type {RenderFile} from "./shot-reuse";
import {contentHash} from "../../generator/src/capabilities";
import {audioHash,audioNumber,audioRecord} from "./audio-performances";
import {dialogueSource,dialogueReportAuditions} from "./dialogue-replacement";
import {assertDialoguePermissions,retainedDialogueTime,validateDialogueOutput} from "./dialogue-jobs";
import {assertLipSyncPermission,validateLipSyncOutput,validateLipSyncReviews} from "./lipsync";
import {configuredLipSyncPolicy,validateLipSyncPolicy} from "./lipsync-policy";
import {configuredAudioPolicies} from "../../generator/src/audio-config";
import {assertRetainedAuditionPermission} from "./retained-auditions";
import {SOUND_RATE,SOUND_FRAME_BYTES,soundFail,soundId,soundAssetAvailable,emptySoundLibrary,validateSoundLibrary} from "./sound-assets";
import {SOUND_MIX_RECIPE,SOUND_STEMS,soundSession,validateSoundSession,soundSessionAssets,soundCopiedAssetName,type SoundSession,type SoundStem} from "./sound-session";
export interface SoundSource {schema:"hv-sound-source/1";projectId:string;jobId:string;completedAt:string;linkExpiresAt:string;outputRevision:string;base:Job;baseFiles:RenderFile[];files:{name:string;file:RenderFile}[];revision:string}
export interface SoundPlan {schema:"hv-sound-plan/1";source:SoundSource;session:SoundSession;engineVersion:string;storage:"local"|"s3";requestHash:string;revision:string}
export function soundCueSheet(plan:SoundPlan,jobId:string){return {schema:"hv-sound-cue-sheet/1",pictureJobId:soundBaseFilm(plan.source.base).id,sourceJobId:plan.source.jobId,soundJobId:soundId(jobId),planRevision:plan.revision,sampleRate:SOUND_RATE,dialogueGainDb:plan.session.dialogueGainDb,narrationGainDb:plan.session.narrationGainDb,cues:plan.session.cues.map(({asset,...cue})=>({...cue,recording:asset.label,recordingId:asset.id,recordingRevision:asset.revision,originalSha256:asset.original.sha256,rights:asset.rights}))};}
export interface SoundMixReport {schema:"hv-sound-result/1";plan:SoundPlan;recipeRevision:string;videoSha256:string;videoStreamSha256:string;totalVideoFrames:number;voiceWindows:{start:number;end:number}[];baseVoiceSourceSha256:{dialogue:string;narration:string};baseVoiceSha256:{dialogue:string;narration:string};stems:Record<SoundStem,string>;peaks:Record<SoundStem,number>}
export interface SoundOutput {schema:"hv-sound-output/1";report:SoundMixReport;files:RenderFile[];revision:string}
const same=(a:unknown,b:unknown)=>contentHash(a)===contentHash(b);
function ownedFile(file:RenderFile,projectId:string,jobId:string):void{audioRecord(file,["path","bytes","sha256"]);audioHash(file.sha256);audioNumber(file.bytes,1,8*1024**3,"Sound artifact bytes",true);if(typeof file.path!=="string"||file.path.length>1024||!file.path.startsWith(projectId+"/"+jobId+"/")||!/^[A-Za-z0-9._/-]+$/.test(file.path)||file.path.split("/").some(p=>!p||p==="."||p===".."))soundFail("Sound media escaped its owner.");}
export function soundBaseFilm(base:Job):Job{return base.dialogueReplacement?.source??base.lipSync?.source.film??base;}
export function soundBaseDialogue(base:Job){return base.output?.dialogue?.report??base.lipSync?.source.dialogue;}
export function soundBaseFrames(base:Job):number{return soundBaseDialogue(base)?.totalFrames??dialogueSource(base,Date.parse(base.completedAt??"")).totalFrames;}
export function soundCaptionLanguage(base:Job):string{return soundBaseDialogue(base)?.plan.dubLanguage??"en";}
export function soundVoiceWindows(base:Job):{start:number;end:number}[]{
  const dialogue=soundBaseDialogue(base),windows:{start:number;end:number}[]=[];const add=(start:number,end:number)=>{if(end>start)windows.push({start:Math.round(start*SOUND_RATE/22050),end:Math.round(end*SOUND_RATE/22050)});};
  if(dialogue){for(const line of dialogue.lines){const read=line.audition?.conversion;add(line.startSample+(read?.speechStartSample??0),read?line.startSample+read.speechEndSample:line.endSample);}if(dialogue.narration)for(const [i,cue]of dialogue.narration.track.cues.entries()){const read=dialogue.narration.conversions[i]!.report;add(cue.startSample+read.speechStartSample,cue.startSample+read.speechEndSample);}}
  else{let offset=0;for(const shot of base.output!.shotRenders!){for(const line of shot.clip.speech?.lines??[])add(offset+line.startSample,offset+line.endSample);offset+=Math.round(shot.clip.durationSec*30)*735;}}
  return windows.sort((a,b)=>a.start-b.start||a.end-b.end);
}
function validateSoundBase(base:Job):void{
  if(!base||base.soundMix||base.soundCheckpoint||base.output?.sound||!base.completedAt||!base.output||base.status!=="done")soundFail("Choose a completed film, dialogue or accepted lip-sync version.");
  if(base.dialogueReplacement)validateDialogueOutput(base,base.output,retainedDialogueTime(base));
  else if(base.lipSync){validateLipSyncOutput(base,base.output);validateLipSyncReviews(base.lipSyncReviews!,contentHash(base.output));if(base.lipSyncReviews?.entries.at(-1)?.decision!=="accept")soundFail("Accept the lip-sync quality review before editing its soundtrack.");}
  else dialogueSource(base,Date.parse(base.completedAt));
}
export function soundBaseKnownFiles(base:Job):RenderFile[]{return base.output!.dialogue?.files??base.output!.lipSync?.files??base.output!.shotRenders!.flatMap(r=>Object.values(r.files).filter(Boolean) as RenderFile[]);}
/** A continued mix keeps one original picture/performance receipt and owned copies, without nesting prior mix jobs. */
export async function retainSoundSource(job:Job,info:(path:string)=>Promise<RenderFile>,now=Date.now()):Promise<SoundSource>{
  if(job.status!=="done"||!job.output||!job.completedAt||!job.linkExpiresAt||Date.parse(job.linkExpiresAt)<=now)soundFail("Choose an available retained film or sound version.");
  let base:Job,baseFiles:RenderFile[],files:SoundSource["files"];
  if(job.soundMix){validateSoundOutput(job,job.output);base=job.soundMix.source.base;baseFiles=job.soundMix.source.baseFiles;const prefix=job.output.mp4Path.slice(0,-"export.mp4".length);files=baseFiles.map(original=>{const name="source/"+original.path,file=job.output!.sound!.files.find(f=>f.path===prefix+name);if(!file)soundFail("The sound version lost original media.");return {name,file};});}
  else{base=job;validateSoundBase(base);const known=new Map(soundBaseKnownFiles(base).map(f=>[f.path,f]));for(const path of [base.output!.mp4Path,base.output!.manifestPath,base.output!.captionsPath])if(!known.has(path))known.set(path,await info(path));baseFiles=[...known.values()].sort((a,b)=>a.path.localeCompare(b.path));files=baseFiles.map(file=>({name:"source/"+file.path,file}));}
  const data={schema:"hv-sound-source/1" as const,projectId:job.projectId,jobId:job.id,completedAt:job.completedAt,linkExpiresAt:job.linkExpiresAt,outputRevision:contentHash(job.output),base:structuredClone(base),baseFiles:structuredClone(baseFiles),files:structuredClone(files)};return validateSoundSource({...data,revision:contentHash(data)},now);
}
export function validateSoundSource(source:SoundSource,now?:number):SoundSource{
  audioRecord(source,["schema","projectId","jobId","completedAt","linkExpiresAt","outputRevision","base","baseFiles","files","revision"]);soundId(source.projectId);soundId(source.jobId);audioHash(source.outputRevision);validateSoundBase(source.base);
  if(source.schema!=="hv-sound-source/1"||source.base.projectId!==source.projectId||!Number.isFinite(Date.parse(source.completedAt))||!Number.isFinite(Date.parse(source.linkExpiresAt))||Date.parse(source.linkExpiresAt)<=Date.parse(source.completedAt)||now!==undefined&&Date.parse(source.linkExpiresAt)<=now)soundFail("The selected sound source is unavailable or expired.");
  if(!Array.isArray(source.baseFiles)||!Array.isArray(source.files)||source.baseFiles.length!==source.files.length||source.files.length>20000||new Set(source.baseFiles.map(f=>f.path)).size!==source.baseFiles.length)soundFail("Invalid retained sound source inventory.");
  const known=soundBaseKnownFiles(source.base);if(known.some(f=>!source.baseFiles.some(b=>same(f,b)))||[source.base.output!.mp4Path,source.base.output!.manifestPath,source.base.output!.captionsPath].some(path=>!source.baseFiles.some(f=>f.path===path)))soundFail("The sound source lost original picture, voice or caption evidence.");
  const expected=new Set([...known.map(f=>f.path),source.base.output!.mp4Path,source.base.output!.manifestPath,source.base.output!.captionsPath]);if(source.baseFiles.length!==expected.size)soundFail("Unexpected sound source files.");
  for(const [i,original]of source.baseFiles.entries()){ownedFile(original,source.projectId,source.base.id);const item=source.files[i]!;audioRecord(item,["name","file"]);ownedFile(item.file,source.projectId,source.jobId);if(item.name!=="source/"+original.path||item.file.sha256!==original.sha256||item.file.bytes!==original.bytes)soundFail("An owned sound source copy changed.");}
  if(new Set(source.files.map(f=>f.file.path)).size!==source.files.length)soundFail("Duplicate sound source copies.");const {revision,...data}=source;if(contentHash(data)!==revision)soundFail("The sound source receipt changed.");return structuredClone(source);
}
export function createSoundPlan(source:SoundSource,input:unknown,engineVersion:string,storage:SoundPlan["storage"],requestHash:string,now=Date.now()):SoundPlan{
  validateSoundSource(source,now);if(!/^ffmpeg-sound-[a-f0-9]{64}$/.test(engineVersion)||!["local","s3"].includes(storage))soundFail("Review the current sound conversion runtime and storage.");audioHash(requestHash);
  const session=soundSession(input,source.projectId,soundBaseFrames(source.base)*1600),data={schema:"hv-sound-plan/1" as const,source:structuredClone(source),session,engineVersion,storage,requestHash};return {...data,revision:contentHash(data)};
}
export function validateSoundPlan(plan:SoundPlan,now?:number):void{audioRecord(plan,["schema","source","session","engineVersion","storage","requestHash","revision"]);validateSoundSource(plan.source,now);validateSoundSession(plan.session,plan.source.projectId,soundBaseFrames(plan.source.base)*1600);if(plan.schema!=="hv-sound-plan/1"||!/^ffmpeg-sound-[a-f0-9]{64}$/.test(plan.engineVersion)||!["local","s3"].includes(plan.storage))soundFail("Invalid sound job plan.");audioHash(plan.requestHash);const {revision,...data}=plan;if(contentHash(data)!==revision)soundFail("The sound job plan changed.");}
export function validateSoundJob(job:Job|JobInput,now?:number):void{
  if((job.stage==="sound-mix")!==Boolean(job.soundMix))soundFail("A sound job needs its own reviewed session.");if(!job.soundMix){if(job.soundCheckpoint||job.output?.sound)soundFail("A different job cannot carry a sound mix.");return;}const plan=job.soundMix;validateSoundPlan(plan,now);
  if(job.id===plan.source.jobId||job.projectId!==plan.source.projectId||job.scriptText!==plan.source.base.scriptText||job.scriptVersion!==plan.source.base.scriptVersion||job.totalFrames!==soundBaseFrames(plan.source.base)||!job.rightsAttestedAt||job.costCapUsd!==0||job.budgetReservedUsd!==0||job.providerPlan||job.providerSpec||job.casting||job.direction||job.shotReuse||job.shotTakes||job.characterSheet||job.dialogueReplacement||job.dialogueCheckpoint||job.audioTake||job.audioOutput||job.audioCheckpoint||job.lipSync||job.lipSyncPrepared||job.lipSyncCheckpoint||job.lipSyncReviews||job.animaticJobId||job.animaticApprovedAt)soundFail("Invalid isolated sound job context.");
}
export function assertSoundIdempotency(existing:Job|undefined,input:JobInput):void{if(existing&&(existing.soundMix||input.soundMix||existing.stage==="sound-mix"||input.stage==="sound-mix")&&(existing.stage!==input.stage||existing.soundMix?.revision!==input.soundMix?.revision))soundFail("This key belongs to a different sound session. Use a new key for a new version.");}
export function assertSoundPermission(plan:SoundPlan,project:Project|PersistedProject|null|undefined,now=Date.now()):void{
  validateSoundPlan(plan);const base=plan.source.base;assertDialoguePermissions(soundBaseFilm(base),project,now);const policies=configuredAudioPolicies(),dialogue=soundBaseDialogue(base);
  if(dialogue)for(const {audition}of dialogueReportAuditions(dialogue))if(audition)assertRetainedAuditionPermission(audition.source,project??undefined,policies.find(p=>p.voiceId===audition.source.take.policy.voiceId),now);
  if(base.lipSync){assertLipSyncPermission(base.lipSync,project,now);const policy=configuredLipSyncPolicy();if(!policy||validateLipSyncPolicy(policy,now).permissionRevision!==base.lipSync.policy.permissionRevision)soundFail("The retained lip-sync provider permission is unavailable.");}
  const library=validateSoundLibrary(project?.soundLibrary??emptySoundLibrary(),plan.source.projectId);if(soundSessionAssets(plan.session).some(asset=>!soundAssetAvailable(library,asset)))soundFail("A sound recording's use was disabled or its receipt changed.");
}
export function assertSoundSourceAvailable(plan:SoundPlan,job:Job|undefined,now=Date.now()):void{validateSoundSource(plan.source,now);if(!job||job.id!==plan.source.jobId||job.projectId!==plan.source.projectId||job.status!=="done"||!job.output||contentHash(job.output)!==plan.source.outputRevision||job.completedAt!==plan.source.completedAt||job.linkExpiresAt!==plan.source.linkExpiresAt)soundFail("The selected sound source changed or is no longer available.");if(job.lipSync&&contentHash(job.lipSyncReviews)!==contentHash(plan.source.base.lipSyncReviews))soundFail("The lip-sync quality review changed. Review this source again before mixing.");}
export function validateSoundOutput(job:Job|JobInput,output:NonNullable<Job["output"]>):void{
  validateSoundJob(job);audioRecord(output,["mp4Path","captionsPath","manifestPath","hlsPlaylistPath","sound"]);const result=output.sound!,plan=job.soundMix!;audioRecord(result,["schema","report","files","revision"]);const report=result.report;audioRecord(report,["schema","plan","recipeRevision","videoSha256","videoStreamSha256","totalVideoFrames","voiceWindows","baseVoiceSourceSha256","baseVoiceSha256","stems","peaks"]);
  if(result.schema!=="hv-sound-output/1"||report.schema!=="hv-sound-result/1"||!same(report.plan,plan)||report.recipeRevision!==contentHash(SOUND_MIX_RECIPE)||report.totalVideoFrames!==job.totalFrames)soundFail("The sound output differs from its reviewed plan.");
  for(const hash of [report.videoSha256,report.videoStreamSha256])audioHash(hash);for(const hashes of [report.baseVoiceSourceSha256,report.baseVoiceSha256]){audioRecord(hashes,["dialogue","narration"]);Object.values(hashes).forEach(h=>audioHash(h));}audioRecord(report.stems,[...SOUND_STEMS]);Object.values(report.stems).forEach(h=>audioHash(h));audioRecord(report.peaks,[...SOUND_STEMS]);Object.values(report.peaks).forEach(p=>audioNumber(p,0,8388608,"Sound sample peak",true));
  if(!same(report.voiceWindows,soundVoiceWindows(plan.source.base)))soundFail("The sound mix changed measured voice timing.");
  if(!Array.isArray(report.voiceWindows)||report.voiceWindows.length>2048)soundFail("Invalid retained voice timing.");for(const w of report.voiceWindows){audioRecord(w,["start","end"]);audioNumber(w.start,0,plan.session.totalFrames-1,"Voice start",true);audioNumber(w.end,w.start+1,plan.session.totalFrames,"Voice end",true);}
  const directory=output.mp4Path.slice(0,-"export.mp4".length);if(!directory.startsWith(job.projectId+"/"+job.id+"/")||output.mp4Path!==directory+"export.mp4"||output.captionsPath!==directory+"captions.vtt"||output.manifestPath!==directory+"provenance.json"||output.hlsPlaylistPath!==directory+"hls/index.m3u8")soundFail("Sound output escaped its job.");
  if(!Array.isArray(result.files)||result.files.length>30000||new Set(result.files.map(f=>f.path)).size!==result.files.length)soundFail("Invalid sound output inventory.");result.files.forEach(f=>ownedFile(f,job.projectId,job.id));
  const find=(name:string)=>{const f=result.files.find(f=>f.path===directory+name);if(!f)soundFail("The sound export is missing "+name+".");return f;};for(const name of ["export.mp4","captions.vtt","provenance.json","cue-sheet.json","hls/index.m3u8"])find(name);
  for(const item of plan.source.files){const f=find(item.name);if(f.sha256!==item.file.sha256||f.bytes!==item.file.bytes)soundFail("The sound export changed original media evidence.");}
  for(const asset of soundSessionAssets(plan.session))for(const kind of ["original","audio"] as const){const f=find(soundCopiedAssetName(asset,kind));if(f.sha256!==asset[kind].sha256||f.bytes!==asset[kind].bytes)soundFail("A sound cue lost its original recording or conversion.");}
  for(const stem of SOUND_STEMS){const f=find("stems/"+stem+".wav");if(f.sha256!==report.stems[stem]||f.bytes!==44+plan.session.totalFrames*SOUND_FRAME_BYTES)soundFail("A sound stem changed length or checksum.");}
  for(const stem of ["dialogue","narration"] as const){const f=find("voices/"+stem+".wav");if(f.sha256!==report.baseVoiceSha256[stem]||f.bytes!==44+plan.session.totalFrames*SOUND_FRAME_BYTES)soundFail("A converted voice stem changed.");}
  const required=new Set(["export.mp4","captions.vtt","provenance.json","cue-sheet.json","hls/index.m3u8",...plan.source.files.map(f=>f.name),...soundSessionAssets(plan.session).flatMap(a=>[soundCopiedAssetName(a,"original"),soundCopiedAssetName(a,"audio")]),...SOUND_STEMS.map(s=>"stems/"+s+".wav"),"voices/dialogue.wav","voices/narration.wav"]);
  if(result.files.some(f=>!required.has(f.path.slice(directory.length))&&!/^hls\/segment-\d{3,5}\.ts$/.test(f.path.slice(directory.length)))||find("export.mp4").sha256!==report.videoSha256)soundFail("Unexpected sound export artifacts.");
  const {revision,...data}=result;if(contentHash(data)!==revision)soundFail("The sound export receipt changed.");
}
