import {expect,test} from "bun:test";
import {readFileSync} from "node:fs";
import {dubStudio} from "../../../test/fixtures/dub-studio";
import {ProjectService} from "../src/index";
import {contentHash} from "../../generator/src/capabilities";
import {inspectEditSource} from "../../generator/src/edit-source-media";
import {bindOriginalEditSource} from "../../planner/src/edit-jobs";
import {deriveEditAssemblyParent,validateProjectAssemblyLibrary,type EditAssemblyCarrier} from "../../planner/src/edit-assembly-parent";
import {emptyEditAssemblyLibrary} from "../../planner/src/edit-assembly-proposals";
import {emptyEditLibrary} from "../../planner/src/edit-library";
import {editHistoryState} from "../../planner/src/edit-history";

function seal<T extends {revision:string}>(value:T):T {const {revision:_revision,...data}=value;return {...data,revision:contentHash(data)} as T;}
test("historical project snapshots omit an empty assembly library and roundtrip without hash changes",()=>{
  const before=process.env.HV_TOKEN_SECRET;process.env.HV_TOKEN_SECRET="assembly-project-fixture-secret-at-least-thirty-two-characters";
  try{const service=new ProjectService(),owner=service.createAnonymousProject(),snapshot=service.snapshot();expect(snapshot.projects[0]!.assemblyLibrary).toBeUndefined();expect(service.peekProject(owner.projectId)!.assemblyLibrary).toEqual(emptyEditAssemblyLibrary());expect(ProjectService.fromState(snapshot).snapshot()).toEqual(snapshot);expect(contentHash(ProjectService.fromState(snapshot).snapshot())).toBe(contentHash(snapshot));expect(validateProjectAssemblyLibrary(emptyEditAssemblyLibrary(),owner.projectId,emptyEditLibrary())).toEqual(emptyEditAssemblyLibrary());}finally{if(before===undefined)delete process.env.HV_TOKEN_SECRET;else process.env.HV_TOKEN_SECRET=before;}
});

test("project assembly mutations derive saved parents, persist independent acceptance and fence stale or withdrawn originals without jobs",async()=>{
  const f=await dubStudio();try{
    const receipt=await inspectEditSource(f.film,"Retained performances",f.paths.artifactRoot,async()=>{}),binding=bindOriginalEditSource(receipt),sequenceId="parent-sequence",editorial=f.projects.createEditSequence(f.owner.token,[receipt],sequenceId,"Parent cut",receipt.facts.id,320,180,0,Date.now(),[binding])!,history=editorial.sequences[0]!.history.revision,originalSequence=structuredClone(editorial.sequences[0]!);
    const carriers=():EditAssemblyCarrier[]=>[{binding:structuredClone(binding),current:f.store.get(binding.owner.jobId)}],expected={libraryVersion:0,historyRevision:history},input={id:"proposal",label:"Reviewed alternate",purpose:"trailer" as const,ranges:[{id:"opening",fromFrame:0,toFrame:Math.min(30,receipt.facts.frames),reason:"Retain the opening performance."}]},parent=deriveEditAssemblyParent(f.owner.projectId,editorial,sequenceId,history);
    expect(parent.sourceReceipts).toEqual([{sourceId:receipt.facts.id,receiptRevision:receipt.revision}]);expect(parent.timeline).toEqual(editHistoryState(originalSequence.history).timeline);expect(()=>deriveEditAssemblyParent(f.owner.projectId,editorial,sequenceId,contentHash("stale"))).toThrow("history changed");
    const queueBefore=readFileSync(f.paths.queuePath,"utf8"),saved=f.projects.createAssemblyProposal(f.owner.token,sequenceId,input,expected,carriers())!;expect(saved.version).toBe(1);expect(saved.proposals[0]!.plan.parent).toEqual(parent);expect(new ProjectService(f.paths.statePath).peekProject(f.owner.projectId)!.assemblyLibrary).toEqual(saved);expect(f.projects.peekProject(f.owner.projectId)!.editLibrary.sequences[0]).toEqual(originalSequence);
    const persisted=readFileSync(f.paths.statePath,"utf8"),proposal=saved.proposals[0]!,fresh={libraryVersion:1,historyRevision:history};
    for(const attempt of [()=>f.projects.createAssemblyProposal(f.owner.token,sequenceId,{...input,id:"second"},expected,carriers()),()=>f.projects.createAssemblyProposal(f.owner.token,sequenceId,{...input,id:"second",parent} as any,fresh,carriers()),()=>f.projects.createAssemblyProposal(f.owner.token,sequenceId,{...input,id:"second"},{...fresh,extra:true} as any,carriers()),()=>f.projects.acceptAssemblyProposal(f.owner.token,proposal.id,proposal.revision,"assembly",fresh,[]),()=>f.projects.acceptAssemblyProposal(f.owner.token,proposal.id,proposal.revision,"assembly",fresh,[{binding,current:undefined}]),()=>f.projects.acceptAssemblyProposal(f.owner.token,proposal.id,proposal.revision,"assembly",fresh,[{binding,current:{...f.film,linkExpiresAt:new Date(0).toISOString()}}]),()=>f.projects.acceptAssemblyProposal(f.owner.token,proposal.id,proposal.revision,"assembly",fresh,[{binding:{...binding,owner:{...binding.owner,projectId:"foreign"}},current:f.film}])]){expect(attempt).toThrow();expect(readFileSync(f.paths.statePath,"utf8")).toBe(persisted);}
    const malformed=f.projects.snapshot(),p=malformed.projects.find(p=>p.id===f.owner.projectId)!,assemblyLibrary=p.assemblyLibrary!;assemblyLibrary.proposals[0]!.plan.parent.sourceReceipts[0]!.receiptRevision=contentHash("another receipt");assemblyLibrary.proposals[0]!.plan=seal(assemblyLibrary.proposals[0]!.plan);assemblyLibrary.proposals[0]=seal(assemblyLibrary.proposals[0]!);p.assemblyLibrary=seal(assemblyLibrary);expect(()=>ProjectService.fromState(malformed)).toThrow("owned original receipt");
    const revised=f.projects.reviseAssemblyProposal(f.owner.token,proposal.id,{label:"Shorter alternate",purpose:"sixty-second",ranges:[{...input.ranges[0]!,toFrame:1}]},{...fresh,proposalRevision:proposal.revision},carriers())!,reviewed=revised.proposals[0]!,accepted=f.projects.acceptAssemblyProposal(f.owner.token,reviewed.id,reviewed.revision,"assembly",{libraryVersion:2,historyRevision:history},carriers())!;expect(accepted.replayed).toBe(false);expect(accepted.assembly.target).toEqual({frames:1800,status:"short",deltaFrames:-1799});expect(accepted.library.version).toBe(3);expect(f.projects.peekProject(f.owner.projectId)!.editLibrary.sequences[0]).toEqual(originalSequence);
    const kept=structuredClone(accepted.assembly);accepted.assembly.plan.ranges[0]!.reason="Caller mutation";expect(new ProjectService(f.paths.statePath).peekProject(f.owner.projectId)!.assemblyLibrary.assemblies[0]).toEqual(kept);
    const changed=f.projects.changeEditSequence(f.owner.token,sequenceId,{kind:"edit",label:"Parent marker",operation:{kind:"marker",marker:{id:"later",frame:0,label:"Later parent edit"}}},editorial.version,history)!,afterParent=readFileSync(f.paths.statePath,"utf8"),retry=f.projects.acceptAssemblyProposal(f.owner.token,reviewed.id,reviewed.revision,"assembly",{libraryVersion:2,historyRevision:history},carriers())!;expect(retry.replayed).toBe(true);expect(retry.assembly).toEqual(kept);expect(readFileSync(f.paths.statePath,"utf8")).toBe(afterParent);expect(()=>f.projects.acceptAssemblyProposal(f.owner.token,reviewed.id,reviewed.revision,"other-assembly",{libraryVersion:3,historyRevision:changed.sequences[0]!.history.revision},carriers())).toThrow();expect(()=>f.projects.reviseAssemblyProposal(f.owner.token,reviewed.id,{label:"Refresh forbidden",purpose:"custom",ranges:input.ranges},{libraryVersion:3,proposalRevision:reviewed.revision,historyRevision:changed.sequences[0]!.history.revision},carriers())).toThrow("parent edit");
    const other=f.projects.createAnonymousProject();expect(()=>f.projects.createAssemblyProposal(other.token,sequenceId,input,expected,carriers())).toThrow("saved parent");expect(f.projects.peekProject(other.projectId)!.assemblyLibrary.version).toBe(0);expect(f.projects.createAssemblyProposal("invalid",sequenceId,input,expected,carriers())).toBeNull();
    const beforeRevoke=f.projects.peekProject(f.owner.projectId)!.assemblyLibrary;expect(f.projects.revokeCharacterPermission(f.owner.token,f.id,1)).not.toBeNull();expect(()=>f.projects.acceptAssemblyProposal(f.owner.token,reviewed.id,reviewed.revision,"assembly",{libraryVersion:2,historyRevision:history},carriers())).toThrow();expect(f.projects.peekProject(f.owner.projectId)!.assemblyLibrary).toEqual(beforeRevoke);
    expect(readFileSync(f.paths.queuePath,"utf8")).toBe(queueBefore);expect(f.ledger.monthSpend()).toBe(0);
  }finally{await f.close();}
},180000);
