import {expect,test} from "bun:test";
import {readFileSync,realpathSync,renameSync,writeFileSync} from "node:fs";
import {join,sep} from "node:path";
import {dubStudio} from "../../../test/fixtures/dub-studio";
import {contentHash} from "../../generator/src/capabilities";
import {editHistoryState,editHistoryReplay} from "../../planner/src/edit-history";
import {validateEditOutput} from '../../planner/src/edit-jobs';
test('owners save crossfades, review borrowed speech, refuse changed blend receipts and restore the hard cut',async()=>{
  const f=await dubStudio();try{const path=f.base+'/editorial',call=(suffix:string,method='GET',body?:unknown)=>f.call(path+suffix,method,body,f.owner.token),source=(await(await call('/sources/'+f.film.id)).json() as any).sources[0],id=crypto.randomUUID(),route='/sequences/'+id;
    const assets=['/api/editorial.js'],visited=new Set<string>();while(assets.length){const asset=assets.pop()!;if(visited.has(asset))continue;visited.add(asset);expect(visited.size).toBeLessThanOrEqual(8);const response=await f.call(asset);expect(response.status).toBe(200);expect(response.headers.get('content-type')).toContain('javascript');const code=await response.text();for(const match of code.matchAll(/(?:^|\n)(?:import|export)\s+(?:[^;\n]*?\s+from\s+)?['"]([^'"]+)['"]/g))assets.push(new URL(match[1]!,new URL(asset,'http://fixture.local')).pathname);}
    expect(visited.has('/api/preview-controller.js')).toBe(true);expect(visited.has('/api/mask-editor.js')).toBe(true);expect(visited.has('/api/mask-source.js')).toBe(true);
    const created=await call('/sequences','POST',{id,label:'Crossfade performances',sources:[{jobId:f.film.id,sourceRevision:source.sourceRevision}],firstSourceId:f.film.id,width:640,height:360,expectedVersion:0});expect(created.status).toBe(201);let state=await created.json() as any;
    const edit=async(operation:unknown)=>{const response=await call(route,'PATCH',{expectedVersion:state.libraryVersion,expectedHistoryRevision:state.sequence.history.revision,change:{kind:'edit',label:'Edit crossfade fixture',operation}});expect(await response.clone().text()).not.toContain('"error"');expect(response.status).toBe(200);state=await response.json();};
    await edit({kind:'trim',clipId:'initial-0',linked:true,edge:'out',delta:30-state.timeline.frames,ripple:true});await edit({kind:'split',clipId:'initial-0',linked:true,at:15,rightIds:{'initial-0':'right-picture','initial-1':'right-mix','initial-2':'right-captions'},rightLink:'right'});const hardCut=structuredClone(state.timeline),op={kind:'crossfade',leftId:'initial-0',rightId:'right-picture',linked:true,frames:6,alignment:'center',ids:{'initial-0':'picture-fade','initial-1':'audio-fade'}};
    await edit(op);expect(state.timeline.clips).toEqual(hardCut.clips);const request={expectedVersion:state.libraryVersion,expectedHistoryRevision:state.sequence.history.revision,change:{kind:'edit',label:'Invalid range',operation:{...op,frames:99}}};expect((await call(route,'PATCH',request)).status).toBe(400);expect((await(await call(route)).json() as any).timeline).toEqual(state.timeline);
    const quote=await(await call(route+'/renders')).json() as any;expect(quote.crossfades).toHaveLength(2);expect(quote.crossfades.find((x:any)=>x.lane==='mix').clips.every((c:any)=>c.captionsFollow)).toBe(true);expect(quote.review.crossfadesRevision).toBe(contentHash(quote.crossfades));
    const render={idempotencyKey:crypto.randomUUID(),generationApproved:true,historyRevision:quote.sequence.historyRevision,sourceBindingsRevision:quote.sourceBindingsRevision,engineVersion:quote.engineVersion,review:{...quote.review,accepted:true}};
    expect((await call(route+'/renders','POST',{...render,review:{...render.review,crossfadesRevision:contentHash([])}})).status).toBe(400);const submitted=await call(route+'/renders','POST',render);expect(await submitted.clone().text()).not.toContain('"error"');expect(submitted.status).toBe(202);const jobId=(await submitted.json() as any).jobId;expect((await(await call(route+'/renders','POST',render)).json() as any).jobId).toBe(jobId);
    const done=(await f.worker())!;expect(done.failureReason??done.cancelReason).toBeUndefined();expect(done.status).toBe('done');expect(done.costUsd).toBe(0);expect(done.output!.editorial!.conform.crossfades).toEqual(quote.crossfades);validateEditOutput(done,done.output!);
    const changed=structuredClone(done.output!);changed.editorial!.conform.picture.parts.find(p=>p.at===12)!.layers[0]!.filter='null';expect(()=>validateEditOutput(done,changed)).toThrow('blend');
    await edit({kind:'remove-crossfade',leftId:'initial-0',rightId:'right-picture',linked:true});expect(state.timeline).toEqual(hardCut);expect((await(await call('/versions/'+done.id+'?outputRevision='+contentHash(done.output))).json() as any).timeline.transitions).toHaveLength(2);
  }finally{await f.close();}
},180000);
for(const retimed of [false,true])test("owners inspect originals, save "+(retimed?"retimed":"trimmed")+" edit history, review exact voice cuts and render continued independent sequences",async()=>{
  const f=await dubStudio();try{
    const path=f.base+"/editorial",call=(suffix:string,method="GET",body?:unknown)=>f.call(path+suffix,method,body,f.owner.token),json=async(suffix:string)=>{const r=await call(suffix);expect(r.status).toBe(200);return r.json() as Promise<any>;};
    expect((await f.call(path)).status).toBe(401);const index=await json("");expect(index.sequences).toEqual([]);expect(index.sources.some((s:any)=>s.jobId===f.film.id)).toBe(true);
    const inspected=await json("/sources/"+f.film.id),source=inspected.sources[0];expect(source.facts.voices.length).toBeGreaterThan(0);expect(source.facts.audio).toContain("dialogue");expect(source.sourceRevision).toHaveLength(64);expect(source.job).toBeUndefined();
    const body={id:crypto.randomUUID(),label:"Opening read",sources:[{jobId:f.film.id,sourceRevision:source.sourceRevision}],firstSourceId:f.film.id,width:640,height:360,expectedVersion:0};
    expect((await call("/sequences","POST",{...body,sources:[{...body.sources[0],sourceRevision:"0".repeat(64)}]})).status).toBe(400);
    const created=await call("/sequences","POST",body);expect(await created.clone().text()).not.toContain('"error"');expect(created.status).toBe(201);let state=await created.json() as any;const sequencePath="/sequences/"+body.id;
    expect(state.timeline.frames).toBe(source.facts.frames);expect(state.head).toBe(0);expect(state.parent).toBeNull();expect(state.children).toEqual([]);
    const change={expectedVersion:state.libraryVersion,expectedHistoryRevision:state.sequence.history.revision,change:{kind:"edit",label:"Keep the first second",operation:retimed?{kind:"retime",clipId:"initial-0",linked:true,from:0,frames:30,points:[{frame:0,rate:1000},{frame:30,rate:500}],ripple:true}:{kind:"trim",clipId:"initial-0",linked:true,edge:"out",delta:30-state.timeline.frames,ripple:true}}};
    const changed=await call(sequencePath,"PATCH",change);expect(changed.status).toBe(200);state=await changed.json();expect(editHistoryState(state.sequence.history).timeline.frames).toBe(30);expect((await call(sequencePath,"PATCH",change)).status).toBe(400);
    const quote=await json(sequencePath+"/renders");expect(quote.speechCuts.length).toBeGreaterThan(0);expect(quote.resources.originalBytes).toBeGreaterThan(0);expect(quote.costUsd).toBe(0);expect(quote.unavailable).toBeNull();
    expect(quote.review).toEqual({timelineRevision:quote.timelineRevision,speechCutsRevision:contentHash(quote.speechCuts),unmeasuredCutsRevision:contentHash(quote.unmeasuredAudioCuts),accepted:false});expect(state.timeline.frames).toBe(30);expect(state.head).toBe(1);expect(state.parent).toBe(0);expect(state.children).toEqual([]);
    const render={idempotencyKey:crypto.randomUUID(),generationApproved:true,historyRevision:quote.sequence.historyRevision,sourceBindingsRevision:quote.sourceBindingsRevision,engineVersion:quote.engineVersion,review:{...quote.review,accepted:true}};
    for(const patch of [{generationApproved:false},{sourceBindingsRevision:"0".repeat(64)},{historyRevision:"0".repeat(64)},{review:{...render.review,accepted:false}},{review:{...render.review,speechCutsRevision:contentHash([])}}])expect((await call(sequencePath+"/renders","POST",{...render,...patch})).status).toBe(400);
    const submitted=await call(sequencePath+"/renders","POST",render);expect(await submitted.clone().text()).not.toContain('"error"');expect(submitted.status).toBe(202);const id=(await submitted.json() as any).jobId;expect((await(await call(sequencePath+"/renders","POST",render)).json() as any).jobId).toBe(id);
    expect((await call(sequencePath+"/renders","POST",{...render,review:{...render.review,accepted:false}})).status).toBe(400);
    const done=(await f.worker())!;expect(done.failureReason??done.cancelReason).toBeUndefined();expect(done.id).toBe(id);expect(done.status).toBe("done");expect(done.costUsd).toBe(0);expect(done.output!.editorial!.conform.pictureFrames).toHaveLength(30);
    const original=realpathSync(join(f.paths.artifactRoot,f.film.projectId,f.film.id));if(!original.startsWith(realpathSync(f.paths.artifactRoot)+sep))throw new Error("Unsafe editorial API fixture");renameSync(original,original+"-hidden");const queueBytes=readFileSync(f.paths.queuePath);writeFileSync(f.paths.queuePath,JSON.stringify([done]));
    try{
      const retained=(await json("/sources/"+done.id)).sources[0];expect(retained.sourceRevision).toBe(source.sourceRevision);expect(retained.jobId).toBe(done.id);
      const nextId=crypto.randomUUID(),next=await call("/sequences","POST",{...body,id:nextId,label:"Alternate assembly from retained originals",sources:[{jobId:done.id,sourceRevision:retained.sourceRevision}],expectedVersion:state.libraryVersion});expect(await next.clone().text()).not.toContain('"error"');expect(next.status).toBe(201);const saved=await next.json() as any;expect(saved.sequence.sourceRevisions).toEqual([source.sourceRevision]);
      const current=await json(sequencePath);expect(current.sequence.history).toEqual(state.sequence.history);const continued=await json(sequencePath+"/renders");expect(continued.sources[0].jobId).toBe(done.id);expect(continued.timelineRevision).toBe(quote.timelineRevision);expect(continued.sourceBindingsRevision).not.toBe(quote.sourceBindingsRevision);
      const previewId=crypto.randomUUID(),previewBase=sequencePath+"/preview",previewQuery="?historyRevision="+state.sequence.history.revision;expect((await call(previewBase,"POST",{id:previewId,historyRevision:state.sequence.history.revision,from:0,frames:60})).status).toBe(202);let preview:any;const previewEnd=Date.now()+60000;
      do{if(Date.now()>previewEnd)throw new Error("Retained-copy preview did not finish.");await Bun.sleep(50);preview=await json(previewBase+"/"+previewId+previewQuery);if(preview.state==="failed")throw new Error(preview.error);}while(preview.state!=="ready");
      const picturePath=previewBase+"/"+previewId+"/picture/"+f.film.id+"/0"+previewQuery+"&sourceKey="+preview.sources[0].sourceKey,picture=await call(picturePath);expect(picture.status).toBe(200);expect((await picture.arrayBuffer()).byteLength).toBeGreaterThan(0);
      writeFileSync(f.paths.queuePath,JSON.stringify([{...done,linkExpiresAt:new Date(Date.now()-1000).toISOString()}]));try{expect((await call(picturePath)).status).toBe(400);}finally{writeFileSync(f.paths.queuePath,JSON.stringify([done]));}expect((await call(previewBase+"/"+previewId+previewQuery,"DELETE")).status).toBe(200);
      expect((await call(sequencePath,"PATCH",{expectedVersion:saved.libraryVersion,expectedHistoryRevision:state.sequence.history.revision,change:{kind:"cursor",reason:"undo",target:0,label:"Restore full original"}})).status).toBe(200);
      const final=await json(sequencePath);expect(final.head).toBe(0);expect(final.timeline.frames).toBe(source.facts.frames);expect(final.parent).toBeNull();expect(final.children).toEqual([1]);expect(final.sequence.history.events.filter((e:any)=>e.kind==="edit")).toHaveLength(1);expect((await json("")).jobs.some((j:any)=>j.pictureEdit.sequenceId===body.id)).toBe(true);
    }finally{renameSync(original+"-hidden",original);writeFileSync(f.paths.queuePath,queueBytes);}
  }finally{await f.close();}
},180000);

test("later dialogue takes are admitted once, replaced in place and recovered from an export of an earlier branch",async()=>{
  const f=await dubStudio();try{
    const path=f.base+"/editorial",call=(suffix:string,method="GET",body?:unknown)=>f.call(path+suffix,method,body,f.owner.token),json=async(suffix:string)=>{const r=await call(suffix);expect(r.status).toBe(200);return r.json() as Promise<any>;},first=(await json("/sources/"+f.film.id)).sources[0],sequenceId=crypto.randomUUID(),route="/sequences/"+sequenceId;
    const created=await call("/sequences","POST",{id:sequenceId,label:"Performance alternates",sources:[{jobId:f.film.id,sourceRevision:first.sourceRevision}],firstSourceId:f.film.id,width:640,height:360,expectedVersion:0});expect(created.status).toBe(201);let state=await created.json() as any;
    const change=async(change:unknown)=>{const r=await call(route,"PATCH",{expectedVersion:state.libraryVersion,expectedHistoryRevision:state.sequence.history.revision,change});expect(await r.clone().text()).not.toContain('"error"');expect(r.status).toBe(200);state=await r.json();};
    await change({kind:"edit",label:"One second",operation:{kind:"trim",clipId:"initial-0",linked:true,edge:"out",delta:30-state.timeline.frames,ripple:true}});await change({kind:"edit",label:"Copy opening",operation:{kind:"duplicate",clipId:"initial-0",linked:true,at:30,ids:{"initial-0":"copy-picture","initial-1":"copy-mix","initial-2":"copy-captions"},link:"copy",ripple:true}});const branch=state.head,root=structuredClone(state.sequence.history.root);
    const dubbed=await f.call(f.base+"/dialogue/"+f.film.id,"POST",f.requestBody(await f.quote()),f.owner.token);expect(dubbed.status).toBe(202);const take=(await f.worker())!;expect(take.failureReason??take.cancelReason).toBeUndefined();expect(take.status).toBe("done");const later=(await json("/sources/"+take.id)).sources[0];expect(later.language).toBe("es");
    const admission={jobId:take.id,sourceRevision:later.sourceRevision,expectedVersion:state.libraryVersion,expectedHistoryRevision:state.sequence.history.revision};expect((await f.call(path+route+"/sources","POST",admission)).status).toBe(401);expect((await call(route+"/sources","POST",{...admission,sourceRevision:"0".repeat(64)})).status).toBe(400);expect((await call(route+"/sources","POST",{...admission,facts:later.facts})).status).toBe(400);
    expect((await call(route,"PATCH",{expectedVersion:state.libraryVersion,expectedHistoryRevision:state.sequence.history.revision,change:{kind:"edit",label:"Bypass admission",operation:{kind:"source",source:later.facts,receiptRevision:later.sourceRevision}}})).status).toBe(400);
    const replies=await Promise.all([call(route+"/sources","POST",admission),call(route+"/sources","POST",admission)]);expect(replies.map(r=>r.status).sort()).toEqual([201,400]);state=await json(route);expect(state.sequence.history.root).toEqual(root);expect(state.timeline.sources).toHaveLength(2);expect(state.sequence.sourceRevisions.slice().sort()).toEqual([first.sourceRevision,later.sourceRevision].sort());const admitted=state.head;
    const replacement={kind:"replace",clipId:"initial-0",linked:true,sourceId:take.id,from:0,frames:30,timing:"preserve",ripple:true};await change({kind:"edit",label:"Use Spanish take",operation:replacement});expect(state.timeline.clips.find((c:any)=>c.id==="initial-0")).toMatchObject({sourceId:take.id,at:0,frames:30,link:"initial"});await change({kind:"cursor",target:admitted,reason:"undo",label:"Undo replacement"});await change({kind:"cursor",target:branch,reason:"undo",label:"Undo take admission"});expect(state.timeline.sources).toHaveLength(1);expect(editHistoryReplay(state.sequence.history).catalog).toHaveLength(2);
    const render=async()=>{const quote=await json(route+"/renders");expect(quote.sources).toHaveLength(2);const r=await call(route+"/renders","POST",{idempotencyKey:crypto.randomUUID(),generationApproved:true,historyRevision:quote.sequence.historyRevision,sourceBindingsRevision:quote.sourceBindingsRevision,engineVersion:quote.engineVersion,review:{...quote.review,accepted:true}});expect(await r.clone().text()).not.toContain('"error"');expect(r.status).toBe(202);const done=(await f.worker())!;expect(done.failureReason??done.cancelReason).toBeUndefined();expect(done.status).toBe("done");expect(done.output!.editorial!.prepared.sources).toHaveLength(2);expect(done.costUsd).toBe(0);return done;};
    const saved=await render(),queueBytes=readFileSync(f.paths.queuePath),hidden:string[]=[];
    try{
      for(const job of [f.film,take]){const original=realpathSync(join(f.paths.artifactRoot,job.projectId,job.id));if(!original.startsWith(realpathSync(f.paths.artifactRoot)+sep))throw new Error("Unsafe take-recovery fixture");renameSync(original,original+"-hidden");hidden.push(original);}writeFileSync(f.paths.queuePath,JSON.stringify([saved]));const retained=(await json("/sources/"+saved.id)).sources.find((s:any)=>s.sourceRevision===later.sourceRevision);expect(retained.jobId).toBe(saved.id);
      const recovered=await call(route+"/sources","POST",{...admission,jobId:saved.id,expectedVersion:state.libraryVersion,expectedHistoryRevision:state.sequence.history.revision});expect(await recovered.clone().text()).not.toContain('"error"');expect(recovered.status).toBe(201);state=await recovered.json();expect(state.sequence.sourceRevisions).toHaveLength(2);await change({kind:"edit",label:"Recover Spanish take",operation:replacement});const final=await render();expect(readFileSync(join(f.paths.artifactRoot,final.output!.captionsPath!),"utf8")).toContain("Bienvenida");expect(final.output!.editorial!.plan.bindings.every(b=>b.owner.jobId===saved.id)).toBe(true);expect(state.sequence.history.root).toEqual(root);
    }finally{for(const original of hidden)renameSync(original+"-hidden",original);writeFileSync(f.paths.queuePath,queueBytes);}
  }finally{await f.close();}
},900000);
