/**
 * HV-031-17 — the films the studio shares are signed too.
 *
 * The crew flow shares the Editor's picture edit, not the assembler's film, and HV-031-15 signed only
 * the assembler. These tests make a picture edit and an assembly through the editorial routes, as
 * the studio does, with the signing variables set to a throwaway identity generated by this run, and
 * read the sidecar the way a reviewer would get it: from the review link's own signed URLs.
 */
import { afterAll, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { dubStudio } from "../../../test/fixtures/dub-studio";
import { inspected } from "../../../test/fixtures/editorial-inspection";
import { verifyC2paSidecar } from "../../assembler/src/c2pa";
import { makeC2paTestIdentity, withC2paEnv } from "../../assembler/test/c2pa-fixture";
import { validateEditOutput } from "../../planner/src/edit-jobs";
import { validateEditAssemblyOutput } from "../../planner/src/edit-assembly-jobs";
import { contentHash } from "../../generator/src/capabilities";
import { verifyExportC2pa } from "../../../scripts/verify-c2pa";
import { signedArtifactUrls } from "../src/server";
import type { Job } from "../../queue/src/index";

const TMP = mkdtempSync(join(tmpdir(), "hv-shared-c2pa-"));
const identity = makeC2paTestIdentity(join(TMP, "identity"));
const signed = { key: identity.keyPath, cert: identity.chainPath };
const sha = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");
afterAll(() => rmSync(TMP, { recursive: true, force: true }));

type Studio = Awaited<ReturnType<typeof dubStudio>>;
function calls(f: Studio) {
  const call = (path: string, method = "GET", body?: unknown) => f.call(path, method, body, f.owner.token);
  const json = async (path: string, method = "GET", body?: unknown) => {const r = await call(path, method, body), t = await r.text();if (!r.ok) throw new Error(path + " " + r.status + " " + t);return JSON.parse(t);};
  return { call, json };
}

/** A one-second picture edit of the studio's film, through the editorial routes the Editor uses. */
async function pictureEdit(f: Studio): Promise<Job> {
  const { json } = calls(f), editorial = f.base + "/editorial";
  const source = (await inspected(async s => await (await f.call(editorial + s, "GET", undefined, f.owner.token)).json() as never, "/sources/" + f.film.id)).sources[0];
  const id = crypto.randomUUID(), sequence = editorial + "/sequences/" + id;
  let state = await json(editorial + "/sequences", "POST", { id, label: "cut", sources: [{ jobId: f.film.id, sourceRevision: source.sourceRevision }], firstSourceId: f.film.id, width: 640, height: 360, expectedVersion: (await json(editorial)).libraryVersion });
  state = await json(sequence, "PATCH", { expectedVersion: state.libraryVersion, expectedHistoryRevision: state.sequence.history.revision,
    change: { kind: "edit", label: "trim", operation: { kind: "trim", clipId: "initial-0", linked: true, edge: "out", delta: 30 - state.timeline.frames, ripple: true } } });
  const quote = await json(sequence + "/renders");
  await json(sequence + "/renders", "POST", { idempotencyKey: crypto.randomUUID(), generationApproved: true, historyRevision: quote.sequence.historyRevision, sourceBindingsRevision: quote.sourceBindingsRevision, engineVersion: quote.engineVersion, review: { ...quote.review, accepted: true } });
  return (await f.worker())!;
}

/** A short assembly of the studio's film, through the assembly routes. */
async function assembly(f: Studio): Promise<Job> {
  const { json } = calls(f), editorial = f.base + "/editorial";
  const source = (await inspected(async s => await (await f.call(editorial + s, "GET", undefined, f.owner.token)).json() as never, "/sources/" + f.film.id)).sources[0], sequenceId = crypto.randomUUID();
  const parent = await json(editorial + "/sequences", "POST", { id: sequenceId, label: "Assembly parent", sources: [{ jobId: f.film.id, sourceRevision: source.sourceRevision }], firstSourceId: f.film.id, width: 32, height: 24, expectedVersion: 0 });
  const proposal = await json(editorial + "/assemblies/proposals", "POST", { sequenceId, input: { id: crypto.randomUUID(), label: "Short cut", purpose: "trailer", ranges: [{ id: "later", fromFrame: 20, toFrame: 30, reason: "Later read first." }, { id: "earlier", fromFrame: 0, toFrame: 5, reason: "Return to opening." }] }, expected: { libraryVersion: 0, historyRevision: parent.sequence.history.revision } });
  const accepted = await json(editorial + "/assemblies/proposals/" + proposal.item.id + "/accept", "POST", { proposalRevision: proposal.item.revision, assemblyId: crypto.randomUUID(), expected: { libraryVersion: proposal.libraryVersion, historyRevision: parent.sequence.history.revision }, reviewRevision: proposal.review.revision, boundariesRevision: proposal.boundaries.revision, sourceBindingsRevision: proposal.sourceBindingsRevision, accepted: true });
  const route = editorial + "/assemblies/accepted/" + accepted.item.id + "/renders", quote = await json(route);
  await json(route, "POST", { idempotencyKey: crypto.randomUUID(), generationApproved: true, assemblyRevision: quote.assembly.revision, sourceBindingsRevision: quote.sourceBindingsRevision, engineVersion: quote.engineVersion, review: { ...quote.review, accepted: true } });
  return (await f.worker())!;
}

/** What a reviewer gets from a review link bound to `job`: the signed URLs, the sidecar and the film. */
async function reviewed(f: Studio, job: Job) {
  const { json } = calls(f), view = await json("/api/jobs/" + job.id);
  const link = await json(f.base + "/reviews", "POST", { jobId: job.id, expectedOutputRevision: view.outputRevision, permission: "approve" });
  const opened = await (await fetch(new URL("/api/reviews/" + encodeURIComponent(link.token), f.server.url))).json() as any;
  const fetched = async (url: string) => fetch(new URL(url, f.server.url));
  const sidecarResponse = opened.output?.c2paUrl ? await fetched(opened.output.c2paUrl) : null;
  const sidecar = sidecarResponse ? Buffer.from(await sidecarResponse.arrayBuffer()) : null;
  const mp4 = new Uint8Array(await (await fetched(opened.output.mp4Url)).arrayBuffer()), mp4Path = join(TMP, crypto.randomUUID() + ".mp4");writeFileSync(mp4Path, mp4);
  const record = await (await fetched(opened.output.manifestUrl)).json() as any;
  return { opened, record, mp4Sha256: sha(mp4), sidecarType: sidecarResponse?.headers.get("content-type") ?? null, sidecarSha256: sidecar ? sha(sidecar) : null,
    verified: sidecar ? await verifyC2paSidecar(mp4Path, sidecar, identity.anchorPem) : null };
}

/**
 * The finding from the Release 2 exit run, reproduced and fixed: the picture edit a review link
 * shares carries a signed sidecar beside its own record, the review link serves it, and it reads
 * `Trusted` against the issuing root, bound to the very MP4 the link serves.
 */
test("the picture edit a review link shares serves a signed sidecar that verifies against the film it serves", async () => {
  await withC2paEnv(signed, async () => {
    const f = await dubStudio();
    try {
      const cut = await pictureEdit(f);
      expect({ status: cut.status, failed: cut.failureReason ?? null }).toEqual({ status: "done", failed: null });
      const output = cut.output!, onDisk = join(f.paths.artifactRoot, dirname(output.manifestPath));
      expect(output.c2paPath).toBe(dirname(output.manifestPath) + "/provenance.c2pa");
      const record = JSON.parse(readFileSync(join(onDisk, "provenance.json"), "utf8"));
      expect(record.credentials).toEqual({ type: "c2pa-sidecar", issuer: "hollywood-video-app", claim: "AI-generated video; content credentials sha256:" + sha(readFileSync(join(f.paths.artifactRoot, output.mp4Path))),
        sidecar: { name: "provenance.c2pa", sha256: sha(readFileSync(join(onDisk, "provenance.c2pa"))) } });
      expect(output.editorial!.credentials).toEqual(record.credentials);

      const shared = await reviewed(f, cut);
      expect({ jobId: shared.opened.jobId, stage: shared.opened.stage }).toEqual({ jobId: cut.id, stage: "picture-edit" });
      expect(shared.opened.output.c2paUrl).toContain("/artifacts/");
      expect(shared.sidecarType).toBe("application/c2pa");
      expect(shared.record.credentials.type).toBe("c2pa-sidecar");
      expect(shared.record.credentials.sidecar.sha256).toBe(shared.sidecarSha256!);
      expect({ state: shared.verified!.state, codes: shared.verified!.codes }).toEqual({ state: "Trusted", codes: [] });
      expect(shared.verified!.provenance).toMatchObject({ spec: "hv-edit-result/1", issuer: "hollywood-video-app", projectId: cut.projectId, mp4Sha256: shared.mp4Sha256 });

      // The operator's check on the host reads an editorial export's directory as it is laid out.
      expect(await verifyExportC2pa(onDisk, identity.anchorPem)).toMatchObject({ ok: true, state: "Trusted", codes: [], problems: [] });
      expect(await verifyExportC2pa(onDisk)).toMatchObject({ ok: true, state: "Valid", codes: ["signingCredential.untrusted"] });
    } finally {await f.close();}
  });
}, 240000);

/**
 * A signed picture edit's sealed output says exactly which sidecar it holds. The validator every
 * reader of the output runs (the worker's checkpoint, the store, review selection, snapshots, restore)
 * refuses the output with its sidecar dropped, moved, or named by different bytes, and a signed
 * record that lost its sidecar. A deliverable is still made from the signed cut.
 */
test("a signed picture edit's output refuses a dropped, moved or changed sidecar, and still makes a deliverable", async () => {
  await withC2paEnv(signed, async () => {
    const f = await dubStudio();
    try {
      const cut = await pictureEdit(f), output = cut.output!;
      expect(cut.status).toBe("done");
      expect(() => validateEditOutput(cut, output)).not.toThrow();
      const reseal = (changed: NonNullable<Job["output"]>) => {const { revision: _r, ...data } = changed.editorial!;changed.editorial!.revision = contentHash(data);return changed;};
      const dropped = structuredClone(output);delete dropped.c2paPath;
      expect(() => validateEditOutput(cut, dropped)).toThrow("names a C2PA sidecar the export does not hold");
      const moved = structuredClone(output);moved.c2paPath = output.mp4Path.replace("export.mp4", "provenance.c2pa");
      expect(() => validateEditOutput(cut, moved)).toThrow("beside its own provenance record");
      const changed = structuredClone(output), file = changed.editorial!.files.find(row => row.path === output.c2paPath)!;file.sha256 = "0".repeat(64);
      expect(() => validateEditOutput(cut, reseal(changed))).toThrow("differs from the bytes its provenance record names");
      const unsignedRecord = structuredClone(output);unsignedRecord.editorial!.credentials = { type: "c2pa-style", issuer: "hollywood-video-app", claim: output.editorial!.credentials!.claim };
      expect(() => validateEditOutput(cut, reseal(unsignedRecord))).toThrow("unsigned record cannot have a C2PA sidecar");

      const { json } = calls(f), deliveries = f.base + "/deliveries/" + cut.id;
      await json(deliveries, "POST", { idempotencyKey: crypto.randomUUID(), kind: "reframe-1:1" });
      const made = (await f.worker())!;
      expect({ status: made.status, failed: made.failureReason ?? null }).toEqual({ status: "done", failed: null });
      expect(made.delivery!.binding.source).toMatchObject({ jobId: cut.id, outputRevision: output.editorial!.revision });
    } finally {await f.close();}
  });
}, 240000);

/** The assembly, the other editorial export, is signed the same way and its review link serves the sidecar. */
test("an assembly is signed beside its own record and its review link serves a sidecar that verifies", async () => {
  await withC2paEnv(signed, async () => {
    const f = await dubStudio();
    try {
      const done = await assembly(f);
      expect({ status: done.status, failed: done.failureReason ?? null }).toEqual({ status: "done", failed: null });
      const output = done.output!;
      expect(output.c2paPath).toBe(dirname(output.manifestPath) + "/provenance.c2pa");
      expect(output.assembly!.credentials!.type).toBe("c2pa-sidecar");
      expect(() => validateEditAssemblyOutput(done, output as never)).not.toThrow();
      const dropped = structuredClone(output);delete dropped.c2paPath;
      expect(() => validateEditAssemblyOutput(done, dropped as never)).toThrow("names a C2PA sidecar the export does not hold");

      const shared = await reviewed(f, done);
      expect(shared.opened.stage).toBe("assembly-edit");
      expect(shared.record.credentials.sidecar.sha256).toBe(shared.sidecarSha256!);
      expect({ state: shared.verified!.state, codes: shared.verified!.codes }).toEqual({ state: "Trusted", codes: [] });
      expect(shared.verified!.provenance).toMatchObject({ spec: "hv-edit-assembly-result/1", mp4Sha256: shared.mp4Sha256 });
      expect(await verifyExportC2pa(join(f.paths.artifactRoot, dirname(output.manifestPath)), identity.anchorPem)).toMatchObject({ ok: true, state: "Trusted" });
    } finally {await f.close();}
  });
}, 240000);

/**
 * Without a key the picture edit is exactly as honest as the assembler's film: its record names its
 * MP4 as unsigned C2PA-style JSON, and there is no sidecar, no `c2paPath` and no `c2paUrl`. A host
 * whose certificate has no C2PA signing EKU refuses the next picture edit before anything is encoded.
 */
test("without a key a picture edit's record says it is unsigned, and an EKU-less certificate refuses before encoding", async () => {
  await withC2paEnv({}, async () => {
    const f = await dubStudio();
    try {
      const cut = await pictureEdit(f), output = cut.output!;
      expect(cut.status).toBe("done");
      expect(Object.hasOwn(output, "c2paPath")).toBe(false);
      const onDisk = join(f.paths.artifactRoot, dirname(output.manifestPath));
      expect(existsSync(join(onDisk, "provenance.c2pa"))).toBe(false);
      const record = JSON.parse(readFileSync(join(onDisk, "provenance.json"), "utf8"));
      expect(record.credentials).toEqual({ type: "c2pa-style", issuer: "hollywood-video-app", claim: "AI-generated video; content credentials sha256:" + sha(readFileSync(join(f.paths.artifactRoot, output.mp4Path))) });
      expect(Object.hasOwn(signedArtifactUrls(cut, "token")!, "c2paUrl")).toBe(false);
      const shared = await reviewed(f, cut);
      expect(Object.hasOwn(shared.opened.output, "c2paUrl")).toBe(false);
      expect(shared.record.credentials.type).toBe("c2pa-style");

      const refused = await withC2paEnv({ key: identity.keyPath, cert: identity.noEkuChainPath }, () => pictureEdit(f));
      // The worker reports the refusal, naming the fix, and the job is not done; it is retried under its policy.
      expect(refused.status).not.toBe("done");
      expect(refused.failureReason).toContain("documentSigning (1.3.6.1.5.5.7.3.36)");
      const jobDirectory = join(f.paths.artifactRoot, refused.projectId, refused.id);
      const exported = existsSync(jobDirectory) ? readdirSync(jobDirectory, { recursive: true }).map(String).filter(name => name.endsWith("export.mp4")) : [];
      expect(exported).toEqual([]);
    } finally {await f.close();}
  });
}, 240000);
