import {expect,test} from "bun:test";
import {readFileSync,writeFileSync} from "node:fs";
import {join} from "node:path";
import {dubStudio} from "../../../test/fixtures/dub-studio";
import {soundFixture,soundCue,SOUND_RIGHTS} from "../../../test/fixtures/sound";
import {verifySoundMedia} from "../../generator/src/sound-media";
import {outputRevision} from "../../planner/src/dialogue-selection";
import {SOUND_STEMS} from "../../planner/src/sound-session";
import {validateSnapshot,type StateSnapshot} from "../../storage/src/snapshots";
import {audioPcmHash} from "../../generator/src/audio-delivery";
import {soundCommand} from "../../generator/src/sound-audio";
import {contentHash} from "../../generator/src/capabilities";
test("reviewed sound sessions retain picture and voices, own all stems, continue independently and enforce revocation",async()=>{
  const f=await dubStudio();try{
    const sound=soundFixture(f.owner.projectId,48000,50000,100000);for(let i=0;i<48000;i++){sound.wav.writeIntLE(Math.round(Math.sin(i*2*Math.PI*220/48000)*500000),44+i*6,3);sound.wav.writeIntLE(Math.round(Math.sin(i*2*Math.PI*660/48000)*1000000),47+i*6,3);}const meta={label:"Synthetic ambience",rights:SOUND_RIGHTS,expectedVersion:0},uploaded=await fetch(new URL(f.base+"/sounds",f.server.url),{method:"POST",headers:{authorization:"Bearer "+f.owner.token,"content-type":"audio/wav","x-hv-sound-record":encodeURIComponent(JSON.stringify(meta))},body:new Uint8Array(sound.wav)});expect(uploaded.status).toBe(201);const {asset}=await uploaded.json() as any;
    const quote=async(id=f.film.id)=>f.call(f.base+"/sound-mixes/"+id,"GET",undefined,f.owner.token).then(r=>r.json() as Promise<any>),q=await quote();expect(q.error).toBeUndefined();expect(q.language).toBe("en");expect(q.costUsd).toBe(0);
    const {asset:_asset,...settings}=soundCue(asset),cue={...settings,assetId:asset.id,assetRevision:asset.revision,role:"ambience",start:48000,frames:96000,loop:true,gainDb:-6,fadeIn:4800,fadeOut:4800,duckDb:-12,duckAttack:2400,duckRelease:4800};
    const body={idempotencyKey:crypto.randomUUID(),generationApproved:true,sourceRevision:q.sourceRevision,engineVersion:q.engineVersion,session:{reviewed:true,dialogueGainDb:0,narrationGainDb:0,cues:[cue]}},path=f.base+"/sound-mixes/"+f.film.id,before=f.store.all().length;
    expect((await f.call(path,"POST",body)).status).toBe(401);for(const patch of [{generationApproved:false},{sourceRevision:"f".repeat(64)},{session:{...body.session,reviewed:false}},{session:{...body.session,cues:[{...cue,loop:false}]}},{session:{...body.session,cues:[{...cue,assetRevision:"f".repeat(64)}]}}])expect((await f.call(path,"POST",{...body,...patch},f.owner.token)).status).toBeOneOf([400,409]);expect(f.store.all()).toHaveLength(before);
    const response=await f.call(path,"POST",body,f.owner.token);expect(await response.clone().text()).not.toContain('"error"');expect(response.status).toBe(202);const id=(await response.json() as any).jobId;expect((await(await f.call(path,"POST",body,f.owner.token)).json() as any).jobId).toBe(id);
    const rendered=await f.worker();expect(rendered?.failureReason??rendered?.cancelReason).toBeUndefined();expect(rendered?.status).toBe("done");await verifySoundMedia(rendered!,rendered!.output!,f.paths.artifactRoot);expect(rendered!.costUsd).toBe(0);expect(rendered!.cost).toBeUndefined();
    const report=rendered!.output!.sound!.report,baseDir=join(f.paths.artifactRoot,rendered!.output!.mp4Path.slice(0,-"export.mp4".length)),wav=(name:string)=>readFileSync(join(baseDir,name));expect(wav("captions.vtt").equals(readFileSync(join(f.paths.artifactRoot,f.film.output!.captionsPath)))).toBe(true);expect(report.stems.mix).not.toBe(report.stems.dialogue);expect(report.stems.me).toBe(report.stems.ambience);expect(wav("stems/narration.wav").subarray(44).every(b=>b===0)).toBe(true);
    const decodedPath=join(f.root,"decoded-sound.f32"),reference=wav("stems/mix.wav");await soundCommand(["ffmpeg","-v","error","-i",join(baseDir,"export.mp4"),"-map","0:a:0","-f","f32le","-c:a","pcm_f32le",decodedPath],f.root);const decoded=readFileSync(decodedPath);expect(decoded.length).toBeGreaterThanOrEqual(report.totalVideoFrames*1600*8);
    let dot=0,refEnergy=0,outEnergy=0;for(let frame=48000;frame<144000;frame++){const expected=(reference.readIntLE(44+frame*6+3,3)-reference.readIntLE(44+frame*6,3))/8388608,actual=decoded.readFloatLE(frame*8+4)-decoded.readFloatLE(frame*8);dot+=expected*actual;refEnergy+=expected*expected;outEnergy+=actual*actual;}expect(dot/Math.sqrt(refEnergy*outEnergy)).toBeGreaterThan(.9);expect(outEnergy/refEnergy).toBeGreaterThan(.7);expect(outEnergy/refEnergy).toBeLessThan(1.3);
    const view=await(await f.call("/api/jobs/"+id,"GET",undefined,f.owner.token)).json() as any;expect(view.soundMix.originalJobId).toBe(f.film.id);for(const stem of SOUND_STEMS){expect(view.output[stem+"StemUrl"]).toContain("/artifacts/");expect((await fetch(new URL(view.output[stem+"StemUrl"],f.server.url))).status).toBe(200);}
    const cueDownload=await fetch(new URL(view.output.cueSheetUrl,f.server.url));expect(cueDownload.status).toBe(200);expect(cueDownload.headers.get("content-disposition")).toContain("attachment;");const sheet=await cueDownload.json() as any;expect(sheet.soundJobId).toBe(id);expect(sheet.cues[0].rights).toEqual(asset.rights);expect(sheet.cues[0].start).toBe(cue.start);
    const playlistPath=join(f.paths.artifactRoot,rendered!.output!.hlsPlaylistPath),playlist=readFileSync(playlistPath),changedPlaylist=Buffer.from(playlist.toString().replace(/segment-\d+\.ts/,"missing.ts")),badOutput=structuredClone(rendered!.output!);writeFileSync(playlistPath,changedPlaylist);const entry=badOutput.sound!.files.find(file=>file.path===badOutput.hlsPlaylistPath)!;entry.bytes=changedPlaylist.length;entry.sha256=audioPcmHash(changedPlaylist);const {revision:_oldRevision,...badData}=badOutput.sound!;badOutput.sound!.revision=contentHash(badData);await expect(verifySoundMedia(rendered!,badOutput,f.paths.artifactRoot)).rejects.toThrow("HLS");writeFileSync(playlistPath,playlist);
    const continued=await quote(id);expect(continued.session.cues[0].asset.id).toBe(asset.id);const next={...body,idempotencyKey:crypto.randomUUID(),sourceRevision:continued.sourceRevision,session:{...body.session,finishing:{schema:"hv-sound-finishing/1",mode:"normalize",targetLufs:-23,ceilingDbtp:-2,rangeLu:7},cues:[{...cue,start:96000,gainDb:-12}]}};expect((await f.call(f.base+"/sound-mixes/"+id,"POST",next,f.owner.token)).status).toBe(202);
    const second=await f.worker();expect(second?.failureReason??second?.cancelReason).toBeUndefined();expect(second?.status).toBe("done");await verifySoundMedia(second!,second!.output!,f.paths.artifactRoot);expect(second!.output!.sound!.report.videoStreamSha256).toBe(report.videoStreamSha256);expect(second!.output!.sound!.report.baseVoiceSha256).toEqual(report.baseVoiceSha256);expect(second!.output!.sound!.report.stems.mix).not.toBe(report.stems.mix);const finishing=second!.output!.sound!.report.finishing!;expect(finishing.settings.mode).toBe("normalize");expect(finishing.before.integratedLufs).not.toBeNull();expect(finishing.after.frames).toBe(report.totalVideoFrames*1600);expect(finishing.encoded.frames).toBe(finishing.after.frames);
    const delivered=await(await f.call("/api/jobs/"+second!.id,"GET",undefined,f.owner.token)).json() as any;for(const key of ["deliveryMasterUrl","loudnessReportUrl"]){const download=await fetch(new URL(delivered.output[key],f.server.url));expect(download.status).toBe(200);}expect((await quote(second!.id)).session.finishing).toEqual(next.session.finishing);
    expect((await f.call(f.base+"/dialogue-selection","PUT",{jobId:second!.id,sourceJobId:f.film.id,expectedVersion:0,expectedOutputRevision:outputRevision(second!)},f.owner.token)).status).toBe(200);
    const snapshot:StateSnapshot={schema:"hv-state/3",projects:JSON.parse(readFileSync(f.paths.statePath,"utf8")),jobs:f.store.all().filter(j=>j.soundMix),ledger:{events:[],reservations:[]},reviews:[]};expect(validateSnapshot(snapshot).jobs).toHaveLength(2);expect(()=>validateSnapshot({...snapshot,schema:"hv-state/1"})).toThrow("schema 3");
    const original=wav("stems/mix.wav"),changed=Buffer.from(original);changed[12345]^=1;writeFileSync(join(baseDir,"stems/mix.wav"),changed);await expect(verifySoundMedia(rendered!,rendered!.output!,f.paths.artifactRoot)).rejects.toThrow("checksum");writeFileSync(join(baseDir,"stems/mix.wav"),original);
    expect((await f.call(f.base+"/sounds/"+asset.id,"PUT",{expectedVersion:1,available:false},f.owner.token)).status).toBe(200);expect((await fetch(new URL(view.output.mixStemUrl,f.server.url))).status).toBe(404);
    const clearing=await quote(second!.id);expect(clearing.error).toBeUndefined();const clear={...body,idempotencyKey:crypto.randomUUID(),sourceRevision:clearing.sourceRevision,session:{reviewed:true,dialogueGainDb:0,narrationGainDb:0,cues:[]}};expect((await f.call(f.base+"/sound-mixes/"+second!.id,"POST",clear,f.owner.token)).status).toBe(202);const cleared=await f.worker();expect(cleared?.failureReason??cleared?.cancelReason).toBeUndefined();expect(cleared?.status).toBe("done");expect(cleared!.output!.sound!.report.finishing).toBeUndefined();expect(cleared!.output!.sound!.report.stems.mix).toBe(report.stems.dialogue);expect(audioPcmHash(wav("stems/dialogue.wav"))).toBe(report.stems.dialogue);
  }finally{await f.close();}
},120000);
