import {expect,test} from "bun:test";
import {readFileSync} from "node:fs";
import {join} from "node:path";
import {DUB_SCRIPT,dubStudio} from "../../../test/fixtures/dub-studio";
import {AMBIENCE_RECIPE} from "../../planner/src/sound-ambience";

// HV-024-12: a cut's scenes get the studio's own ambience beds. The API reads the scenes from the
// cut, renders the beds into the sound library once, and answers cues the sound-mix route takes;
// the worker mixes them under the voices like any other cue. Real server, real worker, real FFmpeg.
const SCRIPT=DUB_SCRIPT+"\n\nEXT. BEACH - NIGHT\n\nWaves roll in under the pier.";

/**
 * The whole path: the cut's two scenes get room tone and surf from their headings, the beds are
 * saved to the library once with the studio's credit, a second request reuses them, and the mixed
 * version carries them on the ambience stem with the studio's credit in its cue sheet, at no cost.
 */
test("a sound session with the studio's ambience mixes a bed under each scene, credited to the studio",async()=>{
  const f=await dubStudio(undefined,SCRIPT);try{
    const path=f.base+"/ambience/"+f.film.id;
    expect((await f.call(path,"GET")).status).toBe(401);
    const quoted=await(await f.call(path,"GET",undefined,f.owner.token)).json() as any;
    expect(quoted.costUsd).toBe(0);expect(quoted.presets.map((p:any)=>p.id)).toEqual(["room-tone","wind","rain","traffic","surf","crowd","night"]);
    expect(quoted.scenes.map((s:any)=>[s.sceneNumber,s.heading,s.preset,s.chosenBy])).toEqual([[1,"INT. GARDEN - DAY","room-tone","heading"],[2,"EXT. BEACH - NIGHT","surf","heading"]]);
    const total=quoted.scenes.at(-1).start+quoted.scenes.at(-1).frames,boundary=quoted.scenes[1].start;expect(quoted.scenes[0].start).toBe(0);expect(boundary).toBe(quoted.scenes[0].frames);

    // A preset outside the catalogue is refused and keeps nothing.
    const refused=await f.call(path,"POST",{overrides:{"2":"thunder"}},f.owner.token);expect(refused.status).toBe(400);expect(await refused.text()).toContain("catalogue");
    expect((await(await f.call(f.base+"/sounds","GET",undefined,f.owner.token)).json() as any).library.assets).toHaveLength(0);

    const made=await f.call(path,"POST",{},f.owner.token);expect(made.status).toBe(201);const first=await made.json() as any;
    expect(first.costUsd).toBe(0);expect(first.library.assets.map((a:any)=>a.label).sort()).toEqual(["Room tone","Surf"]);
    for(const asset of first.library.assets){expect(asset.rights.credit).toBe("Ambience generated by the studio");expect(asset.rights.basis).toBe("original");expect(asset.audio.frames).toBe(AMBIENCE_RECIPE.loopFrames);}
    expect(first.cues.map((c:any)=>[c.role,c.start,c.frames,c.loop])).toEqual([["ambience",0,boundary,true],["ambience",boundary,total-boundary,true]]);
    expect(first.cues[0].fadeOut).toBe(12000);expect(first.cues[1].fadeIn).toBe(12000);

    // Asked again, the beds are reused and the cues are the same.
    const again=await f.call(path,"POST",{},f.owner.token);expect(again.status).toBe(200);const second=await again.json() as any;
    expect(second.cues).toEqual(first.cues);expect(second.library.version).toBe(first.library.version);

    const q=await(await f.call(f.base+"/sound-mixes/"+f.film.id,"GET",undefined,f.owner.token)).json() as any;expect(q.durationSec*30*1600).toBe(total);
    const body={idempotencyKey:crypto.randomUUID(),generationApproved:true,sourceRevision:q.sourceRevision,engineVersion:q.engineVersion,session:{reviewed:true,dialogueGainDb:0,narrationGainDb:0,cues:first.cues}};
    const queued=await f.call(f.base+"/sound-mixes/"+f.film.id,"POST",body,f.owner.token);expect(queued.status).toBe(202);
    const rendered=await f.worker();expect(rendered?.failureReason??rendered?.cancelReason).toBeUndefined();expect(rendered?.status).toBe("done");expect(rendered!.costUsd).toBe(0);
    const report=rendered!.output!.sound!.report,dir=join(f.paths.artifactRoot,rendered!.output!.mp4Path.slice(0,-"export.mp4".length)),ambience=readFileSync(join(dir,"stems/ambience.wav"));
    expect(report.stems.me).toBe(report.stems.ambience);expect(report.stems.mix).not.toBe(report.stems.dialogue);expect(report.peaks.ambience).toBeGreaterThan(0);
    // Each scene has its bed, and the bed dips at the scene boundary where it changes.
    const energy=(from:number,to:number)=>{let sum=0;for(let i=from;i<to;i++)sum+=ambience.readIntLE(44+i*6,3)**2;return sum/(to-from);};
    expect(energy(boundary-48000,boundary-24000)).toBeGreaterThan(0);expect(energy(boundary+24000,boundary+48000)).toBeGreaterThan(0);
    expect(energy(boundary-200,boundary+200)).toBeLessThan(Math.min(energy(boundary-48000,boundary-24000),energy(boundary+24000,boundary+48000))/4);
    expect(ambience.readIntLE(44,3)).toBe(0);
    const view=await(await f.call("/api/jobs/"+rendered!.id,"GET",undefined,f.owner.token)).json() as any,sheet=await(await fetch(new URL(view.output.cueSheetUrl,f.server.url))).json() as any;
    expect(sheet.cues.map((c:any)=>[c.role,c.recording,c.rights.credit])).toEqual([["ambience","Room tone","Ambience generated by the studio"],["ambience","Surf","Ambience generated by the studio"]]);
  }finally{await f.close();}
},180000);

/** The creator's override silences the first scene and the second keeps its bed; nothing new is rendered for it. */
test("a creator's override silences one scene's ambience and keeps the other's",async()=>{
  const f=await dubStudio(undefined,SCRIPT);try{
    const path=f.base+"/ambience/"+f.film.id,response=await f.call(path,"POST",{overrides:{"1":"none"}},f.owner.token);expect(response.status).toBe(201);const made=await response.json() as any;
    expect(made.scenes.map((s:any)=>[s.preset,s.chosenBy])).toEqual([[null,"creator"],["surf","heading"]]);expect(made.library.assets.map((a:any)=>a.label)).toEqual(["Surf"]);
    expect(made.cues).toHaveLength(1);expect(made.cues[0].start).toBe(made.scenes[1].start);
    const unknown=await f.call(path,"POST",{overrides:{"7":"rain"}},f.owner.token);expect(unknown.status).toBe(400);expect(await unknown.text()).toContain("Scene 7 is not in this cut");
    expect((await f.call(f.base+"/ambience/"+crypto.randomUUID(),"GET",undefined,f.owner.token)).status).toBe(404);
  }finally{await f.close();}
},120000);
