/**
 * HV-031-17 — dialogue, lip-sync and sound versions of a film are signed too.
 *
 * A review link can be bound to a dialogue replacement, a lip-sync version or a sound mix, and each
 * writes its own record. These tests make all three in a chain, as the studio does: a dialogue
 * version of the film, a lip-sync pass over it, then a sound mix over the accepted lip-sync. Each is
 * signed beside its own record by a throwaway identity generated by this run, and each later stage
 * reads the earlier one's signed output back as its source.
 */
import { afterAll, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { createLipSyncFixture, completeLipSyncFixture } from "../../../test/fixtures/lipsync";
import { verifyC2paSidecar } from "../../assembler/src/c2pa";
import { makeC2paTestIdentity, withC2paEnv } from "../../assembler/test/c2pa-fixture";
import { contentHash } from "../../generator/src/capabilities";
import { verifySoundMedia } from "../../generator/src/sound-media";
import { validateDialogueOutput } from "../../planner/src/dialogue-jobs";
import { validateLipSyncOutput } from "../../planner/src/lipsync";
import { validateSoundOutput } from "../../planner/src/sound-jobs";
import { CostLedger, OperatorReviewQueue } from "../../operator/src/index";
import { processNextJob } from "../../queue/src/worker";
import type { Job } from "../../queue/src/index";
import { createApiServer } from "../src/server";

const TMP = mkdtempSync(join(tmpdir(), "hv-voice-c2pa-"));
const identity = makeC2paTestIdentity(join(TMP, "identity"));
const sha = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");
const KEYS = ["HV_TOKEN_SECRET", "HV_NARRATION", "HV_ANIMATIC_CAPTIONS", "HV_ANIMATIC_PROVIDER_POOL", "HV_AUDIO_POLICY_FILE", "HV_LIPSYNC_POLICY_FILE"];
afterAll(() => rmSync(TMP, { recursive: true, force: true }));

/** The dialogue version and the lip-sync pass over it, made by the shared fixture, and a server over them. */
async function voiceVersions(root: string) {
  Object.assign(process.env, { HV_TOKEN_SECRET: "voice-c2pa-fixture-secret-at-least-thirty-two-characters", HV_NARRATION: "1", HV_ANIMATIC_CAPTIONS: "0", HV_ANIMATIC_PROVIDER_POOL: '["mock"]' });
  const f = await createLipSyncFixture(root);
  process.env.HV_AUDIO_POLICY_FILE = join(root, "audio-policy.json");process.env.HV_LIPSYNC_POLICY_FILE = join(root, "lipsync-policy.json");
  const lip = await completeLipSyncFixture(f);
  const server = createApiServer({ port: 0, hostname: "127.0.0.1", queuePath: join(root, "jobs.json"), statePath: join(root, "projects.json"), costLedgerPath: join(root, "ledger.json"), artifactRoot: f.artifacts, rateLimit: { api: { limit: 10000, windowMs: 60000 } } });
  const call = (path: string, method = "GET", body?: unknown) => fetch(new URL(path, server.url), { method, headers: { authorization: "Bearer " + f.owner.token, "content-type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
  return { f, lip: lip.done, server, call, base: "/api/projects/" + f.project.id };
}

/** Each stage's record names its own MP4 and its own sidecar's bytes, and the sidecar reads `Trusted`. */
async function signedBeside(artifacts: string, job: Job, spec: string) {
  const output = job.output!, directory = join(artifacts, dirname(output.manifestPath));
  expect({ stage: job.stage, c2paPath: output.c2paPath }).toEqual({ stage: job.stage, c2paPath: dirname(output.manifestPath) + "/provenance.c2pa" });
  const record = JSON.parse(readFileSync(join(directory, "provenance.json"), "utf8")), sidecar = readFileSync(join(directory, "provenance.c2pa")), mp4 = join(artifacts, output.mp4Path);
  expect(record.credentials).toEqual({ type: "c2pa-sidecar", issuer: "hollywood-video-app", claim: "AI-generated video; content credentials sha256:" + sha(readFileSync(mp4)), sidecar: { name: "provenance.c2pa", sha256: sha(sidecar) } });
  const verified = await verifyC2paSidecar(mp4, sidecar, identity.anchorPem);
  expect({ stage: job.stage, state: verified.state, codes: verified.codes }).toEqual({ stage: job.stage, state: "Trusted", codes: [] });
  expect(verified.provenance).toMatchObject({ spec, mp4Sha256: sha(readFileSync(mp4)) });
  return record;
}

/**
 * The dialogue version, the lip-sync pass over it and the sound mix over that are each signed beside
 * their own record. The lip-sync reads the signed dialogue back as its source and the sound mix reads
 * the signed lip-sync back as its base, so a signed record is accepted wherever a later stage checks
 * an earlier one. A review link bound to the sound mix serves its sidecar, which verifies against the
 * MP4 the link serves.
 */
test("a dialogue version, a lip-sync over it and a sound mix over that are each signed, and the mix's review link serves a sidecar that verifies", async () => {
  const root = join(TMP, "signed"), previous = Object.fromEntries(KEYS.map(k => [k, process.env[k]]));let server: ReturnType<typeof createApiServer> | undefined;
  try {
    await withC2paEnv({ key: identity.keyPath, cert: identity.chainPath }, async () => {
      const made = await voiceVersions(root), { f, lip, call, base } = made;server = made.server;
      const dialogue = f.dialogue;
      validateDialogueOutput(dialogue, dialogue.output!);
      const dialogueRecord = await signedBeside(f.artifacts, dialogue, dialogue.output!.dialogue!.report.schema);
      expect(dialogue.output!.dialogue!.report.credentials).toEqual(dialogueRecord.credentials);
      validateLipSyncOutput(lip, lip.output!);
      await signedBeside(f.artifacts, lip, "hv-lipsync-result/1");
      // The lip-sync's admitted source is the signed dialogue record, credentials and all.
      expect(lip.lipSync!.source.dialogue.credentials).toEqual(dialogueRecord.credentials);

      expect((await call(base + "/lip-sync/" + lip.id + "/review", "PUT", { mouthSync: 4, faceStability: 4, expression: 4, decision: "accept", notes: "Synthetic local fixture only.", expectedVersion: 0, expectedOutputRevision: contentHash(lip.output) })).status).toBe(200);
      const path = base + "/sound-mixes/" + lip.id, q = await (await call(path)).json() as any;expect(q.error).toBeUndefined();
      expect((await call(path, "POST", { idempotencyKey: crypto.randomUUID(), generationApproved: true, sourceRevision: q.sourceRevision, engineVersion: q.engineVersion, session: { reviewed: true, dialogueGainDb: 0, narrationGainDb: 0, cues: [] } })).status).toBe(202);
      const mix = (await processNextJob(f.store, f.artifacts, { projects: f.projects, ledger: new CostLedger(join(root, "ledger.json")), reviewQueue: new OperatorReviewQueue(join(root, "reviews.json")) }))!;
      expect({ status: mix.status, failed: mix.failureReason ?? mix.cancelReason ?? null }).toEqual({ status: "done", failed: null });
      await verifySoundMedia(mix, mix.output!, f.artifacts);
      await signedBeside(f.artifacts, mix, mix.output!.sound!.report.schema);
      // The base's own sidecar was carried into the mix's retained copy of its source.
      expect(mix.output!.sound!.files.some(file => file.path.endsWith("/source/" + lip.output!.c2paPath))).toBe(true);

      const dropped = structuredClone(mix.output!);delete dropped.c2paPath;
      expect(() => validateSoundOutput(mix, dropped)).toThrow("names a C2PA sidecar the export does not hold");
      const droppedLip = structuredClone(lip.output!);delete droppedLip.c2paPath;
      // Lip-sync's own inventory check sees the unlisted sidecar first.
      expect(() => validateLipSyncOutput(lip, droppedLip)).toThrow("unexpected artifact");
      const droppedDialogue = structuredClone(dialogue.output!);delete droppedDialogue.c2paPath;
      expect(() => validateDialogueOutput(dialogue, droppedDialogue)).toThrow("names a C2PA sidecar the export does not hold");

      const view = await (await call("/api/jobs/" + mix.id)).json() as any;
      const link = await (await call(base + "/reviews", "POST", { jobId: mix.id, expectedOutputRevision: view.outputRevision, permission: "approve" })).json() as any;
      const opened = await (await fetch(new URL("/api/reviews/" + encodeURIComponent(link.token), server!.url))).json() as any;
      expect({ jobId: opened.jobId, stage: opened.stage }).toEqual({ jobId: mix.id, stage: "sound-mix" });
      const sidecarResponse = await fetch(new URL(opened.output.c2paUrl, server!.url));
      expect(sidecarResponse.headers.get("content-type")).toBe("application/c2pa");
      const sidecar = Buffer.from(await sidecarResponse.arrayBuffer()), mp4 = new Uint8Array(await (await fetch(new URL(opened.output.mp4Url, server!.url))).arrayBuffer()), served = join(TMP, "served-mix.mp4");
      writeFileSync(served, mp4);
      const record = await (await fetch(new URL(opened.output.manifestUrl, server!.url))).json() as any;
      expect(record.credentials.sidecar.sha256).toBe(sha(sidecar));
      expect((await verifyC2paSidecar(served, sidecar, identity.anchorPem)).state).toBe("Trusted");
      // The other two versions are linked for download the same way.
      for (const job of [dialogue, lip]) {
        const jobView = await (await call("/api/jobs/" + job.id)).json() as any;
        expect(jobView.output.c2paUrl).toContain("/" + job.output!.c2paPath);
      }
    });
  } finally {
    await server?.stop(true);
    for (const [k, v] of Object.entries(previous)) {if (v === undefined) delete process.env[k]; else process.env[k] = v;}
  }
}, 240000);

/** Without a key the dialogue and lip-sync versions name their MP4s as unsigned, with no sidecar anywhere. */
test("without a key a dialogue version and a lip-sync over it say they are unsigned and hold no sidecar", async () => {
  const root = join(TMP, "unsigned"), previous = Object.fromEntries(KEYS.map(k => [k, process.env[k]]));let server: ReturnType<typeof createApiServer> | undefined;
  try {
    await withC2paEnv({}, async () => {
      const made = await voiceVersions(root);server = made.server;
      for (const job of [made.f.dialogue, made.lip]) {
        const output = job.output!, directory = join(made.f.artifacts, dirname(output.manifestPath));
        expect({ stage: job.stage, c2paPath: Object.hasOwn(output, "c2paPath"), sidecar: existsSync(join(directory, "provenance.c2pa")) }).toEqual({ stage: job.stage, c2paPath: false, sidecar: false });
        expect(JSON.parse(readFileSync(join(directory, "provenance.json"), "utf8")).credentials).toEqual({ type: "c2pa-style", issuer: "hollywood-video-app", claim: "AI-generated video; content credentials sha256:" + sha(readFileSync(join(made.f.artifacts, output.mp4Path))) });
      }
    });
  } finally {
    await server?.stop(true);
    for (const [k, v] of Object.entries(previous)) {if (v === undefined) delete process.env[k]; else process.env[k] = v;}
  }
}, 240000);
