import {expect,test} from 'bun:test';
import {assemblyDraftKey,assemblyInput,validateAssemblyDetail} from '../src/edit-assemblies-state.js';
import {assemblyFixture,hash} from './edit-assemblies-fixture.js';

test('assembly creation is lazy and saves a full-parent, honestly short 60-second proposal before acceptance',async()=>{
  const f=assemblyFixture();f.store.bind();expect(f.requests).toHaveLength(0);await f.store.load();f.store.fresh();const initial=structuredClone(f.store.state.draft);expect(initial.ranges[0]).toMatchObject({fromFrame:'0',toFrame:'90',reason:'Start from the complete saved cut.'});f.store.edit('label','  My trailer  ');f.store.edit('purpose','sixty-second');await f.store.review();const post=f.requests.at(-1);expect(post).toMatchObject({path:'/assemblies/proposals',method:'POST',body:{sequenceId:'cut',expected:{libraryVersion:0,historyRevision:hash(1)},input:{id:initial.id,label:'My trailer',purpose:'sixty-second',ranges:[{id:initial.ranges[0].id,fromFrame:0,toFrame:90,reason:'Start from the complete saved cut.'}]}}});expect(f.assemblies.size).toBe(0);expect(f.store.state.detail.review.target).toEqual({frames:1800,status:'short',deltaFrames:-1710});expect(f.store.state.list.proposals.map(value=>value.id)).toEqual([initial.id]);expect(f.store.state.dirty).toBe(false);expect(f.dirty).toEqual([true,false]);
});
test('raw fields, range IDs, order and duplicates survive edits, invalid saves and explicit recovery',async()=>{
  const f=assemblyFixture();await f.start();const first=f.store.state.draft.ranges[0].id;f.store.edit('fromFrame',' 03 ',first);f.store.add(first);const second=f.store.state.draft.ranges[1].id;expect(second).not.toBe(first);f.store.move(second,0);f.store.edit('toFrame','',second);const before=f.requests.length;await expect(f.store.review()).rejects.toThrow('whole frame');expect(f.requests).toHaveLength(before);const raw=structuredClone(f.store.state.draft);expect(raw.ranges.map(value=>value.id)).toEqual([second,first]);expect(raw.ranges[0].toFrame).toBe('');f.store.dispose();const restored=assemblyFixture({storage:f.storage});restored.store.bind();expect(restored.store.state.draft).toBeNull();expect(restored.store.state.recovered.draft).toEqual(raw);restored.store.restore();expect(restored.store.state.draft).toEqual(raw);restored.store.edit('toFrame','25',second);expect(assemblyInput(restored.store.state.draft).ranges[0]).toMatchObject({fromFrame:3,toFrame:25});restored.store.remove(second);expect(restored.store.state.draft.ranges[0].id).toBe(first);
});
test('proposal revisions carry exact expected identities; unsaved edits block acceptance',async()=>{
  const f=assemblyFixture(),saved=await f.saved(),range=f.store.state.draft.ranges[0].id;f.store.edit('toFrame','60',range);await expect(f.store.accept()).rejects.toThrow('Save and review');await f.store.review();expect(f.requests.at(-1)).toMatchObject({method:'PATCH',path:'/assemblies/proposals/'+saved.item.id,body:{input:{label:saved.item.label,purpose:'custom',ranges:[{id:range,fromFrame:0,toFrame:60,reason:'Start from the complete saved cut.'}]},expected:{libraryVersion:1,historyRevision:hash(1),proposalRevision:saved.item.revision}}});expect(f.requests.at(-1).body.input).not.toHaveProperty('id');expect(f.store.state.detail.review.omitted).toEqual([{fromFrame:60,toFrame:90}]);expect(f.store.state.dirty).toBe(false);
});
test('lost acceptance persists one fixed request and reload retries it exactly without a second assembly',async()=>{
  let lose=true;const f=assemblyFixture({intercept:(call,run)=>{const result=run();if(call.path.endsWith('/accept')&&lose){lose=false;throw new Error('Response lost.');}return result;}});const reviewed=await f.saved();await f.store.accept();expect(f.store.state.pending.kind).toBe('accept');expect(f.assemblies.size).toBe(1);const pending=structuredClone(f.store.state.pending),first=structuredClone(f.requests.at(-1));expect(first.body).toMatchObject({proposalRevision:reviewed.item.revision,expected:{libraryVersion:1,historyRevision:hash(1)},reviewRevision:reviewed.review.revision,boundariesRevision:reviewed.boundaries.revision,sourceBindingsRevision:reviewed.sourceBindingsRevision,accepted:true});f.store.dispose();const next=assemblyFixture({storage:f.storage,intercept:(call)=>f.request(call.path,{method:call.method,body:call.body})});next.store.bind();expect(next.store.state.pending).toEqual(pending);await next.store.retry();expect(next.requests.at(-1)).toEqual(first);expect(f.assemblies.size).toBe(1);expect(next.accepted).toHaveLength(1);expect(next.store.state.draft.accepted).toBe(true);expect(next.store.state.pending).toBeNull();expect(next.store.state.list.assemblies[0].id).toBe(first.body.assemblyId);expect(next.storage.getItem('hv-assembly-pending:project')).toBeNull();
});
test('lost proposal writes reconcile by exact GET before retry and never recreate matching saved ranges',async()=>{
  let lose=true;const f=assemblyFixture({intercept:(call,run)=>{const result=run();if(call.method==='POST'&&lose){lose=false;throw new Error('Response lost.');}return result;}});await f.start();await f.store.review();expect(f.store.state.pending.kind).toBe('create');await f.store.retry();expect(f.requests.map(call=>call.method)).toEqual(['GET','POST','GET']);expect(f.store.state.pending).toBeNull();expect(f.store.state.dirty).toBe(false);
});
test('post-save HTTP errors reconcile the persisted proposal before releasing the request',async()=>{
  let fail=true;const f=assemblyFixture({intercept:(call,run)=>{const result=run();if(call.method==='POST'&&fail){fail=false;throw Object.assign(new Error('Library changed during response.'),{status:400});}return result;}});await f.start();await f.store.review();expect(f.proposals.size).toBe(1);expect(f.store.state.pending).toBeNull();expect(f.store.state.dirty).toBe(false);expect(f.requests.map(call=>call.method)).toEqual(['GET','POST','GET']);
});
test('acceptance replay permits refreshed carriers without changing the fixed reviewed request',async()=>{
  let lose=true;const f=assemblyFixture({intercept:(call,run)=>{const result=run();if(call.path.endsWith('/accept')){if(lose){lose=false;throw new Error('Lost response.');}result.sourceBindingsRevision=hash(501);}return result;}});await f.saved();await f.store.accept();const body=structuredClone(f.store.state.pending.body);await f.store.retry();expect(f.store.state.pending).toBeNull();expect(f.requests.at(-1).body).toEqual(body);expect(f.accepted[0].sourceBindingsRevision).toBe(hash(501));
});
test('known rejected acceptance is released only after authoritative absence, while uncertain lookup keeps its fixed payload',async()=>{
  let absent=true;const f=assemblyFixture({intercept:(call,run)=>{if(call.path.endsWith('/accept'))throw Object.assign(new Error('Review changed.'),{status:409});if(call.path.startsWith('/assemblies/accepted/')&&!absent)throw new Error('Connection lost.');return run();}});await f.saved();absent=false;await f.store.accept();const pending=structuredClone(f.store.state.pending);expect(pending.kind).toBe('accept');await expect(Promise.resolve().then(()=>f.store.discard())).rejects.toThrow('Check the saved request');absent=true;await f.store.retry();expect(f.store.state.pending).toBeNull();expect(f.store.state.dirty).toBe(true);expect(f.store.state.detail).toBeNull();expect(f.store.state.message).toContain('was not created');expect(f.requests.filter(call=>call.path.endsWith('/accept')).map(call=>call.body.assemblyId)).toEqual([pending.body.assemblyId,pending.body.assemblyId]);
});
test('busy, hidden and changed parent guards preserve raw ranges and require explicit copy without clamping',async()=>{
  const f=assemblyFixture();await f.start();const raw=structuredClone(f.store.state.draft),old=f.current;f.setCurrent({...old,busy:true});f.store.bind();expect(()=>f.store.edit('label','Bad')).toThrow('other open edit');f.setCurrent(null);f.store.bind();expect(f.store.state.draft).toEqual(raw);await expect(f.store.review()).rejects.toThrow('Reopen');f.setCurrent({...old,historyRevision:hash(2),frames:20});f.store.bind();await expect(f.store.review()).rejects.toThrow('saved parent changed');expect(f.store.state.draft).toEqual(raw);f.store.copyCurrent();expect(f.store.state.draft.id).not.toBe(raw.id);expect(f.store.state.draft.parent.historyRevision).toBe(hash(2));expect(f.store.state.draft.ranges).toEqual(raw.ranges);await expect(f.store.review()).rejects.toThrow('within parent frames 0–20');
});
test('stored earlier-history draft restores explicitly and corrupt pending requests cannot be replayed',async()=>{
  const f=assemblyFixture();await f.start();const raw=structuredClone(f.store.state.draft);f.store.dispose();const next=assemblyFixture({storage:f.storage});next.setCurrent({...next.current,historyRevision:hash(2)});next.store.bind();expect(next.store.state.recovered.draft).toEqual(raw);next.store.restore();await expect(next.store.review()).rejects.toThrow('unchanged saved parent');expect(next.storage.getItem(assemblyDraftKey('project','cut'))).toContain(hash(1));next.store.dispose();f.storage.setItem('hv-assembly-pending:project',JSON.stringify({schema:'hv-assembly-pending/1',projectId:'project',kind:'accept',id:raw.id,draft:raw,base:next.current,parent:raw.parent,path:'/assemblies/proposals/'+raw.id+'/accept',method:'DELETE',body:{}}));const corrupt=assemblyFixture({storage:f.storage});corrupt.store.bind();expect(corrupt.store.state.pending).toBeNull();expect(corrupt.store.state.message).toContain('cannot be retried');expect(corrupt.requests).toHaveLength(0);
});
test('late list replies cannot replace a newly bound parent and mismatched review identity fails closed',async()=>{
  let finish;const f=assemblyFixture({intercept:(_call,run)=>new Promise(resolve=>{finish=()=>resolve(run());})});f.store.bind();const loading=f.store.load(),signal=f.requests[0].signal;f.setCurrent({...f.current,historyRevision:hash(2)});f.store.bind();expect(signal.aborted).toBe(true);finish();await loading;expect(f.store.state.list).toBeNull();const good=assemblyFixture();const detail=await good.saved();expect(()=>validateAssemblyDetail({...detail,review:{...detail.review,planRevision:hash(99)}})).toThrow('changed or is incomplete');good.store.dispose();
});
