import {expect,test} from 'bun:test';
import {contentHash} from '../../generator/src/capabilities.ts';
import {createAssemblyRenderState,createAssemblyRenderPanel,validateAssemblyRenderQuote} from '../src/edit-assemblies-render.js';
import {createEditAssemblyStudio} from '../src/edit-assemblies.js';
import {Element,hash,installDom,memoryStorage} from './edit-assemblies-fixture.js';

function fixture({intercept,jobReply,storage=memoryStorage()}={}){
  let active={projectId:'project',sequenceId:'parent',historyRevision:hash(1),frames:90,busy:false,canEdit:true};const item={id:'assembly',label:'Owner trailer',acceptedAt:'2026-09-08T00:00:00Z',revision:hash(2),planRevision:hash(3),frames:30,parent:{sequenceId:'parent',timelineRevision:hash(4),historyRevision:hash(1),frames:90}},assembly={projectId:'project',id:item.id,label:item.label,revision:item.revision,planRevision:item.planRevision,frames:item.frames,parentSequenceId:'parent',parentTimelineRevision:hash(4)};
  const sealed=value=>({...value,revision:contentHash(value)}),rangeReview=sealed({schema:'hv-edit-assembly-review/1',planRevision:item.planRevision,purpose:'sixty-second',frames:30,parentFrames:90,uniqueRetainedFrames:30,repeatedFrames:0,omitted:[{fromFrame:0,toFrame:20},{fromFrame:50,toFrame:90}],joins:[],target:{frames:1800,status:'short',deltaFrames:-1770}}),boundaries=sealed({schema:'hv-edit-assembly-boundaries/1',planRevision:item.planRevision,speechCuts:[{rangeId:'r1',clipId:'voice',sourceId:'source',lane:'dialogue',edge:'in',outputFrame:0,parentFrame:20,sourceSample:32000,mutedHold:false,voiceId:'line-1'}],unmeasuredAudioCuts:[]});
  const speechCuts=[{clipId:'dialogue',voiceId:'line-parent',edge:'out'}],unmeasuredAudioCuts=['music'],crossfades=[{id:'dissolve',lane:'picture',at:40,frames:7,alignment:'center',clips:[]}],compositing={timelineRevision:hash(4),matteOnlyLayers:[2],clips:[{clipId:'picture',maskCount:1,keyframeCount:2}],warnings:['Picture uses a luma matte.']},parentReview={speechCuts,unmeasuredAudioCuts,crossfades,compositing,review:{timelineRevision:hash(4),speechCutsRevision:contentHash(speechCuts),unmeasuredCutsRevision:contentHash(unmeasuredAudioCuts),crossfadesRevision:contentHash(crossfades),compositingRevision:contentHash(compositing),accepted:true}},resources={outputBytes:1024,workspaceBytes:2048,files:8};
  const review={assemblyRevision:item.revision,planRevision:item.planRevision,rangeReviewRevision:rangeReview.revision,boundariesRevision:boundaries.revision,parentReviewRevision:contentHash(parentReview.review),sourceBindingsRevision:hash(5),resourcesRevision:contentHash(resources),accepted:false};
  const quote={assembly:{id:item.id,label:item.label,revision:item.revision,frames:item.frames,parentSequenceId:'parent'},engineVersion:'ffmpeg-sound-'+hash(6),sourceBindingsRevision:hash(5),resources,unavailable:null,costUsd:0,review,rangeReview,boundaries,parentReview,jobs:[]},requests=[],jobs=new Map(),dirty=[],selected=[];
  function job(body,status='queued'){return {id:'job-'+(jobs.size+1),projectId:'project',status,assemblyEdit:{assemblyId:item.id,label:item.label,assemblyRevision:item.revision,planRevision:hash(7),parentSequenceId:'parent',sourceCount:1,review:{...body.review}},outputRevision:status==='done'?hash(8):null,...(status==='done'?{captionLanguage:'en',output:{mp4Url:'/artifacts/result.mp4?signed=yes',hlsUrl:'/artifacts/result.m3u8?signed=yes',captionsUrl:'/artifacts/result.vtt?signed=yes',assemblyUrl:'/artifacts/assembly.json?signed=yes',timelineUrl:'/artifacts/timeline.json?signed=yes',manifestUrl:'/artifacts/provenance.json?signed=yes'}}:{})};}
  const request=async(path,options={})=>{const call={path,method:options.method??'GET',body:options.body?structuredClone(options.body):undefined,signal:options.signal};requests.push(call);const run=()=>{if(path.includes('/render-requests/')){const known=jobs.get(path.split('/').at(-1));return known?{admitted:true,job:structuredClone(known.job),requestHash:contentHash(known.body)}:{admitted:false};}if(call.method==='POST'){let known=jobs.get(call.body.idempotencyKey);if(!known){known={job:job(call.body),body:call.body};jobs.set(call.body.idempotencyKey,known);}return {jobId:known.job.id};}return {...structuredClone(quote),jobs:[...jobs.values()].map(value=>structuredClone(value.job))};};return intercept?await intercept(call,run):run();};
  const jobRequest=async(jobId,options={})=>{requests.push({path:'/api/jobs/'+jobId,method:'GET',signal:options.signal});const found=[...jobs.values()].find(value=>value.job.id===jobId)?.job;if(!found)throw new Error('Job not found.');return jobReply?await jobReply(structuredClone(found)):structuredClone(found);};
  const onSelectExport=async value=>{selected.push(value);return {selected:true};},store=createAssemblyRenderState({request,jobRequest,current:()=>active,storage,onDirty:value=>dirty.push(value),onSelectExport});
  return {item,assembly,quote,requests,jobs,dirty,selected,store,storage,request,jobRequest,onSelectExport,job,get current(){return active;},setCurrent:value=>{active=value;},async load(){store.bind({item});await store.load();},complete(){for(const value of jobs.values())value.job={...job(value.body,'done'),id:value.job.id};}};
}

test('render review binds visible parent, range, boundary and capacity warnings to their seals',async()=>{
  const f=fixture();expect((await validateAssemblyRenderQuote(f.quote,f.assembly)).review.accepted).toBe(false);for(const mutate of [q=>q.parentReview.speechCuts[0].edge='in',q=>q.rangeReview.target.status='exact',q=>q.boundaries.speechCuts[0].voiceId='other',q=>q.resources.workspaceBytes++,q=>q.parentReview.compositing.warnings.push('different')]){const changed=structuredClone(f.quote);mutate(changed);await expect(validateAssemblyRenderQuote(changed,f.assembly)).rejects.toThrow('differ');}await expect(validateAssemblyRenderQuote({...f.quote,assembly:{...f.quote.assembly,revision:hash(99)}},f.assembly)).rejects.toThrow('changed');
});
test('render admission requires a fresh quote and sends only the exact reviewed body; admitted jobs release editing locks',async()=>{
  const f=fixture();f.store.bind({item:f.item});expect(f.requests).toHaveLength(0);await expect(f.store.render()).rejects.toThrow('Load and review');await f.store.load();await f.store.render();const post=f.requests.find(call=>call.method==='POST');expect(post.body).toEqual({idempotencyKey:post.body.idempotencyKey,generationApproved:true,assemblyRevision:f.item.revision,sourceBindingsRevision:f.quote.sourceBindingsRevision,engineVersion:f.quote.engineVersion,review:{...f.quote.review,accepted:true}});expect(post.path).toBe('/assemblies/accepted/assembly/renders');expect(f.store.state.pending.jobId).toBe('job-1');expect(f.store.state.locked).toBe(false);expect(f.store.state.job.status).toBe('queued');expect(f.store.state.quote).toBeNull();expect(f.dirty.at(-1)).toBe(false);
});
test('lost render response and lookup failure survive reload and retry one unchanged request',async()=>{
  let lose=true;const f=fixture({intercept:(call,run)=>{if(call.path.includes('/render-requests/')&&lose)throw new Error('Lookup offline.');const value=run();if(call.method==='POST'&&lose)throw new Error('Response lost.');return value;}});await f.load();await f.store.render();const pending=structuredClone(f.store.state.pending);expect(pending.jobId).toBeUndefined();expect(f.jobs.size).toBe(1);expect(f.store.state.locked).toBe(true);f.store.dispose();lose=false;const next=createAssemblyRenderState({request:f.request,jobRequest:f.jobRequest,current:()=>f.current,storage:f.storage});next.bind(null);expect(next.state.pending).toEqual(pending);await next.retry();expect(f.requests.filter(call=>call.method==='POST').map(call=>call.body)).toEqual([pending.body,pending.body]);expect(f.jobs.size).toBe(1);expect(next.state.pending.jobId).toBe('job-1');expect(next.state.locked).toBe(false);
});
test('an admitted key lookup recovers a lost response, but an absent transport lookup retains the pending request',async()=>{
  const f=fixture({intercept:(call,run)=>{const result=run();if(call.method==='POST')throw new Error('Response lost.');return result;}});await f.load();await f.store.render();expect(f.store.state.pending.jobId).toBe('job-1');expect(f.requests.filter(call=>call.method==='POST')).toHaveLength(1);
  const absent=fixture({intercept:(call,run)=>{if(call.method==='POST')throw new Error('Connection failed before response.');return run();}});await absent.load();await absent.store.render();expect(absent.store.state.pending.jobId).toBeUndefined();expect(absent.store.state.locked).toBe(true);expect(absent.jobs.size).toBe(0);
});
test('definite rejection releases only an authoritative absent render, while mismatched request hashes stay recoverable',async()=>{
  const absent=fixture({intercept:(call,run)=>{if(call.method==='POST')throw Object.assign(new Error('Source carrier changed.'),{status:400});return run();}});await absent.load();await absent.store.render();expect(absent.store.state.pending).toBeNull();expect(absent.store.state.quote).toBeNull();expect(absent.store.state.message).toContain('No render was admitted');expect(absent.storage.getItem('hv-assembly-render-pending:project')).toBeNull();
  const mismatch=fixture({intercept:(call,run)=>{const result=run();if(call.method==='POST')throw new Error('Response lost.');if(call.path.includes('/render-requests/'))result.requestHash=hash(99);return result;}});await mismatch.load();await mismatch.store.render();expect(mismatch.store.state.pending.jobId).toBeUndefined();expect(mismatch.store.state.locked).toBe(true);
});
test('completed jobs use their own output revision for explicit export selection and terminal jobs clear tracking',async()=>{
  const f=fixture();await f.load();await f.store.render();f.complete();await f.store.show('job-1');expect(f.store.state.pending).toBeNull();expect(f.store.state.job.status).toBe('done');expect(f.selected).toHaveLength(0);await f.store.select();expect(f.selected).toEqual([{jobId:'job-1',sourceJobId:'assembly',expectedOutputRevision:hash(8)}]);expect(f.store.state.selected).toBe(true);expect(f.store.state.message).toContain('selected as the project export');
});
test('wrong-job responses and late quote replies never replace an assembly; external drafts block render actions',async()=>{
  const f=fixture({jobReply:value=>({...value,assemblyEdit:{...value.assemblyEdit,assemblyId:'other'}})});await f.load();await f.store.render();expect(f.store.state.job).toBeNull();expect(f.store.state.message).toContain('another saved assembly');f.store.bind({item:f.item},true);await expect(f.store.load()).rejects.toThrow('other edit');
  let complete;const late=fixture({intercept:(_call,run)=>new Promise(resolve=>{complete=()=>resolve(run());})});late.store.bind({item:late.item});const loading=late.store.load(),signal=late.requests[0].signal;late.store.bind(null);expect(signal.aborted).toBe(true);complete();await loading;expect(late.store.state.quote).toBeNull();
});

function mounted(f){const restore=installDom(),root=new Element('section'),panel=createAssemblyRenderPanel({parent:root,request:f.request,jobRequest:f.jobRequest,current:()=>f.current,onSelectExport:f.onSelectExport});const all=(at=root)=>[at,...at.children.flatMap(child=>all(child))],find=(tag,text)=>all().find(element=>element.tagName===tag&&element.textContent===text);panel.bind({item:f.item});return {root,panel,all,find,close(){panel.dispose();restore();}};}
test('mounted render review shows parent warnings, requires approval, then plays signed completed media and exposes files',async()=>{
  const f=fixture(),h=mounted(f);try{expect(f.requests).toHaveLength(0);await h.find('button','Review render and retained outputs').onclick();expect(h.root.textContent).toContain('Parent measured speech cuts');expect(h.root.textContent).toContain('Picture uses a luma matte.');expect(h.root.textContent).toContain('New measured speech boundaries');const render=h.find('button','Render reviewed assembly');expect(render.disabled).toBe(true);const approval=h.all().find(element=>element.type==='checkbox');approval.checked=true;approval.onchange();expect(render.disabled).toBe(false);await render.onclick();expect(h.root.textContent).toContain('queued');f.complete();await h.find('button','Refresh this render status').onclick();const video=h.all().find(element=>element.tagName==='video');expect(video.src).toContain('/artifacts/result.mp4?');expect(video.controls).toBe(true);expect(video.children[0].kind).toBe('captions');expect(h.find('a','Assembly recipe').href).toContain('/artifacts/assembly.json?');expect(h.find('a','Download MP4')).toBeDefined();expect(f.selected).toHaveLength(0);await h.find('button','Use this assembly as project export').onclick();expect(f.selected[0].expectedOutputRevision).toBe(hash(8));expect(h.find('button','Selected project export').disabled).toBe(true);
  }finally{h.close();}
});
test('render refresh clears approval, frozen same-identity binds preserve playback, and unsafe output links never become media',async()=>{
  const f=fixture(),h=mounted(f);try{await h.find('button','Review render and retained outputs').onclick();const approval=h.all().find(element=>element.type==='checkbox');approval.checked=true;approval.onchange();await h.find('button','Refresh render review').onclick();expect(h.all().find(element=>element.type==='checkbox').checked).toBe(false);const second=h.all().find(element=>element.type==='checkbox');second.checked=true;second.onchange();await h.find('button','Render reviewed assembly').onclick();f.complete();await h.find('button','Refresh this render status').onclick();const video=h.all().find(element=>element.tagName==='video');h.panel.bind({item:structuredClone(f.item)});expect(h.all().find(element=>element.tagName==='video')).toBe(video);for(const value of f.jobs.values())value.job.output.mp4Url='javascript:alert(1)';await h.find('button','Refresh this render status').onclick();expect(h.all().some(element=>element.tagName==='video')).toBe(false);expect(h.root.textContent).toContain('output link is unavailable');
  }finally{h.close();}
});
test('studio integrates accepted render controls, request locks and stable saved preview bindings',async()=>{
  const restore=installDom(),f=fixture(),root=new Element('section'),locks=[],bindings=[];let ui;const detail={libraryVersion:2,item:{...f.item,purpose:'sixty-second',ranges:[{id:'r1',fromFrame:20,toFrame:50,reason:'Retain the middle passage.'}]},review:f.quote.rangeReview,boundaries:f.quote.boundaries,resources:f.quote.resources,sourceBindingsRevision:f.quote.sourceBindingsRevision,unavailable:null};
  const request=(path,options={})=>path==='/assemblies'?Promise.resolve({libraryVersion:2,proposals:[],assemblies:[f.item]}):path==='/assemblies/accepted/assembly'?Promise.resolve(detail):f.request(path,options);
  ui=createEditAssemblyStudio({parent:root,request,jobRequest:f.jobRequest,current:()=>f.current,onDirty:value=>locks.push(value),onPreviewBinding:value=>bindings.push(value),onSelectExport:async value=>{expect(ui.pending).toBe(true);return f.onSelectExport(value);}});const all=(at=root)=>[at,...at.children.flatMap(child=>all(child))],find=(tag,text)=>all().find(value=>value.tagName===tag&&value.textContent===text);
  try{ui.bind();ui.panel.open=true;ui.panel.emit('toggle');await Bun.sleep(0);const select=all().find(value=>value.attributes['aria-label']==='Saved assembly proposal');select.value='accepted/assembly';select.onchange();await find('button','Open selected assembly').onclick();expect(bindings.at(-1).item.revision).toBe(f.item.revision);const count=bindings.length;ui.bind();expect(bindings).toHaveLength(count);await find('button','Review render and retained outputs').onclick();expect(find('button','Render reviewed assembly').disabled).toBe(true);const approval=all().find(value=>value.type==='checkbox');approval.checked=true;approval.onchange();await find('button','Render reviewed assembly').onclick();expect(ui.pending).toBe(false);expect(locks).toContain(true);expect(locks.at(-1)).toBe(false);f.complete();await find('button','Refresh this render status').onclick();await find('button','Use this assembly as project export').onclick();expect(f.selected).toHaveLength(1);expect(bindings.at(-1).item.id).toBe('assembly');await find('button','Copy ranges into a new proposal on current parent').onclick();expect(ui.unsaved).toBe(true);expect(bindings.at(-1)).toBeNull();expect(all().some(value=>value.tagName==='video')).toBe(false);
  }finally{ui.dispose();expect(bindings.at(-1)).toBeNull();restore();}
});

/**
 * HV-039-12 — the render panel's messages arrived in a new live region every time, and went unheard.
 *
 * `draw` rebuilt the whole panel on every change, the status line with it:
 *
 *     panel.replaceChildren();…const status=node('p',s.message);…status.setAttribute('role','status');…panel.append(status);
 *
 * so each message ("Loading render capacity…", "Review the range joins…", "Assembly render
 * admitted…", every refusal) was inserted in a newly made role=status element that already held its
 * words. A live region is announced when its content changes; one that appears with its content
 * already inside is not reliably announced at all, so a screen-reader user pressed Render and heard
 * nothing, whether it worked or was refused. The status line is now made once and only its words
 * change.
 */
test('every render message is written into the one status line that was there from the start',async()=>{
  const f=fixture(),h=mounted(f);try{
    const regions=()=>h.all().filter(element=>element.getAttribute?.('role')==='status'),status=regions()[0];
    expect(regions()).toHaveLength(1);expect(status.textContent).toBe('Review and render this independent saved assembly.');
    await h.find('button','Review render and retained outputs').onclick();
    expect(regions()).toEqual([status]);expect(regions()[0]).toBe(status);expect(status.textContent).toContain('Review the range joins');
    const approval=h.all().find(element=>element.type==='checkbox');approval.checked=true;approval.onchange();await h.find('button','Render reviewed assembly').onclick();
    expect(regions()[0]).toBe(status);expect(regions()).toHaveLength(1);expect(status.textContent).not.toContain('Review the range joins');
  }finally{h.close();}
});

test('and a refusal is written there too, where it is announced',async()=>{
  const f=fixture({jobReply:value=>({...value,assemblyEdit:{...value.assemblyEdit,assemblyId:'other'}})}),h=mounted(f);try{
    const status=h.all().find(element=>element.getAttribute?.('role')==='status');
    await h.find('button','Review render and retained outputs').onclick();
    const approval=h.all().find(element=>element.type==='checkbox');approval.checked=true;approval.onchange();await h.find('button','Render reviewed assembly').onclick();
    expect(h.all().find(element=>element.getAttribute?.('role')==='status')).toBe(status);
    expect(status.textContent).toContain('another saved assembly');expect(status.dataset.state).toBe('error');
  }finally{h.close();}
});
