import {expect,test} from 'bun:test';
import {assemblyPreviewView,mountEditAssemblyPreview} from '../src/edit-assembly-preview.js';
import {PreviewMedia,previewIdentity} from '../src/preview-media.js';
import {encodePreviewPage,previewDigest} from '../../planner/src/edit-preview-protocol';
import {PreviewPcmTransport} from '../src/preview-worklet.js';

const hash=n=>n.toString(16).padStart(64,'0'),engineVersion='ffmpeg-sound-'+hash(9),png=Uint8Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAACXBIWXMAAAABAAAAAQBPJcTWAAAAFUlEQVR4nGP8y8Dwn4GBgYEFRIAwAB8HAgKLXcS/AAAAAElFTkSuQmCC','base64'));
const settle=async predicate=>{for(let i=0;i<100;i++){if(predicate())return;await Bun.sleep(1);}throw new Error('Assembly preview fixture did not settle.');};
function detail({accepted=false,frames=66}={}){return {item:{id:'assembly',label:'Reordered and repeated cut',revision:hash(1),planRevision:hash(2),frames,...(accepted?{acceptedAt:'2026-09-08T00:00:00Z'}:{}),parent:{sequenceId:'parent',historyRevision:hash(3),timelineRevision:hash(4),frames:1200,width:640,height:360},ranges:[{id:'late',fromFrame:900,toFrame:930,reason:'Start late.'},{id:'early',fromFrame:70,toFrame:100,reason:'Return earlier.'},{id:'repeat',fromFrame:900,toFrame:906,reason:'Repeat the opening.'}]}};}
class Element{
  constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.attributes={};this.listeners=new Map();this.className='';this.value='';this.disabled=false;this.hidden=false;this.ownText='';this.width=2;this.height=2;this.draws=[];this.context={canvas:this,save(){},restore(){},fillRect(){},drawImage:(image,...rect)=>this.draws.push({image,rect})};}
  set textContent(value){this.ownText=String(value);this.children=[];}
  get textContent(){return this.ownText+this.children.map(child=>child.textContent).join('');}
  append(...values){for(const value of values){value.parentElement=this;this.children.push(value);}}
  setAttribute(key,value){this.attributes[key]=String(value);}
  getAttribute(name){return Object.hasOwn(this.attributes,name)?this.attributes[name]:null;}
  removeAttribute(name){delete this.attributes[name];}
  getContext(){return this.context;}
  checkValidity(){return this.value!==''&&Number.isInteger(Number(this.value))&&Number(this.value)>=Number(this.min??0)&&Number(this.value)<=Number(this.max??Infinity);}
  reportValidity(){return this.checkValidity();}
  addEventListener(type,callback){this.listeners.set(type,callback);}
}
function harness({accepted=false,frames=66,mutateStatus,mutatePacket,deferMedia=false,deferDecode=false}={}){
  const names=['window','document','AudioContext','AudioWorkletNode','requestAnimationFrame','cancelAnimationFrame','createImageBitmap'],originals=new Map(names.map(name=>[name,Object.getOwnPropertyDescriptor(globalThis,name)])),canvases=[],bitmaps=[],requests=[],packets=[],windows=new Map(),contexts=[],nodes=[],animations=new Map(),decodeGates=[];let owner='first',active=true,serial=0;
  const doc=new EventTarget();Object.assign(doc,{activeElement:null,hidden:false,querySelectorAll:()=>[],createElement:tag=>{const element=new Element(tag);if(tag==='canvas')canvases.push(element);return element;}});
  Object.assign(globalThis,{window:new EventTarget(),document:doc,requestAnimationFrame:callback=>{const id=++serial;animations.set(id,callback);return id;},cancelAnimationFrame:id=>animations.delete(id),createImageBitmap:async input=>{const value={kind:input instanceof Blob?'decoded':'composed',width:2,height:2,closed:0,close(){this.closed++;}};bitmaps.push(value);if(deferDecode&&input instanceof Blob)await new Promise(resolve=>decodeGates.push(resolve));return value;},AudioContext:class{sampleRate=48000;currentTime=0;destination={};closed=0;audioWorklet={addModule:async()=>{}};constructor(){contexts.push(this);}async resume(){}async close(){this.closed++;}getOutputTimestamp(){return {contextTime:this.currentTime};}},AudioWorkletNode:class{constructor(){nodes.push(this);this.commands=[];this.transport=new PreviewPcmTransport(message=>this.port.onmessage?.({data:message}));this.port={postMessage:command=>{this.commands.push(command);this.transport.message(command);queueMicrotask(()=>this.port.onmessage?.({data:{kind:'accepted',epoch:command.epoch,requestId:command.requestId}}));},close(){}};}connect(){}disconnect(){}}});
  const saved=detail({accepted,frames}),view=assemblyPreviewView(saved);
  const makeClient=()=>{const captured=owner;return {request:async(path,options={})=>{requests.push({owner:captured,path,...options});if(options.method==='DELETE')return {};let admitted;if(options.method==='POST'){admitted=options.body;windows.set(path+'/'+admitted.id,admitted);}else admitted=windows.get(path.split('?')[0]);if(!admitted)throw new Error('Unknown preview window.');const status={state:'ready',historyRevision:view.assemblyPreview.revision,timelineRevision:view.timeline.revision,from:admitted.from,frames:admitted.frames,audio:{sourceKey:hash(5)},picture:{sourceKey:hash(6),width:2,height:2,pictureEncoding:'png-rgba',picturePurpose:'timeline-composite'},sources:[],engineVersion};return mutateStatus?mutateStatus(status):status;},mediaRequest:async(path,options)=>{packets.push({path,...options});if(deferMedia)await new Promise((_,reject)=>options.signal.addEventListener('abort',()=>reject(options.signal.reason),{once:true}));options.signal.throwIfAborted();const query=new URL(path,'http://fixture').searchParams,from=Number(path.split('?')[0].split('/').at(-1)),picture=path.includes('/picture/'),count=Math.min(60,frames-from),exact=Number(query.get('frame')),base={sourceKey:picture?hash(6):hash(5),sourceId:picture?'timeline-picture':'timeline-audio',sourceRevision:view.timeline.revision,engineVersion,sourceFrames:frames,from,frames:count,width:2,height:2,includePicture:picture,audioLanes:picture?[]:['mix'],...(picture?{pictureEncoding:'png-rgba',picturePurpose:'timeline-composite',pictureFrames:[exact]}:{})};
      if(picture)base.pictureFrames=Array.from({length:count},(_,i)=>from+i).filter(frame=>Math.floor((frame-from)/16)===Math.floor((exact-from)/16));
      const pcm=new Uint8Array(count*1600*6);for(let at=0;at<pcm.length;at+=6){const value=(from+Math.floor(at/(1600*6)))*1000;pcm[at]=value&255;pcm[at+1]=(value>>8)&255;pcm[at+2]=(value>>16)&255;}const identity=mutatePacket?mutatePacket(base):base,bytes=await encodePreviewPage(identity,picture?identity.pictureFrames.map(frame=>({frame,sourceSha256:hash(7),data:png})):[],picture?[]:[{lane:'mix',data:pcm}]);return new Response(new Uint8Array(bytes),{headers:{'content-type':'application/vnd.hollywood-video.preview','x-hv-preview-sha256':await previewDigest(bytes)}});
    }};};
  const run={controller:new AbortController(),at:0},surface=new Element('canvas'),media=new PreviewMedia({surface,active:()=>run,position:()=>Math.floor(run.at/1600),preparing(){},check:value=>{if(!active||value!==run)throw new Error('Wrong active preview.');run.controller.signal.throwIfAborted();}});media.bind(view.timeline,previewIdentity(view,makeClient()));
  return {saved,view,media,run,requests,packets,bitmaps,canvases,contexts,nodes,animations,makeClient,setOwner:value=>{owner=value;},setActive:value=>{active=value;},get active(){return active;},releaseDecode(){deferDecode=false;for(const resolve of decodeGates.splice(0))resolve();},async close(){active=false;run.controller.abort();await media.clear();for(const [name,descriptor]of originals)if(descriptor)Object.defineProperty(globalThis,name,descriptor);else delete globalThis[name];}};
}

test('assembly descriptor exposes only a child display clock and preserves accepted versus proposal identity',()=>{
  const saved=detail(),before=structuredClone(saved),view=assemblyPreviewView(saved);expect(view).toEqual({assemblyPreview:{id:'assembly',revision:hash(1),planRevision:hash(2),kind:'proposals'},timeline:{schema:'hv-edit-assembly-preview-view/1',revision:hash(2),frames:66,width:640,height:360}});expect(view.timeline).not.toHaveProperty('clips');expect(view.timeline).not.toHaveProperty('sources');expect(view).not.toHaveProperty('sequence');expect(saved).toEqual(before);saved.item.frames=12;expect(view.timeline.frames).toBe(66);const proposal=previewIdentity(view,{}),accepted=previewIdentity(assemblyPreviewView(detail({accepted:true})),{});expect(proposal.base).toBe('/assemblies/proposals/assembly/preview');expect(accepted.base).toBe('/assemblies/accepted/assembly/preview');expect(accepted.key).not.toBe(proposal.key);expect(proposal.historyRevision).toBe(hash(1));expect(proposal.assembly).toBe(true);expect(assemblyPreviewView(null)).toBeNull();
});
test('malformed saved descriptors fail before creating a request identity',()=>{
  for(const mutate of [value=>value.item.id='../other',value=>value.item.revision='wrong',value=>value.item.frames=0,value=>value.item.frames=108001,value=>value.item.parent.width=641,value=>value.item.parent.height=1082]){const value=detail();mutate(value);expect(()=>assemblyPreviewView(value)).toThrow('valid saved assembly');}const view=assemblyPreviewView(detail());expect(()=>previewIdentity({...view,timeline:{...view.timeline,schema:'hv-edit-timeline/1'}},{})).toThrow('identity');expect(()=>previewIdentity({...view,timeline:{...view.timeline,revision:hash(99)}},{})).toThrow('identity');
});
test('picture and PCM requests address child frames across reordered and repeated joins without flattened parent clips',async()=>{
  const f=harness();try{for(const frame of [29,30,60,65]){f.run.at=frame*1600;expect(await f.media.picture(f.run,frame)).toBe(true);}const picture=f.packets.filter(value=>value.path.includes('/picture/'));expect(picture.map(value=>Number(new URL(value.path,'http://fixture').searchParams.get('frame')))).toEqual([29,60]);expect(picture.map(value=>Number(value.path.split('?')[0].split('/').at(-1)))).toEqual([0,60]);expect(picture.every(value=>value.path.includes('/picture/timeline-picture/'))).toBe(true);expect(picture.every(value=>new URL(value.path,'http://fixture').searchParams.get('historyRevision')===hash(1))).toBe(true);expect(f.media.stats.packets).toBe(2);expect(f.requests.filter(value=>value.method==='POST')).toHaveLength(1);expect(f.requests[0].body).toMatchObject({historyRevision:hash(1),from:0,frames:66});const pcm=await f.media.audio(f.run,60,66);expect(pcm.length).toBe(6*1600*6);const sample=offset=>pcm[offset]|pcm[offset+1]<<8|pcm[offset+2]<<16;expect(sample(0)).toBe(60000);expect(sample(5*1600*6)).toBe(65000);expect(f.canvases.flatMap(canvas=>canvas.draws).every(draw=>draw.image.kind==='decoded')).toBe(true);expect(f.bitmaps.filter(bitmap=>bitmap.kind==='decoded')).toHaveLength(4);
  }finally{await f.close();}
});
test('derived page identity rejects correctly resealed parent-revision data and requires native composition purpose',async()=>{
  const f=harness({mutatePacket:base=>({...base,sourceRevision:hash(4)})});try{await expect(f.media.picture(f.run,30)).rejects.toThrow('changed');expect(f.bitmaps).toHaveLength(0);}finally{await f.close();}
  for(const mutate of [status=>({...status,timelineRevision:hash(4)}),status=>({...status,historyRevision:hash(3)}),status=>({...status,picture:{...status.picture,picturePurpose:undefined}}),status=>({...status,picture:{...status.picture,pictureEncoding:undefined}})]){const bad=harness({mutateStatus:mutate});try{await expect(bad.media.picture(bad.run,0)).rejects.toThrow('identity changed');expect(bad.packets).toHaveLength(0);}finally{await bad.close();}}
});
test('assembly batches reuse all block tails without crossing a page or the child duration',async()=>{
  const f=harness({frames:122});try{const frames=[47,48,59,60,75,76,91,92,107,108,119,120,121];for(const frame of frames){f.run.at=frame*1600;expect(await f.media.picture(f.run,frame)).toBe(true);}const picture=f.packets.filter(value=>value.path.includes('/picture/'));expect(picture.map(value=>Number(new URL(value.path,'http://fixture').searchParams.get('frame')))).toEqual([47,48,60,76,92,108,120]);expect(picture.map(value=>Number(value.path.split('?')[0].split('/').at(-1)))).toEqual([0,0,60,60,60,60,120]);expect(f.media.stats.packets).toBe(7);expect(f.bitmaps.filter(bitmap=>bitmap.kind==='decoded')).toHaveLength(frames.length);expect(f.requests.filter(value=>value.method==='POST')).toHaveLength(1);
  }finally{await f.close();}
});
test('correctly resealed singleton, shifted and incomplete batch selections fail before decoding',async()=>{
  const cases=[{frame:30,selection:[30]},{frame:30,selection:Array.from({length:16},(_,i)=>17+i)},{frame:65,selection:[60,61,62,63,64]}];for(const {frame,selection}of cases){const f=harness({mutatePacket:base=>({...base,pictureFrames:selection})});try{await expect(f.media.picture(f.run,frame)).rejects.toThrow('changed');expect(f.bitmaps).toHaveLength(0);expect(f.media.stats.packets).toBe(0);}finally{await f.close();}}
});
test('cancellation aborts assembly media and releases the lease using its captured owner identity',async()=>{
  const f=harness({accepted:true,deferMedia:true});try{const picture=f.media.picture(f.run,60).then(()=>null,error=>error);await settle(()=>f.packets.length===1);f.setOwner('second');await f.media.clear();expect(await picture).toBeInstanceOf(Error);expect(f.packets[0].signal.aborted).toBe(true);const release=f.requests.find(value=>value.method==='DELETE');expect(release.owner).toBe('first');expect(release.path).toContain('/assemblies/accepted/assembly/preview/');expect(release.path).toContain('historyRevision='+hash(1));expect(f.media.stats).toEqual({windows:0,packets:0,encodedBytes:0,images:0,composedFrames:0});
  }finally{await f.close();}
});
test('a late decoded batch tail is closed after cancellation and stale lease renewal cannot continue playback',async()=>{
  const f=harness({deferDecode:true});try{const picture=f.media.picture(f.run,65).then(()=>null,error=>error);await settle(()=>f.bitmaps.length===1);expect(f.packets).toHaveLength(1);expect(f.media.stats.packets).toBe(1);f.run.controller.abort(new Error('Superseded assembly.'));f.releaseDecode();expect(await picture).toBeInstanceOf(Error);expect(f.bitmaps[0].closed).toBe(1);expect(f.media.stats.images).toBe(0);}finally{f.releaseDecode();await f.close();}
  let changed=false;const stale=harness({mutateStatus:status=>changed?{...status,picture:{...status.picture,sourceKey:hash(99)}}:status});try{await stale.media.picture(stale.run,0);changed=true;await expect(stale.media.renew(stale.run)).rejects.toThrow('changed');}finally{await stale.close();}
});
test('mounted assembly preview uses child duration, preserves same-revision binding, and cancels on hidden owner',async()=>{
  const f=harness({accepted:true});let mounted;try{const root=new Element('section');mounted=mountEditAssemblyPreview({parent:root,client:f.makeClient,current:()=>f.active});mounted.bind(f.saved);const all=(at=root)=>[at,...at.children.flatMap(child=>all(child))],frame=all().find(value=>value.type==='number'),range=all().find(value=>value.type==='range');expect(root.textContent).toContain('Preview saved assembly');expect(root.textContent).toContain('repeated ranges');expect(frame.max).toBe('65');expect(range.max).toBe('65');expect(root.textContent).toContain('0:00:00 / 0:02:06');frame.value='60';frame.onchange();await settle(()=>f.nodes[0]?.commands.some(value=>value.kind==='page'));expect(f.nodes[0].commands.find(value=>value.kind==='reset')).toMatchObject({frames:66,at:96000});expect(mounted.controller.position).toBe(60);const count=f.requests.length;mounted.bind(structuredClone(f.saved));expect(f.requests).toHaveLength(count);expect(mounted.controller.position).toBe(60);document.hidden=true;document.dispatchEvent(new Event('visibilitychange'));await settle(()=>f.requests.some(value=>value.method==='DELETE'));expect(f.contexts[0].closed).toBe(1);expect(mounted.controller.stats.active).toBe(false);mounted.bind(null);expect(mounted.panel.hidden).toBe(true);
  }finally{mounted?.dispose();await Bun.sleep(1);await f.close();}
});
