import {expect,test} from 'bun:test';
import {createEditAssemblyStudio} from '../src/edit-assemblies.js';
import {assemblyFixture,Element,hash,installDom} from './edit-assemblies-fixture.js';

function mounted(options={}){const restore=installDom(),fixture=assemblyFixture(options),root=new Element('section'),dirty=[],accepted=[],previews=[];const ui=createEditAssemblyStudio({parent:root,current:()=>fixture.current,request:fixture.request,onDirty:value=>dirty.push(value),onAccepted:value=>accepted.push(value),...(options.noPreview?{}:{onParentRange:value=>previews.push(value)})});const all=(at=root)=>[at,...at.children.flatMap(child=>all(child))],find=(tag,text)=>all().find(element=>element.tagName===tag&&element.textContent===text),classed=name=>all().filter(element=>element.className.split(' ').includes(name)),field=key=>all().find(element=>element.dataset.field===key);return {fixture,root,ui,dirty,accepted,previews,all,find,classed,field,async open(){ui.bind();ui.panel.open=true;ui.panel.emit('toggle');await Bun.sleep(0);},async start(){await this.open();await find('button','Start from complete saved cut').onclick();},async save(){await find('button','Save proposal and review').onclick();},close(){ui.dispose();restore();}};}

test('mounted assembly studio loads lazily, exposes target review, and accepts only explicit reviewed identities',async()=>{
  const h=mounted();try{h.ui.bind();expect(h.fixture.requests).toHaveLength(0);await h.start();expect(h.ui.unsaved).toBe(true);h.field('purpose').value='sixty-second';await h.field('purpose').oninput();h.field('label').value='<img src=x> owner cut';await h.field('label').oninput();await h.save();expect(h.root.textContent).toContain('60-second target: short by 1710 frames');expect(h.root.textContent).toContain('not been padded');const accept=h.find('button','Create saved assembly');expect(accept.disabled).toBe(true);const check=h.all().find(element=>element.type==='checkbox');check.checked=true;check.onchange();expect(accept.disabled).toBe(false);await accept.onclick();expect(h.accepted).toHaveLength(1);expect(h.root.textContent).toContain('Saved “<img src=x> owner cut” as an independent assembly');expect(h.root.textContent).toContain('Independent saved assembly');expect(h.all().some(element=>element.tagName==='img')).toBe(false);expect(h.all().some(element=>element.tagName==='button'&&/export|render assembly|play assembly/i.test(element.textContent))).toBe(false);expect(h.field('label').disabled).toBe(true);expect(h.find('button','Copy ranges into a new proposal on current parent')).toBeDefined();expect(h.ui.unsaved).toBe(false);
  }finally{h.close();}
});
test('typing preserves raw field DOM, invalidates exact review, and same-base binds preserve the draft',async()=>{
  const h=mounted();try{await h.start();await h.save();const check=h.all().find(element=>element.type==='checkbox');check.checked=true;check.onchange();const input=h.field('toFrame');globalThis.document.activeElement=input;input.value='';await input.oninput();expect(h.field('toFrame')).toBe(input);expect(h.field('toFrame').value).toBe('');expect(globalThis.document.activeElement).toBe(input);expect(h.find('button','Create saved assembly').disabled).toBe(true);expect(h.all().find(element=>element.type==='checkbox').checked).toBe(false);const count=h.fixture.requests.length;await h.save();expect(h.fixture.requests).toHaveLength(count);expect(h.root.textContent).toContain('whole frame numbers');h.ui.bind();expect(h.field('toFrame')).toBe(input);expect(input.value).toBe('');expect(h.ui.unsaved).toBe(true);
  }finally{h.close();}
});
test('range authoring paginates six rows and preserves duplicates, order and explicit parent-only preview',async()=>{
  const h=mounted();try{await h.start();const first=h.classed('edit-assembly-range')[0].dataset.rangeId;for(let i=0;i<6;i++)await h.find('button','Add parent range').onclick();expect(h.root.textContent).toContain('Ranges 7–7 of 7');expect(h.classed('edit-assembly-range')).toHaveLength(1);expect(h.find('button','Next ranges').disabled).toBe(true);await h.find('button','Previous ranges').onclick();expect(h.classed('edit-assembly-range')).toHaveLength(6);expect(h.find('button','Previous ranges').disabled).toBe(true);await h.find('button','Duplicate range 1').onclick();const duplicate=h.classed('edit-assembly-range')[1].dataset.rangeId;expect(duplicate).not.toBe(first);await h.find('button','Move range 2 up').onclick();expect(h.classed('edit-assembly-range')[0].dataset.rangeId).toBe(duplicate);await h.find('button','Preview parent range 1').onclick();expect(h.previews).toEqual([{sequenceId:'cut',historyRevision:hash(1),rangeId:duplicate,fromFrame:0,toFrame:90}]);await h.find('button','Remove range 1').onclick();expect(h.classed('edit-assembly-range')[0].dataset.rangeId).toBe(first);
  }finally{h.close();}
});
test('stale and external dirty guards disable authoring and preview while retaining raw draft fields',async()=>{
  const h=mounted();try{await h.start();const input=h.field('toFrame');input.value='25';await input.oninput();const preview=h.find('button','Preview parent range 1');h.fixture.setCurrent({...h.fixture.current,historyRevision:hash(2)});h.ui.bind();expect(h.ui.unsaved).toBe(true);expect(h.field('toFrame').value).toBe('25');expect(h.field('toFrame').disabled).toBe(true);expect(h.find('button','Save proposal and review').disabled).toBe(true);expect(h.find('button','Preview parent range 1')).toBeUndefined();expect(h.find('button','Copy ranges into a new proposal on current parent').disabled).toBe(false);await preview.onclick();expect(h.previews).toHaveLength(0);expect(h.root.textContent).toContain('unchanged saved parent');h.fixture.setCurrent(null);h.ui.bind();expect(h.ui.panel.hidden).toBe(false);expect(h.field('toFrame').value).toBe('25');
  }finally{h.close();}
});
test('pending acceptance locks conflicting controls and retries its exact payload; unavailable capacity blocks approval',async()=>{
  let lose=true;const h=mounted({intercept:(call,run)=>{const result=run();if(call.path.endsWith('/accept')&&lose){lose=false;throw new Error('Response lost');}return result;}});try{await h.start();await h.save();const check=h.all().find(element=>element.type==='checkbox');check.checked=true;check.onchange();await h.find('button','Create saved assembly').onclick();expect(h.ui.pending).toBe(true);expect(h.field('label').disabled).toBe(true);expect(h.find('button','Discard range draft').disabled).toBe(true);expect(h.find('button','Preview parent range 1').disabled).toBe(true);const first=h.fixture.requests.at(-1).body;await h.find('button','Retry the same saved request').onclick();expect(h.fixture.requests.at(-1).body).toEqual(first);expect(h.ui.pending).toBe(false);expect(h.fixture.assemblies.size).toBe(1);
  }finally{h.close();}
  const unavailable=mounted({intercept:(call,run)=>{const result=run();if(call.method==='POST')result.unavailable='This assembly exceeds retained workspace capacity.';return result;}});try{await unavailable.start();await unavailable.save();const check=unavailable.all().find(element=>element.type==='checkbox');check.checked=true;check.onchange();expect(unavailable.find('button','Create saved assembly').disabled).toBe(true);expect(unavailable.root.textContent).toContain('exceeds retained workspace capacity');}finally{unavailable.close();}
});

test('saved-item selection follows copies and revisions while preserving a deliberate choice until Open',async()=>{
  const h=mounted(),selector=()=>h.all().find(element=>element.attributes['aria-label']==='Saved assembly proposal');try{
    await h.start();await h.save();expect(selector().value).toBe('proposals/'+[...h.fixture.proposals.keys()][0]);const check=h.all().find(element=>element.type==='checkbox');check.checked=true;check.onchange();await h.find('button','Create saved assembly').onclick();const acceptedId=[...h.fixture.assemblies.keys()][0];expect(selector().value).toBe('accepted/'+acceptedId);
    await h.find('button','Copy ranges into a new proposal on current parent').onclick();h.field('label').value='Reordered preview check';await h.field('label').oninput();await h.save();const proposalId=[...h.fixture.proposals.keys()].at(-1);expect(selector().value).toBe('proposals/'+proposalId);expect(h.field('label').value).toBe('Reordered preview check');
    selector().value='accepted/'+acceptedId;selector().onchange();h.ui.bind();expect(selector().value).toBe('accepted/'+acceptedId);await h.find('button','Refresh assembly list').onclick();expect(selector().value).toBe('accepted/'+acceptedId);expect(h.field('label').value).toBe('Reordered preview check');
    const input=h.field('toFrame');input.value='';await input.oninput();h.ui.bind();expect(h.field('toFrame')).toBe(input);expect(input.value).toBe('');expect(selector().value).toBe('accepted/'+acceptedId);await h.save();expect(selector().value).toBe('accepted/'+acceptedId);
    input.value='60';await input.oninput();await h.save();expect(selector().value).toBe('proposals/'+proposalId);expect(h.field('toFrame').value).toBe('60');
    selector().value='accepted/'+acceptedId;selector().onchange();await h.find('button','Open selected assembly').onclick();expect(selector().value).toBe('accepted/'+acceptedId);expect(h.field('toFrame').value).toBe('90');expect(h.field('label').disabled).toBe(true);
  }finally{h.close();}
});

test('recovered create, revision and acceptance results select their exact saved item',async()=>{
  for(const kind of ['create','revise','accept']){let lose=false;const h=mounted({intercept:(call,run)=>{const result=run(),matches=kind==='accept'?call.path.endsWith('/accept'):kind==='revise'?call.method==='PATCH':call.method==='POST'&&call.path==='/assemblies/proposals';if(lose&&matches){lose=false;throw new Error('Response lost');}return result;}});let recovered;try{
    await h.start();if(kind!=='create')await h.save();lose=true;if(kind==='accept'){const check=h.all().find(element=>element.type==='checkbox');check.checked=true;check.onchange();await h.find('button','Create saved assembly').onclick();}else{h.field('label').value='Recovered '+kind;await h.field('label').oninput();await h.save();}expect(h.ui.pending).toBe(true);
    h.ui.dispose();recovered=createEditAssemblyStudio({parent:h.root,current:()=>h.fixture.current,request:h.fixture.request});recovered.bind();expect(recovered.pending).toBe(true);await h.find('button','Retry the same saved request').onclick();expect(recovered.pending).toBe(false);expect(recovered.unsaved).toBe(false);
    const selector=h.all().find(element=>element.attributes['aria-label']==='Saved assembly proposal'),id=[...(kind==='accept'?h.fixture.assemblies:h.fixture.proposals).keys()].at(-1);expect(selector.value).toBe((kind==='accept'?'accepted/':'proposals/')+id);expect(h.field('label').disabled).toBe(kind==='accept');
  }finally{recovered?.dispose();h.close();}}
});
