import {expect,test} from 'bun:test';
import {createLivingScriptStudio} from '../src/living-script.js';
import {createEditScriptNavigation} from '../src/edit-script.js';
import {Element} from './edit-assemblies-fixture.js';
import {scriptFixture} from './edit-script-fixture.js';
import {hash,livingFixture,tick} from './living-script-fixture.js';

class View extends Element{
  querySelector(selector){const key=selector.match(/^\[data-([a-z-]+)\]$/)?.[1]?.replace(/-([a-z])/g,(_all,letter)=>letter.toUpperCase());const scan=element=>element.children.flatMap(child=>[child,...scan(child)]);return scan(this).find(element=>key?Object.hasOwn(element.dataset,key):element.tagName===selector)??null;}
  pause(){this.pauses=(this.pauses??0)+1;}
}
function dom(){const old=['document','Option'].map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)]);globalThis.document={activeElement:null,createElement:tag=>new View(tag)};globalThis.Option=class extends View{constructor(label,value){super('option');this.textContent=label;this.value=value;}};return ()=>{for(const [key,value]of old)if(value)Object.defineProperty(globalThis,key,value);else delete globalThis[key];};}
function mounted(options={}){const restore=dom(),f=livingFixture(options),root=new View('div'),dirty=[],accepted=[],opened=[],bindings=[];let ui;ui=createLivingScriptStudio({parent:root,current:()=>f.current,request:f.request,jobRequest:f.jobRequest,storage:f.storage,onDirty:value=>dirty.push(value),onAccepted:async value=>{accepted.push(value);await options.onAccepted?.(value);},onOpenSequence:value=>opened.push(value),onRecutPreviewBinding:value=>{bindings.push(value);if(value&&options.readySynchronously)ui.comparisonStatus({recutRevision:value.recut.revision,ready:true});}});const all=(at=root)=>[at,...at.children.flatMap(child=>all(child))],find=(tag,text)=>all().find(element=>element.tagName===tag&&element.textContent===text),input=label=>{const field=find('label',label);return all().find(element=>element.id===field?.htmlFor);},ack=text=>all().find(element=>element.tagName==='label'&&element.textContent===text)?.children.find(element=>element.type==='checkbox');return {ui,f,root,all,find,input,ack,bindings,dirty,accepted,opened,async start(){ui.bind();await tick();ui.selectLine(f.selection);input('Revised dialogue').value='We are absolutely ready.';input('Revised dialogue').oninput();},async save(){await find('button','Review line and cut impact').onclick();const check=ack('I reviewed this exact dialogue, performance rebinding and retained cut impact.');check.checked=true;check.onchange();await find('button','Save reviewed proposal').onclick();},async generated(){await this.start();await this.save();await find('button','Review revised film generation').onclick();const check=ack('I reviewed these exact shots, generation settings and budget.');check.checked=true;check.onchange();await find('button','Start revised film generation').onclick();},async reviewed(){await this.generated();await find('button','Compare actual source timing and map the cut').onclick();await find('button','Suggest mappings for matching source timing').onclick();await find('button','Review exact proposed cut').onclick();},close(){ui.dispose();f.store.dispose();restore();}};}

test('mounted studio preserves typed DOM and removes stale line review when exact dialogue changes',async()=>{const h=mounted({stage:'animatic'});try{h.ui.bind();await tick();expect(h.f.requests).toHaveLength(0);await h.start();const text=h.input('Revised dialogue');globalThis.document.activeElement=text;await h.find('button','Review line and cut impact').onclick();expect(h.root.textContent).toContain('Line direction rebinding');const changed=h.input('Revised dialogue');globalThis.document.activeElement=changed;changed.value='<img src=x> A different line';changed.oninput();expect(h.input('Revised dialogue')).toBe(changed);expect(document.activeElement).toBe(changed);expect(h.root.textContent).not.toContain('Line direction rebinding');expect(h.find('button','Save reviewed proposal')).toBeUndefined();h.ui.bind();expect(h.input('Revised dialogue').value).toBe('<img src=x> A different line');expect(h.all().some(item=>item.tagName==='img')).toBe(false);expect(h.ui.unsaved).toBe(true);}finally{h.close();}});

test('actual source playback and full cut comparison are distinct; only exact prepared comparison unlocks acceptance',async()=>{const h=mounted({stage:'animatic'});try{await h.reviewed();expect(h.root.textContent).toContain('This player shows the revised source film');expect(h.all().find(item=>item.tagName==='video').src).toBe('/media/job-1.mp4');const binding=h.bindings.at(-1);expect(binding.proposalId).toBe([...h.f.proposals.keys()][0]);expect(binding.recut.operations[0].timing).toBe('preserve');const accept=h.find('button','Accept screenplay and revised cut'),check=h.ack('I compared both complete cuts and reviewed the changed dialogue, timing, captions, masks and sound. Save the screenplay and independent cut together.');expect(accept.disabled).toBe(true);expect(check.disabled).toBe(true);
    h.ui.comparisonStatus({recutRevision:hash(900),ready:true});expect(check.disabled).toBe(true);h.ui.comparisonStatus({recutRevision:binding.recut.revision,ready:false,message:'Preparing picture and sound for both cuts…'});expect(h.root.textContent).toContain('Preparing picture and sound');expect(check.disabled).toBe(true);h.ui.comparisonStatus({recutRevision:binding.recut.revision,ready:true});expect(check.disabled).toBe(false);expect(accept.disabled).toBe(true);check.checked=true;check.onchange();expect(accept.disabled).toBe(false);await accept.onclick();expect(h.accepted).toHaveLength(1);expect(h.bindings.at(-1)).toBeNull();expect(h.ui.unsaved).toBe(false);expect(h.root.textContent).toContain('Accepted: Revised dialogue cut');await h.find('button','Open revised cut and review export').onclick();expect(h.opened).toEqual([h.accepted[0].acceptance.sequence.id]);expect(h.f.requests.some(call=>call.path.includes('dialogue-selection'))).toBe(false);
  }finally{h.close();}});

test('comparison identity resets on mapping edits, hide and external guards without losing raw mapping',async()=>{const h=mounted({stage:'animatic',readySynchronously:true});try{await h.reviewed();const check=h.ack('I compared both complete cuts and reviewed the changed dialogue, timing, captions, masks and sound. Save the screenplay and independent cut together.');expect(check.disabled).toBe(false);check.checked=true;check.onchange();h.ui.panel.open=false;h.ui.panel.emit('toggle');expect(h.bindings.at(-1)).toBeNull();expect(check.checked).toBe(false);h.ui.panel.open=true;h.ui.panel.emit('toggle');await tick();const input=h.input('Revised source in-frame');input.value='';input.oninput();expect(h.ui.unsaved).toBe(true);expect(h.bindings.at(-1)).toBeNull();expect(h.find('button','Accept screenplay and revised cut')).toBeUndefined();const before=h.f.requests.length;await h.find('button','Review exact proposed cut').onclick();expect(h.f.requests).toHaveLength(before);expect(h.root.textContent).toContain('whole frame');expect(h.input('Revised source in-frame').value).toBe('');const active=h.f.current;h.f.setCurrent({...active,busy:true});h.ui.bind();expect(h.input('Revised source in-frame').disabled).toBe(true);expect(h.input('Revised source in-frame').value).toBe('');h.f.setCurrent(null);h.ui.bind();expect(h.ui.panel.hidden).toBe(false);expect(h.input('Revised source in-frame').disabled).toBe(true);}finally{h.close();}});

test('pending acceptance has one retry action and preserves the fixed payload after an uncertain response',async()=>{let lose=true;const h=mounted({stage:'animatic',readySynchronously:true,intercept:(call,run)=>{const result=run();if(lose&&call.path.endsWith('/accept')){lose=false;throw new Error('Response lost');}return result;}});try{await h.reviewed();const check=h.ack('I compared both complete cuts and reviewed the changed dialogue, timing, captions, masks and sound. Save the screenplay and independent cut together.');check.checked=true;check.onchange();await h.find('button','Accept screenplay and revised cut').onclick();const pending=h.ui.pending;expect(pending.kind).toBe('accept');expect(h.input('Revised source in-frame').disabled).toBe(true);const primary=h.all().filter(item=>item.tagName==='button'&&item.className==='');expect(primary.map(item=>item.textContent)).toEqual(['Retry the same saved request']);await primary[0].onclick();expect(h.ui.pending).toBeNull();expect(h.f.requests.filter(call=>call.path===pending.path&&call.method==='POST').at(-1).body).toEqual(pending.body);expect(h.f.acceptances.size).toBe(1);}finally{h.close();}});

test('confirmed acceptance can retry screenplay refresh with its exact receipt and never resubmit acceptance',async()=>{let offline=true;const h=mounted({stage:'animatic',readySynchronously:true,onAccepted:()=>{if(offline)throw new Error('Screenplay refresh offline');}});try{await h.reviewed();const check=h.ack('I compared both complete cuts and reviewed the changed dialogue, timing, captions, masks and sound. Save the screenplay and independent cut together.');check.checked=true;check.onchange();await h.find('button','Accept screenplay and revised cut').onclick();expect(h.ui.pending).toBeNull();expect(h.f.acceptances.size).toBe(1);const receipt=structuredClone(h.accepted[0].acceptance),count=h.f.requests.length,bindings=h.bindings.length,refresh=h.find('button','Refresh accepted screenplay');expect(refresh.disabled).toBe(false);await refresh.onclick();expect(h.root.textContent).toContain('Screenplay refresh offline');expect(h.accepted[1]).toEqual({acceptance:receipt});offline=false;await refresh.onclick();expect(h.accepted[2]).toEqual({acceptance:receipt});expect(h.f.requests).toHaveLength(count);expect(h.f.requests.filter(call=>call.path.endsWith('/accept'))).toHaveLength(1);expect(h.bindings).toHaveLength(bindings);expect(h.bindings.at(-1)).toBeNull();h.f.setCurrent({...h.f.current,busy:true});h.ui.bind();expect(refresh.disabled).toBe(true);}finally{h.close();}});

test('navigation revision callback carries exact physical line and original receipt identities only when selected',async()=>{const restore=dom(),f=scriptFixture(),root=new View('div'),selected=[];f.entry.id=hash(6);f.source.entries[1].id=hash(6);f.data.occurrences[0].entryId=hash(6);let current=f.saved;const ui=createEditScriptNavigation({parent:root,current:()=>current,request:async()=>f.data,onReviseLine:value=>selected.push(value)}),all=(at=root)=>[at,...at.children.flatMap(child=>all(child))],find=text=>all().find(item=>item.tagName==='button'&&item.textContent===text);try{ui.bind(f.saved);ui.panel.open=true;ui.panel.emit('toggle');await tick();expect(find('Revise this screenplay line')).toBeUndefined();await find('Dialogue · Kevin: Hello.').onclick();await find('Revise this screenplay line').onclick();expect(selected).toEqual([{navigationRevision:f.data.revision,sourceRevision:f.source.receiptRevision,indexRevision:f.source.revision,entryId:hash(6),text:'Hello.',character:'Kevin',sourceId:'original'}]);current=null;await find('Revise this screenplay line').onclick();expect(selected).toHaveLength(1);}finally{ui.dispose();restore();}});
