import {expect,test} from 'bun:test';
import {createLivingScriptState,createLivingScriptRecovery} from '../src/living-script-state.js';
import {clone,deferred,hash,livingFixture,memoryRecovery,tick} from './living-script-fixture.js';

test('owner state submits exact staged reviews without silently adopting screenplay or choosing export',async()=>{
  const f=livingFixture();try{await f.reviewed();const posts=f.requests.filter(call=>call.method==='POST');expect(posts.map(call=>call.path.split('/').at(-1))).toEqual(['quote','proposals','quote','jobs','decision','quote','jobs','recut']);
    expect(posts[0].body).toEqual({id:f.store.state.proposal.request.id,label:'Revised KEVIN line',sequenceId:'cut',historyRevision:hash(1),editorialRevision:hash(2),navigationRevision:hash(3),sourceRevision:hash(4),entryId:hash(6),indexRevision:hash(5),replacement:'We are absolutely ready.'});
    expect(posts[1].body.accepted).toBe(true);expect(posts[3].body.animaticJobId).toBeNull();expect(posts[5].body).toEqual({role:'render'});expect(posts[6].body.animaticJobId).toBe('job-1');expect(posts[7].body.operations).toEqual([{kind:'replace',clipId:'picture',linked:true,sourceId:'job-2',from:0,frames:90,timing:'preserve',ripple:false}]);expect(f.acceptances.size).toBe(0);expect(f.current.sequenceId).toBe('cut');expect(f.store.state.dirty).toBe(false);
    await f.store.accept();expect(f.accepted).toHaveLength(1);expect(f.store.state.acceptance.sequence.id).toBe(posts[7].body.newSequenceId);expect(f.store.state.pending).toBeNull();expect(f.requests.at(-1).body).toEqual({request:{...f.requests.at(-1).body.request},expectedVersion:0,proposalRevision:hash(20),accepted:true});expect(f.requests.some(call=>/dialogue-selection|\/script$/.test(call.path))).toBe(false);
  }finally{f.store.dispose();}
});

test('raw invalid mapping fields, identities, speed choice and masks survive bind and browser recovery',async()=>{
  const f=livingFixture({stage:'animatic'});let restored;try{await f.mapped();const row=f.store.state.rows[0];f.store.editMapping(row.id,'from','');f.store.editMapping(row.id,'timing','normal');f.store.editMapping(null,'cutName','<script>owner cut</script>');const length=f.requests.length;await expect(f.store.reviewCut()).rejects.toThrow('whole frame');expect(f.requests).toHaveLength(length);f.store.bind();expect(f.store.state.rows[0].id).toBe(row.id);expect(f.store.state.rows[0].from).toBe('');await tick();f.store.dispose();await tick();
    restored=createLivingScriptState({request:f.request,jobRequest:f.jobRequest,current:()=>f.current,storage:f.storage});restored.bind();await tick();expect(restored.state.recovered).not.toBeNull();await restored.restore();expect(restored.state.rows[0]).toEqual(row);expect(restored.state.cutName).toBe('<script>owner cut</script>');expect(restored.state.job.id).toBe('job-1');expect(restored.state.recut).toBeNull();expect(restored.state.dirty).toBe(true);
    f.setCurrent({...f.current,historyRevision:hash(91)});restored.bind();await expect(restored.reviewCut()).rejects.toThrow('context changed');expect(restored.state.rows[0].from).toBe('');
  }finally{restored?.dispose();f.store.dispose();}
});

test('every uncertain mutation recovers its exact fixed payload and result after reload',async()=>{
  for(const kind of ['proposal','generation','decision','accept']){let lose=false;const f=livingFixture({intercept:(call,run)=>{const result=run(),match=kind==='proposal'?call.path==='/screenplay/proposals':kind==='generation'?call.path.endsWith('/jobs'):kind==='decision'?call.path.endsWith('/decision'):call.path.endsWith('/accept');if(lose&&call.method==='POST'&&match){lose=false;throw new Error('Response lost');}return result;}});let restored;try{
      if(kind==='proposal'){await f.start();await f.store.quoteLine();lose=true;await f.store.saveProposal();}
      else if(kind==='generation'){await f.saved();await f.store.quoteGeneration('preview');lose=true;await f.store.generate();}
      else if(kind==='decision'){await f.saved();await f.store.quoteGeneration('preview');await f.store.generate();await f.store.loadDecision();lose=true;await f.store.decide('approved','Exact reviewed note');}
      else{await f.reviewed();lose=true;await f.store.accept();}
      const pending=clone(f.store.state.pending);expect(pending.kind).toBe(kind);expect(f.store.state.busy).toBe(false);await expect(f.store.discard()).rejects.toThrow('saved request');f.store.dispose();await tick();f.setCurrent({...f.current,editorialRevision:hash(99)});
      restored=createLivingScriptState({request:f.request,jobRequest:f.jobRequest,current:()=>f.current,storage:f.storage});restored.bind();await tick();expect(restored.state.pending).toEqual(pending);await restored.retry();expect(restored.state.pending).toBeNull();expect(f.requests.filter(call=>call.path===pending.path&&call.method==='POST').at(-1).body).toEqual(pending.body);expect(f.proposals.size).toBe(1);if(kind==='generation')expect(f.jobMap.size).toBe(1);if(kind==='accept')expect(f.acceptances.size).toBe(1);
    }finally{restored?.dispose();f.store.dispose();}}
});

test('generation lookup cannot resolve an uncertain budget mismatch merely because plan and request key match',async()=>{const f=livingFixture({interceptJob:(_id,run)=>({...run(),costCapUsd:999})});try{await f.saved();await f.store.quoteGeneration('preview');await f.store.generate();expect(f.store.state.pending.kind).toBe('generation');expect(f.store.state.job).toBeNull();expect(f.store.state.message).toContain('exact budget');const pending=clone(f.store.state.pending);await f.store.retry();expect(f.store.state.pending).toEqual(pending);expect(f.jobMap.size).toBe(1);}finally{f.store.dispose();}});

test('invalid physical line text remains raw and is rejected before a quote request',async()=>{const f=livingFixture();try{await f.start();for(const text of [' outer space','line one\nline two','x'.repeat(20001)]){f.store.edit('replacement',text);const count=f.requests.length;await expect(f.store.quoteLine()).rejects.toThrow('one nonblank dialogue line');expect(f.requests).toHaveLength(count);expect(f.store.state.draft.replacement).toBe(text);}}finally{f.store.dispose();}});

test('late line quote is cancelled by parent change and cannot replace current workflow',async()=>{
  const wait=deferred();const f=livingFixture({intercept:async(call,run)=>call.path==='/screenplay/quote'?await wait.promise:run()});try{await f.start();const reading=f.store.quoteLine();await tick();const quoteCall=f.requests.at(-1);f.setCurrent({...f.current,projectId:'second'});f.store.bind();wait.resolve({accepted:false});await expect(reading).rejects.toThrow('active cut changed');expect(quoteCall.signal.aborted).toBe(true);expect(f.store.state.base.projectId).toBe('second');expect(f.store.state.draft).toBeNull();expect(f.store.state.lineQuote).toBeNull();}finally{f.store.dispose();}
});

test('late job confirmation after an admitted request cannot publish into a newly opened project',async()=>{
  const wait=deferred();let hold=false;const f=livingFixture({interceptJob:async(_id,run)=>hold?await wait.promise:run()});try{await f.saved();await f.store.quoteGeneration('preview');hold=true;const sending=f.store.generate();await tick();const old=clone(f.jobMap.get('job-1'));f.setCurrent({...f.current,projectId:'second'});f.store.bind();await tick();wait.resolve(old);await sending;expect(f.store.state.base.projectId).toBe('second');expect(f.store.state.job).toBeNull();expect(f.store.state.proposal).toBeNull();expect(f.storage.data.get('project').pending.kind).toBe('generation');}finally{f.store.dispose();}
});

test('hiding during hydration restarts safely and malformed pending paths never become requests',async()=>{
  const storage=memoryRecovery(),wait=deferred();let calls=0;storage.get=async()=>{calls++;return calls===1?await wait.promise:null;};const f=livingFixture({storage});try{f.store.bind();expect(f.store.state.hydrating).toBe(true);const old=f.current;f.setCurrent(null);f.store.bind();f.setCurrent(old);f.store.bind();await tick();wait.resolve(null);await tick();expect(calls).toBe(2);expect(f.store.state.hydrating).toBe(false);f.store.selectLine(f.selection);expect(f.store.state.dirty).toBe(true);}finally{f.store.dispose();}
  const bad=memoryRecovery();bad.data.set('project',{schema:'hv-living-script-workflow/1',projectId:'project',base:{projectId:'project',sequenceId:'cut',historyRevision:hash(1),editorialRevision:hash(2)},rows:[],pending:{schema:'hv-living-script-pending/1',projectId:'project',base:{projectId:'project',sequenceId:'cut',historyRevision:hash(1),editorialRevision:hash(2)},proposalId:'proposal',kind:'unknown',body:{},path:null}});const g=livingFixture({storage:bad});try{g.store.bind();await tick();expect(g.store.state.invalidRecovery).toBe(true);expect(g.store.state.pending).toBeNull();expect(g.requests).toHaveLength(0);g.store.dispose();await tick();expect(bad.data.get('project').pending.path).toBeNull();}finally{g.store.dispose();}
});

test('dirty mapping guards a different job, restores performance note and does not reset same-job preview approval',async()=>{
  const f=livingFixture();try{await f.generated();await f.store.showJob('job-1');await f.store.loadDecision();f.store.editNote('Keep the hesitation, then pause.');await f.store.showJob('job-1');expect(f.store.state.decision.approval.decision).toBe('approved');expect(f.store.state.reviewNote).toBe('Keep the hesitation, then pause.');await tick();expect(f.storage.data.get('project').reviewNote).toBe('Keep the hesitation, then pause.');await f.store.showJob('job-2');await f.store.mapSource();const rows=clone(f.store.state.rows);await expect(f.store.showJob('job-1')).rejects.toThrow('open source mapping');expect(f.store.state.rows).toEqual(rows);expect(f.store.state.job.id).toBe('job-2');}finally{f.store.dispose();}
});

test('suggestions preserve every authored choice and a new selected line can use another clean saved cut',async()=>{
  const f=livingFixture({stage:'animatic'});try{await f.mapped();const row=f.store.state.rows[0];f.store.editMapping(row.id,'from',' 17 ');f.store.editMapping(row.id,'frames','');const before=clone(row);f.store.suggestMapping();expect(f.store.state.rows[0]).toEqual(before);await f.store.discard();f.setCurrent({...f.current,sequenceId:'another-cut',historyRevision:hash(92),editorialRevision:hash(93)});f.store.bind();f.store.selectLine({...f.selection,navigationRevision:hash(94)});expect(f.store.state.base.sequenceId).toBe('another-cut');expect(f.store.state.base.historyRevision).toBe(hash(92));expect(f.store.state.stale).toBe(false);}finally{f.store.dispose();}
});

test('failed recovery reads leave the browser draft intact and disposal waits for its last storage write',async()=>{
  const f=livingFixture({stage:'animatic'});let restored;try{await f.mapped();await tick();f.store.dispose();await tick();const before=clone(f.storage.data.get('project'));restored=createLivingScriptState({request:async()=>{throw new Error('Offline');},jobRequest:f.jobRequest,current:()=>f.current,storage:f.storage});restored.bind();await tick();await expect(restored.restore()).rejects.toThrow('Offline');expect(restored.state.recovered).toEqual(before);expect(restored.state.rows).toEqual([]);expect(restored.state.busy).toBe(false);expect(f.storage.data.get('project')).toEqual(before);}finally{restored?.dispose();f.store.dispose();}
  const gate=deferred(),storage=memoryRecovery();let closed=false;storage.set=async()=>{await gate.promise;return 'durable';};storage.close=()=>{closed=true;};const g=livingFixture({storage});await g.start();g.store.dispose();await tick();expect(closed).toBe(false);gate.resolve();await tick();expect(closed).toBe(true);
});

test('recovery transparently uses session fallback and never treats unreadable JSON as an empty draft',async()=>{
  const originals=['indexedDB','sessionStorage'].map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)]),values=new Map();try{Object.defineProperty(globalThis,'indexedDB',{value:undefined,configurable:true});Object.defineProperty(globalThis,'sessionStorage',{value:{getItem:key=>values.get(key),setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)},configurable:true});const storage=createLivingScriptRecovery();expect(await storage.set('project',{complete:true})).toBe('session');expect(await storage.get('project')).toEqual({complete:true});values.set('hv-living-script:project','{broken');await expect(storage.get('project')).rejects.toThrow('could not be read');expect(values.has('hv-living-script:project')).toBe(true);await storage.remove('project');expect(await storage.get('project')).toBeNull();storage.close();}finally{for(const [key,value]of originals)if(value)Object.defineProperty(globalThis,key,value);else delete globalThis[key];}
});
