import {expect,test} from 'bun:test';
import {livingScriptSameClock,livingScriptRecutRows,livingScriptRecutOperations} from '../src/living-script-recut.js';
import {clone,livingFixture} from './living-script-fixture.js';

test('matching actual shot clocks suggest a linked exact-timing replacement without mutating the parent',async()=>{const f=livingFixture({stage:'animatic'});try{await f.generated();await f.store.mapSource();const detail=f.store.state.source,before=clone(detail),rows=livingScriptRecutRows(detail,f.impact,{suggest:true});expect(livingScriptSameClock(detail.sourceMap)).toBe(true);expect(rows).toHaveLength(1);expect(rows[0].clipIds).toEqual(['picture','dialogue','captions']);expect(livingScriptRecutOperations(rows,detail)).toEqual([{kind:'replace',clipId:'picture',linked:true,sourceId:'job-1',from:0,frames:90,timing:'preserve',ripple:false}]);expect(detail).toEqual(before);
  detail.sourceMap.shots[0].after.endSample-=.5;expect(livingScriptSameClock(detail.sourceMap)).toBe(false);const unresolved=livingScriptRecutRows(detail,f.impact,{suggest:true});expect(unresolved[0].from).toBe('');expect(()=>livingScriptRecutOperations(unresolved,detail)).toThrow('Choose replacement');}finally{f.store.dispose();}});

test('mask treatment is explicit and complete source phase is retained until owner requests normal speed',async()=>{const f=livingFixture({stage:'animatic'});try{await f.generated();await f.store.mapSource();const detail=clone(f.store.state.source);detail.parent.clips[0].composite={masks:[{id:'mask'}]};detail.parent.clips[0].timing={from:32768,keys:[{frame:0,rate:65536},{frame:90,rate:131072}]};const rows=livingScriptRecutRows(detail,f.impact,{suggest:true});expect(()=>livingScriptRecutOperations(rows,detail)).toThrow('remove or rebind');rows[0].maskAction='rebind';rows[0].from=' 7 ';rows[0].frames='81';rows[0].at='5';expect(livingScriptRecutOperations(rows,detail,{duration:'100'})).toEqual([{kind:'duration',frames:100},{kind:'replace',clipId:'picture',linked:true,sourceId:'job-1',from:7,frames:81,timing:'preserve',ripple:false,maskAction:'rebind'},{kind:'move',clipId:'picture',linked:true,at:5}]);rows[0].timing='normal';expect(livingScriptRecutOperations(rows,detail).find(op=>op.kind==='replace').timing).toBe('normal');rows[0].from='7.5';expect(()=>livingScriptRecutOperations(rows,detail)).toThrow('whole frame');expect(rows[0].from).toBe('7.5');}finally{f.store.dispose();}});

test('mixed-source linked groups require independent unlink and derived performance is never silently replaced',async()=>{const f=livingFixture({stage:'animatic'});try{await f.generated();await f.store.mapSource();const detail=clone(f.store.state.source),impact=clone(f.impact);detail.parent.clips[1].sourceId='derived';impact.relatedSourceIds.push('derived');const rows=livingScriptRecutRows(detail,impact,{suggest:true});expect(rows).toHaveLength(3);expect(rows.every(row=>row.requiresUnlink)).toBe(true);for(const row of rows){row.action=row.related?'delete':'replace';row.from='0';}expect(()=>livingScriptRecutOperations(rows,detail)).toThrow('independent mapping');for(const row of rows)row.unlink=true;const operations=livingScriptRecutOperations(rows,detail);expect(operations.filter(op=>op.kind==='unlink').map(op=>op.clipId)).toEqual(['picture','dialogue','captions']);expect(operations.find(op=>op.kind==='delete')).toEqual({kind:'delete',clipId:'dialogue',linked:false,ripple:false});expect(operations.filter(op=>op.kind==='replace').every(op=>op.linked===false)).toBe(true);rows[1].action='replace';expect(()=>livingScriptRecutOperations(rows,detail)).toThrow('later dialogue or sound');}finally{f.store.dispose();}});

test('ordered repeated source uses stay distinct and explicit deletions cannot leave an empty generated cut',async()=>{const f=livingFixture({stage:'animatic'});try{await f.generated();await f.store.mapSource();const detail=clone(f.store.state.source);delete detail.parent.clips[0].link;detail.parent.clips=[detail.parent.clips[0],{...detail.parent.clips[0],id:'repeat',at:90}];detail.parent.frames=180;const rows=livingScriptRecutRows(detail,f.impact,{suggest:true});rows.reverse();expect(livingScriptRecutOperations(rows,detail).map(op=>op.clipId)).toEqual(['repeat','picture']);rows[0].action='delete';expect(livingScriptRecutOperations(rows,detail,{duration:'90'}).at(-1)).toEqual({kind:'duration',frames:90});rows[1].action='delete';expect(()=>livingScriptRecutOperations(rows,detail)).toThrow('at least one');}finally{f.store.dispose();}});
