/**
 * HV-031-15 — the worker's export carries its signed C2PA sidecar through to the job record and the
 * owner's download links, when the host holds a signing key; and changes nothing when it does not.
 *
 * The key and certificate are a throwaway identity generated by this run; the worker reads their
 * paths from `HV_C2PA_SIGNING_KEY` and `HV_C2PA_SIGNING_CERT`, exactly as on the staging host.
 */
import { expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { existsSync, mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { CostLedger, OperatorReviewQueue } from "../../operator/src/index";
import { signedArtifactUrls } from "../../api/src/server";
import { verifyC2paSidecar } from "../../assembler/src/c2pa";
import { makeC2paTestIdentity, withC2paEnv } from "../../assembler/test/c2pa-fixture";
import { DurableJobStore, type Job } from "../src/index";
import { processNextJob, runWorker } from "../src/worker";

const TMP = mkdtempSync(join(tmpdir(), "hv-c2pa-worker-"));

async function finalJob(root: string): Promise<Job | undefined> {
  const store = new DurableJobStore(`${root}/jobs.json`);
  const base = { idempotencyKey: "", projectId: "project-1", tier: "free" as const, scriptVersion: 1, totalFrames: 60, retryPolicy: { maxRetries: 0, backoffMs: 10 }, timeoutMs: 120000,
    costCapUsd: 5, scriptText: "INT. ROOM - DAY\n\nA lamp glows.", rightsAttestedAt: "2026-08-31T00:00:00.000Z" };
  store.enqueue({ ...base, id: "animatic-1", idempotencyKey: "animatic-1", stage: "animatic", animaticJobId: null, animaticApprovedAt: null } as Parameters<DurableJobStore["enqueue"]>[0]);
  store.claimNext(Date.now(), {}, { workerId: "seed" });
  store.complete("animatic-1", "seed", { mp4Path: "project-1/animatic-1/export.mp4", hlsPlaylistPath: "project-1/animatic-1/hls/index.m3u8", captionsPath: "project-1/animatic-1/captions.vtt", manifestPath: "project-1/animatic-1/provenance.json" });
  store.enqueue({ ...base, id: "job-1", idempotencyKey: "job-1", stage: "final", animaticJobId: "animatic-1", animaticApprovedAt: "2026-08-31T00:05:00.000Z" } as Parameters<DurableJobStore["enqueue"]>[0]);
  return await processNextJob(store, `${root}/artifacts`, { ledger: new CostLedger(`${root}/cost-ledger.json`), reviewQueue: new OperatorReviewQueue(`${root}/review-queue.json`) }) ?? undefined;
}

/** The sidecar is in the job's output, on disk beside the record, named by it, and linked for download. */
test("a host with a key completes the job with a signed sidecar beside its record and a link to it", async () => {
  const id = makeC2paTestIdentity(join(TMP, "identity")), root = join(TMP, "signed");
  const done = await withC2paEnv({ key: id.keyPath, cert: id.chainPath }, () => finalJob(root));
  expect(done?.status).toBe("done");
  const output = done!.output!;
  expect(output.c2paPath).toBe(dirname(output.manifestPath) + "/provenance.c2pa");
  const sidecar = readFileSync(join(root, "artifacts", output.c2paPath!)), record = JSON.parse(readFileSync(join(root, "artifacts", output.manifestPath), "utf8"));
  expect(record.credentials.type).toBe("c2pa-sidecar");
  expect(record.credentials.sidecar).toEqual({ name: "provenance.c2pa", sha256: createHash("sha256").update(sidecar).digest("hex") });
  expect((await verifyC2paSidecar(join(root, "artifacts", output.mp4Path), sidecar, id.anchorPem)).state).toBe("Trusted");
  const urls = signedArtifactUrls(done!, "token")!;
  expect(urls.c2paUrl).toBe("/artifacts/token/" + output.c2paPath);
}, 120000);

/** Without a key the job's output, its record and its links are what they were before this increment. */
test("a host without a key completes the job with no sidecar, an unsigned record and no sidecar link", async () => {
  const root = join(TMP, "unsigned");
  const done = await withC2paEnv({}, () => finalJob(root));
  expect(done?.status).toBe("done");
  const output = done!.output!;
  expect(Object.hasOwn(output, "c2paPath")).toBe(false);
  expect(existsSync(join(root, "artifacts", dirname(output.manifestPath), "provenance.c2pa"))).toBe(false);
  expect(JSON.parse(readFileSync(join(root, "artifacts", output.manifestPath), "utf8")).credentials.type).toBe("c2pa-style");
  expect(Object.hasOwn(signedArtifactUrls(done!, "token")!, "c2paUrl")).toBe(false);
}, 120000);

/** A host whose signing configuration is half-set or wrong refuses to start, before any job is claimed. */
test("the worker refuses to start on a half-set or invalid C2PA signing configuration", async () => {
  const id = makeC2paTestIdentity(join(TMP, "startup-identity")), root = join(TMP, "startup"), stop = new AbortController();stop.abort();
  const start = () => runWorker({ signal: stop.signal, pollMs: 10, queuePath: join(root, "jobs.json"), artifactRoot: join(root, "artifacts") });
  await withC2paEnv({ key: id.keyPath }, () => expect(start()).rejects.toThrow("Set both HV_C2PA_SIGNING_KEY and HV_C2PA_SIGNING_CERT, or neither."));
  await withC2paEnv({ key: id.keyPath, cert: id.noEkuChainPath }, () => expect(start()).rejects.toThrow("extended key usage"));
  expect(existsSync(join(root, "jobs.json"))).toBe(false);
});
