import {buildScriptNavigationIndex,createScriptNavigationState,scriptEntryKey,scriptSavedIdentity} from './edit-script-state.js';

const PAGE=6;
const node=(tag,text)=>{const element=document.createElement(tag);if(text!==undefined)element.textContent=text;return element;};
const time=frame=>Math.floor(frame/1800)+':'+String(Math.floor(frame/30)%60).padStart(2,'0')+':'+String(frame%30).padStart(2,'0');
const evidence=value=>value==='measured-speech'?'Measured speech timing':'Shot coverage; line timing is not measured';
const excerpt=(value,length=140)=>value.length>length?value.slice(0,length-1)+'…':value;
const sceneValue=entry=>entry.sceneIndex===null?'outside':String(entry.sceneIndex);

/** Owner-only, derived navigation. It never writes a screenplay, timeline or render job. */
export function createEditScriptNavigation({parent,request,current,onSeek,onSelectClip,onHighlight=()=>{},onReviseLine}){
  const panel=node('details'),summary=node('summary','Screenplay in this cut'),status=node('p'),actions=node('div'),body=node('div'),controls=node('div'),sourceSelect=node('select'),sceneSelect=node('select'),search=node('input'),follow=node('input'),followLane=node('select'),followStatus=node('p'),sourceDescription=node('p'),warnings=node('div'),entryList=node('div'),entryPager=node('div'),detail=node('section');
  panel.className='edit-script-nav';panel.hidden=true;status.className='edit-script-status';status.setAttribute('role','status');actions.className='edit-script-row';controls.className='edit-script-controls';entryList.className='edit-script-list';entryPager.className='edit-script-row';detail.className='edit-script-detail';followStatus.className='edit-script-follow-status';followStatus.setAttribute('aria-live','off');sourceDescription.className='edit-script-text';search.type='search';follow.type='checkbox';body.hidden=true;
  panel.append(summary,status,actions,body);body.append(node('p','These links describe retained source ranges. A linked picture may be covered by another layer, and linked sound may be muted. Each original keeps its own screenplay version.'),controls,sourceDescription,followStatus,warnings,entryList,entryPager,detail);parent.append(panel);
  let saved=null,identity=null,index=null,data=null,selectedKey=null,visible=[],page=0,occurrencePage=0,frame=0,disposed=false,searchTimer=null,activeSignature=null,activeKeys=new Set(),rows=new Map();
  const tell=(text,error=false)=>{status.textContent=text;status.dataset.state=error?'error':'success';};
  const isCurrent=()=>!disposed&&identity!==null&&scriptSavedIdentity(current())===identity;
  function ensureCurrent(){if(!isCurrent())throw new Error('The open saved cut changed. Reopen its screenplay links.');}
  function highlight(items){try{onHighlight(items);}catch(error){tell(error.message??'The timeline highlight could not update.',true);}}
  const safe=action=>async()=>{try{ensureCurrent();await action();}catch(error){tell(error.message??'This screenplay navigation action could not finish.',true);}};
  function button(parent,label,action){const element=node('button',label);element.type='button';element.className='secondary';element.onclick=safe(action);parent.append(element);return element;}
  function field(label,input){const wrapper=node('div'),caption=node('label',label);wrapper.className='cast-field';input.id='edit-script-'+crypto.randomUUID();caption.htmlFor=input.id;wrapper.append(caption,input);controls.append(wrapper);}
  function options(select,values,selected){select.replaceChildren(...values.map(([value,label])=>new Option(label,value)));if(selected!==undefined)select.value=selected;}
  field('Retained original and screenplay version',sourceSelect);field('Scene',sceneSelect);field('Search original or performed text',search);field('Follow screenplay during playback',follow);field('Follow retained ranges in',followLane);options(followLane,[['picture','Picture'],['dialogue','Dialogue'],['narration','Narration'],['captions','Captions'],['all','All retained lanes']],'picture');
  const loadButton=button(actions,'Load screenplay links',()=>store.load()),cancelButton=button(actions,'Cancel loading',()=>store.cancel());cancelButton.hidden=true;
  function clearSelection(){selectedKey=null;occurrencePage=0;detail.replaceChildren();highlight([]);}
  function clearData(){data=null;index=null;visible=[];rows=new Map();activeSignature=null;activeKeys=new Set();followStatus.textContent='';body.hidden=true;clearSelection();}
  const store=createScriptNavigationState({request,current,onChange(state){
    if(disposed)return;loadButton.disabled=state.status==='loading'||!identity;loadButton.textContent=state.data?'Refresh screenplay links':'Load screenplay links';cancelButton.hidden=state.status!=='loading';panel.setAttribute('aria-busy',String(state.status==='loading'));
    if(state.status!=='ready'){clearData();tell(state.error??({empty:'Choose a saved sequence to inspect its screenplay links.',idle:'Expand this panel or choose Load screenplay links to inspect this saved cut.',loading:'Loading retained screenplay versions and timeline ranges…',cancelled:'Loading cancelled. Choose Load screenplay links to try again.'}[state.status]??'Load screenplay links for the open saved cut.'),Boolean(state.error));return;}
    data=state.data;index=buildScriptNavigationIndex(data);body.hidden=false;clearSelection();options(sourceSelect,data.sources.map((source,i)=>[source.sourceId,(i+1)+'. '+source.label+' · '+source.language+(source.scriptRevision?' · screenplay '+source.scriptRevision.slice(0,12):' · no screenplay')]),data.sources.find(source=>source.scriptRevision)?.sourceId??data.sources[0]?.sourceId);search.value='';page=0;renderSource();tell(data.sources.some(source=>source.entries.length)?'Screenplay links loaded for this saved cut. Select a scene or line to inspect all retained occurrences.':'This saved cut has no retained screenplay entries. Picture and graphic editing remain available.');
  }});
  function appendWarnings(parent,values,label){if(!values.length)return;const box=node('details'),list=node('ul'),pager=node('div');pager.className='edit-script-row';box.append(node('summary',label+' · '+values.length),list,pager);parent.append(box);let at=0;function render(){list.replaceChildren(...values.slice(at,at+PAGE).map(value=>node('li',value)));pager.replaceChildren();if(values.length>PAGE){const previous=button(pager,'Previous warnings',()=>{at=Math.max(0,at-PAGE);render();}),next=button(pager,'Next warnings',()=>{at+=PAGE;render();});previous.disabled=at===0;next.disabled=at+PAGE>=values.length;}}render();}
  function source(){return data?.sources.find(item=>item.sourceId===sourceSelect.value);}
  function renderSource(){
    const original=source();warnings.replaceChildren();if(!original){sourceDescription.textContent='No retained originals are available in this cut.';options(sceneSelect,[['all','All scenes']],'all');visible=[];renderEntries();return;}
    sourceDescription.textContent=original.scriptRevision?'Retained screenplay revision '+original.scriptRevision.slice(0,12)+' · '+original.language+'. This is the text retained with '+original.label+'.':'This original has no screenplay binding. Graphic sources remain available through the picture editor.';
    const scenes=new Map();for(const entry of original.entries)if(entry.sceneIndex!==null&&(!scenes.has(entry.sceneIndex)||entry.kind==='scene'))scenes.set(entry.sceneIndex,entry.kind==='scene'?entry.text:'Scene '+(entry.sceneIndex+1));
    options(sceneSelect,[['all','All scenes'],...[...scenes].sort((a,b)=>a[0]-b[0]).map(([i,label])=>[String(i),'Scene '+(i+1)+' · '+excerpt(label,100)]),...(original.entries.some(entry=>entry.sceneIndex===null)?[['outside','Narration and other unbound entries']]:[])],'all');appendWarnings(warnings,data.warnings,'Cut navigation notes');appendWarnings(warnings,original.warnings,'Original navigation notes');filterEntries();
  }
  function filterEntries(){
    const original=source(),query=search.value.trim().toLocaleLowerCase(),scene=sceneSelect.value;visible=(original?.entries??[]).filter(entry=>(scene==='all'||sceneValue(entry)===scene)&&(!query||index.entries.get(scriptEntryKey(original.sourceId,entry.id)).search.includes(query)));page=0;
    if(selectedKey&&!visible.some(entry=>scriptEntryKey(original.sourceId,entry.id)===selectedKey))clearSelection();else if(selectedKey)highlight(index.byEntry.get(selectedKey)??[]);activeSignature=null;renderEntries();onFrame(frame);
  }
  function entryTitle(entry){const kind=entry.kind[0].toUpperCase()+entry.kind.slice(1);return kind+(entry.character?' · '+entry.character:'')+': '+excerpt(entry.text);}
  function renderEntries(){
    rows=new Map();entryList.replaceChildren();entryPager.replaceChildren();const original=source();if(!visible.length){entryList.append(node('p',!original?.scriptRevision?'No screenplay entries are linked to this original.':search.value.trim()?'No entries match this search in the selected scene.':'No screenplay entries are available in the selected scene.'));return;}
    let lastScene;for(const entry of visible.slice(page*PAGE,(page+1)*PAGE)){if(entry.sceneIndex!==lastScene){entryList.append(node('h4',entry.sceneIndex===null?'Narration and other entries':'Scene '+(entry.sceneIndex+1)));lastScene=entry.sceneIndex;}
      const key=scriptEntryKey(original.sourceId,entry.id),row=node('article'),select=button(row,entryTitle(entry),()=>selectEntry(key)),count=index.byEntry.get(key)?.length??0;row.className='edit-script-entry';row.dataset.selected=String(key===selectedKey);row.dataset.active=String(activeKeys.has(key));select.setAttribute('aria-pressed',String(key===selectedKey));row.append(node('p',entry.unavailableReason??(count?count+' retained '+(count===1?'occurrence':'occurrences'):'No occurrence remains in this saved cut.')));entryList.append(row);rows.set(key,{row,select});}
    entryPager.append(node('span','Entries '+(page*PAGE+1)+'–'+Math.min((page+1)*PAGE,visible.length)+' of '+visible.length));if(visible.length>PAGE){const previous=button(entryPager,'Previous entries',()=>{page--;renderEntries();}),next=button(entryPager,'Next entries',()=>{page++;renderEntries();});previous.disabled=page===0;next.disabled=(page+1)*PAGE>=visible.length;}
  }
  function selectEntry(key){
    const item=index?.entries.get(key);if(!item)return;selectedKey=key;occurrencePage=0;for(const [candidate,{row,select}]of rows){row.dataset.selected=String(candidate===key);select.setAttribute('aria-pressed',String(candidate===key));}renderDetail();highlight(index.byEntry.get(key)??[]);
  }
  function renderDetail(){
    detail.replaceChildren();const item=index?.entries.get(selectedKey);if(!item)return;const {entry,source:original}=item,occurrences=index.byEntry.get(selectedKey)??[];detail.append(node('h4','Selected '+entry.kind),node('p',entry.character?'Character: '+entry.character:'Retained '+entry.kind));const text=node('p',entry.text);text.className='edit-script-text';detail.append(node('h5',entry.kind==='narration'?'Original narration text':'Original screenplay text'),text);
    if(entry.performedText!==undefined){const performed=node('p',entry.performedText);performed.className='edit-script-text';detail.append(node('h5','Retained performed / localized text ('+original.language+')'),performed);}
    if(entry.startLine!==null)detail.append(node('p','Original line '+entry.startLine+(entry.endLine!==entry.startLine?'–'+entry.endLine:'')+' · screenplay '+original.scriptRevision?.slice(0,12)+'.'));
    if(onReviseLine&&entry.kind==='dialogue'&&entry.startLine!==null&&!entry.unavailableReason)button(detail,'Revise this screenplay line',()=>{ensureCurrent();return onReviseLine({navigationRevision:data.revision,sourceRevision:original.receiptRevision,indexRevision:original.revision,entryId:entry.id,text:entry.text,character:entry.character,sourceId:original.sourceId});});
    for(const label of new Set(entry.windows.map(window=>evidence(window.evidence))))detail.append(node('p',label+'.'));if(entry.unavailableReason)detail.append(node('p',entry.unavailableReason));
    if(!occurrences.length){detail.append(node('p','No retained timeline occurrence is available for this entry.'));return;}
    detail.append(node('p',occurrences.length+' retained '+(occurrences.length===1?'occurrence':'occurrences')+' across the listed clips and lanes. Timeline outlines describe retained ranges, including overlaps.'));
    for(const occurrence of occurrences.slice(occurrencePage*PAGE,(occurrencePage+1)*PAGE)){const clipNumber=saved.timeline.clips.findIndex(clip=>clip.id===occurrence.clipId)+1,row=node('div');row.className='edit-script-occurrence';row.append(node('p',occurrence.lane+(occurrence.lane==='picture'?' '+occurrence.layer:'')+' · clip '+clipNumber+' · '+time(occurrence.startFrame)+'–'+time(occurrence.endFrame)),node('p',evidence(occurrence.evidence)+(occurrence.held?' · held source position':'')+(occurrence.transition?' · transition handle':'')+(occurrence.muted?' · muted by held playback timing':'')+'.'));
      button(row,'Select clip '+clipNumber+' and seek to '+time(occurrence.startFrame),async()=>{const bound=identity;await onSelectClip(occurrence.clipId);ensureCurrent();if(bound!==identity)throw new Error('The saved cut changed before seeking.');await onSeek(occurrence.startFrame);});detail.append(row);}
    if(occurrences.length>PAGE){const pager=node('div');pager.className='edit-script-row';pager.append(node('span','Occurrences '+(occurrencePage*PAGE+1)+'–'+Math.min((occurrencePage+1)*PAGE,occurrences.length)+' of '+occurrences.length));const previous=button(pager,'Previous occurrences',()=>{occurrencePage--;renderDetail();}),next=button(pager,'Next occurrences',()=>{occurrencePage++;renderDetail();});previous.disabled=occurrencePage===0;next.disabled=(occurrencePage+1)*PAGE>=occurrences.length;detail.append(pager);}
  }
  function onFrame(value){
    frame=value;if(!index||!panel.open||!isCurrent()||!Number.isSafeInteger(frame)||frame<0)return;const original=source();if(!original)return;const query=search.value.trim().toLocaleLowerCase(),scene=sceneSelect.value,active=index.active(original.sourceId,frame,followLane.value),priorities=new Map();
    for(const occurrence of active){const key=scriptEntryKey(occurrence.sourceId,occurrence.entryId),item=index.entries.get(key);if((scene==='all'||sceneValue(item.entry)===scene)&&(!query||item.search.includes(query)))priorities.set(key,Math.min(priorities.get(key)??1,occurrence.evidence==='measured-speech'?0:1));}
    const keys=new Set(priorities.keys()),signature=JSON.stringify([...priorities].sort(([a],[b])=>a.localeCompare(b)));if(signature===activeSignature)return;activeSignature=signature;activeKeys=keys;
    for(const [key,{row}]of rows)row.dataset.active=String(keys.has(key));const candidates=[...keys].map(key=>({key,priority:priorities.get(key),...index.entries.get(key)})).sort((a,b)=>a.priority-b.priority||Number(a.entry.kind==='scene')-Number(b.entry.kind==='scene'));
    followStatus.textContent=keys.size?(follow.checked?'Following':'At this playhead position')+': '+candidates.slice(0,2).map(item=>excerpt(item.entry.text,100)).join(' · ')+(keys.size>2?' · '+(keys.size-2)+' more retained entries':''):'No matching retained screenplay ranges at this playhead position.';
    const focused=document.activeElement,editingControls=panel.contains(focused)&&focused!==follow;if(follow.checked&&!editingControls&&candidates.length){const chosen=candidates.find(item=>item.key===selectedKey&&item.priority===candidates[0].priority)??candidates[0],at=visible.findIndex(entry=>scriptEntryKey(original.sourceId,entry.id)===chosen.key);if(at>=0&&Math.floor(at/PAGE)!==page){page=Math.floor(at/PAGE);renderEntries();}if(chosen.key!==selectedKey)selectEntry(chosen.key);}
  }
  sourceSelect.onchange=safe(()=>{clearSelection();page=0;renderSource();});sceneSelect.onchange=safe(filterEntries);search.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(isCurrent())filterEntries();},150);};follow.onchange=safe(()=>{activeSignature=null;onFrame(frame);});followLane.onchange=safe(()=>{activeSignature=null;onFrame(frame);});
  panel.addEventListener('toggle',()=>{if(disposed)return;if(!panel.open){store.cancel();return;}if(store.state.status==='idle')void store.load();else{activeSignature=null;onFrame(frame);}});
  return {panel,bind(value){if(disposed)return;const next=scriptSavedIdentity(value);if(next===identity){saved=value;return;}saved=value;identity=next;clearTimeout(searchTimer);panel.hidden=!value;store.bind(value);},onFrame,dispose(){if(disposed)return;disposed=true;clearTimeout(searchTimer);store.dispose();highlight([]);panel.remove();}};
}
