import {EditTime,editPhaseFrame,editCrossfadeWindow,mountEditorialPreview} from './preview-controller.js';
import {mountEditorialComparison} from './preview-comparison.js';
import {mountMaskEditor} from './mask-editor.js';
import {loadMaskSourceFrame} from './mask-source.js';
import {createEditScriptNavigation} from './edit-script.js';
import {createEditAssemblyStudio} from './edit-assemblies.js';
import {mountEditAssemblyPreview} from './edit-assembly-preview.js';
const same=(a,b)=>{const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==="object"?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;return JSON.stringify(canonical(a))===JSON.stringify(canonical(b));};
/** Merge display outlines only; navigation keeps every independently addressable occurrence. */
export function editorialScriptRanges(timeline,occurrences){
  const clips=new Map(timeline.clips.map(clip=>[clip.id,clip])),lanes=new Map();
  for(const item of occurrences){const clip=clips.get(item.clipId);if(!clip||clip.sourceId!==item.sourceId||clip.lane!==item.lane||clip.layer!==item.layer||!Number.isInteger(item.startFrame)||!Number.isInteger(item.endFrame)||item.startFrame<0||item.endFrame>timeline.frames||item.endFrame<=item.startFrame)continue;const lane=clip.lane==='picture'?'picture '+clip.layer:clip.lane;if(!lanes.has(lane))lanes.set(lane,[]);lanes.get(lane).push({at:item.startFrame,end:item.endFrame});}
  return [...lanes].flatMap(([lane,intervals])=>{intervals.sort((a,b)=>a.at-b.at||a.end-b.end);const merged=[];for(const interval of intervals){const last=merged.at(-1);if(last&&last.end>=interval.at)last.end=Math.max(last.end,interval.end);else merged.push({...interval});}return merged.map(range=>({lane,at:range.at,frames:range.end-range.at}));});
}
export function savedEditorialEdit(current,change){const history=current.sequence.history;return {kind:"edit",sequenceId:current.sequence.id,eventCount:history.events.length,previousEventRevision:history.events.at(-1)?.revision??history.root.revision,body:{expectedVersion:current.libraryVersion,expectedHistoryRevision:history.revision,change}};}
export function matchesSavedEditorialEdit(actual,saved){if(actual.sequence.id!==saved.sequenceId)return false;const change=saved.body.change;if(change.kind==="rename")return actual.sequence.label===change.label.trim()&&actual.libraryVersion>saved.body.expectedVersion;const event=actual.sequence.history.events[saved.eventCount];return Boolean(event&&event.previousRevision===saved.previousEventRevision&&event.kind===change.kind&&event.label===change.label&&(change.kind==="edit"?same(event.operation,change.operation):event.target===change.target&&event.reason===change.reason));}
export function savedEditorialSource(current,item){const history=current.sequence.history;return {kind:"source",sequenceId:current.sequence.id,eventCount:history.events.length,previousEventRevision:history.events.at(-1)?.revision??history.root.revision,sourceId:item.facts.id,body:{jobId:item.jobId,sourceRevision:item.sourceRevision,expectedVersion:current.libraryVersion,expectedHistoryRevision:history.revision}};}
export function matchesSavedEditorialSource(actual,saved){const event=actual.sequence.history.events[saved.eventCount];return actual.sequence.id===saved.sequenceId&&Boolean(event&&event.previousRevision===saved.previousEventRevision&&event.kind==="edit"&&event.operation.kind==="source"&&event.operation.source.id===saved.sourceId&&event.operation.receiptRevision===saved.body.sourceRevision);}
export function editorialMaskReview(current,quote){
  const revision=current.timeline.revision,needed=current.timeline.clips.some(c=>c.composite)||Boolean(current.timeline.matteOnlyLayers?.length),compositing=quote.compositing;
  if(quote.timelineRevision!==revision||quote.review?.timelineRevision!==revision||Boolean(compositing)!==needed||compositing&&(compositing.timelineRevision!==revision||!Array.isArray(compositing.warnings)||compositing.warnings.some(w=>typeof w!=='string')||!/^[a-f0-9]{64}$/.test(quote.review.compositingRevision??'')))throw new Error('The saved masks and matte review changed. Refresh the saved sequence and review its export again.');
  return compositing;
}
export function editorialCrossfadeOperation(t,leftId,rightId,linked,frames,alignment,identity=()=>crypto.randomUUID()){
  const left=t.clips.find(c=>c.id===leftId),right=t.clips.find(c=>c.id===rightId);if(!left||!right)throw new Error('Choose an adjacent crossfade boundary.');
  const targets=(linked&&left.link?t.clips.filter(c=>c.link===left.link):[left]).filter(c=>c.lane!=='captions'),rights=linked&&right.link?t.clips.filter(c=>c.link===right.link):[right],ids=Object.create(null);
  for(const c of targets){const peer=rights.find(r=>r.lane===c.lane&&r.layer===c.layer&&r.at===c.at+c.frames);if(!peer)throw new Error('Choose a boundary with matching linked tracks.');ids[c.id]=t.transitions?.find(x=>x.leftId===c.id&&x.rightId===peer.id)?.id??identity();}
  return {kind:'crossfade',leftId,rightId,linked,frames,alignment,ids};
}
/** Every edit is a saved history event. Preview follows its exact saved source addresses. */
export function initEditorial({parent,request,jobRequest,projectState,projectId,assetUrl,canEdit,adopt,previewClient}) {
  const node=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
  const details=label=>{const e=node("details");e.append(node("summary",label));return e;};
  const actions=()=>{const e=node("div");e.className="result-actions";return e;};
  const panel=node("section"),status=node("p"),pendingBox=node("div"),navigation=node("div"),creation=details("Create a sequence from retained originals"),editor=node("div"),review=node("div"),versions=details("Rendered versions and comparison"),playback=node("div");
  panel.className="motion-workbench editorial-studio";panel.hidden=true;status.className="status";status.setAttribute("role","status");
  panel.append(node("h2","Picture editorial"),node("p","Arrange retained picture and performances, preview the saved cut, and render an independent export."),status,pendingBox,navigation,creation,editor,review,versions,playback);parent.append(panel);
  let activeProject=null,index=null,current=null,selectedClip=null,dirty=false,dirtyGroup=null,busy=false,serial=0,bin=[],pending=null,reviewButton=null,selection={version:0,entries:[]},watchTimer=null,watched=null;
  let creationDraft={label:"New assembly",dimensions:"1280x720",width:1280,height:720};
  let playbackSerial=0,comparison=null,maskEditor=null,scriptNavigation=null,scriptHighlights=[],assemblyStudio=null,assemblyLocks=null,assemblyPreview=null;
  const preview=mountEditorialPreview({parent:panel,client:previewClient,current:()=>Boolean(current)&&!busy&&!panel.hidden&&activeProject===projectId(),onFrame:frame=>scriptNavigation?.onFrame(frame)});editor.before(preview.panel);
  const scriptHost=node('div');editor.before(scriptHost);
  scriptNavigation=createEditScriptNavigation({parent:scriptHost,request,current:()=>!panel.hidden&&activeProject===projectId()?current:null,onHighlight:occurrences=>{scriptHighlights=occurrences;drawScriptHighlights();},onSeek:frame=>{clean();if(busy||panel.hidden||activeProject!==projectId())throw new Error('Wait for the current edit and reopen the saved cut before seeking.');return preview.controller.seek(frame,false);},onSelectClip:id=>{clean();if(busy||panel.hidden||activeProject!==projectId())throw new Error('Wait for the current edit before selecting a screenplay range.');if(!current?.timeline.clips.some(c=>c.id===id))throw new Error('This screenplay range is no longer in the saved cut.');selectedClip=id;drawEditor();}});
  const creationDirty=()=>bin.length>0||creationDraft.label!=="New assembly"||creationDraft.dimensions!=="1280x720"||Number(creationDraft.width)!==1280||Number(creationDraft.height)!==720;
  const tell=(message,error=false)=>{status.textContent=message;status.dataset.state=error?"error":"success";};
  const time=frames=>{const seconds=Math.floor(frames/30);return Math.floor(seconds/60)+":"+String(seconds%60).padStart(2,"0")+":"+String(frames%30).padStart(2,"0");};
  const clean=()=>{if(assemblyStudio?.unsaved||assemblyStudio?.pending)throw new Error("Save or discard the assembly draft and resolve its saved request before switching views.");if(dirty)throw new Error("Apply or discard the unsaved fields before switching views.");if(pending&&!pending.jobId)throw new Error("Resolve the saved request before making another change.");};
  const assemblyHost=node('div');editor.before(assemblyHost);
  assemblyPreview=mountEditAssemblyPreview({parent:assemblyHost,client:previewClient,current:()=>!panel.hidden&&!busy&&!dirty&&!creationDirty()&&canEdit()&&activeProject===projectId()&&!(pending&&!pending.jobId)&&!assemblyStudio?.unsaved&&!assemblyStudio?.pending});
  assemblyStudio=createEditAssemblyStudio({parent:assemblyHost,request,jobRequest,assetUrl,current:()=>!panel.hidden&&activeProject===projectId()&&current?{projectId:activeProject,sequenceId:current.sequence.id,historyRevision:current.sequence.history.revision,frames:current.timeline.frames,busy,canEdit:canEdit()&&!dirty&&!creationDirty()&&!(pending&&!pending.jobId)}:null,
    onDirty:active=>{if(active){preview.stop();comparison?.stop();assemblyPreview.stop();if(!assemblyLocks){assemblyLocks=new Map([navigation,creation,editor,review,versions].flatMap(host=>[...host.querySelectorAll('button,input,select,textarea')]).map(control=>[control,control.disabled]));for(const control of assemblyLocks.keys())control.disabled=true;}}else if(assemblyLocks){for(const [control,disabled]of assemblyLocks)if(control.isConnected)control.disabled=disabled;assemblyLocks=null;}},
    onPreviewBinding:detail=>assemblyPreview.bind(detail),
    onAccepted:result=>tell('Saved assembly: '+result.item.label+' · '+time(result.item.frames)+'. The parent cut is retained.'),
    onSelectExport:async binding=>{if(dirty||busy||pending&&!pending.jobId||panel.hidden||activeProject!==projectId())throw new Error('Resolve the current fields before selecting an assembly export.');const saved=await adopt({...binding,expectedVersion:selection.version});selection=saved.dialogueSelections;tell('Assembly export selected. Earlier versions remain available.');return {selected:true};},
    onParentRange:range=>{if(dirty||busy||pending&&!pending.jobId||panel.hidden||activeProject!==projectId()||current?.sequence.id!==range.sequenceId||current.sequence.history.revision!==range.historyRevision)throw new Error('Open the matching saved parent and resolve its fields before previewing this range.');return preview.controller.seek(range.fromFrame,false);}});
  assemblyHost.append(assemblyPreview.panel);
  function refreshAssemblyGuards(){assemblyPreview.stop();assemblyStudio?.bind(current);}
  const button=(label,action)=>{const e=node("button",label);e.type="button";e.className="secondary";e.onclick=()=>run(action);return e;};
  const primary=e=>{for(const b of panel.querySelectorAll("button"))b.classList.add("secondary");e?.classList.remove("secondary");};
  async function run(action){if(busy)return;if(activeProject!==projectId()){tell("The open project changed. Reopen picture editorial.",true);return;}preview.stop();comparison?.stop();assemblyPreview.stop();busy=true;assemblyStudio.bind(current);panel.setAttribute("aria-busy","true");const controls=[...panel.querySelectorAll("button,input,select,textarea")].filter(e=>!e.dataset.previewStop),disabled=controls.map(e=>e.disabled);controls.forEach(e=>e.disabled=true);try{await action();}catch(error){tell(error.message||"This request could not finish. Your saved sequence is retained.",true);}finally{busy=false;controls.forEach((e,i)=>e.disabled=disabled[i]);panel.removeAttribute("aria-busy");drawPending();assemblyStudio.bind(current);}}
  function field(container,label,type,value,{min,max,step=1,track=false,group}={}){const wrap=node("div"),caption=node("label",label),e=node(type==="select"?"select":"input");wrap.className="cast-field";e.id="edit-field-"+(++serial);caption.htmlFor=e.id;if(type!=="select")e.type=type;if(type==="checkbox")e.checked=Boolean(value);else e.value=value??"";if(type==="number"){e.step=String(step);if(min!==undefined)e.min=String(min);if(max!==undefined)e.max=String(max);}if(track){e.dataset.draftGroup=group??container.dataset.draftGroup??"timing";e.oninput=()=>{dirty=true;refreshAssemblyGuards();dirtyGroup=e.dataset.draftGroup;for(const input of editor.querySelectorAll("[data-draft-group]"))if(input.matches("input,select"))input.disabled=input.dataset.draftGroup!==dirtyGroup;review.replaceChildren();primary(reviewButton);tell("Unsaved fields · apply this change or discard these fields before editing another group.");};}wrap.append(caption,e);container.append(wrap);return e;}
  function number(e){const value=Number(e.value),step=e.step&&e.step!=='any'?Number(e.step):null,units=step?(value-Number(e.min||0))/step:0;if(e.value.trim()===""||!e.checkValidity()||!Number.isFinite(value)||e.min!==''&&value<Number(e.min)||e.max!==''&&value>Number(e.max)||step&&Math.abs(units-Math.round(units))>1e-8){e.reportValidity();throw new Error("Enter a value within the displayed range and step.");}return value;}
  function options(e,items,value){e.replaceChildren(...items.map(([id,label])=>new Option(label,String(id))));if(value!==undefined)e.value=String(value);}
  function stop(container){if(container===playback){comparison?.dispose();comparison=null;}for(const video of container.querySelectorAll("video,audio")){video.pause();video.removeAttribute("src");video.load();}}
  function remember(value){pending=value;try{const key="hv-editorial-pending:"+activeProject;if(value)localStorage.setItem(key,JSON.stringify(value));else localStorage.removeItem(key);}catch{/* Keep the request in this open editor when local storage is unavailable. */}drawPending();}
  function drawPending(){pendingBox.replaceChildren();if(!pending)return;if(busy){pendingBox.append(node("p","Processing the saved request…"));return;}const label=pending.jobId?"A reviewed edit is queued or rendering.":"A saved request needs its result checked.";pendingBox.append(node("p",label),button(pending.jobId?"Check render status":"Retry the same saved request",()=>pending.kind==="edit"?sendEdit(pending):pending.kind==="source"?sendSource(pending):pending.kind==="create"?sendCreate(pending):submitRender()));}
  async function sendEdit(saved){tell("Saving edit history…");let response;try{response=await request("/sequences/"+saved.sequenceId,{method:"PATCH",body:saved.body});}catch(error){if(activeProject!==projectId())throw error;let checked=false;
      try{const actual=await request("/sequences/"+saved.sequenceId);checked=true;if(matchesSavedEditorialEdit(actual,saved))response=actual;}catch{/* Keep an uncertain request available for the same-key retry. */}
      if(!response){if(checked&&error.status&&error.status<500)remember(null);throw error;}
    }remember(null);current=response;dirty=false;dirtyGroup=null;if(saved.body.change.operation?.kind==="composite")maskEditor?.saved();drawEditor();await refreshIndex(false);tell("Saved · "+saved.body.change.label+". The earlier history is available for undo or another branch.");}
  async function change(change,group){if(assemblyStudio.unsaved||assemblyStudio.pending)throw new Error("Resolve the assembly draft before changing its parent.");if(pending&&!pending.jobId)throw new Error("Resolve the saved request first.");if(dirty&&dirtyGroup!==group)throw new Error("Apply or discard the fields already being edited first.");const saved=savedEditorialEdit(current,change);remember(saved);await sendEdit(saved);}
  async function sendSource(saved){tell("Saving the inspected original in this sequence…");let response;try{response=await request("/sequences/"+saved.sequenceId+"/sources",{method:"POST",body:saved.body});}catch(error){if(activeProject!==projectId())throw error;let checked=false;try{const actual=await request("/sequences/"+saved.sequenceId);checked=true;if(matchesSavedEditorialSource(actual,saved))response=actual;}catch{/* Retain an uncertain admission for recovery. */}if(!response){if(checked&&error.status&&error.status<500)remember(null);throw error;}}remember(null);current=response;dirty=false;dirtyGroup=null;drawEditor();await refreshIndex(false);tell("Original saved. Select a clip and open Duplicate or replace this range to swap takes. Undo restores the earlier branch.");}
  const operation=(label,value)=>change({kind:"edit",label,operation:value},["crossfade","remove-crossfade"].includes(value.kind)?"transitions":value.kind==="retime"?"retiming":["settings","insert","duration","duplicate","replace","composite","matte-only"].includes(value.kind)?value.kind:["marker","remove-marker"].includes(value.kind)?"marker":"timing");
  async function load(id){clean();clearTimeout(watchTimer);watched=null;playbackSerial++;stop(playback);playback.replaceChildren();review.replaceChildren();current=await request("/sequences/"+id);selectedClip=current.timeline.clips.find(c=>c.lane==="picture")?.id??current.timeline.clips[0]?.id??null;dirty=false;dirtyGroup=null;drawEditor();tell("Step 1 of 3 · Edit the saved sequence, then review its export.");}
  async function refreshIndex(draw=true){index=await request("");selection=(await projectState()).dialogueSelections??{version:0,entries:[]};if(current)current.libraryVersion=index.libraryVersion;if(draw)drawNavigation();else{const select=navigation.querySelector("select");if(select)options(select,index.sequences.map(s=>[s.id,s.label+" · "+time(s.frames)]),current?.sequence.id??select.value);}drawVersions();return index;}
  function drawNavigation(){navigation.replaceChildren();const select=field(navigation,"Saved sequence","select","");options(select,index.sequences.map(s=>[s.id,s.label+" · "+time(s.frames)]),current?.sequence.id);const controls=actions(),open=button("Open sequence",()=>load(select.value));open.disabled=!index.sequences.length;controls.append(open,button("Refresh saved state",async()=>{clean();await refreshIndex();if(current)await load(current.sequence.id);}),button("Close picture editorial",()=>{clean();if(creationDirty())throw new Error("Create or discard the new-sequence draft before closing picture editorial.");stop(playback);clearTimeout(watchTimer);watched=null;scriptNavigation.bind(null);panel.hidden=true;assemblyStudio.bind(null);assemblyPreview.bind(null);}));navigation.append(controls);drawCreation();}
  async function sendCreate(saved){tell("Creating the saved sequence…");let response;try{response=await request("/sequences",{method:"POST",body:saved.body});}catch(error){if(activeProject!==projectId())throw error;let checked=false;try{const actual=await request("/sequences/"+saved.sequenceId);checked=true;if(actual.sequence.label===saved.body.label.trim()&&same(actual.sequence.sourceRevisions.slice().sort(),saved.body.sources.map(s=>s.sourceRevision).sort())&&actual.sequence.history.root.width===saved.body.width&&actual.sequence.history.root.height===saved.body.height&&actual.sequence.history.root.clips.find(c=>c.lane==="picture")?.sourceId===saved.body.firstSourceId)response=actual;}catch(checkError){checked=checkError.status===404;}if(!response){if(checked&&error.status&&error.status<500)remember(null);throw error;}}
    remember(null);current=response;selectedClip=response.timeline.clips.find(c=>c.lane==="picture")?.id??null;bin=[];creationDraft={label:"New assembly",dimensions:"1280x720",width:1280,height:720};creation.open=false;await refreshIndex();drawEditor();tell("Sequence created. Every applied edit will be saved in its history.");
  }
  function drawCreation(){creation.replaceChildren(node("summary","Create a sequence from retained originals"));const source=field(creation,"Retained version","select","");options(source,index.sources.map(s=>[s.jobId,(s.label??s.stage)+" · "+s.jobId.slice(0,8)+" · "+(s.completedAt?new Date(s.completedAt).toLocaleString():"")]));const choices=node("div"),binView=node("div"),name=field(creation,"New sequence name","text",creationDraft.label),dimensions=field(creation,"Export dimensions","select","");options(dimensions,[["640x360","640 × 360"],["1280x720","1280 × 720"],["1920x1080","1920 × 1080"],["custom","Custom dimensions"]],creationDraft.dimensions);name.oninput=()=>{creationDraft.label=name.value;refreshAssemblyGuards();};const custom=node("div"),width=field(custom,"Export width","number",creationDraft.width,{min:16,max:1920,step:2}),height=field(custom,"Export height","number",creationDraft.height,{min:16,max:1080,step:2});custom.hidden=dimensions.value!=="custom";dimensions.onchange=()=>{creationDraft.dimensions=dimensions.value;custom.hidden=dimensions.value!=="custom";refreshAssemblyGuards();};width.oninput=()=>{creationDraft.width=width.value;refreshAssemblyGuards();};height.oninput=()=>{creationDraft.height=height.value;refreshAssemblyGuards();};creation.append(custom);
    const drawBin=()=>{binView.replaceChildren(node("p",bin.length+" of 16 originals selected. The first starts the sequence; insert other originals from the clip tools."));for(const item of bin){const row=actions();row.append(node("span",item.facts.label+" · "+time(item.facts.frames)),button("Remove "+item.facts.label,()=>{bin=bin.filter(b=>b.sourceRevision!==item.sourceRevision);drawBin();}));binView.append(row);}};
    const inspect=button("Inspect this version",async()=>{clean();tell("Checking original picture, performances and captions…");const data=await request("/sources/"+source.value);choices.replaceChildren();for(const item of data.sources){const row=actions(),add=button("Add "+item.facts.label,()=>{if(bin.some(b=>b.facts.id===item.facts.id))throw new Error("This original is already selected.");if(bin.length>=16)throw new Error("A sequence can bind up to sixteen originals.");bin.push(item);drawBin();});row.append(node("span",item.facts.label+" · "+time(item.facts.frames)+" · "+item.language),add);choices.append(row);}tell("Source checked. Add the originals for this sequence.");});inspect.disabled=!index.sources.length;
    const create=button("Create sequence",async()=>{clean();if(!bin.length)throw new Error("Inspect and add a retained original first.");const [w,h]=dimensions.value==="custom"?[number(width),number(height)]:dimensions.value.split("x").map(Number),id=crypto.randomUUID(),saved={kind:"create",sequenceId:id,body:{id,label:name.value,sources:bin.map(b=>({jobId:b.jobId,sourceRevision:b.sourceRevision})),firstSourceId:bin[0].facts.id,width:w,height:h,expectedVersion:index.libraryVersion}};remember(saved);await sendCreate(saved);});const controls=actions();controls.append(create,button("Discard new-sequence draft",()=>{if(pending?.kind==="create")throw new Error("Resolve the saved create request first.");bin=[];creationDraft={label:"New assembly",dimensions:"1280x720",width:1280,height:720};drawCreation();tell("New-sequence draft discarded. Saved sequences remain available.");}));creation.append(inspect,choices,binView,controls);drawBin();if(!current)primary(create);}
  function drawTimeline(container){const t=current.timeline,svg=document.createElementNS("http://www.w3.org/2000/svg","svg"),rows=[...new Set(t.clips.map(c=>c.lane==="picture"?"picture "+c.layer:c.lane))].sort((a,b)=>["picture 0","picture 1","picture 2","picture 3","mix","dialogue","narration","music","ambience","effects","captions"].indexOf(a)-["picture 0","picture 1","picture 2","picture 3","mix","dialogue","narration","music","ambience","effects","captions"].indexOf(b));
    svg.setAttribute("viewBox","0 0 1000 "+(40+rows.length*42));svg.setAttribute("role","img");svg.setAttribute("aria-label","Saved timeline with "+t.clips.length+" clips, "+rows.length+" tracks, and duration "+time(t.frames)+" at thirty frames per second");
    const shape=(tag,attrs,text)=>{const e=document.createElementNS(svg.namespaceURI,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;svg.append(e);return e;};
    for(let i=0;i<=4;i++)shape("text",{x:130+i*215,y:17,fill:"currentColor","font-size":20,"text-anchor":i===4?"end":"start"},time(Math.round(t.frames*i/4)));
    rows.forEach((lane,i)=>{const y=32+i*42;shape("text",{x:4,y:y+23,fill:"currentColor","font-size":20},lane);shape("rect",{x:130,y,width:860,height:32,fill:"#17232c","data-timeline-lane":lane});for(const c of t.clips.filter(c=>(c.lane==="picture"?"picture "+c.layer:c.lane)===lane)){const rect=shape("rect",{x:130+c.at/t.frames*860,y:y+3,width:Math.max(.5,c.frames/t.frames*860),height:26,fill:c.id===selectedClip?"#efb75c":c.lane==="picture"?"#797bca":c.lane==="captions"?"#b58bba":"#4a9992",stroke:c.id===selectedClip?"#fff":"none"});const title=document.createElementNS(svg.namespaceURI,"title");title.textContent=clipLabel(c);rect.append(title);}});
    for(const x of t.transitions??[]){const left=t.clips.find(c=>c.id===x.leftId),right=t.clips.find(c=>c.id===x.rightId),w=editCrossfadeWindow(left,right,x.frames,x.alignment,t.frames),lane=left.lane==='picture'?'picture '+left.layer:left.lane,y=35+rows.indexOf(lane)*42,start=130+w.at/t.frames*860,end=130+(w.at+w.frames)/t.frames*860;shape('line',{x1:start,y1:y,x2:end,y2:y+26,stroke:'#fff','stroke-width':2});shape('line',{x1:start,y1:y+26,x2:end,y2:y,stroke:'#fff','stroke-width':2});}
    for(const marker of t.markers)shape("line",{x1:130+marker.frame/t.frames*860,x2:130+marker.frame/t.frames*860,y1:23,y2:40+rows.length*42,stroke:"#eee","stroke-dasharray":"3 3"});const viewport=node("div");viewport.className="editorial-timeline";viewport.append(svg);container.append(viewport,node("p","Timecode is minutes:seconds:frames at 30 fps. Select a clip below for exact frame controls. Higher picture layers cover lower layers."));
  }
  function clipLabel(c){const source=current.timeline.sources.find(s=>s.id===c.sourceId);return c.lane+(c.lane==="picture"?" "+c.layer:"")+" · "+(source?.label??c.sourceId)+" · "+time(c.at)+"–"+time(c.at+c.frames)+" · "+c.id.slice(0,16);}
  function drawScriptHighlights(){const svg=editor.querySelector('.editorial-timeline svg');if(!svg||!current)return;svg.querySelector('[data-script-ranges]')?.remove();const t=current.timeline,group=document.createElementNS(svg.namespaceURI,'g'),rows=new Map([...svg.querySelectorAll('[data-timeline-lane]')].map(row=>[row.getAttribute('data-timeline-lane'),Number(row.getAttribute('y'))]));group.setAttribute('data-script-ranges','true');group.setAttribute('pointer-events','none');const paths=new Map();for(const range of editorialScriptRanges(t,scriptHighlights)){if(!rows.has(range.lane))continue;const x=130+range.at/t.frames*860,y=rows.get(range.lane)+1,w=Math.max(1,range.frames/t.frames*860);paths.set(range.lane,(paths.get(range.lane)??'')+`M${x} ${y}h${w}v30h${-w}z `);}for(const [lane,d]of paths){const path=document.createElementNS(svg.namespaceURI,'path');for(const [key,value]of Object.entries({d,fill:'none',stroke:'#fff4a3','stroke-width':2}))path.setAttribute(key,String(value));const title=document.createElementNS(svg.namespaceURI,'title');title.textContent='Selected screenplay ranges · '+lane;path.append(title);group.append(path);}svg.append(group);}
  function drawEditor(){maskEditor?.dispose();maskEditor=null;editor.replaceChildren();review.replaceChildren();preview.bind(current);scriptNavigation.bind(current);assemblyStudio.bind(current);scriptNavigation.onFrame(preview.controller.position);if(!current)return;const t=current.timeline;editor.append(node("h3",current.sequence.label),node("p",time(t.frames)+" · "+t.width+" × "+t.height+" · saved branch "+current.head));drawTimeline(editor);drawScriptHighlights();
    const toolbar=actions(),undo=button("Undo saved edit",()=>{clean();return change({kind:"cursor",reason:"undo",target:current.parent,label:"Undo to prior edit"});});undo.disabled=current.parent===null;reviewButton=button("Review export",reviewExport);toolbar.append(undo,button("Discard unsaved fields",()=>{if(pending&&!pending.jobId)throw new Error("Resolve the saved request first.");dirty=false;dirtyGroup=null;maskEditor?.saved();drawEditor();tell("Unsaved fields discarded. Saved history is unchanged.");}),reviewButton);editor.append(toolbar);
    const history=details("Redo and branch history"),branch=field(history,"Saved branch","select","");options(branch,[[0,"Original sequence"],...current.sequence.history.events.filter(e=>e.kind==="edit").map(e=>[e.sequence,e.sequence+" · "+e.label])],current.head);history.append(button("Open this branch",()=>{clean();return change({kind:"cursor",reason:current.children.includes(Number(branch.value))?"redo":"branch",target:Number(branch.value),label:"Open saved branch "+branch.value});}));editor.append(history);
    const choose=field(editor,"Selected clip","select","");options(choose,t.clips.map(c=>[c.id,clipLabel(c)]),t.clips.some(c=>c.id===selectedClip)?selectedClip:t.clips[0]?.id);selectedClip=choose.value||null;choose.onchange=()=>{if(dirty){choose.value=selectedClip;tell("Apply or discard the current fields before choosing another clip.",true);return;}selectedClip=choose.value;drawEditor();};
    const c=t.clips.find(c=>c.id===selectedClip);if(c)drawClipTools(c);drawSourceTools();drawInsert();drawMatteRoles();drawSequenceTools();primary(preview.playButton);
  }
  function drawClipTools(c){const tools=node("div");tools.className="editorial-tools";editor.append(tools);const basic=details("Split, move and trim"),advanced=details("Slip, roll, slide and remove"),settings=details("Levels, opacity, crop and fades");basic.dataset.draftGroup="timing";advanced.dataset.draftGroup="timing";settings.dataset.draftGroup="settings";basic.open=true;tools.append(basic,advanced,settings);
    basic.append(node("p","Source frames "+(new EditTime(c).source(c.at*1600)/1600).toFixed(3)+"–"+(new EditTime(c).source((c.at+c.frames)*1600)/1600).toFixed(3)+" · "+(c.link?"Linked to picture/audio/caption clips":"Unlinked clip")));const linked=field(basic,"Apply timing changes to linked clips","checkbox",true,{track:true}),ripple=field(basic,"Ripple following ranges","checkbox",true,{track:true}),frame=field(basic,"Timeline frame for split or move","number",c.at+Math.floor(c.frames/2),{min:0,max:current.timeline.frames,track:true}),basicActions=actions();
    const split=button("Split at frame",()=>{const targets=linked.checked&&c.link?current.timeline.clips.filter(x=>x.link===c.link):[c];return operation("Split "+c.lane+" at frame "+number(frame),{kind:"split",clipId:c.id,linked:linked.checked,at:number(frame),rightIds:Object.fromEntries(targets.map(x=>[x.id,crypto.randomUUID()])),rightLink:c.link&&linked.checked?crypto.randomUUID():null});});split.disabled=c.frames<2;basicActions.append(split,button("Move to frame",()=>operation("Move "+c.lane+" to frame "+number(frame),{kind:"move",clipId:c.id,linked:linked.checked,at:number(frame)})),button("Reorder linked range",()=>operation("Reorder range to frame "+number(frame),{kind:"reorder",clipId:c.id,at:number(frame)})));basic.append(basicActions);
    const edge=field(basic,"Trim edge","select","",{track:true});options(edge,[["in","In (start)"],["out","Out (end)"]],"out");const trim=field(basic,"Move edge by frames (+ later, − earlier)","number",0,{min:-108000,max:108000,track:true});basic.append(button("Apply trim",()=>operation("Trim "+c.lane+" "+edge.value+" by "+number(trim)+" frames",{kind:"trim",clipId:c.id,linked:linked.checked,edge:edge.value,delta:number(trim),ripple:ripple.checked})));
    const delta=field(advanced,"Shift source or shared boundary by frames","number",0,{min:-108000,max:108000,track:true}),neighbors=current.timeline.clips.filter(x=>x.lane===c.lane&&x.layer===c.layer&&x.id!==c.id),left=field(advanced,"Left clip for roll or slide","select",""),right=field(advanced,"Right clip for slide","select","");options(left,neighbors.map(x=>[x.id,clipLabel(x)]),neighbors.find(x=>x.at+x.frames===c.at)?.id);options(right,neighbors.map(x=>[x.id,clipLabel(x)]),neighbors.find(x=>x.at===c.at+c.frames)?.id);const controls=actions();
    controls.append(button("Slip source",()=>operation("Slip "+c.lane+" by "+number(delta)+" frames",{kind:"slip",clipId:c.id,linked:linked.checked,delta:number(delta)})),button("Roll left boundary",()=>operation("Roll shared boundary",{kind:"roll",leftId:left.value,rightId:c.id,linked:linked.checked,delta:number(delta)})),button("Slide clip",()=>operation("Slide middle range",{kind:"slide",leftId:left.value,clipId:c.id,rightId:right.value,linked:linked.checked,delta:number(delta)})),button("Unlink this group",()=>operation("Unlink selected group",{kind:"unlink",clipId:c.id})),button("Remove selected range",()=>operation("Remove "+c.lane+" range",{kind:"delete",clipId:c.id,linked:linked.checked,ripple:ripple.checked})));advanced.append(controls,node("p","Roll and slide need adjacent ranges on the same track. Removal is saved and can be undone."));
    drawRetimeTools(tools,c);drawTakeTools(tools,c);drawCrossfadeTools(tools,c);if(c.lane==="picture")drawMaskTools(tools,c);
    if(c.lane==="captions"){settings.remove();return;}
    const isPicture=c.lane==="picture",gain=isPicture?null:field(settings,"Gain (dB)","number",c.gainDb,{min:-60,max:12,step:.1,track:true}),opacity=isPicture?field(settings,"Picture opacity","number",c.opacity,{min:0,max:1,step:.01,track:true}):null,fadeIn=field(settings,"Fade in (frames)","number",c.envelope.fadeIn,{min:0,max:108000,track:true}),fadeOut=field(settings,"Fade out (frames)","number",c.envelope.fadeOut,{min:0,max:108000,track:true}),source=current.timeline.sources.find(s=>s.id===c.sourceId),coordinates={};
    const crop=isPicture?field(settings,"Crop picture","checkbox",Boolean(c.crop),{track:true}):null,cropFields=node("div");cropFields.dataset.draftGroup="settings";cropFields.hidden=!c.crop;settings.append(cropFields);
    if(isPicture){crop.onchange=()=>{cropFields.hidden=!crop.checked;};for(const [key,label,value]of [["x","Crop X",0],["y","Crop Y",0],["width","Crop width",source.width],["height","Crop height",source.height]])coordinates[key]=field(cropFields,label,"number",c.crop?.[key]??value,{min:key==="x"||key==="y"?0:2,max:key==="x"||key==="width"?source.width:source.height,step:2,track:true});}
    const inherited=(c.envelope.from!==editPhaseFrame(c)||c.envelope.frames!==c.frames)&&(c.envelope.fadeIn||c.envelope.fadeOut),reanchor=inherited?field(settings,"Reanchor the inherited fades to this clip","checkbox",false,{track:true}):null;
    settings.append(node("p","Fades must total at most "+c.frames+" frames. Applying settings anchors them to this clip's output range."));if(inherited)settings.append(node("p","This clip currently preserves part of a longer fade after an edit. Review the new fade lengths and explicitly reanchor them before applying settings."));
    settings.append(button("Apply clip settings",()=>{const fi=number(fadeIn),fo=number(fadeOut);if(fi+fo>c.frames)throw new Error("Set fade lengths that total at most "+c.frames+" frames before applying settings.");if(reanchor&&!reanchor.checked)throw new Error("Review the fade lengths and check Reanchor the inherited fades to this clip.");return operation("Update "+c.lane+" settings",{kind:"settings",clipId:c.id,gainDb:gain?number(gain):c.gainDb,opacity:opacity?number(opacity):c.opacity,crop:crop?.checked?Object.fromEntries(Object.entries(coordinates).map(([key,input])=>[key,number(input)])):null,fadeIn:fi,fadeOut:fo});}));
  }
  function drawCrossfadeTools(tools,c){if(c.lane==='captions')return;const t=current.timeline,box=details('Crossfades between clips');box.dataset.draftGroup='transitions';tools.append(box);
    const neighbors=t.clips.filter(x=>x.id!==c.id&&x.lane===c.lane&&x.layer===c.layer),pairs=[...neighbors.filter(x=>x.at===c.at+c.frames).map(right=>({left:c,right})),...neighbors.filter(x=>x.at+x.frames===c.at).map(left=>({left,right:c}))];
    if(!pairs.length){box.append(node('p','Place two clips next to each other on this track to add a crossfade. Each source needs retained frames or samples beyond the cut.'));return;}
    const boundary=field(box,'Crossfade boundary','select','');options(boundary,pairs.map((p,i)=>[i,(p.left.id===c.id?'End':'Start')+' at '+time(p.right.at)+' · '+clipLabel(p.left)+' → '+clipLabel(p.right)]),0);
    const frames=field(box,'Crossfade duration (frames)','number',10,{min:1,max:t.frames,track:true}),alignment=field(box,'Crossfade alignment','select','',{track:true});options(alignment,[['center','Centered on cut'],['start','Starts at cut'],['end','Ends at cut']],'center');const linked=field(box,'Crossfade linked picture and sound','checkbox',true,{track:true}),saved=node('p');box.append(saved,node('p','Original clip timing stays saved. Crossfades borrow retained source handles, replace adjoining fades inside the transition, and preserve outer fades. Linked captions follow the audio handles. Listen for overlapping words.'));
    let selected=0;const controls=actions(),save=button('Save crossfade',()=>{const p=pairs[selected];return operation('Crossfade '+c.lane+' at '+time(p.right.at),editorialCrossfadeOperation(t,p.left.id,p.right.id,linked.checked,number(frames),alignment.value));}),remove=button('Remove crossfade',()=>{const p=pairs[selected];return operation('Restore hard cut at '+time(p.right.at),{kind:'remove-crossfade',leftId:p.left.id,rightId:p.right.id,linked:linked.checked});});controls.append(save,remove);box.append(controls);
    const display=()=>{const p=pairs[selected],x=t.transitions?.find(x=>x.leftId===p.left.id&&x.rightId===p.right.id);frames.value=String(x?.frames??10);alignment.value=x?.alignment??'center';remove.disabled=!x;saved.textContent=x?'Saved '+x.frames+'-frame crossfade. Save to change its duration or alignment; remove restores the original hard cut.':'This boundary currently uses a hard cut.';};boundary.onchange=()=>{if(dirty){boundary.value=String(selected);tell('Apply or discard the crossfade fields before choosing another boundary.',true);return;}selected=Number(boundary.value);display();};display();
  }
  function drawMaskTools(tools,c){
    maskEditor=mountMaskEditor({parent:tools,saved:current,clip:c,projectId:activeProject,loadSourceFrame:args=>loadMaskSourceFrame(previewClient(),args),canChange:group=>!busy&&(!dirty||dirtyGroup===group)&&!(pending&&!pending.jobId),
      onDirty(group,action){if(group===null){if(dirtyGroup==='composite'){dirty=false;dirtyGroup=null;refreshAssemblyGuards();for(const input of editor.querySelectorAll('[data-draft-group]'))if(input.matches('input,select'))input.disabled=false;}return;}dirty=true;refreshAssemblyGuards();dirtyGroup=group;preview.stop();review.replaceChildren();for(const input of editor.querySelectorAll('[data-draft-group]'))if(input.matches('input,select'))input.disabled=input.dataset.draftGroup!==group;primary(action);tell('Unsaved masks and mattes · apply or discard this draft before changing another edit group.');},
      onSave:value=>run(()=>operation('Update masks and mattes on picture '+c.layer,value)),onSavedPreview(sourceFrame){clean();const clock=new EditTime(c);let low=c.at,high=c.at+c.frames-1;while(low<high){const middle=Math.floor((low+high)/2);if(clock.frame(middle)<sourceFrame)low=middle+1;else high=middle;}preview.controller.seek(low,false);preview.panel.scrollIntoView({block:'nearest'});tell('Showing saved composite at timeline '+time(low)+' · original source frame '+clock.frame(low)+'.');}});
  }
  function drawMatteRoles(){
    const layers=[...new Set(current.timeline.clips.filter(c=>c.lane==='picture').map(c=>c.layer))].sort(),box=details('Picture track visibility and matte-only roles');box.dataset.draftGroup='matte-only';box.append(node('p','Matte-only tracks stay available to their consumers but do not draw into the final picture. These roles affect the whole saved timeline.'));const fields=[];
    for(const layer of layers){const clips=current.timeline.clips.filter(c=>c.lane==='picture'&&c.layer===layer),consumers=current.timeline.clips.filter(c=>c.composite?.matte?.layer===layer),input=field(box,'Use picture '+layer+' only as a matte','checkbox',current.timeline.matteOnlyLayers?.includes(layer),{track:true,group:'matte-only'});fields.push({layer,input});const ranges=details('Picture '+layer+' · '+clips.length+' ranges · '+consumers.length+' matte consumers');for(const c of clips)ranges.append(node('p',time(c.at)+'–'+time(c.at+c.frames)+' · '+current.timeline.sources.find(s=>s.id===c.sourceId).label));if(!consumers.length)ranges.append(node('p','No clip currently uses this track as a matte. Marking it matte-only hides its picture.'));box.append(ranges);}
    box.append(button('Save picture track roles',()=>operation('Update picture track matte-only roles',{kind:'matte-only',layers:fields.filter(f=>f.input.checked).map(f=>f.layer)})));editor.append(box);
  }
  function drawRetimeTools(tools,c){
    const box=details("Speed ramps and freeze frames"),time=new EditTime(c);box.dataset.draftGroup="retiming";tools.append(box);
    box.append(node("p","Speed changes also change audio pitch. Frozen audio is silent. Applying starts a new curve at the source frame below; undo restores the previous timing."));
    const mode=field(box,"Playback speed","select","",{track:true}),from=field(box,"Retime source in (frame)","number",c.from,{min:0,max:current.timeline.sources.find(s=>s.id===c.sourceId).frames-1,track:true}),frames=field(box,"Retime output length (frames)","number",c.frames,{min:1,max:108000,track:true}),rates=node("div");rates.dataset.draftGroup="retiming";box.append(rates);
    const start=field(rates,"Starting speed (%)","number",Math.round(time.speed(c.at*1600)*1000)/10,{min:0,max:800,step:.1,track:true}),end=field(rates,"Ending speed (%)","number",Math.round(time.speed((c.at+c.frames)*1600)*1000)/10,{min:0,max:800,step:.1,track:true}),points=details("Intermediate speed points"),rows=[];points.dataset.draftGroup="retiming";rates.append(points);
    const add=(frame,rate)=>{const row=node("div");row.dataset.draftGroup="retiming";points.append(row);const at=field(row,"Speed point output frame","number",frame,{min:1,max:108000,track:true}),speed=field(row,"Speed point (%)","number",rate/10,{min:0,max:800,step:.1,track:true}),entry={row,at,speed};rows.push(entry);row.append(button("Remove speed point",()=>{rows.splice(rows.indexOf(entry),1);row.remove();mode.oninput();}));};
    for(const p of c.timing?.points??[])if(p.frame>c.timing.offset&&p.frame<c.timing.offset+c.frames)add(p.frame-c.timing.offset,p.rate);
    points.append(button("Add speed point",()=>{if(rows.length>=30)throw new Error("Use at most thirty intermediate points.");add(Math.floor(number(frames)/2),Math.round(number(start)*10));mode.oninput();}));
    options(mode,[["normal","Normal speed"],["constant","Constant speed"],["ramp","Speed ramp"],["freeze","Freeze frame"]],c.timing?(time.maximumRate===0?"freeze":"ramp"):"normal");
    const display=()=>{rates.hidden=mode.value==="normal"||mode.value==="freeze";end.parentElement.hidden=mode.value!=="ramp";points.hidden=mode.value!=="ramp";};mode.onchange=display;display();
    const linked=field(box,"Retime linked clips together","checkbox",true,{track:true}),ripple=field(box,"Ripple after retiming","checkbox",true,{track:true});
    box.append(button("Apply playback timing",()=>{const length=number(frames),rate=["constant","ramp"].includes(mode.value)?Math.round(number(start)*10):0,curve=mode.value==="normal"?null:[{frame:0,rate},...(mode.value==="ramp"?rows.map(p=>({frame:number(p.at),rate:Math.round(number(p.speed)*10)})).sort((a,b)=>a.frame-b.frame):[]),{frame:length,rate:mode.value==="ramp"?Math.round(number(end)*10):rate}];return operation("Set "+c.lane+" playback to "+mode.value,{kind:"retime",clipId:c.id,linked:linked.checked,from:number(from),frames:length,points:curve,ripple:ripple.checked});}));
  }
  function drawTakeTools(tools,c){const box=details("Duplicate or replace this range"),copy=details("Duplicate range"),replace=details("Replace with another take");copy.dataset.draftGroup="duplicate";replace.dataset.draftGroup="replace";box.append(copy,replace);tools.append(box);
    const at=field(copy,"Copy at timeline frame","number",c.at+c.frames,{min:0,max:current.timeline.frames,track:true}),copyLinked=field(copy,"Copy linked clips together","checkbox",true,{track:true}),copyRipple=field(copy,"Ripple after copying","checkbox",true,{track:true});copy.append(button("Duplicate selected range",()=>{const targets=copyLinked.checked&&c.link?current.timeline.clips.filter(x=>x.link===c.link):[c];return operation("Duplicate "+c.lane+" range",{kind:"duplicate",clipId:c.id,linked:copyLinked.checked,at:number(at),ids:Object.fromEntries(targets.map(x=>[x.id,crypto.randomUUID()])),link:c.link&&copyLinked.checked?crypto.randomUUID():null,ripple:copyRipple.checked});}));
    replace.append(node("p","Add a retained original below if the new take is not listed. Replacement keeps the clip's position, identity and settings. A new duration anchors fades to the new range; the same duration preserves inherited fades."));const source=field(replace,"Replacement original","select","",{track:true});options(source,current.timeline.sources.map(s=>[s.id,s.label]),c.sourceId);const from=field(replace,"Replacement source in (frame)","number",c.from,{min:0,max:108000,track:true}),frames=field(replace,"Replacement output length (frames)","number",c.frames,{min:1,max:108000,track:true}),timing=field(replace,"Replacement playback timing","select","",{track:true});options(timing,[["preserve","Keep current speed curve"],["normal","Normal speed"]],"preserve");const linked=field(replace,"Replace linked clips together","checkbox",true,{track:true}),ripple=field(replace,"Ripple after replacement","checkbox",true,{track:true}),maskAction=field(replace,"Masks when changing the original","select","",{track:true});options(maskAction,[["","Choose if this changes a masked original"],["remove","Remove source-bound masks"],["rebind","Rebind masks and review every source key"]],"");replace.append(node("p","Changing a masked original requires an explicit choice. Rebinding preserves every keyframe and vertex; review them against the new picture. Matte and placement settings remain attached to the clip."));replace.append(button("Replace selected range",()=>operation("Replace "+c.lane+" with "+current.timeline.sources.find(s=>s.id===source.value).label,{kind:"replace",clipId:c.id,linked:linked.checked,sourceId:source.value,from:number(from),frames:number(frames),timing:timing.value,ripple:ripple.checked,...(maskAction.value?{maskAction:maskAction.value}:{})})));
  }
  function drawSourceTools(){const box=details("Add a retained original to this sequence"),source=field(box,"Retained version for this sequence","select",""),choices=node("div");options(source,index.sources.map(s=>[s.jobId,(s.label??s.stage)+" · "+s.jobId.slice(0,8)+" · "+(s.completedAt?new Date(s.completedAt).toLocaleString():"")]));box.append(node("p","Each sequence retains up to sixteen originals across its saved branches. Exports preserve all of them for later recovery."));const inspect=button("Inspect source for this sequence",async()=>{clean();tell("Checking retained picture, performances and captions…");const data=await request("/sources/"+source.value);choices.replaceChildren();for(const item of data.sources){const row=actions(),add=button("Add "+item.facts.label+" to sequence",async()=>{clean();const saved=savedEditorialSource(current,item);remember(saved);await sendSource(saved);});add.disabled=current.timeline.sources.some(s=>s.id===item.facts.id);row.append(node("span",item.facts.label+" · "+time(item.facts.frames)+" · "+item.language),add);choices.append(row);}tell("Source checked. Add an original, then replace or insert a range.");});inspect.disabled=!index.sources.length;box.append(inspect,choices);editor.append(box);}
  function drawInsert(){const box=details("Insert a source range");box.dataset.draftGroup="insert";const source=field(box,"Original source","select","",{track:true});options(source,current.timeline.sources.map(s=>[s.id,s.label]));const from=field(box,"Source in (frame)","number",0,{min:0,max:108000,track:true}),frames=field(box,"Length (frames)","number",30,{min:1,max:108000,track:true}),at=field(box,"Insert at timeline frame","number",current.timeline.frames,{min:0,max:108000,track:true}),layer=field(box,"Picture layer","number",0,{min:0,max:3,track:true}),audio=field(box,"Audio to insert","select","",{track:true});options(audio,[["mix","Original mix"],["separate","Available isolated lanes"],["none","No audio"]]);const picture=field(box,"Include picture","checkbox",true,{track:true}),captions=field(box,"Include captions","checkbox",true,{track:true}),ripple=field(box,"Ripple following ranges","checkbox",true,{track:true});
    let timingTouched=false;for(const input of [from,frames])input.addEventListener("input",()=>{timingTouched=true;});source.onchange=()=>{const s=current.timeline.sources.find(s=>s.id===source.value),graphic=s.media==="graphic-rgba";audio.parentElement.hidden=captions.parentElement.hidden=graphic;from.max=String(s.frames-1);frames.max=String(s.frames);if(!timingTouched){from.value="0";frames.value=String(Math.min(30,s.frames));}};source.onchange();
    box.append(button("Insert linked range",()=>{const s=current.timeline.sources.find(s=>s.id===source.value),start=number(from),length=number(frames),position=number(at),lanes=[...(picture.checked?["picture"]:[]),...(s.media==="graphic-rgba"?[]:audio.value==="mix"?["mix"]:audio.value==="separate"?s.audio.filter(l=>l!=="mix"):[]),...(s.media!=="graphic-rgba"&&captions.checked?["captions"]:[])],link=lanes.length>1?crypto.randomUUID():null;if(!lanes.length)throw new Error("Choose picture, audio or captions to insert.");return operation("Insert "+s.label+" at frame "+position,{kind:"insert",clips:lanes.map(lane=>({id:crypto.randomUUID(),sourceId:s.id,lane,layer:lane==="picture"?number(layer):0,link,at:position,from:start,frames:length,gainDb:0,opacity:1,crop:null,envelope:{from:start,frames:length,fadeIn:0,fadeOut:0}})),...(ripple.checked?{rippleAt:position,rippleFrames:length}:{})});}));editor.append(box);
  }
  function drawSequenceTools(){const box=details("Sequence name, duration and markers"),name=field(box,"Sequence name","text",current.sequence.label,{track:true,group:"name"}),duration=field(box,"Sequence duration (frames)","number",current.timeline.frames,{min:1,max:108000,track:true,group:"duration"}),label=field(box,"Marker label","text","",{track:true,group:"marker"}),frame=field(box,"Marker frame","number",0,{min:0,max:current.timeline.frames,track:true,group:"marker"}),controls=actions();controls.append(button("Save sequence name",()=>change({kind:"rename",label:name.value},"name")),button("Set sequence duration",()=>operation("Set duration to "+number(duration)+" frames",{kind:"duration",frames:number(duration)})),button("Add marker",()=>operation("Add marker: "+label.value,{kind:"marker",marker:{id:crypto.randomUUID(),frame:number(frame),label:label.value}})));box.append(controls);for(const marker of current.timeline.markers){const row=actions();row.append(node("span",time(marker.frame)+" · "+marker.label),button("Remove marker "+marker.label,()=>operation("Remove marker: "+marker.label,{kind:"remove-marker",id:marker.id})));box.append(row);}editor.append(box);}
  async function reviewExport(){clean();const quote=await request("/sequences/"+current.sequence.id+"/renders");if(quote.sequence.historyRevision!==current.sequence.history.revision)throw new Error("This sequence changed in another window. Refresh saved state before reviewing its export.");review.replaceChildren(node("h3","Step 2 of 3 · Review this export"),node("p",time(quote.sequence.frames)+" · "+quote.sequence.width+" × "+quote.sequence.height+" · no new provider generation"));
    const compositing=editorialMaskReview(current,quote);
    const ids=[...new Set([...quote.speechCuts.map(c=>c.clipId),...quote.unmeasuredAudioCuts])];if(!ids.length)review.append(node("p","No partial measured voice windows or trimmed unmeasured audio were found. Listen to the rendered result before selecting it."));else{const warnings=details("Review speech boundaries · "+ids.length+" affected clips");warnings.open=true;for(const id of ids){const c=current.timeline.clips.find(c=>c.id===id),cuts=quote.speechCuts.filter(c=>c.clipId===id),group=details((c?clipLabel(c):id)+" · "+cuts.length+" measured boundaries"),list=node("ul");for(const cut of cuts){const voice=current.timeline.sources.find(s=>s.id===c?.sourceId)?.voices.find(v=>v.id===cut.voiceId);list.append(node("li","Cuts the "+(cut.edge==="in"?"start":"end")+" of "+(voice?voice.lane+" at source "+(voice.start/48000).toFixed(3)+"–"+(voice.end/48000).toFixed(3)+" s":"measured voice "+cut.voiceId)+"."));}if(quote.unmeasuredAudioCuts.includes(id))group.append(node("p","Edits audio without measured speech timing. Listen for cut words."));group.append(list);warnings.append(group);}review.append(warnings);}
    if(current.timeline.clips.some(c=>c.timing))review.append(node("p","This edit includes changed playback timing. Speed changes affect audio pitch; freeze frames mute the held sound. Listen to the retimed performances before selecting the export."));
    if(quote.crossfades?.length){const crossfades=details('Review crossfades · '+quote.crossfades.length+' tracks');crossfades.open=true;crossfades.append(node('p','Transitions borrow original source handles. Review overlapping speech and captions in playback before choosing this export.'));
      for(const x of quote.crossfades){const group=details(x.lane+' · '+time(x.at)+'–'+time(x.at+x.frames)+' · '+x.frames+' frames');for(const [i,c]of x.clips.entries()){const list=node('ul'),source=current.timeline.sources.find(s=>s.id===c.sourceId);list.append(node('li',(i===0?'Outgoing':'Incoming')+' · '+(source?.label??'Retained original')+' · source '+(c.from/48000).toFixed(3)+'–'+(c.end/48000).toFixed(3)+' s'));for(const voice of c.voices)list.append(node('li','Fades across '+voice.lane+' at source '+(voice.start/48000).toFixed(3)+'–'+(voice.end/48000).toFixed(3)+' s.'));if(c.unmeasured)list.append(node('li','Speech timing is unknown. Listen for overlapping or cut words.'));if(x.lane!=='picture')list.append(node('li',c.captionsFollow?'Linked captions follow these borrowed audio handles.':'Captions are independent of this audio clip. Review their timing through the transition.'));group.append(list);}crossfades.append(group);}review.append(crossfades);}
    const composites=current.timeline.clips.filter(c=>c.composite);if(composites.length||current.timeline.matteOnlyLayers?.length){const effects=details('Review saved masks and mattes');effects.open=true;effects.append(node('p','This review follows the saved timeline revision. Masks use original source frames; each matte track keeps its own timeline timing.'));for(const c of composites){const setup=c.composite,item=details(clipLabel(c)),list=node('ul');for(const mask of setup.masks??[])list.append(node('li',mask.label+' · '+mask.kind+' · '+mask.combine+(mask.invert?' · inverted':'')+' · '+mask.featherQ8/256+' px feather · '+mask.keyframes.length+' source keys ('+mask.keyframes[0].sourceFrame+'–'+mask.keyframes.at(-1).sourceFrame+').'));if(setup.matte)list.append(node('li','Matte: picture '+setup.matte.layer+' · '+setup.matte.channel+(setup.matte.invert?' · inverted, including track gaps':'')));if(setup.placement)list.append(node('li','Placement: '+(setup.placement.scaleQ16/655.36).toFixed(2)+'% scale · '+setup.placement.rotationMilliDegrees/1000+'° clockwise · offset '+(setup.placement.xQ16/655.36).toFixed(2)+'%, '+(setup.placement.yQ16/655.36).toFixed(2)+'%.'));item.append(list);effects.append(item);}if(current.timeline.matteOnlyLayers?.length)effects.append(node('p','Matte-only picture tracks: '+current.timeline.matteOnlyLayers.join(', ')+'.'));if(compositing?.warnings.length){const warnings=node('ul');for(const warning of compositing.warnings)warnings.append(node('li',warning));effects.append(node('h4','Saved composition warnings'),warnings);}review.append(effects);}
    const storage=details("Storage and retained sources");storage.append(node("p","Estimated export: "+(quote.resources.outputBytes/1024**3).toFixed(2)+" GiB · working space: "+(quote.resources.workspaceBytes/1024**3).toFixed(2)+" GiB. The worker checks its available disk before processing."));for(const source of quote.sources)storage.append(node("p",source.facts.label+" · retained until "+new Date(source.expiresAt).toLocaleString()));review.append(storage);
    const approved=field(review,"I reviewed these cuts and want to render this saved edit","checkbox",false),render=button("Render reviewed edit",async()=>{clean();if(!approved.checked)throw new Error("Review the listed cuts and check the export confirmation.");remember({kind:"render",sequenceId:current.sequence.id,body:{idempotencyKey:crypto.randomUUID(),generationApproved:true,historyRevision:quote.sequence.historyRevision,sourceBindingsRevision:quote.sourceBindingsRevision,engineVersion:quote.engineVersion,review:{...quote.review,accepted:true}}});await submitRender();});render.disabled=Boolean(quote.unavailable);if(quote.unavailable)review.append(node("p",quote.unavailable));review.append(render);primary(render);review.scrollIntoView({block:"nearest",behavior:"smooth"});tell("Review the speech boundaries and confirm this export.");
  }
  async function submitRender(){if(!pending||pending.kind!=="render")throw new Error("No saved export request is waiting.");if(!pending.jobId){tell("Submitting the reviewed export…");try{const admitted=await request("/sequences/"+pending.sequenceId+"/renders",{method:"POST",body:pending.body});remember({...pending,jobId:admitted.jobId});review.replaceChildren();}catch(error){if(error.status&&error.status<500)remember(null);throw error;}}await show(pending.jobId);await refreshIndex(false);}
  function drawVersions(){const previous=[...versions.querySelectorAll("select")].map(e=>e.value);versions.replaceChildren(node("summary","Rendered versions and comparison"));const jobs=index?.jobs??[];if(!jobs.length){versions.append(node("p","Rendered edits will appear here, including earlier branches."));return;}const select=field(versions,"Rendered edit","select","");options(select,jobs.map(j=>[j.id,j.pictureEdit.label+" · "+j.status+" · "+j.id.slice(0,8)]),jobs.some(j=>j.id===previous[0])?previous[0]:jobs.at(-1)?.id);const controls=actions();controls.append(button("Open rendered version",()=>{clean();return show(select.value);}));const completed=jobs.filter(j=>j.status==="done"&&j.output),other=field(versions,"Compare with another completed edit","select","");options(other,completed.map(j=>[j.id,j.pictureEdit.label+" · "+j.id.slice(0,8)]),completed.some(j=>j.id===previous[1])?previous[1]:completed[0]?.id);const comparison=button("Compare these versions",()=>{clean();if(select.value===other.value)throw new Error("Choose two different completed versions.");return compare(select.value,other.value);});comparison.disabled=completed.length<2;controls.append(comparison);versions.append(controls);}
  function player(container,job){const video=node("video");video.controls=true;video.preload="metadata";video.playsInline=true;video.src=assetUrl(job.output.mp4Url);video.setAttribute("aria-label",job.pictureEdit.label+" rendered version "+job.id.slice(0,8));if(job.output.captionsUrl){const track=node("track");track.kind="captions";track.label="Captions";track.srclang=job.captionLanguage||"en";track.src=assetUrl(job.output.captionsUrl);video.append(track);}container.append(video);return video;}
  async function show(id){clearTimeout(watchTimer);watched=id;const attempt=++playbackSerial;stop(playback);playback.replaceChildren();const job=await jobRequest(id);if(watched!==id||panel.hidden||attempt!==playbackSerial)return;if(index){const previous=index.jobs.find(j=>j.id===id);if(!previous||previous.status!==job.status||Boolean(previous.output)!==Boolean(job.output)){index.jobs=[...index.jobs.filter(j=>j.id!==id),job];drawVersions();}}playback.append(node("h3","Step 3 of 3 · "+job.pictureEdit.label+" · "+job.status));versions.open=true;
    if(job.status!=="done"){playback.append(node("p",job.failureReason||job.cancelReason||"This saved export is "+job.status+". You can keep editing; this render retains the reviewed version."));if(["failed","cancelled"].includes(job.status)){if(pending?.jobId===id)remember(null);}else watchTimer=setTimeout(()=>{if(!panel.hidden&&watched===id)show(id).catch(e=>tell(e.message,true));},1500);return;}
    if(pending?.jobId===id)remember(null);if(!job.output){playback.append(node("p",job.mediaUnavailable||"This retained version is unavailable."));return;}player(playback,job);if(current?.sequence.id===job.pictureEdit.sequenceId&&current.sequence.history.revision!==job.pictureEdit.historyRevision)playback.append(node("p","This rendered version predates the current saved edits."));
    const links=actions();for(const [key,label]of [["mp4Url","Download MP4"],["deliveryMasterUrl","Master WAV"],["captionsUrl","Captions"],["timelineUrl","Timeline"],["conformReportUrl","Conform report"],["manifestUrl","Provenance"]])if(job.output[key]){const a=node("a",label);a.className="button-link";a.href=assetUrl(job.output[key]);links.append(a);}playback.append(links);
    if(selection.entries.at(-1)?.jobId===id)playback.append(node("p","This is the selected project export."));else{const use=button("Use this version as export",async()=>{const saved=await adopt({jobId:id,sourceJobId:job.pictureEdit.sequenceId,expectedVersion:selection.version,expectedOutputRevision:job.outputRevision});selection=saved.dialogueSelections;await show(id);tell("Export selected. Earlier rendered versions remain available for comparison or rollback.");});playback.append(use);primary(use);}tell("Rendered edit is ready. Play it through before selecting the project export.");
  }
  async function compare(a,b){clearTimeout(watchTimer);watched=null;const attempt=++playbackSerial,openedProject=activeProject,jobs=await Promise.all([jobRequest(a),jobRequest(b)]);if(panel.hidden||attempt!==playbackSerial||openedProject!==projectId())return;if(jobs.some(j=>j.status!=="done"||!j.output))throw new Error("Both versions must be completed and available.");const cuts=await Promise.all(jobs.map(job=>request('/versions/'+encodeURIComponent(job.id)+'?outputRevision='+encodeURIComponent(job.outputRevision))));if(panel.hidden||attempt!==playbackSerial||openedProject!==projectId())return;stop(playback);playback.replaceChildren(node("h3","Compare rendered edits"));comparison=mountEditorialComparison({parent:playback,client:previewClient,current:()=>!busy&&!panel.hidden&&attempt===playbackSerial&&openedProject===projectId(),cuts});primary(comparison.playButton);tell("Comparison ready. Choose the soundtrack and press Play to prepare both saved versions.");}
  async function open(){if(activeProject!==projectId()){preview.bind(null);scriptNavigation.bind(null);assemblyPreview.bind(null);assemblyStudio.bind(null);clearTimeout(watchTimer);watched=null;playbackSerial++;stop(playback);}if(busy){tell("The current request is still processing. Wait for its result before reopening picture editorial.");return;}if(activeProject===projectId()&&(assemblyStudio.unsaved||assemblyStudio.pending)){panel.hidden=false;assemblyStudio.bind(current);tell("Your assembly draft or saved request is still open. Resolve it before refreshing the parent editor.",true);return;}if(!canEdit()){panel.hidden=false;tell("Save or discard the other open edit before opening picture editorial.",true);return;}if(activeProject===projectId()&&dirty){panel.hidden=false;tell("Your unsaved fields are still open. Apply or discard them first.",true);return;}if(activeProject!==projectId()){playback.replaceChildren();editor.replaceChildren();review.replaceChildren();current=null;selectedClip=null;dirty=false;dirtyGroup=null;bin=[];creationDraft={label:"New assembly",dimensions:"1280x720",width:1280,height:720};}activeProject=projectId();panel.hidden=false;scriptNavigation.bind(current);await run(async()=>{try{pending=JSON.parse(localStorage.getItem("hv-editorial-pending:"+activeProject)||"null");if(pending&&!(["edit","source","render","create"].includes(pending.kind)&&typeof pending.sequenceId==="string"&&pending.body))pending=null;}catch{pending=null;}await refreshIndex();drawPending();if(pending?.jobId)await show(pending.jobId);else if(!pending&&!current&&index.sequences.length)await load(index.sequences[0].id);else tell("Choose a saved sequence or inspect a retained original to create one.");});}
  window.addEventListener("beforeunload",event=>{if(dirty||busy||creationDirty()||pending&&!pending.jobId||assemblyStudio.unsaved||assemblyStudio.pending){event.preventDefault();event.returnValue="";}});
  return {open,get unsaved(){return dirty||busy||creationDirty()||Boolean(pending&&!pending.jobId)||assemblyStudio.unsaved||Boolean(assemblyStudio.pending);},get previewStats(){return preview.controller.stats;},get comparisonStats(){return comparison?.controller.stats??null;}};
}
