const same=(a,b)=>{const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==="object"?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;return JSON.stringify(canonical(a))===JSON.stringify(canonical(b));};
export function savedEditorialEdit(current,change){const history=current.sequence.history;return {kind:"edit",sequenceId:current.sequence.id,eventCount:history.events.length,previousEventRevision:history.events.at(-1)?.revision??history.root.revision,body:{expectedVersion:current.libraryVersion,expectedHistoryRevision:history.revision,change}};}
export function matchesSavedEditorialEdit(actual,saved){if(actual.sequence.id!==saved.sequenceId)return false;const change=saved.body.change;if(change.kind==="rename")return actual.sequence.label===change.label.trim()&&actual.libraryVersion>saved.body.expectedVersion;const event=actual.sequence.history.events[saved.eventCount];return Boolean(event&&event.previousRevision===saved.previousEventRevision&&event.kind===change.kind&&event.label===change.label&&(change.kind==="edit"?same(event.operation,change.operation):event.target===change.target&&event.reason===change.reason));}
/** Every edit is a saved history event. Playback uses a verified rendered version. */
export function initEditorial({parent,request,jobRequest,projectState,projectId,assetUrl,canEdit,adopt}) {
  const node=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
  const details=label=>{const e=node("details");e.append(node("summary",label));return e;};
  const actions=()=>{const e=node("div");e.className="result-actions";return e;};
  const panel=node("section"),status=node("p"),pendingBox=node("div"),navigation=node("div"),creation=details("Create a sequence from retained originals"),editor=node("div"),review=node("div"),versions=details("Rendered versions and comparison"),playback=node("div");
  panel.className="motion-workbench editorial-studio";panel.hidden=true;status.className="status";status.setAttribute("role","status");
  panel.append(node("h2","Picture editorial"),node("p","Arrange retained picture and performances, save each change, and render an independent export. The timeline shows saved timing; use a rendered version to see and hear the assembled cut."),status,pendingBox,navigation,creation,editor,review,versions,playback);parent.append(panel);
  let activeProject=null,index=null,current=null,selectedClip=null,dirty=false,dirtyGroup=null,busy=false,serial=0,bin=[],pending=null,reviewButton=null,selection={version:0,entries:[]},watchTimer=null,watched=null;
  let creationDraft={label:"New assembly",dimensions:"1280x720",width:1280,height:720};
  let playbackSerial=0;
  const creationDirty=()=>bin.length>0||creationDraft.label!=="New assembly"||creationDraft.dimensions!=="1280x720"||Number(creationDraft.width)!==1280||Number(creationDraft.height)!==720;
  const tell=(message,error=false)=>{status.textContent=message;status.dataset.state=error?"error":"success";};
  const time=frames=>{const seconds=Math.floor(frames/30);return Math.floor(seconds/60)+":"+String(seconds%60).padStart(2,"0")+":"+String(frames%30).padStart(2,"0");};
  const clean=()=>{if(dirty)throw new Error("Apply or discard the unsaved fields before switching views.");if(pending&&!pending.jobId)throw new Error("Resolve the saved request before making another change.");};
  const button=(label,action)=>{const e=node("button",label);e.type="button";e.className="secondary";e.onclick=()=>run(action);return e;};
  const primary=e=>{for(const b of panel.querySelectorAll("button"))b.classList.add("secondary");e?.classList.remove("secondary");};
  async function run(action){if(busy)return;if(activeProject!==projectId()){tell("The open project changed. Reopen picture editorial.",true);return;}busy=true;panel.setAttribute("aria-busy","true");const controls=[...panel.querySelectorAll("button,input,select,textarea")],disabled=controls.map(e=>e.disabled);controls.forEach(e=>e.disabled=true);try{await action();}catch(error){tell(error.message||"This request could not finish. Your saved sequence is retained.",true);}finally{busy=false;controls.forEach((e,i)=>e.disabled=disabled[i]);panel.removeAttribute("aria-busy");drawPending();}}
  function field(container,label,type,value,{min,max,step=1,track=false,group}={}){const wrap=node("div"),caption=node("label",label),e=node(type==="select"?"select":"input");wrap.className="cast-field";e.id="edit-field-"+(++serial);caption.htmlFor=e.id;if(type!=="select")e.type=type;if(type==="checkbox")e.checked=Boolean(value);else e.value=value??"";if(type==="number"){e.step=String(step);if(min!==undefined)e.min=String(min);if(max!==undefined)e.max=String(max);}if(track){e.dataset.draftGroup=group??container.dataset.draftGroup??"timing";e.oninput=()=>{dirty=true;dirtyGroup=e.dataset.draftGroup;for(const input of editor.querySelectorAll("[data-draft-group]"))if(input.matches("input,select"))input.disabled=input.dataset.draftGroup!==dirtyGroup;review.replaceChildren();primary(reviewButton);tell("Unsaved fields · apply this change or discard these fields before editing another group.");};}wrap.append(caption,e);container.append(wrap);return e;}
  function number(e){if(e.value.trim()===""||!e.checkValidity()||!Number.isFinite(Number(e.value))){e.reportValidity();throw new Error("Enter a value within the displayed range.");}return Number(e.value);}
  function options(e,items,value){e.replaceChildren(...items.map(([id,label])=>new Option(label,String(id))));if(value!==undefined)e.value=String(value);}
  function stop(container){for(const video of container.querySelectorAll("video,audio")){video.pause();video.removeAttribute("src");video.load();}}
  function remember(value){pending=value;try{const key="hv-editorial-pending:"+activeProject;if(value)localStorage.setItem(key,JSON.stringify(value));else localStorage.removeItem(key);}catch{/* Keep the request in this open editor when local storage is unavailable. */}drawPending();}
  function drawPending(){pendingBox.replaceChildren();if(!pending)return;if(busy){pendingBox.append(node("p","Processing the saved request…"));return;}const label=pending.jobId?"A reviewed edit is queued or rendering.":"A saved request needs its result checked.";pendingBox.append(node("p",label),button(pending.jobId?"Check render status":"Retry the same saved request",()=>pending.kind==="edit"?sendEdit(pending):pending.kind==="create"?sendCreate(pending):submitRender()));}
  async function sendEdit(saved){tell("Saving edit history…");let response;try{response=await request("/sequences/"+saved.sequenceId,{method:"PATCH",body:saved.body});}catch(error){let checked=false;
      try{const actual=await request("/sequences/"+saved.sequenceId);checked=true;if(matchesSavedEditorialEdit(actual,saved))response=actual;}catch{/* Keep an uncertain request available for the same-key retry. */}
      if(!response){if(checked&&error.status&&error.status<500)remember(null);throw error;}
    }remember(null);current=response;dirty=false;dirtyGroup=null;drawEditor();await refreshIndex(false);tell("Saved · "+saved.body.change.label+". The earlier history is available for undo or another branch.");}
  async function change(change,group){if(pending&&!pending.jobId)throw new Error("Resolve the saved request first.");if(dirty&&dirtyGroup!==group)throw new Error("Apply or discard the fields already being edited first.");const saved=savedEditorialEdit(current,change);remember(saved);await sendEdit(saved);}
  const operation=(label,value)=>change({kind:"edit",label,operation:value},value.kind==="settings"?"settings":value.kind==="insert"?"insert":value.kind==="duration"?"duration":["marker","remove-marker"].includes(value.kind)?"marker":"timing");
  async function load(id){clean();clearTimeout(watchTimer);watched=null;playbackSerial++;stop(playback);playback.replaceChildren();review.replaceChildren();current=await request("/sequences/"+id);selectedClip=current.timeline.clips.find(c=>c.lane==="picture")?.id??current.timeline.clips[0]?.id??null;dirty=false;dirtyGroup=null;drawEditor();tell("Step 1 of 3 · Edit the saved sequence, then review its export.");}
  async function refreshIndex(draw=true){index=await request("");selection=(await projectState()).dialogueSelections??{version:0,entries:[]};if(current)current.libraryVersion=index.libraryVersion;if(draw)drawNavigation();else{const select=navigation.querySelector("select");if(select)options(select,index.sequences.map(s=>[s.id,s.label+" · "+time(s.frames)]),current?.sequence.id??select.value);}drawVersions();return index;}
  function drawNavigation(){navigation.replaceChildren();const select=field(navigation,"Saved sequence","select","");options(select,index.sequences.map(s=>[s.id,s.label+" · "+time(s.frames)]),current?.sequence.id);const controls=actions(),open=button("Open sequence",()=>load(select.value));open.disabled=!index.sequences.length;controls.append(open,button("Refresh saved state",async()=>{clean();await refreshIndex();if(current)await load(current.sequence.id);}),button("Close picture editorial",()=>{clean();if(creationDirty())throw new Error("Create or discard the new-sequence draft before closing picture editorial.");stop(playback);clearTimeout(watchTimer);watched=null;panel.hidden=true;}));navigation.append(controls);drawCreation();}
  async function sendCreate(saved){tell("Creating the saved sequence…");let response;try{response=await request("/sequences",{method:"POST",body:saved.body});}catch(error){let checked=false;try{const actual=await request("/sequences/"+saved.sequenceId);checked=true;if(actual.sequence.label===saved.body.label.trim()&&same(actual.sequence.sourceRevisions.slice().sort(),saved.body.sources.map(s=>s.sourceRevision).sort())&&actual.sequence.history.root.width===saved.body.width&&actual.sequence.history.root.height===saved.body.height&&actual.sequence.history.root.clips.find(c=>c.lane==="picture")?.sourceId===saved.body.firstSourceId)response=actual;}catch(checkError){checked=checkError.status===404;}if(!response){if(checked&&error.status&&error.status<500)remember(null);throw error;}}
    remember(null);current=response;selectedClip=response.timeline.clips.find(c=>c.lane==="picture")?.id??null;bin=[];creationDraft={label:"New assembly",dimensions:"1280x720",width:1280,height:720};creation.open=false;await refreshIndex();drawEditor();tell("Sequence created. Every applied edit will be saved in its history.");
  }
  function drawCreation(){creation.replaceChildren(node("summary","Create a sequence from retained originals"));const source=field(creation,"Retained version","select","");options(source,index.sources.map(s=>[s.jobId,s.stage+" · "+s.jobId.slice(0,8)+" · "+(s.completedAt?new Date(s.completedAt).toLocaleString():"")]));const choices=node("div"),binView=node("div"),name=field(creation,"New sequence name","text",creationDraft.label),dimensions=field(creation,"Export dimensions","select","");options(dimensions,[["640x360","640 × 360"],["1280x720","1280 × 720"],["1920x1080","1920 × 1080"],["custom","Custom dimensions"]],creationDraft.dimensions);name.oninput=()=>{creationDraft.label=name.value;};const custom=node("div"),width=field(custom,"Export width","number",creationDraft.width,{min:16,max:1920,step:2}),height=field(custom,"Export height","number",creationDraft.height,{min:16,max:1080,step:2});custom.hidden=dimensions.value!=="custom";dimensions.onchange=()=>{creationDraft.dimensions=dimensions.value;custom.hidden=dimensions.value!=="custom";};width.oninput=()=>{creationDraft.width=width.value;};height.oninput=()=>{creationDraft.height=height.value;};creation.append(custom);
    const drawBin=()=>{binView.replaceChildren(node("p",bin.length+" of 16 originals selected. The first starts the sequence; insert other originals from the clip tools."));for(const item of bin){const row=actions();row.append(node("span",item.facts.label+" · "+time(item.facts.frames)),button("Remove "+item.facts.label,()=>{bin=bin.filter(b=>b.sourceRevision!==item.sourceRevision);drawBin();}));binView.append(row);}};
    const inspect=button("Inspect this version",async()=>{clean();tell("Checking original picture, performances and captions…");const data=await request("/sources/"+source.value);choices.replaceChildren();for(const item of data.sources){const row=actions(),add=button("Add "+item.facts.label,()=>{if(bin.some(b=>b.facts.id===item.facts.id))throw new Error("This original is already selected.");if(bin.length>=16)throw new Error("A sequence can bind up to sixteen originals.");bin.push(item);drawBin();});row.append(node("span",item.facts.label+" · "+time(item.facts.frames)+" · "+item.language),add);choices.append(row);}tell("Source checked. Add the originals for this sequence.");});inspect.disabled=!index.sources.length;
    const create=button("Create sequence",async()=>{clean();if(!bin.length)throw new Error("Inspect and add a retained original first.");const [w,h]=dimensions.value==="custom"?[number(width),number(height)]:dimensions.value.split("x").map(Number),id=crypto.randomUUID(),saved={kind:"create",sequenceId:id,body:{id,label:name.value,sources:bin.map(b=>({jobId:b.jobId,sourceRevision:b.sourceRevision})),firstSourceId:bin[0].facts.id,width:w,height:h,expectedVersion:index.libraryVersion}};remember(saved);await sendCreate(saved);});const controls=actions();controls.append(create,button("Discard new-sequence draft",()=>{if(pending?.kind==="create")throw new Error("Resolve the saved create request first.");bin=[];creationDraft={label:"New assembly",dimensions:"1280x720",width:1280,height:720};drawCreation();tell("New-sequence draft discarded. Saved sequences remain available.");}));creation.append(inspect,choices,binView,controls);drawBin();if(!current)primary(create);}
  function drawTimeline(container){const t=current.timeline,svg=document.createElementNS("http://www.w3.org/2000/svg","svg"),rows=[...new Set(t.clips.map(c=>c.lane==="picture"?"picture "+c.layer:c.lane))].sort((a,b)=>["picture 0","picture 1","picture 2","picture 3","mix","dialogue","narration","music","ambience","effects","captions"].indexOf(a)-["picture 0","picture 1","picture 2","picture 3","mix","dialogue","narration","music","ambience","effects","captions"].indexOf(b));
    svg.setAttribute("viewBox","0 0 1000 "+(40+rows.length*42));svg.setAttribute("role","img");svg.setAttribute("aria-label","Saved timeline with "+t.clips.length+" clips, "+rows.length+" tracks, and duration "+time(t.frames)+" at thirty frames per second");
    const shape=(tag,attrs,text)=>{const e=document.createElementNS(svg.namespaceURI,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;svg.append(e);return e;};
    for(let i=0;i<=4;i++)shape("text",{x:130+i*215,y:17,fill:"currentColor","font-size":20,"text-anchor":i===4?"end":"start"},time(Math.round(t.frames*i/4)));
    rows.forEach((lane,i)=>{const y=32+i*42;shape("text",{x:4,y:y+23,fill:"currentColor","font-size":20},lane);shape("rect",{x:130,y,width:860,height:32,fill:"#17232c"});for(const c of t.clips.filter(c=>(c.lane==="picture"?"picture "+c.layer:c.lane)===lane)){const rect=shape("rect",{x:130+c.at/t.frames*860,y:y+3,width:Math.max(.5,c.frames/t.frames*860),height:26,fill:c.id===selectedClip?"#efb75c":c.lane==="picture"?"#797bca":c.lane==="captions"?"#b58bba":"#4a9992",stroke:c.id===selectedClip?"#fff":"none"});const title=document.createElementNS(svg.namespaceURI,"title");title.textContent=clipLabel(c);rect.append(title);}});
    for(const marker of t.markers)shape("line",{x1:130+marker.frame/t.frames*860,x2:130+marker.frame/t.frames*860,y1:23,y2:40+rows.length*42,stroke:"#eee","stroke-dasharray":"3 3"});const viewport=node("div");viewport.className="editorial-timeline";viewport.append(svg);container.append(viewport,node("p","Timecode is minutes:seconds:frames at 30 fps. Select a clip below for exact frame controls. Higher picture layers cover lower layers."));
  }
  function clipLabel(c){const source=current.timeline.sources.find(s=>s.id===c.sourceId);return c.lane+(c.lane==="picture"?" "+c.layer:"")+" · "+(source?.label??c.sourceId)+" · "+time(c.at)+"–"+time(c.at+c.frames)+" · "+c.id.slice(0,16);}
  function drawEditor(){editor.replaceChildren();review.replaceChildren();if(!current)return;const t=current.timeline;editor.append(node("h3",current.sequence.label),node("p",time(t.frames)+" · "+t.width+" × "+t.height+" · saved branch "+current.head));drawTimeline(editor);
    const toolbar=actions(),undo=button("Undo saved edit",()=>{clean();return change({kind:"cursor",reason:"undo",target:current.parent,label:"Undo to prior edit"});});undo.disabled=current.parent===null;reviewButton=button("Review export",reviewExport);toolbar.append(undo,button("Discard unsaved fields",()=>{if(pending&&!pending.jobId)throw new Error("Resolve the saved request first.");dirty=false;dirtyGroup=null;drawEditor();tell("Unsaved fields discarded. Saved history is unchanged.");}),reviewButton);editor.append(toolbar);
    const history=details("Redo and branch history"),branch=field(history,"Saved branch","select","");options(branch,[[0,"Original sequence"],...current.sequence.history.events.filter(e=>e.kind==="edit").map(e=>[e.sequence,e.sequence+" · "+e.label])],current.head);history.append(button("Open this branch",()=>{clean();return change({kind:"cursor",reason:current.children.includes(Number(branch.value))?"redo":"branch",target:Number(branch.value),label:"Open saved branch "+branch.value});}));editor.append(history);
    const choose=field(editor,"Selected clip","select","");options(choose,t.clips.map(c=>[c.id,clipLabel(c)]),t.clips.some(c=>c.id===selectedClip)?selectedClip:t.clips[0]?.id);selectedClip=choose.value||null;choose.onchange=()=>{if(dirty){choose.value=selectedClip;tell("Apply or discard the current fields before choosing another clip.",true);return;}selectedClip=choose.value;drawEditor();};
    const c=t.clips.find(c=>c.id===selectedClip);if(c)drawClipTools(c);drawInsert();drawSequenceTools();primary(reviewButton);
  }
  function drawClipTools(c){const tools=node("div");tools.className="editorial-tools";editor.append(tools);const basic=details("Split, move and trim"),advanced=details("Slip, roll, slide and remove"),settings=details("Levels, opacity, crop and fades");basic.dataset.draftGroup="timing";advanced.dataset.draftGroup="timing";settings.dataset.draftGroup="settings";basic.open=true;tools.append(basic,advanced,settings);
    basic.append(node("p","Source frames "+c.from+"–"+(c.from+c.frames)+" · "+(c.link?"Linked to picture/audio/caption clips":"Unlinked clip")));const linked=field(basic,"Apply timing changes to linked clips","checkbox",true,{track:true}),ripple=field(basic,"Ripple following ranges","checkbox",true,{track:true}),frame=field(basic,"Timeline frame for split or move","number",c.at+Math.floor(c.frames/2),{min:0,max:current.timeline.frames,track:true}),basicActions=actions();
    const split=button("Split at frame",()=>{const targets=linked.checked&&c.link?current.timeline.clips.filter(x=>x.link===c.link):[c];return operation("Split "+c.lane+" at frame "+number(frame),{kind:"split",clipId:c.id,linked:linked.checked,at:number(frame),rightIds:Object.fromEntries(targets.map(x=>[x.id,crypto.randomUUID()])),rightLink:c.link&&linked.checked?crypto.randomUUID():null});});split.disabled=c.frames<2;basicActions.append(split,button("Move to frame",()=>operation("Move "+c.lane+" to frame "+number(frame),{kind:"move",clipId:c.id,linked:linked.checked,at:number(frame)})),button("Reorder linked range",()=>operation("Reorder range to frame "+number(frame),{kind:"reorder",clipId:c.id,at:number(frame)})));basic.append(basicActions);
    const edge=field(basic,"Trim edge","select","",{track:true});options(edge,[["in","In (start)"],["out","Out (end)"]],"out");const trim=field(basic,"Move edge by frames (+ later, − earlier)","number",0,{min:-108000,max:108000,track:true});basic.append(button("Apply trim",()=>operation("Trim "+c.lane+" "+edge.value+" by "+number(trim)+" frames",{kind:"trim",clipId:c.id,linked:linked.checked,edge:edge.value,delta:number(trim),ripple:ripple.checked})));
    const delta=field(advanced,"Shift source or shared boundary by frames","number",0,{min:-108000,max:108000,track:true}),neighbors=current.timeline.clips.filter(x=>x.lane===c.lane&&x.layer===c.layer&&x.id!==c.id),left=field(advanced,"Left clip for roll or slide","select",""),right=field(advanced,"Right clip for slide","select","");options(left,neighbors.map(x=>[x.id,clipLabel(x)]),neighbors.find(x=>x.at+x.frames===c.at)?.id);options(right,neighbors.map(x=>[x.id,clipLabel(x)]),neighbors.find(x=>x.at===c.at+c.frames)?.id);const controls=actions();
    controls.append(button("Slip source",()=>operation("Slip "+c.lane+" by "+number(delta)+" frames",{kind:"slip",clipId:c.id,linked:linked.checked,delta:number(delta)})),button("Roll left boundary",()=>operation("Roll shared boundary",{kind:"roll",leftId:left.value,rightId:c.id,linked:linked.checked,delta:number(delta)})),button("Slide clip",()=>operation("Slide middle range",{kind:"slide",leftId:left.value,clipId:c.id,rightId:right.value,linked:linked.checked,delta:number(delta)})),button("Unlink this group",()=>operation("Unlink selected group",{kind:"unlink",clipId:c.id})),button("Remove selected range",()=>operation("Remove "+c.lane+" range",{kind:"delete",clipId:c.id,linked:linked.checked,ripple:ripple.checked})));advanced.append(controls,node("p","Roll and slide need adjacent ranges on the same track. Removal is saved and can be undone."));
    if(c.lane==="captions"){settings.remove();return;}
    const isPicture=c.lane==="picture",gain=isPicture?null:field(settings,"Gain (dB)","number",c.gainDb,{min:-60,max:12,step:.1,track:true}),opacity=isPicture?field(settings,"Picture opacity","number",c.opacity,{min:0,max:1,step:.01,track:true}):null,fadeIn=field(settings,"Fade in (frames)","number",c.envelope.fadeIn,{min:0,max:108000,track:true}),fadeOut=field(settings,"Fade out (frames)","number",c.envelope.fadeOut,{min:0,max:108000,track:true}),source=current.timeline.sources.find(s=>s.id===c.sourceId),coordinates={};
    const crop=isPicture?field(settings,"Crop picture","checkbox",Boolean(c.crop),{track:true}):null,cropFields=node("div");cropFields.dataset.draftGroup="settings";cropFields.hidden=!c.crop;settings.append(cropFields);
    if(isPicture){crop.onchange=()=>{cropFields.hidden=!crop.checked;};for(const [key,label,value]of [["x","Crop X",0],["y","Crop Y",0],["width","Crop width",source.width],["height","Crop height",source.height]])coordinates[key]=field(cropFields,label,"number",c.crop?.[key]??value,{min:key==="x"||key==="y"?0:2,max:key==="x"||key==="width"?source.width:source.height,step:2,track:true});}
    const inherited=(c.envelope.from!==c.from||c.envelope.frames!==c.frames)&&(c.envelope.fadeIn||c.envelope.fadeOut),reanchor=inherited?field(settings,"Reanchor the inherited fades to this clip","checkbox",false,{track:true}):null;
    settings.append(node("p","Fades must total at most "+c.frames+" frames. Applying settings anchors them to this clip's source range."));if(inherited)settings.append(node("p","This clip currently preserves part of a longer fade after an edit. Review the new fade lengths and explicitly reanchor them before applying settings."));
    settings.append(button("Apply clip settings",()=>{const fi=number(fadeIn),fo=number(fadeOut);if(fi+fo>c.frames)throw new Error("Set fade lengths that total at most "+c.frames+" frames before applying settings.");if(reanchor&&!reanchor.checked)throw new Error("Review the fade lengths and check Reanchor the inherited fades to this clip.");return operation("Update "+c.lane+" settings",{kind:"settings",clipId:c.id,gainDb:gain?number(gain):c.gainDb,opacity:opacity?number(opacity):c.opacity,crop:crop?.checked?Object.fromEntries(Object.entries(coordinates).map(([key,input])=>[key,number(input)])):null,fadeIn:fi,fadeOut:fo});}));
  }
  function drawInsert(){const box=details("Insert a source range");box.dataset.draftGroup="insert";const source=field(box,"Original source","select","",{track:true});options(source,current.timeline.sources.map(s=>[s.id,s.label]));const from=field(box,"Source in (frame)","number",0,{min:0,max:108000,track:true}),frames=field(box,"Length (frames)","number",30,{min:1,max:108000,track:true}),at=field(box,"Insert at timeline frame","number",current.timeline.frames,{min:0,max:108000,track:true}),layer=field(box,"Picture layer","number",0,{min:0,max:3,track:true}),audio=field(box,"Audio to insert","select","",{track:true});options(audio,[["mix","Original mix"],["separate","Available isolated lanes"],["none","No audio"]]);const picture=field(box,"Include picture","checkbox",true,{track:true}),captions=field(box,"Include captions","checkbox",true,{track:true}),ripple=field(box,"Ripple following ranges","checkbox",true,{track:true});
    box.append(button("Insert linked range",()=>{const s=current.timeline.sources.find(s=>s.id===source.value),start=number(from),length=number(frames),position=number(at),lanes=[...(picture.checked?["picture"]:[]),...(audio.value==="mix"?["mix"]:audio.value==="separate"?s.audio.filter(l=>l!=="mix"):[]),...(captions.checked?["captions"]:[])],link=lanes.length>1?crypto.randomUUID():null;if(!lanes.length)throw new Error("Choose picture, audio or captions to insert.");return operation("Insert "+s.label+" at frame "+position,{kind:"insert",clips:lanes.map(lane=>({id:crypto.randomUUID(),sourceId:s.id,lane,layer:lane==="picture"?number(layer):0,link,at:position,from:start,frames:length,gainDb:0,opacity:1,crop:null,envelope:{from:start,frames:length,fadeIn:0,fadeOut:0}})),...(ripple.checked?{rippleAt:position,rippleFrames:length}:{})});}));editor.append(box);
  }
  function drawSequenceTools(){const box=details("Sequence name, duration and markers"),name=field(box,"Sequence name","text",current.sequence.label,{track:true,group:"name"}),duration=field(box,"Sequence duration (frames)","number",current.timeline.frames,{min:1,max:108000,track:true,group:"duration"}),label=field(box,"Marker label","text","",{track:true,group:"marker"}),frame=field(box,"Marker frame","number",0,{min:0,max:current.timeline.frames,track:true,group:"marker"}),controls=actions();controls.append(button("Save sequence name",()=>change({kind:"rename",label:name.value},"name")),button("Set sequence duration",()=>operation("Set duration to "+number(duration)+" frames",{kind:"duration",frames:number(duration)})),button("Add marker",()=>operation("Add marker: "+label.value,{kind:"marker",marker:{id:crypto.randomUUID(),frame:number(frame),label:label.value}})));box.append(controls);for(const marker of current.timeline.markers){const row=actions();row.append(node("span",time(marker.frame)+" · "+marker.label),button("Remove marker "+marker.label,()=>operation("Remove marker: "+marker.label,{kind:"remove-marker",id:marker.id})));box.append(row);}editor.append(box);}
  async function reviewExport(){clean();const quote=await request("/sequences/"+current.sequence.id+"/renders");if(quote.sequence.historyRevision!==current.sequence.history.revision)throw new Error("This sequence changed in another window. Refresh saved state before reviewing its export.");review.replaceChildren(node("h3","Step 2 of 3 · Review this export"),node("p",time(quote.sequence.frames)+" · "+quote.sequence.width+" × "+quote.sequence.height+" · no new provider generation"));
    const ids=[...new Set([...quote.speechCuts.map(c=>c.clipId),...quote.unmeasuredAudioCuts])];if(!ids.length)review.append(node("p","No partial measured voice windows or trimmed unmeasured audio were found. Listen to the rendered result before selecting it."));else{const warnings=details("Review speech boundaries · "+ids.length+" affected clips");warnings.open=true;for(const id of ids){const c=current.timeline.clips.find(c=>c.id===id),cuts=quote.speechCuts.filter(c=>c.clipId===id),group=details((c?clipLabel(c):id)+" · "+cuts.length+" measured boundaries"),list=node("ul");for(const cut of cuts){const voice=current.timeline.sources.find(s=>s.id===c?.sourceId)?.voices.find(v=>v.id===cut.voiceId);list.append(node("li","Cuts the "+(cut.edge==="in"?"start":"end")+" of "+(voice?voice.lane+" at source "+(voice.start/48000).toFixed(3)+"–"+(voice.end/48000).toFixed(3)+" s":"measured voice "+cut.voiceId)+"."));}if(quote.unmeasuredAudioCuts.includes(id))group.append(node("p","Trims audio without measured speech timing. Listen for cut words."));group.append(list);warnings.append(group);}review.append(warnings);}
    const storage=details("Storage and retained sources");storage.append(node("p","Estimated export: "+(quote.resources.outputBytes/1024**3).toFixed(2)+" GiB · working space: "+(quote.resources.workspaceBytes/1024**3).toFixed(2)+" GiB. The worker checks its available disk before processing."));for(const source of quote.sources)storage.append(node("p",source.facts.label+" · retained until "+new Date(source.expiresAt).toLocaleString()));review.append(storage);
    const approved=field(review,"I reviewed these cuts and want to render this saved edit","checkbox",false),render=button("Render reviewed edit",async()=>{clean();if(!approved.checked)throw new Error("Review the listed cuts and check the export confirmation.");remember({kind:"render",sequenceId:current.sequence.id,body:{idempotencyKey:crypto.randomUUID(),generationApproved:true,historyRevision:quote.sequence.historyRevision,sourceBindingsRevision:quote.sourceBindingsRevision,engineVersion:quote.engineVersion,review:{...quote.review,accepted:true}}});await submitRender();});render.disabled=Boolean(quote.unavailable);if(quote.unavailable)review.append(node("p",quote.unavailable));review.append(render);primary(render);review.scrollIntoView({block:"nearest",behavior:"smooth"});tell("Review the speech boundaries and confirm this export.");
  }
  async function submitRender(){if(!pending||pending.kind!=="render")throw new Error("No saved export request is waiting.");if(!pending.jobId){tell("Submitting the reviewed export…");try{const admitted=await request("/sequences/"+pending.sequenceId+"/renders",{method:"POST",body:pending.body});remember({...pending,jobId:admitted.jobId});review.replaceChildren();}catch(error){if(error.status&&error.status<500)remember(null);throw error;}}await show(pending.jobId);await refreshIndex(false);}
  function drawVersions(){const previous=[...versions.querySelectorAll("select")].map(e=>e.value);versions.replaceChildren(node("summary","Rendered versions and comparison"));const jobs=index?.jobs??[];if(!jobs.length){versions.append(node("p","Rendered edits will appear here, including earlier branches."));return;}const select=field(versions,"Rendered edit","select","");options(select,jobs.map(j=>[j.id,j.pictureEdit.label+" · "+j.status+" · "+j.id.slice(0,8)]),jobs.some(j=>j.id===previous[0])?previous[0]:jobs.at(-1)?.id);const controls=actions();controls.append(button("Open rendered version",()=>{clean();return show(select.value);}));const completed=jobs.filter(j=>j.status==="done"&&j.output),other=field(versions,"Compare with another completed edit","select","");options(other,completed.map(j=>[j.id,j.pictureEdit.label+" · "+j.id.slice(0,8)]),completed.some(j=>j.id===previous[1])?previous[1]:completed[0]?.id);const comparison=button("Compare these versions",()=>{clean();if(select.value===other.value)throw new Error("Choose two different completed versions.");return compare(select.value,other.value);});comparison.disabled=completed.length<2;controls.append(comparison);versions.append(controls);}
  function player(container,job){const video=node("video");video.controls=true;video.preload="metadata";video.playsInline=true;video.src=assetUrl(job.output.mp4Url);video.setAttribute("aria-label",job.pictureEdit.label+" rendered version "+job.id.slice(0,8));if(job.output.captionsUrl){const track=node("track");track.kind="captions";track.label="Captions";track.srclang=job.captionLanguage||"en";track.src=assetUrl(job.output.captionsUrl);video.append(track);}container.append(video);return video;}
  async function show(id){clearTimeout(watchTimer);watched=id;const attempt=++playbackSerial;stop(playback);playback.replaceChildren();const job=await jobRequest(id);if(watched!==id||panel.hidden||attempt!==playbackSerial)return;if(index){const previous=index.jobs.find(j=>j.id===id);if(!previous||previous.status!==job.status||Boolean(previous.output)!==Boolean(job.output)){index.jobs=[...index.jobs.filter(j=>j.id!==id),job];drawVersions();}}playback.append(node("h3","Step 3 of 3 · "+job.pictureEdit.label+" · "+job.status));versions.open=true;
    if(job.status!=="done"){playback.append(node("p",job.failureReason||job.cancelReason||"This saved export is "+job.status+". You can keep editing; this render retains the reviewed version."));if(["failed","cancelled"].includes(job.status)){if(pending?.jobId===id)remember(null);}else watchTimer=setTimeout(()=>{if(!panel.hidden&&watched===id)show(id).catch(e=>tell(e.message,true));},1500);return;}
    if(pending?.jobId===id)remember(null);if(!job.output){playback.append(node("p",job.mediaUnavailable||"This retained version is unavailable."));return;}player(playback,job);if(current?.sequence.id===job.pictureEdit.sequenceId&&current.sequence.history.revision!==job.pictureEdit.historyRevision)playback.append(node("p","This rendered version predates the current saved edits."));
    const links=actions();for(const [key,label]of [["mp4Url","Download MP4"],["deliveryMasterUrl","Master WAV"],["captionsUrl","Captions"],["timelineUrl","Timeline"],["conformReportUrl","Conform report"],["manifestUrl","Provenance"]])if(job.output[key]){const a=node("a",label);a.className="button-link";a.href=assetUrl(job.output[key]);links.append(a);}playback.append(links);
    if(selection.entries.at(-1)?.jobId===id)playback.append(node("p","This is the selected project export."));else{const use=button("Use this version as export",async()=>{const saved=await adopt({jobId:id,sourceJobId:job.pictureEdit.sequenceId,expectedVersion:selection.version,expectedOutputRevision:job.outputRevision});selection=saved.dialogueSelections;await show(id);tell("Export selected. Earlier rendered versions remain available for comparison or rollback.");});playback.append(use);primary(use);}tell("Rendered edit is ready. Play it through before selecting the project export.");
  }
  async function compare(a,b){clearTimeout(watchTimer);watched=null;const attempt=++playbackSerial,jobs=await Promise.all([jobRequest(a),jobRequest(b)]);if(panel.hidden||attempt!==playbackSerial)return;if(jobs.some(j=>j.status!=="done"||!j.output))throw new Error("Both versions must be completed and available.");stop(playback);playback.replaceChildren(node("h3","Compare rendered edits"));const grid=node("div");grid.className="editorial-compare";const videos=jobs.map((job,i)=>{const box=node("div");box.append(node("h4",(i?"B":"A")+" · "+job.pictureEdit.label+" · "+job.id.slice(0,8)));grid.append(box);return player(box,job);});videos[1].muted=true;playback.append(grid,node("p","Audio starts on A. Playback starts together; a longer version can continue after the shorter ends. Browser playback is not a frame-comparison measurement."));const controls=actions();controls.append(button("Play both",async()=>{videos[1].currentTime=videos[0].currentTime;await Promise.all(videos.map(v=>v.play()));}),button("Pause both",()=>videos.forEach(v=>v.pause())),button("Listen to A",()=>{videos[0].muted=false;videos[1].muted=true;}),button("Listen to B",()=>{videos[0].muted=true;videos[1].muted=false;}));playback.append(controls);videos[0].ontimeupdate=()=>{if(Math.abs(videos[1].currentTime-videos[0].currentTime)>2/30&&videos[0].currentTime<videos[1].duration)videos[1].currentTime=videos[0].currentTime;};}
  async function open(){if(!canEdit()){panel.hidden=false;tell("Save or discard the other open edit before opening picture editorial.",true);return;}if(activeProject===projectId()&&dirty){panel.hidden=false;tell("Your unsaved fields are still open. Apply or discard them first.",true);return;}if(activeProject!==projectId()){clearTimeout(watchTimer);watched=null;stop(playback);playback.replaceChildren();editor.replaceChildren();review.replaceChildren();current=null;selectedClip=null;dirty=false;dirtyGroup=null;bin=[];creationDraft={label:"New assembly",dimensions:"1280x720",width:1280,height:720};}activeProject=projectId();panel.hidden=false;await run(async()=>{try{pending=JSON.parse(localStorage.getItem("hv-editorial-pending:"+activeProject)||"null");if(pending&&!(["edit","render","create"].includes(pending.kind)&&typeof pending.sequenceId==="string"&&pending.body))pending=null;}catch{pending=null;}await refreshIndex();drawPending();if(pending?.jobId)await show(pending.jobId);else if(!pending&&!current&&index.sequences.length)await load(index.sequences[0].id);else tell("Choose a saved sequence or inspect a retained original to create one.");});}
  window.addEventListener("beforeunload",event=>{if(dirty||busy||creationDirty()||pending&&!pending.jobId){event.preventDefault();event.returnValue="";}});
  return {open,get unsaved(){return dirty||busy||creationDirty()||Boolean(pending&&!pending.jobId);}};
}
