export function initLipSync({parent,request,jobRequest,projectState,assetUrl,adopt,projectId,canEdit}){
  const node=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;},panel=node("section"),status=node("p"),pick=node("div"),edit=node("div"),confirmation=node("div"),results=node("div");
  panel.className="cast-panel lipsync-workbench";panel.hidden=true;status.className="status";status.setAttribute("role","status");panel.append(node("h2","Direct lip-sync"),node("p","Animate one speaker to an applied voice take. Each pass creates a new picture version and carries forward the saved dialogue waveform and caption timing."),status,pick,edit,confirmation,results);parent.append(panel);
  let busy=false,dirty=false,catalogue=null,quote=null,line=null,frame=null,point=null,pending=null,serial=0,selected=null;
  const tell=(text,error=false)=>{status.textContent=text;status.dataset.state=error?"error":"success";};
  const button=(label,action,primary=false)=>{const b=node("button",label);b.type="button";b.className=primary?"":"secondary";b.onclick=()=>run(action);return b;};
  function field(parent,label,type,value,min,max){const wrap=node("div"),caption=node("label",label),input=node(type==="select"?"select":type==="textarea"?"textarea":"input");wrap.className="cast-field";input.id="lip-field-"+(++serial);caption.htmlFor=input.id;if(type==="number"){input.type=type;input.min=min;input.max=max;input.step=1;input.required=true;}if(type==="textarea"){input.rows=3;input.maxLength=600;}input.value=value??"";wrap.append(caption,input);parent.append(wrap);return input;}
  async function run(action){if(busy)return;busy=true;panel.setAttribute("aria-busy","true");const controls=[...panel.querySelectorAll("button,input,select,textarea")],disabled=controls.map(e=>e.disabled);controls.forEach(e=>e.disabled=true);try{await action();}catch(error){tell(error.message||"This step failed. Refresh the retained versions and try again.",true);}finally{busy=false;controls.forEach((e,i)=>e.disabled=disabled[i]);panel.removeAttribute("aria-busy");}}
  const pendingKey=()=>"hv-lipsync-pending:"+projectId();
  function remember(value){pending=value;try{if(value)localStorage.setItem(pendingKey(),JSON.stringify(value));else localStorage.removeItem(pendingKey());}catch{/* The same request is retained in this open editor. */}}
  function changed(){dirty=true;confirmation.replaceChildren();if(pending)throw new Error("Resolve the pending request before changing its speaker.");}
  async function inspect(id){if(pending)throw new Error("Check the saved request before starting another pass.");tell("Loading applied dialogue lines…");quote=await request("/"+id);edit.replaceChildren();confirmation.replaceChildren();frame=null;point=null;dirty=false;
    if(!quote.lines.length){edit.append(node("p","Apply a saved audition to this cut before directing its lips."));return;}
    const choice=field(edit,"Applied dialogue line","select","");for(const [i,l]of quote.lines.entries())choice.append(new Option(l.character+" · "+l.text.slice(0,110),String(i)));choice.onchange=()=>{frame=null;point=null;confirmation.replaceChildren();framePanel.replaceChildren();dirty=false;};
    const framePanel=node("div");edit.append(button("Choose speaker frame",async()=>{line=quote.lines[Number(choice.value)];framePanel.replaceChildren();frame=null;point=null;confirmation.replaceChildren();
      const number=field(framePanel,"Frame within this line","number",0,0,line.window.frames-1),canvas=node("div");framePanel.append(node("p","Line starts at "+(line.window.startFrame/30).toFixed(2)+" s and spans "+line.window.frames+" frames. Choose a frame with the speaking face visible."),button("Show frame",()=>loadFrame(Number(number.value),canvas)),canvas);await loadFrame(0,canvas);
    }),framePanel);tell("Step 1 of 3 · Choose an applied line and its speaker.");
  }
  async function loadFrame(number,parent){if(pending)throw new Error("Resolve the pending request first.");tell("Verifying the source frame…");frame=await request("/"+quote.sourceJobId+"/preview",{method:"POST",body:{sourceRevision:quote.sourceRevision,shotId:line.shotId,lineIndex:line.lineIndex,frame:number}});point=null;confirmation.replaceChildren();parent.replaceChildren();
    const surface=node("button"),image=node("img"),marker=node("span","+");surface.type="button";surface.className="lip-face-surface secondary";surface.style.cssText="display:block;position:relative;padding:0;overflow:hidden;width:100%;max-width:850px;border:2px solid currentColor;";surface.setAttribute("aria-label","Speaker frame. Click the speaking face, or enter its position below.");
    image.src=frame.image;image.alt="Verified source frame for "+line.character;image.style.cssText="display:block;width:100%;height:auto;";marker.hidden=true;marker.setAttribute("aria-hidden","true");marker.style.cssText="position:absolute;transform:translate(-50%,-50%);background:#101017;color:#fff;border:2px solid #fff;border-radius:50%;width:30px;height:30px;line-height:25px;font-size:25px;pointer-events:none;";surface.append(image,marker);parent.append(node("h3",line.character+" · select the speaking face"),surface);
    const coordinates=node("details");coordinates.append(node("summary","Enter the face position with the keyboard"));const x=field(coordinates,"Face X in native pixels","number","",0,frame.width-1),y=field(coordinates,"Face Y in native pixels","number","",0,frame.height-1);parent.append(coordinates);const place=()=>{const px=Number(x.value),py=Number(y.value);if(x.value===""||y.value===""||!Number.isInteger(px)||!Number.isInteger(py)||px<0||py<0||px>=frame.width||py>=frame.height){point=null;marker.hidden=true;confirmation.replaceChildren();return;}point={x:px,y:py};marker.hidden=false;marker.style.left=(px/frame.width*100)+"%";marker.style.top=(py/frame.height*100)+"%";changed();tell("Speaker marked. Review this line and its reserved cost.");};x.oninput=place;y.oninput=place;
    surface.onclick=event=>{if(busy||pending)return;if(event.detail===0){coordinates.open=true;x.focus();return;}const rect=image.getBoundingClientRect();x.value=Math.min(frame.width-1,Math.max(0,Math.floor((event.clientX-rect.left)*frame.width/rect.width)));y.value=Math.min(frame.height-1,Math.max(0,Math.floor((event.clientY-rect.top)*frame.height/rect.height)));place();};
    const review=button("Review lip-sync pass",reviewPass,true);review.disabled=!catalogue.enabled;parent.append(review);if(!catalogue.enabled)parent.append(node("p","Generation is unavailable until the operator's provider service and policy are ready. You can inspect sources and review retained results."));tell("Step 1 of 3 · Mark the face that delivers this line.");
  }
  async function reviewPass(){if(!frame||!point)throw new Error("Mark the speaking face before reviewing the pass.");if(!catalogue.enabled||!catalogue.policy)throw new Error("Generation is currently unavailable.");
    confirmation.replaceChildren(node("h3","Review lip-sync pass"),node("p",line.character+": "+line.text),node("p","Saved voice: "+line.voiceLabel+" · "+(line.window.frames/30).toFixed(2)+" s · "+catalogue.policy.label),node("p","Reserved cost: $"+catalogue.policy.heldUsd.toFixed(2)+". Actual cost remains unknown until the operator allocates the provider invoice."),node("p","Only this line's picture window is sent with its retained audio. The full export is encoded again; its original cut remains available. Review mouth timing, face stability and expression before choosing an export."),button("Render reviewed lip-sync",async()=>{
      remember({sourceId:quote.sourceJobId,body:{idempotencyKey:crypto.randomUUID(),generationApproved:true,sourceRevision:quote.sourceRevision,policyRevision:catalogue.policy.revision,capabilityRevision:catalogue.capabilityRevision,shotId:line.shotId,lineIndex:line.lineIndex,selection:{frame:frame.frame,width:frame.width,height:frame.height,rgbSha256:frame.rgbSha256,...point}}});await submit();},true));edit.querySelectorAll("button").forEach(b=>b.classList.add("secondary"));tell("Step 2 of 3 · Check the speaker, saved voice and reserved cost.");
  }
  async function submit(){if(!pending)throw new Error("There is no saved request to check.");tell("Submitting the reviewed pass…");drawPending();const admitted=await request("/"+pending.sourceId,{method:"POST",body:pending.body});remember(null);dirty=false;confirmation.replaceChildren();edit.replaceChildren();await load();await show(admitted.jobId);}
  function drawPending(){confirmation.replaceChildren(node("h3","Saved lip-sync request"),node("p","The request key is retained. Checking it returns the original job if submission already succeeded."),button("Check or resume saved request",submit,true));}
  async function load(){catalogue=await request("");pick.replaceChildren();const sources=field(pick,"Retained dialogue or lip-sync version","select","");for(const source of catalogue.sources){const o=new Option(source.id.slice(0,8)+" · "+source.stage+" · "+(source.unavailable||source.lines+" applied lines"),source.id);o.disabled=Boolean(source.unavailable);sources.append(o);}const eligible=catalogue.sources.filter(s=>!s.unavailable);if(eligible.length)sources.value=eligible.at(-1).id;
    const open=button("Load applied lines",()=>inspect(sources.value));open.disabled=!eligible.length||Boolean(pending);pick.append(open);if(!eligible.length)pick.append(node("p","Apply a saved voice audition in Dialogue replacement to prepare your first lip-sync source."));
    const archive=node("details");archive.append(node("summary","Retained lip-sync results · "+catalogue.jobs.length));if(catalogue.jobs.length){const versions=field(archive,"Lip-sync result","select",selected);for(const job of catalogue.jobs)versions.append(new Option(job.id.slice(0,8)+" · "+job.status+" · "+job.lipSync.character,job.id));versions.value=catalogue.jobs.some(j=>j.id===selected)?selected:catalogue.jobs.at(-1).id;archive.append(button("Open result",()=>show(versions.value)));}pick.append(archive);
  }
  function player(job,title){const group=node("div");group.append(node("h4",title));if(!job.output){group.append(node("p",job.mediaUnavailable||"Source media is unavailable."));return group;}const video=node("video");video.controls=true;video.playsInline=true;video.preload="metadata";video.style.width="100%";video.src=assetUrl(job.output.mp4Url);video.onplay=()=>document.querySelectorAll("audio,video").forEach(other=>{if(other!==video)other.pause();});video.onerror=()=>tell("This media is unavailable or expired. Refresh its retained result.",true);const track=node("track");track.kind="captions";track.srclang="en";track.label="English";track.src=assetUrl(job.output.captionsUrl);video.append(track);group.append(video);return group;}
  async function show(id){selected=id;for(const media of results.querySelectorAll("video,audio")){media.pause();media.removeAttribute("src");media.load();}results.replaceChildren();const job=await jobRequest(id);results.append(node("h3","Lip-sync result · "+id.slice(0,8)));const bill=job.lipSyncBilling;
    if(bill)results.append(node("p",bill.actualUsd===null?"Invoice pending · $"+bill.heldUsd.toFixed(2)+" held":"Invoice allocated · $"+bill.actualUsd.toFixed(4)));
    if(job.status!=="done"||!job.output){results.append(node("p",job.mediaUnavailable||job.failureReason||job.cancelReason||"This pass is "+job.status+"."));if(["queued","running"].includes(job.status))results.append(button("Refresh this pass",()=>show(id),true));tell("Pass saved · return here to review its result.");return;}
    const compare=node("div");compare.className="lip-compare";compare.style.cssText="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:20px;";compare.append(player(job,"New picture version"));const source=await jobRequest(job.lipSync.sourceJobId).catch(()=>null);if(source)compare.append(player(source,"Source version"));else compare.append(node("p","The source job has expired or was removed. This retained output remains independent."));results.append(compare);
    const links=node("div");links.className="result-actions";for(const [key,label]of [["mp4Url","Download MP4"],["audioUrl","Dialogue WAV"],["captionsUrl","Captions"],["manifestUrl","Provenance"]])if(job.output[key]){const a=node("a",label);a.className="button-link";a.href=assetUrl(job.output[key]);links.append(a);}results.append(links);
    const form=node("form"),history=job.lipSyncReviews??{version:0,entries:[]},last=history.entries.at(-1);form.append(node("h4","Your quality review"),node("p","Rate each item from 1 (poor) to 5 (strong). These are your observations; no automatic quality score has been qualified."));
    const mouth=field(form,"Mouth timing","number",last?.mouthSync??3,1,5),face=field(form,"Face stability","number",last?.faceStability??3,1,5),expression=field(form,"Expression","number",last?.expression??3,1,5),decision=field(form,"Decision","select","");for(const [id,label]of [["revise","Needs another pass"],["accept","Accept this result"],["cutaway","Use cutaway coverage"]])decision.append(new Option(label,id));decision.value=last?.decision??"revise";const notes=field(form,"Visible issues or review notes","textarea",last?.notes??"");const save=node("button","Save quality review");save.type="submit";form.append(save);form.onsubmit=event=>{event.preventDefault();void run(async()=>{await request("/"+id+"/review",{method:"PUT",body:{mouthSync:Number(mouth.value),faceStability:Number(face.value),expression:Number(expression.value),decision:decision.value,notes:notes.value,expectedVersion:history.version,expectedOutputRevision:job.outputRevision}});await show(id);tell("Step 3 of 3 · Quality review saved. Accept the result to make it your export, or prepare another pass.");});};results.append(form);
    const coverage=node("details");coverage.append(node("summary","Available cutaway coverage"));if(job.lipSync.cutaways.length)for(const cut of job.lipSync.cutaways)coverage.append(node("p",cut.shotId+" · "+(cut.startFrame/30).toFixed(2)+"–"+((cut.startFrame+cut.frames)/30).toFixed(2)+" s · "+cut.reason));else coverage.append(node("p","No retained shot without recorded dialogue is available in this scene. Prepare additional coverage before replacing this shot."));coverage.append(node("p","Suggestions are advisory; they do not change the edit."));results.append(coverage);
    const past=node("details");past.append(node("summary","Saved quality reviews · "+history.version));for(const entry of history.entries)past.append(node("p",entry.at+" · "+entry.decision+" · mouth "+entry.mouthSync+", face "+entry.faceStability+", expression "+entry.expression+(entry.notes?" · "+entry.notes:"")));results.append(past);
    if(last?.decision==="accept"){save.className="secondary";results.append(button("Use accepted result as export",async()=>{const state=await projectState();await adopt({jobId:id,sourceJobId:job.lipSync.originalJobId,expectedVersion:state.dialogueSelections.version,expectedOutputRevision:job.outputRevision});tell("Export choice saved. Existing review links keep their selected version.");},true));}results.append(button("Prepare another pass from this result",()=>inspect(id)));tell("Step 3 of 3 · Compare playback and record your quality review.");
  }
  async function open(){panel.hidden=false;if(!canEdit())return tell("Save or discard your other open edit before directing lip-sync.",true);await run(async()=>{tell("Loading lip-sync sources and results…");try{pending=JSON.parse(localStorage.getItem(pendingKey())||"null");}catch{pending=null;}await load();if(pending)drawPending();else tell("Choose a retained dialogue version or open a saved lip-sync result.");});}
  return {open,get unsaved(){return busy||dirty||Boolean(pending);}};
}
