import {createLivingScriptState} from './living-script-state.js';
export {livingScriptResumeMedia} from './living-script-state.js';
import {livingScriptSameClock} from './living-script-recut.js';
import {applyBusy} from './busy.js';
const PAGE=6,node=(tag,text)=>{const element=document.createElement(tag);if(text!==undefined)element.textContent=text;return element;},time=frames=>frames+' frames · '+(frames/30).toFixed(2)+' seconds',money=value=>'$'+Number(value??0).toFixed(4),short=value=>String(value??'').slice(0,12);

/** Source-film playback and the proposed cut comparison have separate, explicit identities.
 * Atomic acceptance remains gated on the current complete-cut comparison and owner review. */
export function createLivingScriptStudio({parent,request,jobRequest,assetUrl=value=>value,current,onDirty=()=>{},onAccepted=()=>{},onOpenSequence,onRecutPreviewBinding=()=>{},storage}){
  const panel=node('details'),summary=node('summary','Revise dialogue and its cut'),status=node('p'),warning=node('p'),step=node('p'),recovery=node('div'),library=node('section'),draft=node('section'),proposal=node('section'),generation=node('section'),media=node('section'),mapping=node('section'),review=node('section'),success=node('section');panel.className='living-script';status.className='living-script-status';status.setAttribute('role','status');warning.className='living-script-warning';step.className='living-script-step';recovery.className='living-script-recovery';panel.append(summary,status,warning,step,recovery,library,draft,proposal,generation,media,mapping,review,success);parent.append(panel);
  let disposed=false,controls=[],localError=null,selectedProposal='',rowPage=0,jobPage=0,lineAck=null,generationAck=null,decisionAck=null,cutAck=null,video=null,originalVideo=null,mediaKey=null,originalKey=null,poll=null,comparison=null,lastPreviewRevision=null,primary=null;
  const safe=action=>async()=>{localError=null;try{await action();}catch(error){localError=error.message??String(error);sync();}};
  function button(target,label,action,guard='read',dominant=false){const element=node('button',label);element.type='button';element.className='secondary';element.onclick=safe(action);target.append(element);controls.push({element,guard});if(dominant)primary=element;return element;}
  function field(target,label,value,change,{type='text',options,guard='edit',rows=3}={}){const wrapper=node('div'),caption=node('label',label),input=node(options?'select':type==='textarea'?'textarea':'input');wrapper.className='living-script-field';input.id='living-script-'+crypto.randomUUID();caption.htmlFor=input.id;if(options)input.replaceChildren(...options.map(([value,label])=>new Option(label,value)));else if(type==='textarea')input.rows=rows;else input.type=type==='integer'?'text':type;if(type==='integer')input.inputMode='numeric';if(type==='checkbox')input.checked=Boolean(value);else input.value=value??'';const action=()=>{localError=null;try{change(type==='checkbox'?input.checked:input.value);}catch(error){localError=error.message;sync();}};if(type==='checkbox'||options)input.onchange=action;else input.oninput=action;wrapper.append(caption,input);target.append(wrapper);controls.push({element:input,guard});return input;}
  function row(target){const value=node('div');value.className='living-script-actions';target.append(value);return value;}
  function acknowledgement(target,label,change){const wrapper=node('label'),input=node('input');input.type='checkbox';wrapper.className='living-script-acknowledgement';input.onchange=change;wrapper.append(input,node('span',label));target.append(wrapper);return input;}
  function listing(target,title,items,format){if(!items?.length)return;const box=node('details'),body=node('div'),pager=node('div');pager.className='living-script-actions';box.append(node('summary',title+' · '+items.length),body,pager);target.append(box);let at=0;const render=()=>{body.replaceChildren(...items.slice(at,at+PAGE).map(item=>node('p',format(item))));controls=controls.filter(item=>!pager.contains(item.element));pager.replaceChildren();if(items.length>PAGE){const back=button(pager,'Previous '+title.toLowerCase(),()=>{at-=PAGE;render();sync();}),next=button(pager,'Next '+title.toLowerCase(),()=>{at+=PAGE;render();sync();});back.dataset.edge=String(at===0);next.dataset.edge=String(at+PAGE>=items.length);}};render();}
  function pause(){for(const item of [video,originalVideo])item?.pause?.();}
  function previewBinding(s){const active=current(),ready=Boolean(panel.open&&s.recut&&!s.acceptance&&!s.dirty&&!s.pending&&!s.stale&&active&&!active.busy&&active.canEdit),revision=ready?s.recut.recut.revision:null;if(revision!==lastPreviewRevision){lastPreviewRevision=revision;comparison=null;if(cutAck)cutAck.checked=false;onRecutPreviewBinding(ready?{...s.recut,proposalId:s.proposal.request.id}:null);}}
  function sync(){if(disposed)return;const s=store.state,active=current(),external=Boolean(!active||active.projectId!==s.base?.projectId||active.busy||!active.canEdit),blocked=external||s.busy||s.hydrating;
    panel.hidden=!active&&!s.pending&&!s.dirty;applyBusy(panel,Boolean(s.busy||s.hydrating));status.textContent=localError??(s.stale&&!s.acceptance?'The saved cut context changed. Your workflow is preserved; reopen its original parent or start a fresh review.':s.message);status.dataset.state=localError||s.error?'error':'success';warning.textContent=s.warning??'';warning.hidden=!s.warning;previewBinding(s);
    if(s.pending)primary=controls.find(control=>control.guard==='retry')?.element;
    for(const {element,guard}of controls){const stale=s.stale&&!s.acceptance,disabled=blocked||element.dataset.edge==='true'||guard!=='retry'&&Boolean(s.pending)||guard==='edit'&&(stale||!s.draft||Boolean(s.proposal))||guard==='quote-line'&&(stale||!s.draft)||guard==='save-proposal'&&(stale||!s.lineQuote||!lineAck?.checked)||guard==='open'&&(s.dirty||Boolean(s.recovered))||guard==='generation'&&(stale||s.dirty||!s.proposal||Boolean(s.acceptance))||guard==='final-generation'&&(stale||s.dirty||!s.proposal||s.decision?.approval?.decision!=='approved')||guard==='submit-generation'&&(stale||!s.generationQuote||!generationAck?.checked)||guard==='decision'&&(stale||!s.decision||!decisionAck?.checked)||guard==='map'&&(stale||s.job?.status!=='done'||s.job?.livingScript?.role!=='render')||guard==='mapping'&&(stale||!s.source||Boolean(s.acceptance))||guard==='accept'&&(stale||!s.recut||s.dirty||!cutAck?.checked||comparison?.recutRevision!==s.recut.recut.revision||!comparison.ready)||guard==='retry'&&!s.pending||guard==='discard'&&Boolean(s.pending);element.disabled=Boolean(disabled);element.className=element===primary?'':'secondary';}
    if(lineAck)lineAck.disabled=blocked||!s.lineQuote||Boolean(s.pending);if(generationAck)generationAck.disabled=blocked||!s.generationQuote||Boolean(s.pending);if(decisionAck)decisionAck.disabled=blocked||!s.decision||Boolean(s.pending);if(cutAck)cutAck.disabled=blocked||!s.recut||s.dirty||Boolean(s.pending)||comparison?.recutRevision!==s.recut.recut.revision||!comparison.ready;
    if(external||!panel.open)pause();schedulePoll();
  }
  /**
   * HV-039-11: while a preview or film generates, the status is checked every three seconds. The
   * check went through the same path as a creator's own "Check generation status": it marked the
   * studio busy, which disabled every control, and it redrew every section twice, collapsing open
   * reviews and dropping focus to the page body. Through `safe`, it also cleared any error on screen.
   * It is now quiet: it redraws only when the job's status or output changes.
   */
  function schedulePoll(){clearTimeout(poll);const s=store.state;if(!disposed&&panel.open&&!s.busy&&!s.pending&&!s.stale&&current()?.canEdit&&s.job&&!['done','failed','cancelled'].includes(s.job.status))poll=setTimeout(()=>{if(store.state.busy)return schedulePoll();void store.showJob(s.job.id,{quiet:true}).catch(error=>{localError=error.message??String(error);sync();});},3000);}
  function renderRecovery(s){recovery.replaceChildren();if(s.pending){recovery.append(node('p','A saved request needs its exact result checked. The same review, identities and payload are retained.'));button(row(recovery),'Retry the same saved request',()=>store.retry(),'retry',true);}
    else if(s.recovered){recovery.append(node('p','A browser workflow is available'+(s.recovered.base.historyRevision!==current()?.historyRevision?' from an earlier saved cut':'')+'. Restoring it keeps raw fields and exact clip identities.'));const actions=row(recovery);button(actions,'Restore browser workflow',()=>store.restore(),'read',true);button(actions,'Discard browser workflow',()=>store.discard(),'discard');}
    else if(s.invalidRecovery){recovery.append(node('p','Unreadable browser recovery data remains stored. Check saved proposals and generated jobs before discarding this browser copy.'));button(row(recovery),'Discard unreadable browser copy',()=>store.discard(),'discard');}
  }
  function renderLibrary(s){library.replaceChildren();const actions=row(library);button(actions,s.list?'Refresh saved proposals':'Load saved proposals',()=>store.load(),'read',!s.draft&&!s.proposal&&!s.pending&&!s.recovered);if(s.list){const selected=field(library,'Saved screenplay proposal',selectedProposal,value=>{selectedProposal=value;},{options:[['','Choose a saved proposal'],...s.list.proposals.map(item=>[item.id,item.label+' · version '+item.beforeVersion+' → '+item.proposedVersion])],guard:'open'});button(actions,'Open selected proposal',()=>{if(!selected.value)throw new Error('Choose a saved proposal.');return store.open(selected.value);},'open');}
    if(!s.draft&&!s.proposal)library.append(node('p','Select a dialogue line in “Screenplay in this cut”, then choose “Revise this screenplay line”. The review verifies its exact original and current screenplay version.'));
  }
  function renderDraft(s){draft.replaceChildren();lineAck=null;if(!s.draft)return;draft.append(node('h3','1. Revise one screenplay line'),node('p',(s.draft.selection.character??'Dialogue')+' · retained original '+short(s.draft.selection.sourceRevision)),node('h4','Original screenplay text'),node('p',s.draft.selection.text));field(draft,'Proposal name',s.draft.label,value=>store.edit('label',value));field(draft,'Revised dialogue',s.draft.replacement,value=>{if(lineAck)lineAck.checked=false;store.edit('replacement',value);},{type:'textarea',rows:4});const actions=row(draft);button(actions,'Review line and cut impact',()=>store.quoteLine(),'quote-line',!s.lineQuote);button(actions,'Discard line draft',()=>store.discard(),'discard');
    if(s.lineQuote){const impact=node('div');impact.dataset.impactReview='true';draft.append(impact);renderImpact(impact,s.lineQuote.impact,s.lineQuote.settings);lineAck=acknowledgement(impact,'I reviewed this exact dialogue, performance rebinding and retained cut impact.',sync);button(row(impact),'Save reviewed proposal',()=>store.saveProposal(),'save-proposal',true);}
  }
  function renderImpact(target,impact,settings){target.append(node('h4','Retained cut impact'),node('p',impact.generation.generateShotIds.length+' shots need generation · '+impact.generation.reusableRecords.length+' unchanged shot receipts are available for verified reuse · '+impact.clips.length+' retained clips need review.'));
    listing(target,'Changed shots',impact.generation.shots,shot=>shot.shotId+' · '+shot.treatment+' · planned '+(shot.beforePlannedFrames??'new')+' → '+(shot.afterPlannedFrames??'removed')+' frames.');
    listing(target,'Retained clip effects',impact.clips,item=>item.clip.lane+' '+(item.clip.layer??0)+' at '+time(item.clip.at)+' · '+item.reviewReasons.join(' '));
    if(settings){const changes=settings.changes;listing(target,'Line direction rebinding',changes.directions,item=>item.shotId+' · '+item.lines.length+' exact spoken-line settings carried to the revised text.');listing(target,'Scene performance rebinding',changes.scenePerformances,item=>'Scene '+item.sceneNumber+' · performance settings rebound to the reviewed screenplay.');listing(target,'Scene coverage rebinding',changes.sceneCuts,item=>'Scene '+(item.sceneIndex+1)+' · existing authored coverage retained.');listing(target,'Performance review notes',settings.warnings,value=>value);}
    listing(target,'Impact review notes',impact.warnings,value=>value);target.append(node('p','Retained ranges describe source use. They do not establish what is visible through masks or which speech is audible in the final mix.'));
  }
  function renderProposal(s){proposal.replaceChildren();if(!s.proposal||s.acceptance)return;proposal.append(node('h3','2. Saved proposal: '+s.proposal.request.label),node('p','Screenplay '+s.proposal.request.patch.before.version+' → proposed '+s.proposal.request.patch.after.version+' · saved review '+short(s.proposal.revision)),node('p',s.proposal.request.patch.replacement));const impact=node('details');impact.append(node('summary','Review saved line and cut impact'));renderImpact(impact,s.proposal.impact);proposal.append(impact);
    if(s.stale){proposal.append(node('p','This proposal retains a different saved cut context. Your workflow is preserved. Open its original cut; if the screenplay or saved cuts changed, create a fresh proposal.'));if(onOpenSequence)button(row(proposal),'Open proposal’s original cut',()=>onOpenSequence(s.proposal.request.sequenceId),'open');}
  }
  function renderGeneration(s){generation.replaceChildren();generationAck=null;if(!s.proposal||s.acceptance)return;generation.append(node('h3','3. Generate and review actual media'));const actions=row(generation),final=s.proposal.request.candidate.stage==='final';if(final)button(actions,'Review preview generation',()=>store.quoteGeneration('preview'),'generation',!s.job&&!s.generationQuote);button(actions,final?'Review selective final generation':'Review revised film generation',()=>store.quoteGeneration('render'),final?'final-generation':'generation',!final&&!s.job&&!s.generationQuote);button(actions,'Load proposal generations',()=>store.loadJobs(),'read');
    if(s.generationQuote){const q=s.generationQuote;generation.append(node('h4',q.plan.request.role==='preview'?'Preview generation quote':'Revised film generation quote'),node('p',q.plan.shotReuse.forceShotIds.length+' shots to generate · '+q.plan.shotReuse.shots.length+' retained shots to reuse · '+time(q.totalFrames)),node('p','Estimated generation '+money(q.minimumEstimateUsd)+'–'+money(q.maximumEstimateUsd)+'. Reservation '+money(q.budgetReservedUsd)+'; job cost cap '+money(q.costCapUsd)+'.'));generationAck=acknowledgement(generation,'I reviewed these exact shots, generation settings and budget.',sync);button(row(generation),q.plan.request.role==='preview'?'Start preview generation':'Start revised film generation',()=>store.generate(),'submit-generation',true);}
    if(s.jobs.length){const list=node('div');jobPage=Math.min(jobPage,Math.floor((s.jobs.length-1)/PAGE));for(const item of s.jobs.slice(jobPage*PAGE,(jobPage+1)*PAGE)){const line=row(list);line.append(node('span',(item.livingScript.role==='preview'?'Preview':'Revised film')+' · '+item.status+' · '+short(item.id)));button(line,'Open '+(item.livingScript.role==='preview'?'preview':'film')+' '+short(item.id),()=>store.showJob(item.id),'read');}generation.append(list);if(s.jobs.length>PAGE){const pager=row(generation),back=button(pager,'Previous generations',()=>{jobPage--;render();}),next=button(pager,'Next generations',()=>{jobPage++;render();});back.dataset.edge=String(jobPage===0);next.dataset.edge=String((jobPage+1)*PAGE>=s.jobs.length);}}
  }
  function player(target,job,label){const wrapper=node('section');wrapper.className='living-script-player';wrapper.append(node('h4',label));const value=node('video');value.controls=true;value.playsInline=true;value.preload='metadata';value.src=assetUrl(job.output.mp4Url);value.setAttribute('aria-label',label);wrapper.append(value);target.append(wrapper);return value;}
  async function originalPlayback(){const s=store.state;if(!s.source)throw new Error('Load the actual source correspondence first.');const bound=s.source.sourceMap.revision,original=await jobRequest(s.source.sourceMap.before.sourceId,{});if(disposed||store.state.source?.sourceMap.revision!==bound)throw new Error('The selected source mapping changed.');if(original.id!==s.source.sourceMap.before.sourceId||original.projectId!==s.base.projectId||!original.output?.mp4Url)throw new Error('This original film is unavailable for direct playback. Use the complete parent-cut comparison.');originalVideo?.pause?.();const old=media.querySelector('[data-original-film]');old?.remove();const host=node('div');host.dataset.originalFilm='true';media.append(host);originalVideo=player(host,original,'Original source film');originalKey=bound;}
  function renderMedia(s){const next=s.job?JSON.stringify([s.job.id,s.job.status,s.job.outputRevision,s.decision?.review?.revision,s.decision?.approval?.at,s.source?.sourceMap?.revision]):null;if(next===mediaKey)return;mediaKey=next;video?.pause?.();originalVideo?.pause?.();video=null;originalVideo=null;originalKey=null;controls=controls.filter(({element})=>!media.contains(element));media.replaceChildren();decisionAck=null;if(!s.job)return;media.append(node('h4',(s.job.livingScript.role==='preview'?'Pending preview':'Revised source film')+' · '+s.job.status));
    if(s.job.status!=='done'){media.append(node('p',s.job.failureReason??s.job.cancelReason??'The worker reports this generation as '+s.job.status+'.'));button(row(media),'Check generation status',()=>store.showJob(s.job.id),'read',!['failed','cancelled'].includes(s.job.status));return;}
    if(s.job.output?.mp4Url)video=player(media,s.job,s.job.livingScript.role==='preview'?'Actual proposed-dialogue preview':'Actual revised source film');else media.append(node('p','Completed media is currently unavailable. Refresh this generation’s status.'));
    const actions=row(media);button(actions,'Refresh completed media',()=>{mediaKey=null;return store.showJob(s.job.id);},'read');if(s.job.livingScript.role==='preview'){button(actions,'Load exact preview review',()=>store.loadDecision(),'read',!s.decision);if(s.decision){media.append(node('p','Preview review '+short(s.decision.review.revision)+' · '+(s.decision.approval?'latest decision: '+s.decision.approval.decision:'no saved decision')));field(media,'Performance review note',s.reviewNote,value=>store.editNote(value),{type:'textarea',guard:'read'});decisionAck=acknowledgement(media,'I watched this exact preview and reviewed the changed performance.',sync);const decisions=row(media);button(decisions,'Approve actual preview',()=>store.decide('approved',store.state.reviewNote),'decision',!s.decision.approval);button(decisions,'Request performance changes',()=>store.decide('changes_requested',store.state.reviewNote),'decision');}}
    else{media.append(node('p','This player shows the revised source film. Map its retained ranges below, then compare the complete original and proposed cuts before acceptance.'));if(!s.source)button(actions,'Compare actual source timing and map the cut',()=>store.mapSource(),'map',true);if(s.source&&originalKey!==s.source.sourceMap.revision)button(actions,'Load original source film',originalPlayback,'read');}
  }
  function renderMapping(s){mapping.replaceChildren();if(!s.source||s.acceptance)return;mapping.append(node('h3','4. Map the revised film into an independent cut'));const m=s.source.sourceMap;mapping.append(node('p','Original '+time(m.before.frames)+' → actual revised '+time(m.after.frames)+' · '+m.durationDeltaFrames+' frame duration change.'));
    listing(mapping,'Actual shot correspondence',m.shots,item=>item.shotId+' · '+item.treatment+' · source '+(item.before?item.before.startFrame+'–'+item.before.endFrame:'new')+' → '+(item.after?item.after.startFrame+'–'+item.after.endFrame:'removed')+' · '+(item.durationDeltaFrames??0)+' frame change.');
    listing(mapping,'Changed line timing',m.entries.filter(entry=>entry.patched||entry.measuredSpeechChanged||entry.captionWindowsChanged),entry=>(entry.before.character??entry.before.kind)+': '+entry.before.text+' → '+entry.after.text+' · '+(entry.measuredSpeechChanged?'measured speech changed':'measured speech retained')+' · '+(entry.captionWindowsChanged?'caption windows changed':'caption windows retained')+'.');listing(mapping,'Source correspondence notes',s.source.warnings,value=>value);
    const actions=row(mapping);button(actions,livingScriptSameClock(m)?'Suggest mappings for matching source timing':'Check conservative mapping suggestions',()=>store.suggestMapping(),'mapping');mapping.append(node('p','Suggestions remain draft choices. Every selected-source clip must be replaced or explicitly removed. Related dialogue and sound work must be reviewed separately.'));
    field(mapping,'Independent revised cut name',s.cutName,value=>store.editMapping(null,'cutName',value),{guard:'mapping'});field(mapping,'Revised cut length in frames (blank keeps parent length)',s.cutLength,value=>store.editMapping(null,'cutLength',value),{type:'integer',guard:'mapping'});
    rowPage=Math.min(rowPage,Math.max(0,Math.ceil(s.rows.length/PAGE)-1));for(const item of s.rows.slice(rowPage*PAGE,(rowPage+1)*PAGE)){const card=node('article');card.className='living-script-mapping';card.append(node('h4',item.lane),node('p','Original output start '+time(item.originalAt)+(item.related?' · derived performance or sound source':'')+'.'));listing(card,'Range review notes',item.notes,value=>value);
      field(card,'Treatment for '+item.lane,item.action,value=>store.editMapping(item.id,'action',value),{options:[['unresolved','Choose a treatment'],...(!item.related?[['replace','Replace with revised film']]:[]),['delete','Remove these retained clips']],guard:'mapping'});
      const fields=row(card);field(fields,'Revised source in-frame',item.from,value=>store.editMapping(item.id,'from',value),{type:'integer',guard:'mapping'});field(fields,'Output clip length',item.frames,value=>store.editMapping(item.id,'frames',value),{type:'integer',guard:'mapping'});field(fields,'Output start frame',item.at,value=>store.editMapping(item.id,'at',value),{type:'integer',guard:'mapping'});
      const advanced=node('details');advanced.append(node('summary','Speed, linked tracks and masks'));field(advanced,'Speed treatment',item.timing,value=>store.editMapping(item.id,'timing',value),{options:[['preserve','Preserve complete speed curve and source phase'],['normal','Reset to normal speed']],guard:'mapping'});field(advanced,'Move later clips when duration changes',item.ripple,value=>store.editMapping(item.id,'ripple',value),{type:'checkbox',guard:'mapping'});if(item.requiresUnlink)field(advanced,'Unlink this mixed-source clip for independent mapping',item.unlink,value=>store.editMapping(item.id,'unlink',value),{type:'checkbox',guard:'mapping'});if(item.hasMasks)field(advanced,'Source mask treatment',item.maskAction,value=>store.editMapping(item.id,'maskAction',value),{options:[['choose','Choose after reviewing masks'],['rebind','Rebind masks to the revised source'],['remove','Remove source masks']],guard:'mapping'});card.append(advanced);
      const order=row(card),at=s.rows.findIndex(value=>value.id===item.id),up=button(order,'Move this mapping earlier',()=>store.moveMapping(item.id,-1),'mapping'),down=button(order,'Move this mapping later',()=>store.moveMapping(item.id,1),'mapping');up.dataset.edge=String(at===0);down.dataset.edge=String(at===s.rows.length-1);mapping.append(card);
    }
    if(s.rows.length>PAGE){const pager=row(mapping);pager.append(node('span','Mappings '+(rowPage*PAGE+1)+'–'+Math.min((rowPage+1)*PAGE,s.rows.length)+' of '+s.rows.length));const back=button(pager,'Previous mappings',()=>{rowPage--;render();},'mapping'),next=button(pager,'Next mappings',()=>{rowPage++;render();},'mapping');back.dataset.edge=String(rowPage===0);next.dataset.edge=String((rowPage+1)*PAGE>=s.rows.length);}
    const reviewActions=row(mapping);button(reviewActions,'Review exact proposed cut',()=>store.reviewCut(),'mapping',!s.recut);button(reviewActions,'Discard browser mapping',()=>store.discard(),'discard');
  }
  function renderReview(s){review.replaceChildren();cutAck=null;if(!s.recut||s.acceptance)return;const r=s.recut.recut;review.append(node('h3','5. Compare and accept screenplay + cut'),node('p','Original saved cut '+time(r.parent.timeline.frames)+' → proposed cut '+time(r.afterTimeline.frames)+' · '+r.operations.length+' reviewed edits.'));
    listing(review,'Reviewed clip operations',r.operations,operation=>operation.kind+(operation.kind==='replace'?' · revised source in '+operation.from+' · '+operation.frames+' output frames · '+operation.timing+' speed'+(operation.maskAction?' · masks '+operation.maskAction:''):'')+'.');listing(review,'Revised line occurrences',r.mappedNewLineOccurrences,occurrence=>occurrence.lane+' '+occurrence.layer+' · '+time(occurrence.startFrame)+'–'+time(occurrence.endFrame)+' · '+(occurrence.evidence==='measured-speech'?'measured speech':'shot coverage')+(occurrence.held?' · held source position':'')+(occurrence.transition?' · transition handle':'')+'.');listing(review,'Recut review notes',r.warnings,value=>value);
    const comparisonText=node('p',comparison?.recutRevision===r.revision?comparison.message??(comparison.ready?'Complete cut comparison is ready. Review both cuts before accepting.':'Preparing the complete cut comparison…'):'Prepare and review the complete original/proposed cut comparison below.');comparisonText.dataset.comparisonStatus='true';review.append(comparisonText);
    cutAck=acknowledgement(review,'I compared both complete cuts and reviewed the changed dialogue, timing, captions, masks and sound. Save the screenplay and independent cut together.',sync);button(row(review),'Accept screenplay and revised cut',()=>store.accept(),'accept',true);
  }
  function renderSuccess(s){success.replaceChildren();if(!s.acceptance)return;const a=s.acceptance;success.append(node('h3','Accepted: '+a.name),node('p','Screenplay version '+a.beforeScript.version+' → '+a.afterScript.version+' · independent revised cut saved. The original cut and earlier exports remain available.'));const actions=row(success);if(onOpenSequence)button(actions,'Open revised cut and review export',()=>onOpenSequence(a.sequence.id),'read',true);button(actions,'Refresh accepted screenplay',()=>onAccepted({acceptance:structuredClone(a)}),'read');success.append(node('p','Use picture editorial to preview the accepted composition, review its render and explicitly select the completed project export.'));}
  function render(){if(disposed)return;const s=store.state;controls=controls.filter(({element})=>media.contains(element));primary=null;step.textContent='Step '+(s.acceptance?5:s.recut?5:s.source?4:s.proposal?3:s.lineQuote?2:1)+' of 5 · '+(s.acceptance?'Accepted independent cut':s.recut?'Complete cut comparison':s.source?'Explicit source mapping':s.proposal?'Generation and actual performance review':s.lineQuote?'Line and retained cut impact':'Physical dialogue revision');renderRecovery(s);renderLibrary(s);renderDraft(s);renderProposal(s);renderGeneration(s);renderMedia(s);renderMapping(s);renderReview(s);renderSuccess(s);sync();}
  const store=createLivingScriptState({request,jobRequest,current,onDirty,onAccepted,storage,onChange:(_state,kind)=>{if(kind==='guards')sync();else if(kind==='input'){if(lineAck)lineAck.checked=false;if(cutAck)cutAck.checked=false;if(!store.state.lineQuote)draft.querySelector('[data-impact-review]')?.remove();if(!store.state.recut)review.replaceChildren();sync();}else render();}});
  panel.addEventListener('toggle',()=>{if(!panel.open){pause();clearTimeout(poll);sync();return;}if(!store.state.list&&!store.state.pending&&!store.state.recovered&&!store.state.dirty&&!store.state.hydrating)void safe(()=>store.load())();sync();});
  return {panel,bind(){store.bind();sync();},selectLine(selection){store.selectLine(selection);panel.open=true;panel.scrollIntoView?.({block:'start'});},get unsaved(){return store.state.dirty||store.state.busy||store.state.hydrating;},get pending(){return store.state.pending;},comparisonStatus(value){const s=store.state;if(!s.recut||value?.recutRevision!==s.recut.recut.revision)return;comparison={...value,ready:value.ready===true};const label=review.querySelector('[data-comparison-status]');if(label)label.textContent=value.message??(comparison.ready?'Complete cut comparison is ready. Review both cuts before accepting.':'Preparing the complete cut comparison…');sync();},dispose(){if(disposed)return;disposed=true;clearTimeout(poll);pause();store.dispose();onRecutPreviewBinding(null);panel.remove();}};
}
