import {EDIT_COMPOSITE_LIMITS as limits} from '../../planner/src/edit-composite-types';
import {validateEditComposite,editCompositeGraph} from '../../planner/src/edit-composite';
import {rasterEditMasksAsync} from '../../planner/src/edit-composite-sampling';
import {emptyComposite,newMask,setMaskKey,deleteMaskKey,editPolygonTopology,reorderMask,maskGeometryAt,maskDraftKey,maskDraftRecord,inspectMaskDraft} from './mask-draft.js';
import {mountMaskViewport,MASK_STEP_SENTENCE} from './mask-viewport.js';

const node=(tag,text)=>{const value=document.createElement(tag);if(text!==undefined)value.textContent=text;return value;};
const group=(parent,label,open=false)=>{const value=node('details');value.append(node('summary',label));value.open=open;parent.append(value);return value;};
const row=parent=>{const value=node('div');value.className='result-actions';parent.append(value);return value;};
const options=(input,values,selected)=>{input.replaceChildren(...values.map(([value,label])=>new Option(label,String(value))));if(selected!==undefined)input.value=String(selected);};
const integer=(input)=>{if(input.value.trim()===''||!input.checkValidity()||!Number.isFinite(Number(input.value))){input.reportValidity();throw new Error('Enter a value within the displayed range.');}return Number(input.value);};

/** Draft authoring stays local. Saving creates one normal editorial history operation. */
export function mountMaskEditor({parent,saved,clip,projectId,loadSourceFrame,onDirty,onSave,onSavedPreview,canChange}){
  const source=saved.timeline.sources.find(s=>s.id===clip.sourceId),panel=group(parent,'Masks and mattes'),status=node('p'),recovery=node('div'),workspace=node('div'),controls=node('div');panel.className='mask-editor';panel.dataset.draftGroup='composite';status.setAttribute('role','status');workspace.className='mask-workspace';controls.className='mask-controls';panel.append(status,recovery,node('p','Masks follow original source frames, including restored handles and speed changes. Track mattes follow their own timeline timing.'),workspace,controls);
  let composite=structuredClone(clip.composite??emptyComposite()),frame=Math.min(source.frames-1,clip.from),selectedMask=composite.masks?.[0]?.id??null,selectedVertex=null,bitmap=null,coverage=null,disposed=false,changed=false,persistTimer=null,sourceRequest=null,serial=0,coverageVersion=0,recovered=null;
  const storageKey=maskDraftKey(projectId,saved.sequence.id,clip.id),tell=(text,error=false)=>{status.textContent=text;status.dataset.state=error?'error':'success';};
  function persist(){clearTimeout(persistTimer);if(!changed)return;try{localStorage.setItem(storageKey,JSON.stringify(maskDraftRecord(saved,clip,composite,frame,selectedMask,selectedVertex)));}catch{tell('This browser could not store recovery data. Keep this editor open until the draft is saved.',true);}}
  function dirty(){if(!canChange('composite'))throw new Error('Apply or discard the other open fields first.');changed=true;coverage=null;coverageVersion++;onDirty('composite',apply);clearTimeout(persistTimer);persistTimer=setTimeout(persist,150);tell('Unsaved masks and mattes. Apply this draft to save one history event.');}
  const run=(action,recoveryAction=false)=>async()=>{try{if(recovered&&!recoveryAction)throw new Error('Restore or discard the recovered mask draft first.');if(!canChange('composite'))throw new Error('Apply or discard the other open fields first.');await action();}catch(error){tell(error.message??'This mask change could not finish.',true);}};
  function button(parent,label,action,recoveryAction=false){const input=node('button',label);input.type='button';input.className='secondary';input.onclick=run(()=>{if(viewport.drawing&&!['Finish polygon','Discard mask draft'].includes(label))throw new Error('Finish the shape or press Escape before changing mask controls.');return action();},recoveryAction);parent.append(input);return input;}
  function field(parent,label,type,value,{min,max,step='any',change,draft=true}={}){const wrapper=node('div'),caption=node('label',label),input=node(type==='select'?'select':'input');wrapper.className='cast-field';input.id='mask-field-'+crypto.randomUUID();caption.htmlFor=input.id;if(type!=='select')input.type=type;if(type==='text'){input.required=true;input.maxLength=160;}if(type==='checkbox')input.checked=Boolean(value);else input.value=value??'';if(type==='number'){if(min!==undefined)input.min=String(min);if(max!==undefined)input.max=String(max);input.step=String(step);}if(draft)input.dataset.draftGroup='composite';if(change)input.addEventListener(type==='select'||type==='checkbox'?'change':'input',run(()=>{if(draft&&!canChange('composite'))throw new Error('Apply or discard the other open fields first.');if(viewport.drawing)throw new Error('Finish the shape or press Escape before changing mask fields.');if(draft)dirty();input.setCustomValidity('');try{if(!input.checkValidity()){input.reportValidity();throw new Error('Enter a value within the displayed range.');}change(type==='checkbox'?input.checked:type==='number'?integer(input):input.value);}catch(error){input.setCustomValidity(error.message);throw error;}paint();}));wrapper.append(caption,input);parent.append(wrapper);return input;}
  const currentMask=()=>composite.masks?.find(m=>m.id===selectedMask);
  function validate(){if(!composite.masks?.length)delete composite.masks;if(Object.keys(composite).length>1)validateEditComposite(composite,source,clip.layer);editCompositeGraph({clips:saved.timeline.clips.map(c=>c.id===clip.id?{...c,composite}:c),matteOnlyLayers:saved.timeline.matteOnlyLayers});}
  function replaceMask(mask){validateEditComposite({schema:'hv-edit-composite/1',masks:[{...mask,combine:'replace'}]},source,clip.layer);composite.masks=composite.masks.map(m=>m.id===mask.id?mask:m);dirty();}
  function geometryChanged(geometry){const mask=currentMask();if(!mask)return;replaceMask(setMaskKey(mask,frame,geometry,interpolation.value));drawGeometryFields();drawKeyChoices();paint();}
  const viewport=mountMaskViewport({parent:workspace,source,onGeometry:geometryChanged,onVertex:id=>{selectedVertex=id;drawGeometryFields();paint();},onError:message=>tell(message,true),canChange:()=>!recovered&&canChange('composite')});
  const view=field(workspace,'Mask viewport mode','select','',{draft:false});options(view,[['source','Original with draft outline'],['coverage','Draft mask coverage']],'source');view.onchange=()=>{paint();if(view.value==='coverage'&&!coverage)tell('Choose Refresh draft coverage to rasterize the current authored mask stack. Placement and track mattes appear in the saved composite.');};
  const frameControls=row(workspace),frameInput=field(workspace,'Original source frame','number',frame,{min:0,max:source.frames-1,step:1,draft:false});
  async function loadFrame(next=frame){if(viewport.drawing)throw new Error('Finish the shape or press Escape before changing source frames.');if(!Number.isSafeInteger(next)||next<0||next>=source.frames)throw new Error('Choose an original source frame from 0 to '+(source.frames-1)+'.');bitmap?.close();bitmap=null;viewport.image(null);frame=next;frameInput.value=String(frame);coverage=null;coverageVersion++;drawKeyChoices();drawGeometryFields();paint();sourceRequest?.abort();const controller=new AbortController(),attempt=++serial;sourceRequest=controller;tell('Loading original source frame '+frame+'…');try{const result=await loadSourceFrame({saved,sourceId:source.id,sourceFrame:frame,signal:controller.signal});if(disposed||attempt!==serial||controller.signal.aborted){result.bitmap.close();return;}if(result.sourceRevision!==source.revision||result.sourceFrame!==frame){result.bitmap.close();throw new Error('The original source identity changed. Reopen the saved sequence.');}bitmap?.close();bitmap=result.bitmap;viewport.image(bitmap);tell('Original source frame '+frame+' loaded. '+(changed?'The mask draft is not saved.':'Choose a mask or draw a new shape.'));}catch(error){if(controller.signal.aborted)return;bitmap?.close();bitmap=null;viewport.image(null);throw error;}}
  button(frameControls,'Previous source frame',()=>loadFrame(Math.max(0,frame-1)));button(frameControls,'Next source frame',()=>loadFrame(Math.min(source.frames-1,frame+1)));button(frameControls,'Load source frame',()=>loadFrame(integer(frameInput)));frameInput.onchange=run(()=>loadFrame(integer(frameInput)));
  const viewActions=row(workspace);button(viewActions,'Refresh draft coverage',async()=>{validate();const version=++coverageVersion,at=frame,masks=structuredClone(composite.masks??[]);tell('Preparing authored-mask coverage at original resolution…');const data=await rasterEditMasksAsync(masks,at,source.width,source.height,async()=>{if(disposed||version!==coverageVersion)throw new Error('Coverage changed. Refresh it for the current draft.');await new Promise(resolve=>setTimeout(resolve,0));});if(disposed||version!==coverageVersion)return;const surface=node('canvas');surface.width=source.width;surface.height=source.height;const ctx=surface.getContext('2d'),image=ctx.createImageData(source.width,source.height);for(let i=0;i<data.length;i++){const at=i*4;image.data[at]=data[i];image.data[at+1]=data[i];image.data[at+2]=data[i];image.data[at+3]=255;if(i%32768===0){await new Promise(resolve=>setTimeout(resolve,0));if(disposed||version!==coverageVersion)return;}}ctx.putImageData(image,0,0);coverage=surface;view.value='coverage';paint();tell('Draft mask coverage ready. White reveals the source; black removes it. Save to review placement and track mattes in the final composite.');});button(viewActions,'Show saved composite',()=>{if(changed)throw new Error('Apply or discard this draft before reviewing the saved composite.');return onSavedPreview(frame);});
  const masksBox=group(controls,'Mask stack',true),maskSelect=field(masksBox,'Selected mask','select','',{draft:false}),addRow=row(masksBox),kind=field(addRow,'New mask shape','select','',{draft:false});options(kind,[['rectangle','Rectangle'],['ellipse','Ellipse'],['polygon','Polygon']],'rectangle');button(addRow,'Add mask',()=>{if((composite.masks?.length??0)>=limits.masks)throw new Error('Use up to eight masks on one clip.');const mask=newMask(kind.value,source,frame);if(composite.masks?.length)mask.combine='union';(composite.masks??=[]).push(mask);selectedMask=mask.id;selectedVertex=mask.kind==='polygon'?mask.keyframes[0].geometry.points[0].id:null;dirty();drawMask();});
  maskSelect.onchange=run(()=>{if(viewport.drawing){maskSelect.value=selectedMask;throw new Error('Finish the shape or press Escape before selecting another mask.');}selectedMask=maskSelect.value;selectedVertex=null;drawMask();});const maskFields=node('div');masksBox.append(maskFields);const orderRow=row(masksBox);button(orderRow,'Move mask earlier',()=>{composite.masks=reorderMask(composite.masks??[],selectedMask,-1);dirty();drawMask();});button(orderRow,'Move mask later',()=>{composite.masks=reorderMask(composite.masks??[],selectedMask,1);dirty();drawMask();});button(orderRow,'Remove selected mask',()=>{composite.masks=composite.masks?.filter(m=>m.id!==selectedMask);if(composite.masks?.length)composite.masks[0].combine='replace';selectedMask=composite.masks?.[0]?.id??null;dirty();drawMask();});
  const keys=group(controls,'Source keyframes',true),keySelect=field(keys,'Saved draft keyframes','select','',{draft:false}),interpolation=field(keys,'Interpolation to next keyframe','select','',{change:value=>{const mask=currentMask();if(mask)replaceMask(setMaskKey(mask,frame,maskGeometryAt(mask,frame),value));}});options(interpolation,[['linear','Linear movement'],['hold','Hold until next key']],'linear');keySelect.onchange=run(()=>loadFrame(Number(keySelect.value)));
  const keyActions=row(keys);button(keyActions,'Previous keyframe',()=>{const mask=currentMask(),key=mask?.keyframes.filter(k=>k.sourceFrame<frame).at(-1);if(key)return loadFrame(key.sourceFrame);});button(keyActions,'Next keyframe',()=>{const key=currentMask()?.keyframes.find(k=>k.sourceFrame>frame);if(key)return loadFrame(key.sourceFrame);});button(keyActions,'Add or update keyframe',()=>{const mask=currentMask();if(!mask)throw new Error('Add a mask first.');replaceMask(setMaskKey(mask,frame,maskGeometryAt(mask,frame),interpolation.value));drawKeyChoices();paint();});button(keyActions,'Delete this keyframe',()=>{const mask=currentMask();if(!mask?.keyframes.some(k=>k.sourceFrame===frame))throw new Error('Choose an authored keyframe first.');replaceMask(deleteMaskKey(mask,frame));drawKeyChoices();drawGeometryFields();paint();});
  const geometryBox=group(controls,'Shape coordinates and vertices',true),geometryFields=node('div');geometryBox.append(node('p','Coordinates are pixels in the original source. Drag a corner or vertex in the viewport, or use these fields. '+MASK_STEP_SENTENCE),geometryFields);const geometryActions=row(geometryBox);button(geometryActions,'Draw shape in viewport',()=>{if(!currentMask())throw new Error('Add a mask first.');if(currentMask().kind==='polygon'&&currentMask().keyframes.length>1)throw new Error('Redraw a polygon before adding animation keys. Use the vertex controls to change an animated polygon across all keys.');dirty();viewport.draw();});button(geometryActions,'Finish polygon',()=>viewport.finishPolygon());
  const topology=group(geometryBox,'Change polygon topology at every keyframe'),propagate=field(topology,'I reviewed changes to every polygon keyframe','checkbox',false,{draft:false});const topologyActions=row(topology);for(const [action,label]of [['insert','Insert vertex after selection'],['remove','Remove selected vertex']])button(topologyActions,label,()=>{const mask=currentMask();if(!mask||mask.kind!=='polygon')throw new Error('Select a polygon mask.');if(mask.keyframes.length>1&&!propagate.checked)throw new Error('Review and confirm the vertex change at every keyframe.');const id=crypto.randomUUID();replaceMask(editPolygonTopology(mask,selectedVertex,action,id));selectedVertex=action==='insert'?id:currentMask().keyframes[0].geometry.points[0].id;propagate.checked=false;drawGeometryFields();paint();});
  const matteBox=group(controls,'Track matte and placement'),matteLayer=field(matteBox,'Matte picture layer','select','',{change:value=>{if(value==='none')delete composite.matte;else composite.matte={layer:Number(value),channel:matteChannel.value,invert:matteInvert.checked};}}),layers=[...new Set(saved.timeline.clips.filter(c=>c.lane==='picture'&&c.layer!==clip.layer).map(c=>c.layer))].sort();options(matteLayer,[['none','No track matte'],...layers.map(layer=>[layer,'Picture '+layer])],composite.matte?.layer??'none');
  const matteChannel=field(matteBox,'Matte channel','select','',{change:value=>{if(composite.matte)composite.matte.channel=value;}});options(matteChannel,[['alpha','Alpha coverage'],['luma','Luminance × alpha']],composite.matte?.channel??'alpha');const matteInvert=field(matteBox,'Invert track matte','checkbox',composite.matte?.invert??false,{change:value=>{if(composite.matte)composite.matte.invert=value;}});
  matteBox.append(node('p','A track matte samples its own timeline position. Gaps give zero coverage, or full coverage when inverted. Matte-only roles are saved in the separate track controls below.'));
  const placementEnabled=field(matteBox,'Position this foreground','checkbox',Boolean(composite.placement),{change:value=>{if(value)composite.placement={xQ16:0,yQ16:0,scaleQ16:65536,rotationMilliDegrees:0};else delete composite.placement;drawPlacement();}}),placementFields=node('div');matteBox.append(placementFields);
  function drawPlacement(){placementFields.replaceChildren();placementFields.hidden=!placementEnabled.checked;if(!composite.placement)return;for(const [key,label,min,max,divisor]of [['xQ16','Horizontal offset (% of timeline)',-100,200,655.36],['yQ16','Vertical offset (% of timeline)',-100,200,655.36],['scaleQ16','Foreground scale (%)',25,400,655.36],['rotationMilliDegrees','Clockwise rotation (degrees)',-360,360,1000]])field(placementFields,label,'number',composite.placement[key]/divisor,{min,max,step:'any',change:value=>{composite.placement[key]=Math.round(value*divisor);}});}
  const saveRow=row(controls),apply=button(saveRow,'Apply masks and mattes',async()=>{if(viewport.drawing)throw new Error('Finish or cancel the shape before applying this draft.');for(const input of panel.querySelectorAll('input[data-draft-group]'))if(!input.checkValidity()||input.type==='number'&&input.value.trim()===''){input.reportValidity();throw new Error('Correct the highlighted mask field before applying this draft.');}validate();await onSave({kind:'composite',clipId:clip.id,composite:Object.keys(composite).length>1?structuredClone(composite):null});});button(saveRow,'Discard mask draft',()=>{viewport.cancelDrawing();coverage=null;coverageVersion++;composite=structuredClone(clip.composite??emptyComposite());selectedMask=composite.masks?.[0]?.id??null;changed=false;clearTimeout(persistTimer);localStorage.removeItem(storageKey);recovered=null;recovery.replaceChildren();onDirty(null);drawMask();matteLayer.value=String(composite.matte?.layer??'none');matteChannel.value=composite.matte?.channel??'alpha';matteInvert.checked=composite.matte?.invert??false;placementEnabled.checked=Boolean(composite.placement);drawPlacement();tell('Draft discarded. Saved masks and mattes are unchanged.');});apply.classList.remove('secondary');
  function drawMask(){options(maskSelect,(composite.masks??[]).map((m,i)=>[m.id,(i+1)+'. '+m.label]),selectedMask);maskFields.replaceChildren();const mask=currentMask();if(mask){field(maskFields,'Mask label','text',mask.label,{change:value=>{currentMask().label=value;}});const combine=field(maskFields,'Combine with previous masks','select','',{change:value=>{currentMask().combine=value;}});options(combine,(composite.masks[0]===mask?[['replace','Start coverage']]:[['replace','Replace previous coverage'],['union','Union'],['intersect','Intersect'],['subtract','Subtract']]),mask.combine);field(maskFields,'Invert mask','checkbox',mask.invert,{change:value=>{currentMask().invert=value;}});field(maskFields,'Feather radius (source pixels)','number',mask.featherQ8/256,{min:0,max:128,step:1/256,change:value=>{currentMask().featherQ8=Math.round(value*256);}});}drawKeyChoices();drawGeometryFields();paint();}
  function drawKeyChoices(){const mask=currentMask();options(keySelect,(mask?.keyframes??[]).map(k=>[k.sourceFrame,'Source '+k.sourceFrame+' · '+k.interpolation]),mask?.keyframes.some(k=>k.sourceFrame===frame)?frame:undefined);const key=mask?.keyframes.find(k=>k.sourceFrame===frame)??mask?.keyframes.filter(k=>k.sourceFrame<=frame).at(-1)??mask?.keyframes[0];interpolation.value=key?.interpolation??'linear';}
  function drawGeometryFields(){geometryFields.replaceChildren();const mask=currentMask();topology.hidden=mask?.kind!=='polygon';if(!mask)return;const geometry=maskGeometryAt(mask,frame);if(mask.kind==='polygon'){if(!geometry.points.some(p=>p.id===selectedVertex))selectedVertex=geometry.points[0].id;const vertex=field(geometryFields,'Selected polygon vertex','select','',{draft:false});options(vertex,geometry.points.map((p,i)=>[p.id,'Vertex '+(i+1)]),selectedVertex);vertex.onchange=()=>{selectedVertex=vertex.value;drawGeometryFields();paint();};const point=geometry.points.find(p=>p.id===selectedVertex);for(const [key,label,size]of [['xQ16','Vertex X (source pixels)',source.width],['yQ16','Vertex Y (source pixels)',source.height]])field(geometryFields,label,'number',point[key]/65536*size,{min:-size,max:size*2,change:value=>{const next=maskGeometryAt(currentMask(),frame);next.points.find(p=>p.id===selectedVertex)[key]=Math.round(value/size*65536);replaceMask(setMaskKey(currentMask(),frame,next,interpolation.value));drawKeyChoices();}});}else for(const [key,label,size,isSize]of [['xQ16','Mask X (source pixels)',source.width,false],['yQ16','Mask Y (source pixels)',source.height,false],['widthQ16','Mask width (source pixels)',source.width,true],['heightQ16','Mask height (source pixels)',source.height,true]])field(geometryFields,label,'number',geometry[key]/65536*size,{min:isSize?size/65536:-size,max:size*(isSize?3:2),change:value=>{const next=maskGeometryAt(currentMask(),frame);next[key]=Math.round(value/size*65536);replaceMask(setMaskKey(currentMask(),frame,next,interpolation.value));drawKeyChoices();}});}
  function paint(){const mask=currentMask();viewport.set({geometry:mask?maskGeometryAt(mask,frame):null,kind:mask?.kind,selectedVertex,mode:view.value,frame,coverage});}
  function recover(){try{const raw=localStorage.getItem(storageKey);if(!raw)return;if(raw.length>limits.payloadBytes)throw new Error('The stored mask draft exceeds the supported size.');const value=JSON.parse(raw),state=inspectMaskDraft(value,saved,clip);if(state==='invalid')throw new Error('The stored mask draft cannot be restored.');recovered=value;recovery.append(node('p',state==='source-changed'?'A mask draft for this clip belongs to another original source. It is preserved here; reopen its saved branch to review it.':state==='stale'?'A recovered draft belongs to an earlier saved revision. Review it before applying it to this version.':'This clip has a recoverable unsaved mask draft.'));if(state!=='source-changed')button(recovery,state==='stale'?'Restore draft onto this saved clip':'Restore mask draft',()=>{if(Object.keys(value.composite).length>1)validateEditComposite(value.composite,source,clip.layer);composite=structuredClone(value.composite);frame=Math.max(0,Math.min(source.frames-1,Number.isSafeInteger(value.frame)?value.frame:clip.from));selectedMask=composite.masks?.some(m=>m.id===value.selectedMask)?value.selectedMask:composite.masks?.[0]?.id??null;selectedVertex=value.selectedVertex;frameInput.value=String(frame);recovery.replaceChildren();recovered=null;dirty();drawMask();matteLayer.value=String(composite.matte?.layer??'none');matteChannel.value=composite.matte?.channel??'alpha';matteInvert.checked=composite.matte?.invert??false;placementEnabled.checked=Boolean(composite.placement);drawPlacement();},true);button(recovery,'Discard stored mask draft',()=>{localStorage.removeItem(storageKey);recovery.replaceChildren();recovered=null;},true);}catch(error){recovered={invalid:true};tell(error.message,true);recovery.append(node('p','The stored mask draft is preserved. Discard it explicitly before starting another draft.'));button(recovery,'Discard stored mask draft',()=>{localStorage.removeItem(storageKey);recovery.replaceChildren();recovered=null;},true);}}
  drawMask();drawPlacement();recover();window.addEventListener('beforeunload',persist);panel.addEventListener('toggle',()=>{if(panel.open&&!bitmap&&!sourceRequest)void run(()=>loadFrame())();});
  return {panel,get changed(){return changed;},saved(){changed=false;clearTimeout(persistTimer);try{localStorage.removeItem(storageKey);}catch{}},dispose(){window.removeEventListener('beforeunload',persist);disposed=true;coverageVersion++;sourceRequest?.abort();persist();bitmap?.close();bitmap=null;coverage=null;viewport.dispose();},hasRecovery:()=>Boolean(recovered)};
}
