/**
 * The Composer's score (HV-024-02). With no music vendor in Release 1, the Composer writes its own
 * bed: a slow chord pad and bass from fixed tables, rendered by this code as a PCM WAV. No sample,
 * recording or model output is used, so the recording is the application's own, and its rights
 * record says exactly that. The bytes depend only on the recipe, so the same film always gets the
 * same file and the library keeps one copy.
 */
export const SCORE_RECIPE = Object.freeze({schema: "hv-crew-score/1", sampleRate: 48000, channels: 2, bars: 8, beatsPerBar: 4, peak: 0.25});

const MINOR_WORDS = /\b(dark|tense|sad|grim|melanchol\w*|noir|eerie|bleak|haunt\w*|ominous|mournful|lonely)\b/i;
const FAST_WORDS = /\b(tense|urgent|action|chase|frantic|fast|energetic|upbeat|playful)\b/i;
const SLOW_WORDS = /\b(quiet|calm|gentle|slow|warm|tender|hopeful|dreamy|soft|windswept)\b/i;
const NO_MUSIC = /\b(no music|without music|no score|silence|silent)\b/i;

/** The Composer's decision, from the tone and the creator's answers; never a setting the creator fills in. */
export function scoreDirection({tone = "", answers = []} = {}) {
  const refused = answers.some(answer => answer.persona === "sound" && !answer.accepted && NO_MUSIC.test(answer.reply ?? ""));
  const minor = MINOR_WORDS.test(tone);
  const bpm = FAST_WORDS.test(tone) ? 96 : SLOW_WORDS.test(tone) ? 72 : 80;
  return {enabled: !refused, mode: minor ? "minor" : "major", bpm, gainDb: -12, duckDb: -10};
}

// Semitones above A2 (110 Hz). Major: C Am F G. Minor: Am F C G.
const PROGRESSIONS = {
  major: [[3, 7, 10], [0, 3, 7], [8, 12, 15], [10, 14, 17]],
  minor: [[0, 3, 7], [8, 12, 15], [3, 7, 10], [10, 14, 17]],
};
const hz = semitone => 110 * 2 ** (semitone / 12);

/** A seamless loop: every bar's envelope starts and ends at zero; peaks at SCORE_RECIPE.peak (-12 dBFS). */
export function composeScore({mode = "major", bpm = 80} = {}) {
  const {sampleRate, bars, beatsPerBar, peak} = SCORE_RECIPE;
  if (!PROGRESSIONS[mode] || !Number.isInteger(bpm) || bpm < 40 || bpm > 160) throw new Error("Unknown score direction.");
  const barFrames = Math.round(sampleRate * 60 / bpm * beatsPerBar), frames = barFrames * bars;
  const left = new Float64Array(frames), right = new Float64Array(frames);
  const attack = Math.round(sampleRate * 0.6), release = Math.round(sampleRate * 0.9);
  for (let bar = 0; bar < bars; bar++) {
    const chord = PROGRESSIONS[mode][bar % 4], start = bar * barFrames;
    const voices = [...chord.map(note => ({f: hz(note + 12), a: 0.22})), {f: hz(chord[0]), a: 0.3}];
    for (let i = 0; i < barFrames; i++) {
      const envelope = Math.min(1, i / attack, (barFrames - 1 - i) / release);
      const t = i / sampleRate;
      let l = 0, r = 0;
      for (const [index, voice] of voices.entries()) {
        const tone = Math.sin(2 * Math.PI * voice.f * t) + 0.3 * Math.sin(4 * Math.PI * voice.f * t);
        const detune = Math.sin(2 * Math.PI * voice.f * 1.003 * t);
        const pan = voices.length > 1 ? index / (voices.length - 1) : 0.5;
        l += voice.a * (tone * (1 - 0.4 * pan) + 0.2 * detune);
        r += voice.a * (tone * (0.6 + 0.4 * pan) + 0.2 * detune);
      }
      left[start + i] = l * envelope; right[start + i] = r * envelope;
    }
  }
  let max = 0;
  for (let i = 0; i < frames; i++) max = Math.max(max, Math.abs(left[i]), Math.abs(right[i]));
  const scale = max ? peak / max : 0, bytes = new Uint8Array(44 + frames * 4), view = new DataView(bytes.buffer);
  const text = (offset, value) => { for (let i = 0; i < value.length; i++) bytes[offset + i] = value.charCodeAt(i); };
  text(0, "RIFF"); view.setUint32(4, 36 + frames * 4, true); text(8, "WAVE"); text(12, "fmt ");
  view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 2, true); view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * 4, true); view.setUint16(32, 4, true); view.setUint16(34, 16, true); text(36, "data"); view.setUint32(40, frames * 4, true);
  for (let i = 0; i < frames; i++) {
    view.setInt16(44 + i * 4, Math.round(left[i] * scale * 32767), true);
    view.setInt16(46 + i * 4, Math.round(right[i] * scale * 32767), true);
  }
  return bytes;
}

/** The library record for the score: the rights are the application's own, and it says so. */
export function scoreRecord(direction, expectedVersion) {
  return {label: `Composer score ${SCORE_RECIPE.schema} ${direction.mode} ${direction.bpm}`, expectedVersion,
    rights: {basis: "original", attested: true, credit: "Original score: Composer (AI crew)",
      source: `Generated by this application's Composer persona from recipe ${SCORE_RECIPE.schema}`,
      terms: "Generated by the application's own code from fixed chord tables; no third-party recording, sample or model output."}};
}
