/** Private point authoring. The overlay previews requested coordinates, not generated subject motion. */
export function initSubjectMotion({parent,request,image,download,prepare,canEdit,changed}) {
  let opener=null;
  const node=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
  const button=(text,action)=>{const e=node("button",text);e.type="button";e.className="secondary";e.onclick=action;return e;};
  const section=title=>{const e=node("fieldset");e.append(node("legend",title));return e;};
  const details=title=>{const e=node("details");e.append(node("summary",title));return e;};
  const panel=node("section"),title=node("h3","Plan subject motion"),source=node("p"),status=node("p"),form=node("form"),stage=button("",event=>place(event)),img=node("img"),svg=document.createElementNS("http://www.w3.org/2000/svg","svg");
  panel.hidden=true;panel.className="motion-workbench";form.noValidate=true;status.className="status";status.setAttribute("role","status");
  stage.className="motion-image-stage";stage.setAttribute("aria-label","Place selected point on source image; numeric position controls are also available");img.alt="Source image for requested subject motion";svg.setAttribute("viewBox","0 0 10000 10000");svg.setAttribute("preserveAspectRatio","none");svg.setAttribute("aria-hidden","true");stage.append(img,svg);
  const choose=section("1. Prepare the source image"),author=section("2. Place subjects and movement points"),saveSection=section("3. Save and export the movement plan");
  function field(parent,id,label,tag="input") {const wrapper=node("div"),caption=node("label",label),input=node(tag);wrapper.className="cast-field";input.id="motion-"+id;caption.htmlFor=input.id;wrapper.append(caption,input);parent.append(wrapper);return input;}
  const asset=field(choose,"source","Prepared private source","select"),upload=details("Prepare a new private image"),file=field(upload,"file","PNG or JPEG image"),orientation=field(upload,"orientation","Image orientation","select"),imageLabel=field(upload,"image-label","Image label"),permission=field(upload,"permission","I may use this image and share it with a selected rendering provider");
  file.type="file";file.accept="image/png,image/jpeg";permission.type="checkbox";imageLabel.maxLength=120;orientation.append(new Option("Landscape · 832 × 480","landscape"),new Option("Portrait · 480 × 832","portrait"));
  upload.append(node("p","The image is fitted within the selected frame, with black padding when needed. Place points after preparation. Changing the source keeps your coordinates for review and clears the source confirmation."));
  upload.append(button("Prepare private image",()=>run(async()=>{
    if(!context?.source)throw new Error("Restore or reload the source shot before preparing an image.");
    if(!file.files?.length||!permission.checked)throw new Error("Choose an image and confirm permission before preparing it.");
    await prepare();
    const response=await request(`/${shotId}/motion-image?maxShots=${maxShots}&orientation=${orientation.value}&label=${encodeURIComponent(imageLabel.value.trim()||"Movement source")}`,{method:"POST",body:file.files[0],headers:{"content-type":file.files[0].type,"x-hv-reference-attested":"true","x-hv-direction-version":String(context.directionVersion),"x-hv-script-version":String(context.scriptVersion),"x-hv-source-hash":context.source.sourceHash}});
    context.assets.push(response.asset);selectedAsset=response.asset.id;reviewed.checked=false;dirty=true;file.value="";permission.checked=false;renderAssets();await loadImage();tell("Private source prepared. Review the points on this image, then save the movement plan.");
  })));choose.append(upload);
  const subjectChoice=field(author,"subject","Selected subject","select"),label=field(author,"subject-label","Subject label"),character=field(author,"character","Cast association (optional)","select"),subjectActions=node("div");subjectActions.className="result-actions";label.maxLength=80;
  const addSubject=button("Add subject",()=>{if(!validPoint()||subjects.length>=6)return;const id=newId("subject",subjects);subjects.push({id,label:"Subject "+(subjects.length+1),tracks:[newTrack("point-1",subjects.length*300)]});selectedSubject=id;selectedTrack="point-1";selectedFrame=0;dirty=true;render();});
  const removeSubject=button("Remove subject",()=>{if(!validPoint()||!currentSubject())return;rememberRemoval();subjects=subjects.filter(s=>s.id!==selectedSubject);links=links.filter(l=>l.subjectId!==selectedSubject);selectedSubject=subjects[0]?.id??"";selectedTrack=subjects[0]?.tracks[0]?.id??"";selectedFrame=0;dirty=true;render();});
  subjectActions.append(addSubject,removeSubject);author.append(subjectActions);
  const points=details("Points on the selected subject"),trackChoice=field(points,"track","Selected point track","select"),trackActions=node("div");trackActions.className="result-actions";
  const addTrack=button("Add point track",()=>{if(!validPoint())return;const s=currentSubject();if(!s||s.tracks.length>=8)return;const id=newId("point",s.tracks);s.tracks.push(newTrack(id,subjects.indexOf(s)*300+s.tracks.length*100));selectedTrack=id;selectedFrame=0;dirty=true;render();});
  const removeTrack=button("Remove point track",()=>{if(!validPoint())return;const s=currentSubject();if(!s||s.tracks.length<=1)return;rememberRemoval();s.tracks=s.tracks.filter(t=>t.id!==selectedTrack);selectedTrack=s.tracks[0].id;selectedFrame=0;dirty=true;render();});trackActions.append(addTrack,removeTrack);points.append(trackActions,node("p","Place the first point visibly on its intended subject. Additional tracks can identify separate parts of the same subject. The model may not preserve identity or follow every position."));author.append(points,stage);
  const frameChoice=field(author,"keyframe","Selected keyframe","select"),position=section("Position of selected point"),x=field(position,"x","Horizontal position (%)"),y=field(position,"y","Vertical position (%)"),easing=field(position,"easing","Movement toward next keyframe","select"),visible=field(position,"visible","Point is visible from this keyframe");
  for(const input of [x,y]){input.type="number";input.min=0;input.max=100;input.step=.01;}visible.type="checkbox";easing.append(new Option("Linear","linear"),new Option("Smooth start and stop","smooth"));author.append(position);
  const more=details("Add or remove a keyframe"),newFrame=field(more,"new-frame","New keyframe time","select"),frameActions=node("div");frameActions.className="result-actions";
  const insert=button("Add keyframe",()=>{if(!validPoint())return;const t=currentTrack(),frame=Number(newFrame.value);if(!t||!Number.isInteger(frame)||t.keyframes.some(k=>k.frame===frame))return;const p=sample(t,frame);t.keyframes.push({frame,x:Math.round(p.x),y:Math.round(p.y),easing:"linear",visible:p.visible});t.keyframes.sort((a,b)=>a.frame-b.frame);selectedFrame=frame;scrub.value=String(frame);dirty=true;render();});
  const removeFrame=button("Remove keyframe",()=>{if(!validPoint()||selectedFrame===0||selectedFrame===80||!currentTrack())return;rememberRemoval();currentTrack().keyframes=currentTrack().keyframes.filter(k=>k.frame!==selectedFrame);selectedFrame=0;scrub.value="0";dirty=true;render();});frameActions.append(insert,removeFrame);more.append(frameActions);author.append(more);
  const scrub=field(author,"scrub","Preview requested position","input"),previewText=node("p");scrub.type="range";scrub.min=0;scrub.max=80;scrub.step=1;scrub.value="0";scrub.oninput=()=>draw();author.append(previewText,node("p","This overlay shows requested point positions on a still source. Native generation is not running. Keyframes use a quarter-second grid; the final sample is at 5 seconds."));
  const prompt=field(saveSection,"prompt","Motion prompt","textarea"),seed=field(saveSection,"seed","Seed"),reviewed=field(saveSection,"reviewed","I reviewed these points on the chosen image and will use its appearance; cast portraits are not reapplied");prompt.rows=3;prompt.maxLength=2000;prompt.required=true;seed.type="number";seed.min=0;seed.max=2147483647;seed.step=1;seed.required=true;reviewed.type="checkbox";reviewed.required=true;
  const actions=node("div"),save=node("button","Save movement plan"),exportButton=button("Download native inputs",()=>run(async()=>{if(dirty||!context.study||context.staleReason)throw new Error("Review and save this movement plan before exporting it.");const blob=await download(shotId,context.study.revision),url=URL.createObjectURL(blob),a=node("a");a.href=url;a.download=shotId+"-movement-inputs.tar.gz";a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);tell("Native input packet downloaded. It contains the source, requested tracks and saved context; generated video remains pending.");}));save.type="submit";actions.className="result-actions";actions.append(save,exportButton);saveSection.append(actions);
  const undo=button("Undo last removal",()=>{if(!undoState)return;({subjects,links,selectedSubject,selectedTrack,selectedFrame}=structuredClone(undoState));undoState=null;dirty=true;render();});undo.hidden=true;
  const discard=button("Discard movement draft",()=>{fill(context.study);dirty=false;panel.hidden=true;tell("Movement draft discarded.");/* HV-039-17: closing returns focus to the control that opened the panel; hiding the panel with focus inside it left focus on the page body. */if(opener?.isConnected&&!opener.disabled)opener.focus();});
  const removeSaved=button("Remove saved movement plan",()=>run(async()=>{if(dirty)throw new Error("Save or discard the draft first.");if(!context.study)return;removedSaved=structuredClone(context.study);await request(`/${shotId}/subject-motion/remove`,{method:"POST",body:{expectedVersion:context.version,revision:context.study.revision}});context=await readContext();fill(null);await changed();restoreSaved.hidden=false;tell("Saved movement plan removed. Restore it below if needed; the private image is retained.");}));
  const restoreSaved=button("Restore removed plan as draft",()=>{if(!removedSaved||dirty)return;fill(removedSaved);dirty=true;restoreSaved.hidden=true;tell("Removed plan restored as a draft. Review its source and save to keep it.");});restoreSaved.hidden=true;
  const toolbar=node("div");toolbar.className="result-actions";toolbar.append(button("Reload movement context",()=>reload(true)),discard,undo);
  const savedControls=details("Saved plan controls");savedControls.append(removeSaved,restoreSaved);form.append(choose,author,saveSection);panel.append(title,source,node("p","Save a movement plan for native rendering preparation. These plans are not applied to film previews or finals yet."),toolbar,form,savedControls,status);parent.append(panel);
  let context=null,shotId="",maxShots=24,subjects=[],links=[],selectedSubject="",selectedTrack="",selectedFrame=0,selectedAsset="",busy=false,dirty=false,undoState=null,removedSaved=null,imageUrl=null,imageGeneration=0,loadedAsset="";
  const tell=(text,error=false)=>{status.textContent=text;status.dataset.state=error?"error":"success";};
  const currentSubject=()=>subjects.find(s=>s.id===selectedSubject),currentTrack=()=>currentSubject()?.tracks.find(t=>t.id===selectedTrack),currentFrame=()=>currentTrack()?.keyframes.find(k=>k.frame===selectedFrame);
  const time=frame=>`${(frame/16).toFixed(2)} seconds · frame ${frame}`;
  const newId=(prefix,values)=>{let i=1;while(values.some(v=>v.id===prefix+"-"+i))i++;return prefix+"-"+i;};
  const newTrack=(id,offset)=>{let x=4000+offset;while(subjects.some(s=>s.tracks.some(t=>t.keyframes[0].x===x&&t.keyframes[0].y===5000)))x=(x+100)%10001;return {id,keyframes:[0,80].map(frame=>({frame,x,y:5000,easing:"linear",visible:true}))};};
  function rememberRemoval(){undoState=structuredClone({subjects,links,selectedSubject,selectedTrack,selectedFrame});undo.hidden=false;}
  function sample(track,frame){let i=0;while(i+1<track.keyframes.length&&track.keyframes[i+1].frame<=frame)i++;const a=track.keyframes[i],b=track.keyframes[i+1];if(!b)return a;let t=(frame-a.frame)/(b.frame-a.frame);if(a.easing==="smooth")t=t*t*(3-2*t);return {x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,visible:a.visible};}
  function validPoint(){if(!currentFrame())return true;for(const input of [x,y])if(!input.disabled&&(input.value===""||!input.checkValidity())){tell("Keep a position from 0 to 100 percent before changing the selection.",true);input.reportValidity();return false;}return true;}
  function renderAssets(){asset.replaceChildren(new Option("Choose a prepared image",""));for(const a of context?.assets??[])asset.append(new Option((a.source?.label||"Private image")+` · ${a.width} × ${a.height}`+(a.source?.sourceHash!==context.source?.sourceHash?" · earlier source":""),a.id));asset.value=selectedAsset;}
  async function loadImage(){const generation=++imageGeneration;draw();if(loadedAsset===selectedAsset&&imageUrl)return;if(imageUrl)URL.revokeObjectURL(imageUrl);imageUrl=null;loadedAsset="";img.removeAttribute("src");stage.hidden=true;if(!selectedAsset)return;
    try{const blob=await image(selectedAsset);if(generation!==imageGeneration)return;imageUrl=URL.createObjectURL(blob);loadedAsset=selectedAsset;img.src=imageUrl;stage.hidden=false;draw();}catch(error){if(generation===imageGeneration)tell(error.message,true);}}
  function fill(study){subjects=structuredClone(study?.plan.subjects??[]);links=structuredClone(study?.links??[]);selectedAsset=study?.asset.id??"";selectedSubject=subjects[0]?.id??"";selectedTrack=subjects[0]?.tracks[0]?.id??"";selectedFrame=0;scrub.value="0";prompt.value=study?.plan.prompt??"";seed.value=String(study?.plan.seed??7);reviewed.checked=Boolean(study&&!context.staleReason&&study.scriptVersion===context.scriptVersion&&study.castingRevision===context.castingRevision&&study.directionRevision===context.directionRevision&&study.sourceHash===context.source?.sourceHash);undoState=null;undo.hidden=true;render();renderAssets();void loadImage();}
  function render(){
    source.textContent=(context?.source?"Current source · "+context.source.source.id+": "+context.source.source.prompt:"Source shot is no longer in this screenplay.")+(context?.staleReason?"\nSaved plan needs review: "+context.staleReason:"");
    subjectChoice.replaceChildren(new Option("Choose a subject",""));for(const s of subjects)subjectChoice.append(new Option(s.label||s.id,s.id));subjectChoice.value=selectedSubject;
    const s=currentSubject(),t=currentTrack(),k=currentFrame();label.value=s?.label??"";character.replaceChildren(new Option("Object or unlinked subject",""));for(const c of context?.characters??[])character.append(new Option(c.name,c.id));const association=links.find(l=>l.subjectId===selectedSubject);if(association&&!context?.characters.some(c=>c.id===association.characterId))character.append(new Option("Earlier cast association",association.characterId));character.value=association?.characterId??"";
    trackChoice.replaceChildren();for(const t of s?.tracks??[])trackChoice.append(new Option(t.id,t.id));trackChoice.value=selectedTrack;frameChoice.replaceChildren();for(const k of t?.keyframes??[])frameChoice.append(new Option(time(k.frame),String(k.frame)));frameChoice.value=String(selectedFrame);
    x.value=k?String(k.x/100):"";y.value=k?String(k.y/100):"";x.setCustomValidity("");y.setCustomValidity("");easing.value=k?.easing??"linear";visible.checked=k?.visible??true;
    newFrame.replaceChildren();for(let f=4;f<80;f+=4)if(!t?.keyframes.some(k=>k.frame===f))newFrame.append(new Option(time(f),String(f)));if([...newFrame.options].some(o=>o.value==="40"))newFrame.value="40";
    updateDisabled();draw();
  }
  function updateDisabled(){const s=currentSubject(),k=currentFrame();for(const e of [label,character,trackChoice,removeSubject])e.disabled=busy||!s;for(const e of [x,y,easing,frameChoice,newFrame])e.disabled=busy||!k;visible.disabled=busy||!k||selectedFrame===0;removeTrack.disabled=busy||!s||s.tracks.length<=1;removeFrame.disabled=busy||!k||[0,80].includes(selectedFrame);insert.disabled=busy||!k||!newFrame.options.length;addSubject.disabled=busy||subjects.length>=6;addTrack.disabled=busy||!s||s.tracks.length>=8;save.disabled=busy||!context?.source;exportButton.disabled=busy||dirty||!context?.study||Boolean(context?.staleReason);removeSaved.disabled=busy||!context?.study||dirty;}
  function draw(){svg.replaceChildren();const frame=Number(scrub.value),colors=["#d82724","#087fbe","#248137","#8358bf","#b36a00","#067b78"];
    for(const [index,s]of subjects.entries())for(const t of s.tracks){const poly=document.createElementNS(svg.namespaceURI,"polyline"),dot=document.createElementNS(svg.namespaceURI,"circle"),point=sample(t,frame);poly.setAttribute("points",Array.from({length:81},(_,f)=>{const p=sample(t,f);return p.x+","+p.y;}).join(" "));poly.setAttribute("fill","none");poly.setAttribute("stroke",colors[index]);poly.setAttribute("stroke-width",s.id===selectedSubject&&t.id===selectedTrack?"45":"22");poly.setAttribute("stroke-dasharray","70 40");dot.setAttribute("cx",point.x);dot.setAttribute("cy",point.y);dot.setAttribute("r","85");dot.setAttribute("stroke",colors[index]);dot.setAttribute("stroke-width","35");dot.setAttribute("fill",point.visible?colors[index]:"none");svg.append(poly,dot);}
    previewText.textContent=`Requested positions at ${time(frame)}. Filled points are visible; hollow points are hidden. This is a planning overlay.`;
    exportButton.disabled=busy||dirty||!context?.study||Boolean(context?.staleReason);removeSaved.disabled=busy||!context?.study||dirty;
  }
  function place(event){if(busy||!currentFrame()||!img.complete||!img.naturalWidth||!validPoint())return;if(event.detail===0){x.focus();return;}const r=stage.getBoundingClientRect(),k=currentFrame();k.x=Math.round(Math.max(0,Math.min(10000,(event.clientX-r.left)/r.width*10000)));k.y=Math.round(Math.max(0,Math.min(10000,(event.clientY-r.top)/r.height*10000)));x.value=String(k.x/100);y.value=String(k.y/100);dirty=true;draw();}
  for(const [input,key]of [[x,"x"],[y,"y"]])input.oninput=()=>{dirty=true;const n=Number(input.value),valid=input.value!==""&&Number.isFinite(n)&&n>=0&&n<=100;input.setCustomValidity(valid?"":"Choose a position from 0 to 100 percent.");if(valid&&currentFrame())currentFrame()[key]=Math.round(n*100);draw();};
  label.oninput=()=>{if(currentSubject()){currentSubject().label=label.value;dirty=true;subjectChoice.selectedOptions[0].textContent=label.value||selectedSubject;draw();}};
  character.onchange=()=>{links=links.filter(l=>l.subjectId!==selectedSubject);if(character.value)links.push({subjectId:selectedSubject,characterId:character.value});dirty=true;draw();};
  easing.onchange=()=>{if(currentFrame())currentFrame().easing=easing.value;dirty=true;draw();};visible.onchange=()=>{if(currentFrame())currentFrame().visible=visible.checked;dirty=true;draw();};
  for(const input of [prompt,seed,reviewed])input.oninput=()=>{dirty=true;draw();};
  asset.onchange=()=>{if(!validPoint()){asset.value=selectedAsset;return;}selectedAsset=asset.value;reviewed.checked=false;dirty=true;void loadImage();};
  subjectChoice.onchange=()=>{if(!validPoint()){subjectChoice.value=selectedSubject;return;}selectedSubject=subjectChoice.value;selectedTrack=currentSubject()?.tracks[0]?.id??"";selectedFrame=0;scrub.value="0";render();};
  trackChoice.onchange=()=>{if(!validPoint()){trackChoice.value=selectedTrack;return;}selectedTrack=trackChoice.value;selectedFrame=0;scrub.value="0";render();};
  frameChoice.onchange=()=>{if(!validPoint()){frameChoice.value=String(selectedFrame);return;}selectedFrame=Number(frameChoice.value);scrub.value=String(selectedFrame);render();};
  const readContext=()=>request(`/${shotId}/subject-motion?maxShots=${maxShots}`);
  async function run(action){if(busy)return;busy=true;tell("Working on the movement plan…");const controls=[...panel.querySelectorAll("button,input,textarea,select")],previous=controls.map(e=>e.disabled);controls.forEach(e=>{e.disabled=true;});try{await action();}catch(error){tell(error.message||"The movement operation failed. Your draft is still here.",true);}finally{busy=false;controls.forEach((e,i)=>{e.disabled=previous[i];});updateDisabled();}}
  async function reload(keep){if(!validPoint())return;await run(async()=>{await prepare();const next=await readContext();const changedContext=context&&(next.source?.sourceHash!==context.source?.sourceHash||next.castingRevision!==context.castingRevision||next.directionVersion!==context.directionVersion||next.scriptVersion!==context.scriptVersion);context=next;if(!keep||!dirty)fill(context.study);else{if(changedContext)reviewed.checked=false;render();renderAssets();}tell(keep&&dirty?"Draft kept. Review the latest source and cast context before saving.":context.staleReason||"Movement plan loaded.",Boolean(context.staleReason));});}
  form.onsubmit=event=>{event.preventDefault();if(!validPoint()||!form.reportValidity())return;void run(async()=>{if(!selectedAsset||!subjects.length||!reviewed.checked)throw new Error("Choose a source, add a subject and confirm the reviewed image.");const expected={version:context.version,scriptVersion:context.scriptVersion,directionVersion:context.directionVersion,castingRevision:context.castingRevision},input={sourceHash:context.source?.sourceHash,maxShots,assetId:selectedAsset,appearance:"source-image",prompt:prompt.value,seed:Number(seed.value),subjects,links};await prepare();await request(`/${shotId}/subject-motion`,{method:"PUT",body:{input,expected}});context=await readContext();dirty=false;fill(context.study);await changed();tell("Movement plan saved. Download its native input packet when ready; film renders do not apply this plan yet.");});};
  return {get unsaved(){return dirty||busy;},async open(plan,limit=24){if(!panel.contains(document.activeElement))opener=document.activeElement;if(!canEdit())return tell("Save or cancel the other shot or take draft first.",true);if(dirty&&shotId!==plan.source.id)return tell("Save or discard this movement draft first.",true);shotId=plan.source.id;maxShots=limit;panel.hidden=false;if(!dirty)await reload(false);title.tabIndex=-1;title.focus();},close(){if(!dirty&&!busy)panel.hidden=true;}};
}
