import {expect,test} from "bun:test";
import {contentHash} from "../src/capabilities";
import {pictureSpans} from "../src/edit-picture";
import {editAssemblyStorageEstimate,assertEditAssemblyStorageEstimate,type EditAssemblyStorageBinding} from "../../planner/src/edit-assembly-resources";
import {editStorageEstimate,EDIT_STORAGE_LIMITS} from "../../planner/src/edit-resources";
import {createEditAssemblyPlan} from "../../planner/src/edit-assembly-clock";
import {applyEditOperation,editTimeline,type EditClip,type EditSource,type EditTimeline} from "../../planner/src/edit-timeline";
import type {EditAssemblyRange} from "../../planner/src/edit-assembly-types";

const source=(id='film',frames=300,width=64,height=48):EditSource=>({id,label:id,revision:contentHash(id),frames,width,height,audio:['mix','dialogue'],captions:[],voices:[],unmeasuredAudio:false});
const clip=(id:string,sourceId='film',at=0,from=0,frames=180,layer=0):EditClip=>({id,sourceId,lane:'picture',layer,link:null,at,from,frames,gainDb:0,opacity:1,crop:null,envelope:{from,frames,fadeIn:0,fadeOut:0}});
const timeline=(sources=[source()],clips=[clip('picture')],frames=180,width=64,height=48)=>editTimeline({schema:clips.some(c=>c.composite)?'hv-edit-timeline/2':'hv-edit-timeline/1',width,height,frames,sources,clips,markers:[]});
const range=(id:string,fromFrame:number,toFrame:number):EditAssemblyRange=>({id,fromFrame,toFrame,reason:'Keep this parent output.'});
const plan=(t:EditTimeline,ranges=[range('whole',0,t.frames)])=>createEditAssemblyPlan({sequenceId:'parent',historyRevision:contentHash('history'),timeline:t,sourceReceipts:t.sources.map(s=>({sourceId:s.id,receiptRevision:contentHash('receipt-'+s.id)}))},ranges);
const file=(id:string,index:number,bytes=1024)=>({path:`project/${id}/original-${index}.dat`,bytes,sha256:contentHash('artifact')});
function bindings(t:EditTimeline):EditAssemblyStorageBinding[]{return t.sources.map(facts=>({source:{facts,files:[file(facts.id,0)],audio:Object.fromEntries(facts.audio.map(lane=>[lane,{kind:'decode',path:`project/${facts.id}/original-0.dat`}]))}}));}

test('full-range assembly reproduces every existing capacity metric and counts exact parent span intersections',()=>{
  const t=applyEditOperation(timeline([source()],[clip('left','film',0,0,120),clip('right','film',120,180,60)]),{kind:'crossfade',leftId:'left',rightId:'right',linked:false,frames:7,alignment:'center',ids:{left:'dissolve'}}),b=bindings(t),p=plan(t),before=JSON.stringify({p,b}),base=editStorageEstimate(t,b),estimate=editAssemblyStorageEstimate(p,b);
  for(const key of Object.keys(base) as (keyof typeof base)[])expect(estimate[key]).toEqual(base[key]);expect(estimate.parts).toBe(4);expect(estimate.parts).toBe(pictureSpans(t).length);expect(estimate.parentFrames).toBe(180);expect(estimate.childFrames).toBe(180);expect(estimate.planRevision).toBe(p.revision);expect(estimate.limits).toEqual({outputBytes:48*1024**3,workspaceBytes:128*1024**3,files:80000,freeReserveBytes:512*1024**2});expect(()=>assertEditAssemblyStorageEstimate(estimate)).not.toThrow();
  const short=editAssemblyStorageEstimate(plan(t,[range('dissolve',118,122),range('cross-span',59,62),range('repeat',118,122)]),b);expect(short.parts).toBe(4);expect(short.childFrames).toBe(11);expect(short.originalBytes).toBe(base.originalBytes);expect(short.canonicalBytes).toBe(base.canonicalBytes);expect(short.laneBytes).toBe(7*(44+11*1600*6));expect(short.pictureBytes).toBe(11*64*48*3);expect(short.files).toBe(base.files-4-Math.ceil(180/30)+4+Math.ceil(11/30));expect(JSON.stringify({p,b})).toBe(before);
});

test('repeated ranges drive child media costs and preserve every one-frame selection seam',()=>{
  const t=timeline([source('film',30,1920,1080)],[clip('picture','film',0,0,30)],30,1920,1080),b=bindings(t),parent=editStorageEstimate(t,b),repeated=editAssemblyStorageEstimate(plan(t,Array.from({length:256},(_,i)=>range('r'+i,0,30))),b);
  expect(parent.outputBytes).toBeLessThan(EDIT_STORAGE_LIMITS.outputBytes);expect(repeated.parts).toBe(256);expect(repeated.childFrames).toBe(7680);expect(repeated.pictureBytes).toBe(parent.pictureBytes*256);expect(repeated.canonicalBytes).toBe(parent.canonicalBytes);expect(repeated.originalBytes).toBe(parent.originalBytes);expect(repeated.outputBytes).toBeGreaterThan(EDIT_STORAGE_LIMITS.outputBytes);expect(()=>assertEditAssemblyStorageEstimate(repeated)).toThrow('workspace estimate');
  const tiny=timeline([source('film',256)],[clip('picture','film',0,0,256)],256),oneFrame=editAssemblyStorageEstimate(plan(tiny,Array.from({length:256},(_,i)=>range('f'+i,i,i+1))),bindings(tiny));expect(oneFrame.parts).toBe(256);expect(oneFrame.parts).toBeGreaterThan(Math.ceil(oneFrame.childFrames/60));expect(oneFrame.files).toBe(1+2+256+Math.ceil(256/30)+2+32);
});

test('off-range native timing and matte effects retain the full parent scratch recipe and maximum frame buffers',()=>{
  const film=source('film',90),native:EditSource={...source('native',90,3840,2160),media:'graphic-rgba',audio:[]},outside=clip('outside','native',70,4,10,1);outside.timing={from:4,offset:0,points:[{frame:0,rate:0},{frame:10,rate:0}]};
  const plain=timeline([film,native],[clip('picture','film',0,0,90),outside],90),p=plan(plain,[range('opening',0,1)]),b=bindings(plain),base=editStorageEstimate(plain,b),nativeEstimate=editAssemblyStorageEstimate(p,b);
  expect(nativeEstimate.rgbaScratchBytes).toBe(base.rgbaScratchBytes);expect(nativeEstimate.rgbaScratchBytes).toBeGreaterThan(3840*2160*4*60*2);expect(nativeEstimate.retimingScratchBytes).toBe(base.retimingScratchBytes);expect(nativeEstimate.retimingScratchBytes).toBeGreaterThan(3840*2160*4*60*3);expect(nativeEstimate.compositeScratchBytes).toBeUndefined();
  const foreground=clip('foreground','film',60,0,10,2);foreground.composite={schema:'hv-edit-composite/1',matte:{layer:1,channel:'alpha',invert:false}};let masked=timeline([film,native],[clip('picture','film',0,0,90),outside,foreground],90);masked=applyEditOperation(masked,{kind:'matte-only',layers:[1]});const composite=editAssemblyStorageEstimate(plan(masked,[range('opening',0,1)]),bindings(masked)),parent=editStorageEstimate(masked,bindings(masked));
  expect(composite.rgbaScratchBytes).toBeUndefined();expect(composite.compositeScratchBytes).toBe(parent.compositeScratchBytes);expect(composite.compositeWorkingFrameBytes).toBe(parent.compositeWorkingFrameBytes);expect(composite.retimingScratchBytes).toBe(parent.retimingScratchBytes);expect(composite.workspaceBytes).toBe(composite.outputBytes*3+composite.retimingScratchBytes!+composite.compositeScratchBytes!);expect(composite.parts).toBe(1);
});

test('output, workspace and file capacity reject complete oversized estimates without truncating retained inventories',()=>{
  const t=timeline(),b=bindings(t);b[0]!.source.files=Array.from({length:7},(_,i)=>file('film',i,8*1024**3));const output=editAssemblyStorageEstimate(plan(t,[range('one',0,1)]),b);expect(output.originalBytes).toBe(56*1024**3);expect(()=>assertEditAssemblyStorageEstimate(output)).toThrow('workspace estimate');
  const big=source('big',3,3840,2160),c=clip('effect','big',2,0,1);c.composite={schema:'hv-edit-composite/1',placement:{xQ16:0,yQ16:0,scaleQ16:65536,rotationMilliDegrees:0}};const effect=timeline([big],[c],3,1920,1080),effectBindings=bindings(effect);effectBindings[0]!.source.files=Array.from({length:6},(_,i)=>file('big',i,7*1024**3));const workspace=editAssemblyStorageEstimate(plan(effect,[range('gap',0,1)]),effectBindings);expect(workspace.outputBytes).toBeLessThan(EDIT_STORAGE_LIMITS.outputBytes);expect(workspace.workspaceBytes).toBeGreaterThan(EDIT_STORAGE_LIMITS.workspaceBytes);expect(()=>assertEditAssemblyStorageEstimate(workspace)).toThrow('workspace estimate');
  const many=timeline([source('a',1),source('b',1),source('c',1)],[],1),inventories=bindings(many);for(const [i,binding]of inventories.entries())binding.source.files=Array.from({length:i===2?26652:26651},(_,n)=>file(binding.source.facts.id,n,1));const full=editAssemblyStorageEstimate(plan(many),inventories);expect(full.files).toBe(80000);expect(()=>assertEditAssemblyStorageEstimate(full)).not.toThrow();inventories[2]!.source.files.push(file('c',26652,1));const excess=editAssemblyStorageEstimate(plan(many),inventories);expect(excess.files).toBe(80001);expect(excess.originalBytes).toBe(full.originalBytes+1);expect(()=>assertEditAssemblyStorageEstimate(excess)).toThrow('too many source files');
});

test('capacity validates every canonical parent binding and refuses malformed arithmetic metadata or changed plans',()=>{
  const t=timeline([source('a'),source('b')],[clip('picture','a')]),p=plan(t),valid=bindings(t),changes:((b:any)=>void)[]=[b=>b.pop(),b=>b.reverse(),b=>b[1]=b[0],b=>b[0].source.facts={...b[0].source.facts,frames:1},b=>b[0].source.files=[],b=>b[0].source.files[0].bytes=-1,b=>b[0].source.files[0].bytes=0,b=>b[0].source.files[0].bytes=NaN,b=>b[0].source.files[0].bytes=Infinity,b=>b[0].source.files[0].bytes=.5,b=>b[0].source.files[0].bytes=8*1024**3+1,b=>b[0].source.files.push(b[0].source.files[0]),b=>b[0].source.files[0].path='../escape',b=>b[0].source.files[0].sha256='bad',b=>b[0].source.audio={},b=>b[0].source.audio.music={kind:'film-dialogue'},b=>b[0].source.audio.mix={kind:'copy48',path:'missing.wav'},b=>b[0].source.audio.mix={kind:'invented'}];
  for(const change of changes){const bad=structuredClone(valid);change(bad);expect(()=>editAssemblyStorageEstimate(p,bad)).toThrow();}expect(()=>editAssemblyStorageEstimate(p,[])).toThrow('every retained');const changed=structuredClone(p);changed.frames--;expect(()=>editAssemblyStorageEstimate(changed,valid)).toThrow('changed');
  const estimate=editAssemblyStorageEstimate(p,valid);estimate.limits.outputBytes=0 as any;expect(EDIT_STORAGE_LIMITS.outputBytes).toBe(48*1024**3);expect(editAssemblyStorageEstimate(p,valid).limits.outputBytes).toBe(48*1024**3);
});
