import {expect,test} from "bun:test";
import {applyEditOperation,initialEditTimeline,type EditSource,type EditTimeline} from "../../planner/src/edit-timeline";
import {appendEdit,createEditHistory,editHistoryReplay,moveEditCursor} from "../../planner/src/edit-history";
import {EditTime} from "../../planner/src/edit-time";
import {editGainQ20,editGainScale} from "../../planner/src/edit-sampling";
const source=(id="first"):EditSource=>({id,revision:"a".repeat(64),label:id,frames:90,width:64,height:48,audio:["mix"],captions:[],voices:[],unmeasuredAudio:true});
const fixture=()=>initialEditTimeline([source(),source("next")],"first",64,48);
const copy=(t:EditTimeline,at=t.frames,ripple=true)=>applyEditOperation(t,{kind:"duplicate",clipId:"initial-0",linked:true,at,ripple,ids:{"initial-0":"copy-picture","initial-1":"copy-mix","initial-2":"copy-captions"},link:"copy"});
const replacement={kind:"replace" as const,clipId:"initial-0",linked:true,sourceId:"next",from:0,frames:90,timing:"preserve" as const,ripple:true};
test("duplicates preserve per-track settings and source clocks with new identities, ripple and undo",()=>{
  let t=applyEditOperation(fixture(),{kind:"settings",clipId:"initial-1",gainDb:-6,opacity:1,crop:null,fadeIn:20,fadeOut:10});t=applyEditOperation(t,{kind:"marker",marker:{id:"m",frame:45,label:"Original beat"}});const untouched=structuredClone(t),duplicated=copy(t,0);
  expect(t).toEqual(untouched);expect(duplicated.frames).toBe(180);expect(duplicated.markers[0]!.frame).toBe(135);for(const c of t.clips){const cloned=duplicated.clips.find(x=>x.id==="copy-"+c.lane)!;expect(cloned).toEqual({...c,id:cloned.id,link:"copy"});expect(duplicated.clips.find(x=>x.id===c.id)!.at).toBe(90);}
  let h=createEditHistory("history",t);h=appendEdit(h,{kind:"duplicate",clipId:"initial-0",linked:true,at:90,ripple:true,ids:{"initial-0":"p","initial-1":"a","initial-2":"c"},link:"another"},"Copy take",h.revision);h=moveEditCursor(h,0,"undo","Restore",h.revision);expect(editHistoryReplay(h).state.timeline).toEqual(t);
  expect(()=>copy(t,45)).toThrow("ripple boundary");expect(()=>copy(t,90,false)).toThrow();expect(()=>copy(duplicated)).toThrow("fresh group");
});
test("replacement of split ramps preserves fractional sample phase and inherited fades near source zero",()=>{
  let t=applyEditOperation(fixture(),{kind:"settings",clipId:"initial-1",gainDb:-6,opacity:1,crop:null,fadeIn:20,fadeOut:10});t=applyEditOperation(t,{kind:"retime",clipId:"initial-0",linked:true,from:5,frames:60,points:[{frame:0,rate:0},{frame:60,rate:2000}],ripple:true});
  t=applyEditOperation(t,{kind:"split",clipId:"initial-0",linked:true,at:23,rightIds:{"initial-0":"right-picture","initial-1":"right-mix","initial-2":"right-captions"},rightLink:"right"});const before=t.clips.find(c=>c.id==="right-mix")!,original=new EditTime(before),replaced=applyEditOperation(t,{...replacement,clipId:"right-picture",from:0,frames:37}),after=replaced.clips.find(c=>c.id===before.id)!,clock=new EditTime(after);
  expect(after.timing!.from).toBeLessThan(0);expect(after.gainDb).toBe(-6);expect(after.link).toBe(before.link);expect(after.at).toBe(before.at);expect(after.sourceId).toBe("next");expect(clock.source(after.at*1600)%1600).toBe(original.source(before.at*1600)%1600);
  for(let at=before.at*1600;at<(before.at+before.frames)*1600;at+=997){expect(clock.source(at)).toBe(original.source(at)-before.from*1600);expect(editGainQ20(after,clock.phase(at),editGainScale(after))).toBe(editGainQ20(before,original.phase(at),editGainScale(before)));}
  const normal=applyEditOperation(replaced,{...replacement,clipId:"right-picture",frames:37,timing:"normal"}).clips.find(c=>c.id===before.id)!;expect(normal.timing).toBeUndefined();expect(new EditTime(normal).source(normal.at*1600)).toBe(0);expect(editGainQ20(normal,new EditTime(normal).phase(normal.at*1600),editGainScale(normal))).toBe(editGainQ20(before,original.phase(before.at*1600),editGainScale(before)));
  const copied=applyEditOperation(replaced,{kind:"duplicate",clipId:"right-picture",linked:true,at:60,ids:{"right-picture":"p","right-mix":"a","right-captions":"c"},link:"last",ripple:true}).clips.find(c=>c.id==="a")!;expect(new EditTime(copied).source(60*1600)).toBe(clock.source(23*1600));
});
test("shorter replacement reanchors fades and ripples following clips and markers without changing source facts",()=>{
  let t=applyEditOperation(fixture(),{kind:"settings",clipId:"initial-1",gainDb:-3,opacity:1,crop:null,fadeIn:5,fadeOut:10});t=copy(t);t=applyEditOperation(t,{kind:"marker",marker:{id:"later",frame:100,label:"Later"}});const replaced=applyEditOperation(t,{...replacement,frames:30,from:10});expect(replaced.frames).toBe(120);expect(replaced.markers[0]!.frame).toBe(40);expect(replaced.clips.find(c=>c.id==="copy-picture")!.at).toBe(30);expect(replaced.sources).toEqual(t.sources);expect(replaced.clips.find(c=>c.id==="initial-1")!.envelope).toEqual({from:10,frames:30,fadeIn:5,fadeOut:10});expect(()=>applyEditOperation(t,{...replacement,frames:10})).toThrow("Fade");
});
test("take edits refuse missing lanes, invalid handles/crops, unlinked selections and identity reuse atomically",()=>{
  const t=fixture(),before=structuredClone(t);for(const patch of [{sourceId:"missing"},{from:80},{linked:false}])expect(()=>applyEditOperation(t,{...replacement,...patch})).toThrow();expect(t).toEqual(before);
  const noAudio=initialEditTimeline([source(),{...source("next"),audio:[]}],"first",64,48);expect(()=>applyEditOperation(noAudio,replacement)).toThrow("waveform");const smaller=initialEditTimeline([source(),{...source("next"),width:32,height:16}],"first",64,48),cropped=applyEditOperation(smaller,{kind:"settings",clipId:"initial-0",gainDb:0,opacity:.5,crop:{x:0,y:0,width:64,height:48},fadeIn:0,fadeOut:0});expect(()=>applyEditOperation(cropped,replacement)).toThrow("Crop");
  expect(()=>applyEditOperation(t,{kind:"duplicate",clipId:"initial-0",linked:true,at:90,ids:{"initial-0":"initial-0","initial-1":"a","initial-2":"c"},link:"copy",ripple:true})).toThrow("Duplicate clip");
});
test("source admission is branch-local while the immutable global catalog retains abandoned originals",()=>{
  const root=initialEditTimeline([source()],"first",64,48),initial=createEditHistory("history",root),op={kind:"source" as const,source:source("next"),receiptRevision:"b".repeat(64)};let h=appendEdit(initial,op,"New take",initial.revision);expect(h.root).toEqual(root);expect(editHistoryReplay(h).catalog).toHaveLength(2);h=moveEditCursor(h,0,"undo","Undo admission",h.revision);expect(editHistoryReplay(h).state.timeline.sources).toHaveLength(1);expect(editHistoryReplay(h).catalog).toHaveLength(2);
  for(const patch of [{receiptRevision:"c".repeat(64)},{source:{...op.source,frames:91}}])expect(()=>appendEdit(h,{...op,...patch},"Conflicting original",h.revision)).toThrow("changed between");h=appendEdit(h,op,"Admit on alternate branch",h.revision);expect(editHistoryReplay(h).catalog).toHaveLength(2);expect(editHistoryReplay(h).receipts).toEqual({next:op.receiptRevision});expect(h.events.filter(e=>e.kind==="edit")).toHaveLength(2);
});
test("source catalog cap counts originals on discarded branches and validates receipt hashes",()=>{
  let h=createEditHistory("history",initialEditTimeline([source()],"first",64,48));for(let i=0;i<15;i++){h=appendEdit(h,{kind:"source",source:source("take-"+i),receiptRevision:"b".repeat(64)},"Admit",h.revision);h=moveEditCursor(h,0,"undo","Undo",h.revision);}expect(editHistoryReplay(h).state.timeline.sources).toHaveLength(1);expect(editHistoryReplay(h).catalog).toHaveLength(16);expect(()=>appendEdit(h,{kind:"source",source:source("overflow"),receiptRevision:"b".repeat(64)},"Too many",h.revision)).toThrow("sixteen originals");expect(()=>appendEdit(h,{kind:"source",source:source("bad"),receiptRevision:"fake"},"Invalid",h.revision)).toThrow("revision");
});
