import {expect,test} from "bun:test";
import {mkdtempSync,mkdirSync,realpathSync,rmSync,writeFileSync,readFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join,sep} from "node:path";
import type {EditMask} from "../../planner/src/edit-composite-types";
import {editMaskGeometry,rasterEditMask,rasterEditMasks,rasterEditMaskAsync,editMatteCoverage} from "../../planner/src/edit-composite-sampling";
import {composeEditCompositeFrame,editCompositeDemand,fitEditCompositeFrame} from "../../planner/src/edit-composite-render";
import {editTimeline,applyEditOperation,type EditSource,type EditClip} from "../../planner/src/edit-timeline";
import {contentHash} from "../src/capabilities";
import {conformEditPicture,editPictureRecipe} from "../src/edit-picture";
import {soundProcessingCommand} from "../src/sound-finishing";
import {editStorageEstimate} from "../../planner/src/edit-resources";
const revision=contentHash("mask-original"),access=async()=>{};
const box=(xQ16=0,yQ16=0,widthQ16=32768,heightQ16=65536)=>({xQ16,yQ16,widthQ16,heightQ16});
function mask(kind:"rectangle"|"ellipse"="rectangle",geometry=box()):EditMask{return {id:"mask",label:"Authored mask",sourceRevision:revision,kind,combine:"replace",invert:false,featherQ8:0,keyframes:[{sourceFrame:0,interpolation:"linear",geometry}]};}
function source(id:string,media?:"graphic-rgba"):EditSource{return {id,revision,label:id,frames:90,width:32,height:24,audio:[],captions:[],voices:[],unmeasuredAudio:false,...(media?{media}:{})};}
function clip(id:string,sourceId:string,layer:number,at=0,from=0,frames=8):EditClip{return {id,sourceId,lane:"picture",layer,at,from,frames,link:null,gainDb:0,opacity:1,crop:null,envelope:{from,frames,fadeIn:0,fadeOut:0}};}
function solid(s:EditSource,color:number[]){const data=new Uint8Array(s.width*s.height*4);for(let p=0;p<data.length;p+=4)data.set(color,p);return {width:s.width,height:s.height,data};}
function pixel(data:Uint8Array,x:number,y=12,w=32){return [...data.subarray((y*w+x)*4,(y*w+x)*4+4)];}
function cleanup(root:string){const parent=realpathSync(tmpdir());if(!root.startsWith(parent+sep+"hv-composite-media-")||realpathSync(root)!==root)throw new Error("Unsafe composite cleanup");rmSync(root,{recursive:true,force:true});}

test("manual mask keys and 4x4 coverage agree with independent point tests; feather and ordered combinations remain exact",async()=>{
  const polygon:EditMask={...mask(),kind:"polygon",keyframes:[{sourceFrame:0,interpolation:"linear",geometry:{points:[{id:"a",xQ16:8192,yQ16:8192},{id:"b",xQ16:57344,yQ16:8192},{id:"c",xQ16:32768,yQ16:57344}]}}]},shapes=[mask("rectangle",box(8192,8192,40960,40960)),mask("ellipse",box(8192,8192,40960,40960)),polygon];
  for(const shape of shapes){const coverage=rasterEditMask(shape,0,32,24);for(let y=0;y<24;y++)for(let x=0;x<32;x++){let inside=0;for(let yy=0;yy<4;yy++)for(let xx=0;xx<4;xx++){const px=(x+(xx+.5)/4)/32,py=(y+(yy+.5)/4)/24;if(shape.kind==="rectangle")inside+=Number(px>=.125&&px<.75&&py>=.125&&py<.75);else if(shape.kind==="ellipse")inside+=Number(((px-.4375)/.3125)**2+((py-.4375)/.3125)**2<1);else inside+=Number(py>=.125&&py<.875&&px>=.125+(py-.125)/2&&px<.875-(py-.125)/2);}expect(coverage[y*32+x]).toBe(Math.floor((inside*255+8)/16));}}
  const moving=mask();if(moving.kind!=="polygon")moving.keyframes.push({sourceFrame:10,interpolation:"hold",geometry:box(32768)});expect(editMaskGeometry(moving,5)).toEqual(box(16384));expect(editMaskGeometry(moving,20)).toEqual(box(32768));moving.keyframes[0]!.interpolation="hold";expect(editMaskGeometry(moving,5)).toEqual(box());
  const feather=mask("rectangle",box(32768,-65536,65536,196608));feather.featherQ8=128;const soft=rasterEditMask(feather,0,32,24);expect(soft[12*32+15]).toBe(64);expect(soft[12*32+16]).toBe(191);feather.invert=true;expect(rasterEditMask(feather,0,32,24)[12*32+15]).toBe(191);
  const full=mask("rectangle",box(-65536,-65536,196608,196608));full.featherQ8=12*256;expect(new Set(rasterEditMask(full,0,32,24))).toEqual(new Set([255]));
  const left=mask(),right={...mask("rectangle",box(32768)),id:"right",combine:"union" as const};expect(new Set(rasterEditMasks([left,right],0,32,24))).toEqual(new Set([255]));right.combine="union";const subtract={...mask("rectangle",box(16384,0,32768)),id:"subtract",combine:"subtract" as const},cut=rasterEditMasks([left,right,subtract],0,32,24);expect([cut[0],cut[8],cut[24]]).toEqual([255,0,255]);
  const intersection=rasterEditMasks([left,{...subtract,combine:"intersect"}],0,32,24);expect([intersection[0],intersection[8],intersection[16]]).toEqual([0,255,0]);let checks=0;await expect(rasterEditMaskAsync(full,0,256,256,async()=>{if(++checks===2)throw new Error("mask cancelled");})).rejects.toThrow("mask cancelled");
});

test("isolated four-track mattes honor independent clocks, gaps, alpha/luma, hidden RGB and matte-only layers",async()=>{
  const sources=[source("base"),source("foreground","graphic-rgba"),source("matte1","graphic-rgba"),source("matte2","graphic-rgba"),source("matte3","graphic-rgba")],clips=[clip("base","base",0),clip("z-foreground","foreground",0,0,5),clip("matte1","matte1",1,2,10,4),clip("matte2","matte2",2,0,3),clip("matte3","matte3",3,0,8)];
  clips[1]!.opacity=.75;clips[1]!.composite={schema:"hv-edit-composite/1",masks:[mask()],matte:{layer:1,channel:"alpha",invert:false}};clips[2]!.composite={schema:"hv-edit-composite/1",matte:{layer:2,channel:"luma",invert:false}};clips[3]!.composite={schema:"hv-edit-composite/1",matte:{layer:3,channel:"alpha",invert:false}};
  const t=editTimeline({schema:"hv-edit-timeline/2",width:32,height:24,frames:8,sources,clips,markers:[],matteOnlyLayers:[1,2,3]}),colors:Record<string,number[]>={base:[20,40,180,255],foreground:[200,20,10,128],matte1:[255,255,255,128],matte2:[128,128,128,255],matte3:[255,255,255,128]},calls:string[]=[];
  for(const frame of [0,2,3,6,7]){calls.length=0;const actual=await composeEditCompositeFrame(t,frame,(id,at)=>{calls.push(id+":"+at);return solid(sources.find(s=>s.id===id)!,colors[id]!);});const alpha=frame>=2&&frame<6?16*191/65025:0,expected=[Math.round(20*(1-alpha)+200*alpha),Math.round(40*(1-alpha)+20*alpha),Math.round(180*(1-alpha)+10*alpha),255];expect(pixel(actual,4)).toEqual(expected);expect(pixel(actual,24)).toEqual(colors.base!);expect(calls.includes("foreground:"+(5+frame))).toBe(true);expect(calls.includes("matte1:"+(10+frame-2))).toBe(frame>=2&&frame<6);expect(calls.some(c=>c.startsWith("matte3:"))).toBe(frame>=2&&frame<6);}
  expect(editMatteCoverage(255,255,255,0,"luma")).toBe(0);expect(editMatteCoverage(0,255,0,255,"luma")).toBe(182);expect(editMatteCoverage(255,255,255,0,"luma",true)).toBe(255);
  const inverted=applyEditOperation(t,{kind:"composite",clipId:"z-foreground",composite:{...clips[1]!.composite!,matte:{layer:1,channel:"alpha",invert:true}}}),gap=await composeEditCompositeFrame(inverted,0,(id)=>solid(sources.find(s=>s.id===id)!,colors[id]!));expect(pixel(gap,4)[0]).toBeGreaterThan(80);expect(editCompositeDemand(t,0).map(d=>d.clip.id)).toEqual(["base","z-foreground"]);
  await expect(composeEditCompositeFrame(t,2,()=>{throw new Error("source withdrawn");})).rejects.toThrow("source withdrawn");await expect(composeEditCompositeFrame(t,2,id=>({...solid(sources.find(s=>s.id===id)!,colors[id]!),width:16}))).rejects.toThrow("full-resolution");
});

test("effect placement samples premultiplied masked originals without colored fringes",async()=>{
  const s=source("native","graphic-rgba"),c=clip("picture",s.id,0),input=solid(s,[0,0,255,0]);for(let y=0;y<s.height;y++)for(let x=0;x<16;x++)input.data.set([240,30,10,255],(y*s.width+x)*4);
  c.composite={schema:"hv-edit-composite/1",placement:{xQ16:32768,yQ16:0,scaleQ16:65536,rotationMilliDegrees:0}};const moved=await fitEditCompositeFrame(c,s,0,input,32,24,access);expect(pixel(moved,0)).toEqual([0,0,0,0]);expect(pixel(moved,20)).toEqual([240,30,10,255]);
  c.composite.placement={xQ16:0,yQ16:0,scaleQ16:49152,rotationMilliDegrees:17000};const rotated=await fitEditCompositeFrame(c,s,0,input,32,24,access);let partial=0;for(let p=0;p<rotated.length;p+=4)if(rotated[p+3]!>0&&rotated[p+3]!<255){partial++;expect([...rotated.subarray(p,p+3)]).toEqual([240,30,10]);}expect(partial).toBeGreaterThan(0);
});

test("actual film/native mask and matte conform matches shared RGBA composition across holds, dissolve handles and span seams",async()=>{
  const root=realpathSync(mkdtempSync(join(tmpdir(),"hv-composite-media-"))),sources=[source("film"),source("left","graphic-rgba"),source("right","graphic-rgba"),source("matte","graphic-rgba")],paths=new Map<string,string>(),originals=new Map<string,Buffer>();
  try{
    for(const s of sources){const raw=Buffer.alloc(32*24*4*90);for(let f=0;f<90;f++)for(let y=0;y<24;y++)for(let x=0;x<32;x++){const color=s.id==="film"?[30,70,130,255]:s.id==="left"?[170+f%40,10,20,x<24?128:0]:s.id==="right"?[5,20,170+f%40,192]:[255,255,255,f%3===0?128:255];raw.set(color,(f*32*24+y*32+x)*4);}writeFileSync(join(root,s.id+".raw"),raw);const path=join(root,s.id+".mkv");await soundProcessingCommand(["ffmpeg","-v","error","-nostdin","-f","rawvideo","-pixel_format","rgba","-video_size","32x24","-framerate","30","-i",join(root,s.id+".raw"),"-frames:v","90","-an","-c:v","ffv1","-level","3","-threads","1","-pix_fmt",s.media?"bgra":"yuv420p",path],root,access);paths.set(s.id,path);
      const decoded=join(root,s.id+"-decoded.raw");await soundProcessingCommand(["ffmpeg","-v","error","-nostdin","-threads","1","-i",path,"-an","-c:v","rawvideo","-threads","1","-pix_fmt","rgba","-f","rawvideo",decoded],root,access);originals.set(s.id,readFileSync(decoded));
    }
    const polygon:EditMask={...mask(),kind:"polygon",keyframes:[{sourceFrame:0,interpolation:"linear",geometry:{points:[{id:"a",xQ16:0,yQ16:0},{id:"b",xQ16:32768,yQ16:0},{id:"c",xQ16:32768,yQ16:65536},{id:"d",xQ16:0,yQ16:65536}]}},{sourceFrame:89,interpolation:"hold",geometry:{points:[{id:"a",xQ16:32768,yQ16:0},{id:"b",xQ16:65536,yQ16:0},{id:"c",xQ16:65536,yQ16:65536},{id:"d",xQ16:32768,yQ16:65536}]}}]},clips=[clip("base","film",0,0,0,75),clip("left","left",1,0,5,65),clip("right","right",1,65,40,10),clip("matte-left","matte",2,0,4,65),clip("matte-right","matte",2,65,40,10)];
    clips[0]!.composite={schema:"hv-edit-composite/1",masks:[mask("rectangle",box(0,0,65536,49152))]};clips[1]!.composite={schema:"hv-edit-composite/1",masks:[polygon],matte:{layer:2,channel:"alpha",invert:false}};clips[2]!.composite={schema:"hv-edit-composite/1",masks:[mask("ellipse",box(8192,8192,49152,49152))],matte:{layer:2,channel:"luma",invert:true}};
    clips[1]!.opacity=.8;clips[2]!.opacity=.6;clips[4]!.opacity=.5;let timeline=editTimeline({schema:"hv-edit-timeline/2",width:32,height:24,frames:75,sources,clips,markers:[],matteOnlyLayers:[2]});timeline=applyEditOperation(timeline,{kind:"crossfade",leftId:"left",rightId:"right",linked:false,frames:6,alignment:"center",ids:{left:"masked-dissolve"}});timeline=applyEditOperation(timeline,{kind:"crossfade",leftId:"matte-left",rightId:"matte-right",linked:false,frames:6,alignment:"center",ids:{"matte-left":"matte-dissolve"}});timeline=applyEditOperation(timeline,{kind:"retime",clipId:"matte-left",linked:false,from:4,frames:65,points:[{frame:0,rate:0},{frame:65,rate:0}],ripple:false});
    timeline=applyEditOperation(timeline,{kind:"retime",clipId:"left",linked:false,from:5,frames:65,points:[{frame:0,rate:500},{frame:65,rate:1500}],ripple:false});
    const directory=join(root,"render");mkdirSync(directory);const result=await conformEditPicture(timeline,paths,directory,access);expect(result.picture.recipe.schema).toBe("hv-edit-picture/6");expect(result.picture.parts.map(p=>p.frames)).toEqual([60,2,6,7]);expect(result.picture.parts.find(p=>p.at===62)!.layers.map(p=>p.clipId)).toEqual(["base","left","right","matte-left","matte-right"]);
    const final=join(root,"output.raw");await soundProcessingCommand(["ffmpeg","-v","error","-nostdin","-protocol_whitelist","file,pipe","-f","concat","-safe","0","-threads","1","-i",join(directory,result.picture.concatFile),"-an","-c:v","rawvideo","-threads","1","-pix_fmt","rgba","-f","rawvideo",final],root,access);const actual=readFileSync(final);
    const expected=Buffer.alloc(75*3072);for(let frame=0;frame<75;frame++)expected.set(await composeEditCompositeFrame(timeline,frame,(id,sourceFrame)=>({width:32,height:24,data:originals.get(id)!.subarray(sourceFrame*3072,(sourceFrame+1)*3072)})),frame*3072);writeFileSync(join(root,"expected.raw"),expected);
    // Compare in the actual output color domain: YUV420 chroma subsampling changes sharp mask-edge RGB.
    await soundProcessingCommand(["ffmpeg","-v","error","-nostdin","-filter_threads","1","-f","rawvideo","-pixel_format","rgba","-video_size","32x24","-framerate","30","-i",join(root,"expected.raw"),"-frames:v","75","-an","-c:v","ffv1","-level","3","-threads","1","-pix_fmt","yuv420p",join(root,"expected.mkv")],root,access);await soundProcessingCommand(["ffmpeg","-v","error","-nostdin","-threads","1","-i",join(root,"expected.mkv"),"-an","-c:v","rawvideo","-threads","1","-pix_fmt","rgba","-f","rawvideo",join(root,"expected-decoded.raw")],root,access);expect(actual).toEqual(readFileSync(join(root,"expected-decoded.raw")));expect(sources[0]!.media).toBeUndefined();
    const estimate=editStorageEstimate(timeline,[]);expect(estimate.compositeScratchBytes).toBeGreaterThan(0);expect(estimate.compositeWorkingFrameBytes).toBeGreaterThan(0);expect(estimate.rgbaScratchBytes).toBeUndefined();const {revision:_revision,matteOnlyLayers:_roles,...plainData}=timeline,plain=editTimeline({...plainData,schema:"hv-edit-timeline/1",clips:timeline.clips.map(({composite:_composite,...c})=>c)});expect(editPictureRecipe(plain).schema).not.toBe("hv-edit-picture/6");
  }finally{cleanup(root);}
},120000);
