import {expect,test} from "bun:test";
import {contentHash} from "../src/capabilities";
import {applyEditOperation,editCaptionCues,editEnvelopeGain,editSpeechCuts,editTimeline,editUnmeasuredCuts,initialEditTimeline,validateEditTimeline,type EditTimeline,type EditSource} from "../../planner/src/edit-timeline";
import {parseEditCaptions} from "../../planner/src/edit-captions";
import {editVtt} from "../src/edit-conform";
import {appendEdit,createEditHistory,editHistoryState,moveEditCursor} from "../../planner/src/edit-history";
const source:EditSource={id:"film",revision:contentHash("film"),label:"Retained test picture",frames:90,width:64,height:48,audio:["mix"],unmeasuredAudio:false,voices:[{id:"red",start:4800,end:40000,lane:"dialogue"},{id:"green",start:52800,end:88000,lane:"dialogue"},{id:"blue",start:100800,end:136000,lane:"dialogue"}],captions:[{id:"red",start:4800,end:40000,text:"Red line"},{id:"green",start:52800,end:88000,text:"Green line"},{id:"blue",start:100800,end:136000,text:"Blue line"}]};
export const timelineFixture=()=>initialEditTimeline([structuredClone(source)],source.id,64,48);
export function splitTimeline(t=timelineFixture()):EditTimeline{t=applyEditOperation(t,{kind:"split",clipId:"initial-0",linked:true,at:30,rightIds:{"initial-0":"middle-picture","initial-1":"middle-mix","initial-2":"middle-captions"},rightLink:"middle"});return applyEditOperation(t,{kind:"split",clipId:"middle-picture",linked:true,at:60,rightIds:{"middle-picture":"last-picture","middle-mix":"last-mix","middle-captions":"last-captions"},rightLink:"last"});}
test("linked editorial splits and ripple reorder preserve sources, length, captions and in-range markers",()=>{
  let t=splitTimeline();t=applyEditOperation(t,{kind:"marker",marker:{id:"beat",frame:35,label:"Green beat"}});t=applyEditOperation(t,{kind:"marker",marker:{id:"outro",frame:80,label:"Blue beat"}});const before=contentHash(t);
  const moved=applyEditOperation(t,{kind:"reorder",clipId:"middle-picture",at:60});expect(contentHash(t)).toBe(before);expect(moved.frames).toBe(90);expect(moved.clips.filter(c=>c.lane==="picture").map(c=>[c.at,c.from,c.frames])).toEqual([[0,0,30],[30,60,30],[60,30,30]]);expect(moved.markers.map(m=>[m.id,m.frame])).toEqual([["outro",50],["beat",65]]);expect(editCaptionCues(moved).map(c=>[c.text,c.start,c.end])).toEqual([["Red line",4800,40000],["Blue line",52800,88000],["Green line",100800,136000]]);
  const removed=applyEditOperation(moved,{kind:"delete",clipId:"last-picture",linked:true,ripple:true});expect(removed.frames).toBe(60);expect(removed.markers.map(m=>m.id)).toEqual(["beat"]);expect(removed.clips.filter(c=>c.lane==="picture").map(c=>c.from)).toEqual([0,30]);
});
test("roll, slide, slip and ripple trim produce exact source and timeline ranges",()=>{
  let t=splitTimeline();t=applyEditOperation(t,{kind:"roll",leftId:"initial-0",rightId:"middle-picture",linked:true,delta:5});expect(t.clips.filter(c=>c.lane==="picture").map(c=>[c.at,c.from,c.frames])).toEqual([[0,0,35],[35,35,25],[60,60,30]]);
  t=applyEditOperation(splitTimeline(),{kind:"slide",leftId:"initial-0",clipId:"middle-picture",rightId:"last-picture",linked:true,delta:5});expect(t.clips.filter(c=>c.lane==="picture").map(c=>[c.at,c.from,c.frames])).toEqual([[0,0,35],[35,30,30],[65,65,25]]);
  t=applyEditOperation(t,{kind:"slip",clipId:"middle-picture",linked:true,delta:-4});expect(t.clips.filter(c=>c.link==="middle").every(c=>c.from===26&&c.at===35&&c.frames===30)).toBe(true);
  t=applyEditOperation(t,{kind:"trim",clipId:"middle-picture",linked:true,edge:"in",delta:4,ripple:true});expect(t.frames).toBe(86);expect(t.clips.filter(c=>c.lane==="picture").map(c=>[c.at,c.from,c.frames])).toEqual([[0,0,35],[35,30,26],[61,65,25]]);
});
test("independent L/J edits require unlinking and partial speech cuts stay visible without captions",()=>{
  let t=splitTimeline();expect(()=>applyEditOperation(t,{kind:"move",clipId:"middle-mix",linked:false,at:35})).toThrow("Unlink");t=applyEditOperation(t,{kind:"unlink",clipId:"middle-mix"});t=applyEditOperation(t,{kind:"move",clipId:"middle-mix",linked:false,at:35});expect(t.clips.find(c=>c.id==="middle-picture")!.at).toBe(30);expect(t.clips.find(c=>c.id==="middle-mix")!.at).toBe(35);
  t=applyEditOperation(t,{kind:"trim",clipId:"middle-mix",linked:false,edge:"in",delta:10,ripple:false});expect(editSpeechCuts(t)).toContainEqual({clipId:"middle-mix",voiceId:"green",edge:"in"});
  t=applyEditOperation(t,{kind:"unlink",clipId:"middle-captions"});t=applyEditOperation(t,{kind:"delete",clipId:"middle-captions",linked:false,ripple:false});expect(editSpeechCuts(t)).toContainEqual({clipId:"middle-mix",voiceId:"green",edge:"in"});expect(editCaptionCues(t).map(c=>c.text)).not.toContain("Green line");
});
test("splitting preserves fade phase and invalid linked ranges, ripple collisions and source overflow fail",()=>{
  let t=timelineFixture();t=applyEditOperation(t,{kind:"settings",clipId:"initial-1",gainDb:-3,opacity:1,crop:null,fadeIn:45,fadeOut:30});const initial=t.clips.find(c=>c.id==="initial-1")!;t=splitTimeline(t);for(const c of t.clips.filter(c=>c.lane==="mix"))for(let f=c.from;f<c.from+c.frames;f+=.5)expect(editEnvelopeGain(c,f)).toBe(editEnvelopeGain(initial,f));
  expect(()=>applyEditOperation(t,{kind:"slip",clipId:"last-picture",linked:true,delta:1})).toThrow("Clip duration");expect(()=>applyEditOperation(t,{kind:"reorder",clipId:"last-picture",at:15})).toThrow("ripple boundary");const forged=structuredClone(t);forged.clips[0]!.at++;expect(()=>validateEditTimeline(forged)).toThrow();expect(()=>applyEditOperation(t,{kind:"insert",clips:[structuredClone(t.clips[0]!)]})).toThrow("Duplicate clip");
});
test("append-only history restores earlier branches, retains abandoned edits and rejects stale concurrent writes",()=>{
  let h=createEditHistory("cut",timelineFixture());h=appendEdit(h,{kind:"split",clipId:"initial-0",linked:true,at:30,rightIds:{"initial-0":"b-video","initial-1":"b-mix","initial-2":"b-captions"},rightLink:"b"},"Split at first beat",h.revision,1);const firstRevision=h.revision;
  h=appendEdit(h,{kind:"marker",marker:{id:"beat",frame:35,label:"First branch"}},"Add a beat",h.revision,2);const marked=editHistoryState(h).timeline.revision;h=moveEditCursor(h,1,"undo","Undo marker",h.revision,3);h=appendEdit(h,{kind:"slip",clipId:"initial-0",linked:true,delta:5},"Try a later opening",h.revision,4);expect(editHistoryState(h).head).toBe(4);expect(h.events.length).toBe(4);expect(()=>appendEdit(h,{kind:"duration",frames:120},"Concurrent change",firstRevision,5)).toThrow("another window");
  h=moveEditCursor(h,1,"undo","Back to split",h.revision,5);expect(editHistoryState(h).children).toEqual([2,4]);h=moveEditCursor(h,2,"redo","Return to first branch",h.revision,6);expect(editHistoryState(h).timeline.revision).toBe(marked);expect(h.events.length).toBe(6);expect(()=>moveEditCursor(h,0,"redo","Invalid redo",h.revision,7)).toThrow("follow the selected branch");
  const tampered=structuredClone(h);tampered.events[0]!.label="Changed";expect(()=>editHistoryState(tampered)).toThrow("event changed");
});
test("source captions retain plain text and measured narration remains independent of caption coverage",()=>{
  const captions=parseEditCaptions("WEBVTT\n\ncue\n00:00:00.100 --> 00:00:00.900\nA &amp; B\n",90);expect(captions[0]!.text).toBe("A & B");expect(captions[0]!.start).toBe(4800);expect(()=>parseEditCaptions("WEBVTT\n\nSTYLE\n::cue {color: red;}\n",90)).toThrow("styled or malformed");expect(()=>parseEditCaptions("WEBVTT\n\n00:00:00.000 --> 00:00:04.000\nOutside\n",90)).toThrow("timing");
  const t=timelineFixture(),{revision:_revision,...data}=t,s=data.sources[0]!;s.voices.push({id:"narrator",start:30000,end:60000,lane:"narration"});s.unmeasuredAudio=true;s.captions=[{id:"submillisecond",start:16000,end:16001,text:"Tiny cue"}];const split=splitTimeline(editTimeline(data));expect(editSpeechCuts(split)).toContainEqual({clipId:"initial-1",voiceId:"narrator",edge:"out"});expect(editSpeechCuts(split)).toContainEqual({clipId:"middle-mix",voiceId:"narrator",edge:"in"});expect(editUnmeasuredCuts(split)).toHaveLength(3);expect(editVtt(split)).toContain("00:00:00.333 --> 00:00:00.334");
});
