// The conformance suite FULL-SCOPE §7 already requires of the Voice and Lip-sync
// lanes. §7 lists both in the same candidate matrix as the video adapters and
// holds them to the same rule — "each must pass the adapter conformance suite and
// the studio benchmark before promotion" — and until this file there was no suite
// at all for either.
//
// Why that mattered more than tidiness: nothing anywhere guarded the five
// performance capability revisions. Not one of them appeared as a literal in any
// committed test, fixture or evidence file; every audio test derives its
// expectation from the live constant, so an edit to a capability definition moved
// the test's expectation along with the code and `bun test` stayed green. But
// those revisions are pinned inside *already-delivered* records — line plans,
// dispatch receipts, deliveries, policies — and every validator that reads one
// back re-derives the revision and refuses a mismatch. `validateSnapshot` reaches
// `validateAudioTake` and `validateAudioIntent` from all four snapshot entry
// points, so one moved revision makes every portable archive and every backup
// restore containing an audio take permanently un-importable.
//
// So this suite does two things the video suite already does for its lane:
// it pins the revisions as committed evidence re-derived on every run, and it
// commits golden delivered records that this build must still be able to read.
// A revision edit now fails here, with the message an operator would see, instead
// of passing and failing on a restore.
//
// No capability definition is touched, no adapter is constructed, no key is read,
// and `globalThis.fetch` is replaced by a stub that throws and is asserted never
// to have been called.
import { afterAll, beforeAll, expect, test } from "bun:test";
import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  PERFORMANCE_LANES, PERFORMANCE_REGISTRY, performanceCapability, performanceEntry, performanceRevisions,
} from "../src/performance-registry";
import { AUDIO_CAPABILITIES, CARTESIA_AUDIO_CAPABILITY, CARTESIA_MULTILINGUAL_CAPABILITY, CARTESIA_PHRASE_CAPABILITY, audioCapability } from "../src/audio-capabilities";
import { AZURE_AUDIO_CAPABILITY } from "../src/azure-capability";
import { LIPSYNC_CAPABILITY, LIPSYNC_MODEL } from "../src/lipsync-capability";
import { capability, contentHash } from "../src/capabilities";
import { describeProvider } from "../src/catalog";
import { createAudioDelivery, validateAudioDelivery } from "../src/audio-delivery";
import { validateAudioIntent } from "../src/cartesia-audio";
import { azureLineRequest } from "../src/azure-request";
import { validateLipSyncDelivery } from "../src/sync-lipsync";
import { compileAudioLine, validateAudioLinePlan } from "../../planner/src/audio-performances";
import { lineSources } from "../../planner/src/performances";
import { validateAudioPolicy } from "../../planner/src/audio-jobs";
import { lipSyncPolicy, validateLipSyncPolicy } from "../../planner/src/lipsync-policy";
import { AUDIO_POLICY, AUDIO_PCM, audioIntent } from "../../../test/fixtures/audio";
import { AZURE_POLICY, AZURE_PROFILE } from "../../../test/fixtures/azure-audio";
import { localizedLine } from "../../../test/fixtures/localized-audio";

const REPO_ROOT = resolve(import.meta.dir, "../../..");
const PINS_PATH = join(REPO_ROOT, "docs/evidence/hv019-performance/capability-revision-pins.json");
// A separate directory from docs/evidence/hv019-router/ on purpose: HV-019-01's evidence
// statement requires a directory-wide grep over that path for `cartesia` to return nothing.
const RECORDS_PATH = join(import.meta.dir, "fixtures/performance-records.json");

let fetchCalls = 0;
const realFetch = globalThis.fetch;
beforeAll(() => {
  globalThis.fetch = (() => {
    fetchCalls += 1;
    throw new Error("The performance conformance suite performs no network calls.");
  }) as unknown as typeof fetch;
});
afterAll(() => { globalThis.fetch = realFetch; });

interface CheckRecord { name: string; pairs: number; passed: number; skipped: number; skipReason?: string }
const checks: CheckRecord[] = [];
const record = (value: CheckRecord) => { checks.push(value); };

// ---------------------------------------------------------------------------
// Golden records. Generated by this suite under HV_PERFORMANCE_RECORDS_REFRESH and
// then committed, so refreshing them has to be a decision rather than a side effect.
// They cannot be hand-written: compileAudioLine re-hashes its source, validateAudioPolicy
// re-derives its permission and price revisions, and the safety gate runs over the
// character name and dialogue. Fixture text is deliberately bland for that reason.
// ---------------------------------------------------------------------------
const source = lineSources([{ character: "MARLA", lines: ["Hello Zo, hello Zo."] }])[0]!;
const cartesiaProfile = {
  schema: "hv-audio-voice/1" as const, provider: "cartesia" as const, language: "en" as const,
  voice: { id: AUDIO_POLICY.voiceId, catalogueRevision: AUDIO_POLICY.catalogueRevision, permissionRevision: AUDIO_POLICY.permissionRevision },
  controls: { emotion: "calm" as const, speed: 1.2, volume: 0.9 }, pronunciations: [{ word: "Zo", say: "Zoe" }],
};
const azureSource = lineSources([{ character: "MARLA", lines: ["Hello there."] }])[0]!;

function buildRecords() {
  const lineV1 = compileAudioLine(source, cartesiaProfile);
  const lineV3 = compileAudioLine(source, cartesiaProfile, { sourceHash: source.hash, phrases: [{ start: 0, end: 5, text: "Hello", speed: 0.8 }] });
  const lineV4 = compileAudioLine(azureSource, AZURE_PROFILE);
  const lineV5 = localizedLine(lineSources([{ character: "MARLA", lines: ["Welcome home."] }])[0]!, "es", "Bienvenida a casa.");
  const delivery = createAudioDelivery(lineV1, crypto.randomUUID(), AUDIO_PCM,
    [{ text: "Hello", startSec: 0, endSec: 0.5 }], [{ text: "h", startSec: 0, endSec: 0.2 }]).report;
  const intent = audioIntent(lineV1);
  // The Azure read-back lane has its own discriminants — hv-audio-line-delivery/2 and
  // hv-audio-dispatch/2 — and validateAudioIntent hashes an azureLineRequest rather than a
  // Cartesia one, so a Cartesia record does not exercise it. Azure word boundaries carry no
  // phoneme timings, which is why its alignment list is words only.
  const azureDeliveryAttempt = crypto.randomUUID();
  const azureDelivery = createAudioDelivery(lineV4, azureDeliveryAttempt, AUDIO_PCM,
    [{ text: "Hello", startSec: 0, endSec: 0.5 }], []).report;
  const azureDispatchId = crypto.randomUUID();
  const azureIntent = {
    schema: "hv-audio-dispatch/2" as const, attemptId: azureDispatchId, contextId: azureDispatchId,
    planRevision: lineV4.revision, capabilityRevision: lineV4.capabilityRevision,
    requestSha256: contentHash(azureLineRequest(lineV4)), provider: "azure" as const,
    model: AZURE_AUDIO_CAPABILITY.model, apiVersion: AZURE_AUDIO_CAPABILITY.apiVersion,
  };
  const lipPolicy = lipSyncPolicy({
    label: "Closed lip-sync fixture", accountRevision: "a".repeat(64), licenceEvidenceSha256: "b".repeat(64),
    priceEvidenceSha256: "c".repeat(64), outputHosts: ["output.example.com"], heldUsd: 0.5, maxFrames: 300,
    validFrom: "2026-01-01T00:00:00.000Z", expiresAt: "2099-01-01T00:00:00.000Z",
  });
  const lipDeliveryData = {
    schema: "hv-lipsync-delivery/1" as const, capabilityRevision: LIPSYNC_CAPABILITY.revision,
    planRevision: "d".repeat(64), preparedRevision: "e".repeat(64), attemptId: crypto.randomUUID(),
    generationId: "fixture-generation-0001", provider: "sync" as const, model: LIPSYNC_MODEL,
    videoSha256: "f".repeat(64), videoBytes: 4096, outputHost: "output.example.com",
  };
  return {
    schema: "hv-performance-golden-records/1" as const,
    note: "Generated by packages/generator/test/performance-conformance.test.ts under HV_PERFORMANCE_RECORDS_REFRESH. "
      + "Every identifier is a test UUID and every evidence hash is a repeated character. No operator catalogue voice, "
      + "no credential, no real screenplay. The dialogue is deliberately bland because packages/safety runs over it and "
      + "its refusals may grow, which would otherwise make a committed record un-validatable later.",
    audioLineV1: lineV1, audioLineV3: lineV3, audioLineV4: lineV4, audioLineV5: lineV5,
    audioDelivery: delivery, audioIntent: intent,
    azureDelivery, azureIntent,
    audioPolicyCartesia: AUDIO_POLICY, audioPolicyAzure: AZURE_POLICY,
    lipSyncPolicy: lipPolicy, lipSyncDelivery: { ...lipDeliveryData, revision: contentHash(lipDeliveryData) },
  };
}

type GoldenRecords = ReturnType<typeof buildRecords>;

// ---------------------------------------------------------------------------
// 1. The registry is derived, and enumerates every capability this build produces
// ---------------------------------------------------------------------------
test("performance conformance: the registry is derived from the capability constants, both ways", () => {
  const live = [...AUDIO_CAPABILITIES, LIPSYNC_CAPABILITY];
  expect(PERFORMANCE_REGISTRY).toHaveLength(live.length);
  expect(PERFORMANCE_REGISTRY.map((entry) => entry.capabilityRevision).sort())
    .toEqual(live.map((value) => value.revision).sort());
  for (const value of live) {
    const entry = performanceEntry(value.revision);
    expect(entry).toBeDefined();
    expect(entry!.schema).toBe(value.schema);
    expect(entry!.provider).toBe(value.provider);
    expect(entry!.model).toBe(value.model);
    expect(entry!.apiVersion).toBe(value.apiVersion);
    expect(entry!.qualification).toBe(value.qualification);
  }
  expect([...new Set(PERFORMANCE_REGISTRY.map((entry) => entry.lane))].sort()).toEqual([...PERFORMANCE_LANES].sort());
  expect(performanceRevisions("voice")).toHaveLength(AUDIO_CAPABILITIES.length);
  expect(performanceRevisions("lip-sync")).toEqual([LIPSYNC_CAPABILITY.revision]);
  expect(performanceRevisions("voice", "azure")).toEqual([AZURE_AUDIO_CAPABILITY.revision]);
  // Every performance capability bills. The audio contract says so in its own words — it has no
  // zero-dollar price and cannot be admitted through the free render lane — so there is no
  // "free performance lane" to route to and no mock voice provider.
  for (const entry of PERFORMANCE_REGISTRY) expect(entry.paid).toBe(true);
  record({ name: "registry-derivation", pairs: PERFORMANCE_REGISTRY.length, passed: PERFORMANCE_REGISTRY.length, skipped: 0 });
});

// ---------------------------------------------------------------------------
// 2. `schema` is not a key in this lane
// ---------------------------------------------------------------------------
test("performance conformance: the revision is the key, because two capabilities share one schema", () => {
  const schemas = PERFORMANCE_REGISTRY.map((entry) => entry.schema);
  const revisions = PERFORMANCE_REGISTRY.map((entry) => entry.capabilityRevision);
  // Four distinct schemas across five capabilities: hv-audio-capability/3 is carried by both the
  // Azure contract and the Cartesia multilingual one. A registry keyed on schema loses one of them.
  expect(new Set(schemas).size).toBe(4);
  expect(new Set(revisions).size).toBe(5);
  const shared = PERFORMANCE_REGISTRY.filter((entry) => entry.schema === "hv-audio-capability/3");
  expect(shared).toHaveLength(2);
  expect(shared.map((entry) => entry.provider).sort()).toEqual(["azure", "cartesia"]);
  expect(shared[0]!.capabilityRevision).not.toBe(shared[1]!.capabilityRevision);
  // performanceEntry is total and injective over the registry.
  for (const entry of PERFORMANCE_REGISTRY) expect(performanceEntry(entry.capabilityRevision)).toBe(entry);
  expect(performanceEntry("0".repeat(64))).toBeUndefined();
  expect(performanceEntry(undefined as unknown as string)).toBeUndefined();
  record({ name: "revision-is-the-key", pairs: PERFORMANCE_REGISTRY.length, passed: PERFORMANCE_REGISTRY.length, skipped: 0 });
});

// ---------------------------------------------------------------------------
// 3. The hash shapes of the two lanes, reproduced rather than asserted in prose
// ---------------------------------------------------------------------------
test("performance conformance: schema is inside every performance hash and outside the video hash", () => {
  for (const value of [...AUDIO_CAPABILITIES, LIPSYNC_CAPABILITY]) {
    const { revision, ...definition } = value as Record<string, unknown> & { revision: string };
    // The definition that was hashed includes the schema string.
    expect(contentHash(definition)).toBe(revision);
    const { schema: _schema, ...withoutSchema } = definition;
    expect(contentHash(withoutSchema)).not.toBe(revision);
    // Therefore a schema rename alone moves this revision. This is the fact that makes
    // "re-express these as hv-capability/2" non-additive under any lookup shim.
    const renamed = { ...definition, schema: "hv-capability/2" };
    expect(contentHash(renamed)).not.toBe(revision);
  }
  // The video lane is the opposite: capability() hashes a definition with no schema key and
  // adds the literal afterwards, so the video schema string is not in any video revision.
  const snapshot = describeProvider("mock", "final", {}).snapshot;
  const { schema: _vs, revision: _vr, priceVersion: _vp, ...videoDefinition } = snapshot as unknown as Record<string, unknown>;
  expect(contentHash(videoDefinition)).toBe(snapshot.revision);
  record({ name: "hash-shape", pairs: AUDIO_CAPABILITIES.length + 2, passed: AUDIO_CAPABILITIES.length + 2, skipped: 0 });
});

test("performance conformance: the video capability builder cannot express an audio contract", () => {
  const snapshot = describeProvider("mock", "final", {}).snapshot;
  const { schema: _s, revision: _r, priceVersion: _p, ...definition } = snapshot as unknown as Record<string, unknown>;
  // `modality: "audio"` is refused today. Widening that union is a loosening and would be safe,
  // but it buys nothing: capability() also requires output.minWidth/minHeight/maxWidth/maxHeight
  // as integers in [16, 8192], so an audio contract could only be expressed by fabricating
  // dimensions into a content-addressed record — which CLAUDE.md forbids — or by making the whole
  // output block modality-conditional, which is a validator change, not a union widening.
  expect(() => capability({ ...definition, modality: "audio" } as never)).toThrow("Invalid provider capability configuration.");
  const { output } = definition as { output: Record<string, unknown> };
  for (const field of ["minWidth", "minHeight", "maxWidth", "maxHeight"]) expect(typeof output[field]).toBe("number");
  record({ name: "audio-modality-unexpressible", pairs: 5, passed: 5, skipped: 0 });
});

// ---------------------------------------------------------------------------
// 4. A resolver that spans both lanes
// ---------------------------------------------------------------------------
test("performance conformance: the cross-lane resolver covers lip-sync, which audioCapability does not", () => {
  for (const entry of PERFORMANCE_REGISTRY) expect(performanceCapability(entry.capabilityRevision)).toBeDefined();
  // audioCapability() is the voice-lane lookup only: LIPSYNC_CAPABILITY is in neither
  // AUDIO_CAPABILITIES nor that lookup, so a lip-sync revision has no resolver there.
  expect(audioCapability(LIPSYNC_CAPABILITY.revision)).toBeUndefined();
  expect(performanceCapability(LIPSYNC_CAPABILITY.revision)).toBe(LIPSYNC_CAPABILITY);
  expect(performanceCapability("0".repeat(64))).toBeUndefined();
  record({ name: "cross-lane-resolver", pairs: PERFORMANCE_REGISTRY.length + 3, passed: PERFORMANCE_REGISTRY.length + 3, skipped: 0 });
});

// ---------------------------------------------------------------------------
// 5. Golden delivered records, re-validated by the validator that reads them in production
// ---------------------------------------------------------------------------
test("performance conformance: this build can still read the work it already delivered", () => {
  if (process.env.HV_PERFORMANCE_RECORDS_REFRESH?.trim()) {
    const built = buildRecords();
    mkdirSync(dirname(RECORDS_PATH), { recursive: true });
    const staging = RECORDS_PATH + ".tmp";
    writeFileSync(staging, JSON.stringify(built, null, 2) + "\n");
    renameSync(staging, RECORDS_PATH);
  }
  const golden = JSON.parse(readFileSync(RECORDS_PATH, "utf8")) as GoldenRecords;
  expect(golden.schema).toBe("hv-performance-golden-records/1");

  // Each record goes through the validator that reads it back in production. A revision edit
  // fails here, with the message an operator would see on a restore.
  for (const [name, line, expectedRevision] of [
    ["audioLineV1", golden.audioLineV1, CARTESIA_AUDIO_CAPABILITY.revision],
    ["audioLineV3", golden.audioLineV3, CARTESIA_PHRASE_CAPABILITY.revision],
    ["audioLineV4", golden.audioLineV4, AZURE_AUDIO_CAPABILITY.revision],
    ["audioLineV5", golden.audioLineV5, CARTESIA_MULTILINGUAL_CAPABILITY.revision],
  ] as const) {
    expect({ name, revision: line.capabilityRevision }).toEqual({ name, revision: expectedRevision });
    expect(validateAudioLinePlan(line)).toEqual(line);
  }
  expect(validateAudioDelivery(golden.audioDelivery)).toEqual(golden.audioDelivery);
  expect(validateAudioDelivery(golden.azureDelivery)).toEqual(golden.azureDelivery);
  expect(golden.azureDelivery.schema).toBe("hv-audio-line-delivery/2");
  expect(() => validateAudioIntent(golden.audioIntent, golden.audioLineV1)).not.toThrow();
  expect(() => validateAudioIntent(golden.azureIntent, golden.audioLineV4)).not.toThrow();
  expect(golden.azureIntent.schema).toBe("hv-audio-dispatch/2");
  // The two policy records are NOT revision tripwires and are not claimed to be.
  // validateAudioPolicy resolves no capability: it re-derives permissionRevision, priceRevision,
  // the record revision and the model string from the live AZURE_AUDIO_MODEL / CARTESIA_MODEL
  // constants and hash-compares. The capability-model comparison lives in audioTakePlan, which
  // needs a job and a screenplay and is exercised by the PostgreSQL-backed storage suites. They
  // are committed here because a model-constant edit is its own hazard, and listed in the pins
  // evidence's unpinnedReadBackPaths so nobody reads them as revision coverage.
  // `now` is deliberately omitted — a golden fixture with a fixed validity window must not become
  // a time bomb that turns CI red on a date nobody chose.
  expect(validateAudioPolicy(golden.audioPolicyCartesia)).toEqual(golden.audioPolicyCartesia);
  expect(validateAudioPolicy(golden.audioPolicyAzure)).toEqual(golden.audioPolicyAzure);
  expect(validateLipSyncPolicy(golden.lipSyncPolicy)).toEqual(golden.lipSyncPolicy);
  expect(golden.lipSyncPolicy.capabilityRevision).toBe(LIPSYNC_CAPABILITY.revision);
  expect(() => validateLipSyncDelivery(golden.lipSyncDelivery)).not.toThrow();

  // The fixture carries no credential, no destination and no host path. Two URIs do appear and
  // are allowed by name rather than by loosening the pattern: the Azure line's provider transcript
  // is SSML, whose XML namespaces are part of the format the adapter generates. They are namespace
  // identifiers, not endpoints — nothing fetches them.
  const text = readFileSync(RECORDS_PATH, "utf8");
  const SSML_NAMESPACES = ["http://www.w3.org/2001/10/synthesis", "https://www.w3.org/2001/mstts"];
  let scrubbed = text;
  for (const namespace of SSML_NAMESPACES) {
    expect(text).toContain(namespace);
    scrubbed = scrubbed.split(namespace).join("<ssml-namespace>");
  }
  for (const pattern of [/:\/\//, /API_KEY/i, /\/home\//, /\/Users\//, /\/tmp\//, /cartesia\.ai/, /\.microsoft\.com/, /sync\.so/]) {
    expect(scrubbed).not.toMatch(pattern);
  }
  record({ name: "golden-records", pairs: 12, passed: 12, skipped: 0 });
});

test("performance conformance: a moved revision is refused, not silently accepted", () => {
  const golden = JSON.parse(readFileSync(RECORDS_PATH, "utf8")) as GoldenRecords;
  // What a revision edit would actually do to finished work. Substituting any other live revision
  // into a delivered record makes the record unreadable — which is the same outcome as this build
  // no longer being able to produce the revision the record pins.
  const { revision: _r, ...data } = { ...golden.audioLineV1, capabilityRevision: CARTESIA_PHRASE_CAPABILITY.revision };
  expect(() => validateAudioLinePlan({ ...data, revision: contentHash(data) } as never)).toThrow();
  expect(() => validateLipSyncDelivery({ ...golden.lipSyncDelivery, capabilityRevision: CARTESIA_AUDIO_CAPABILITY.revision })).toThrow();
  const lip = { ...golden.lipSyncPolicy, capabilityRevision: CARTESIA_AUDIO_CAPABILITY.revision };
  expect(() => validateLipSyncPolicy(lip)).toThrow();
  record({ name: "moved-revision-refused", pairs: 3, passed: 3, skipped: 0 });
});

// ---------------------------------------------------------------------------
// 6. The pins evidence
// ---------------------------------------------------------------------------
interface PinsDocument {
  schema: "hv-performance-capability-pins/1";
  recordedAt: string;
  lanes: string[];
  entries: { lane: string; provider: string; schema: string; model: string; apiVersion: string; capabilityRevision: string; paid: boolean; qualification: string }[];
  schemaIsInsideTheHash: true;
  videoSchemaIsOutsideTheHash: true;
  goldenRecords: string[];
  revisionPinningShapes: number;
  goldenRecordsCarryingARevisionPin: number;
  additionalRecordsWithoutARevisionPin: string[];
  unpinnedReadBackPaths: { path: string; reason: string; coveredBy: string }[];
  checks: CheckRecord[];
  poolAdmitted: false;
  newProviderSpendUsd: 0;
  liveProviderDispatches: 0;
  provesVendorAvailability: false;
  provesVoiceQuality: false;
  provesLipSyncQuality: false;
  provesLivePricing: false;
}

function buildPins(): PinsDocument {
  return {
    schema: "hv-performance-capability-pins/1",
    recordedAt: new Date().toISOString(),
    lanes: [...PERFORMANCE_LANES],
    entries: PERFORMANCE_REGISTRY.map((entry) => ({
      lane: entry.lane, provider: entry.provider, schema: entry.schema, model: entry.model,
      apiVersion: entry.apiVersion, capabilityRevision: entry.capabilityRevision, paid: entry.paid,
      qualification: entry.qualification,
    })),
    schemaIsInsideTheHash: true,
    videoSchemaIsOutsideTheHash: true,
    goldenRecords: ["hv-audio-line/1", "hv-audio-line/3", "hv-audio-line/4", "hv-audio-line/5",
      "hv-audio-line-delivery/1", "hv-audio-line-delivery/2", "hv-audio-dispatch/1", "hv-audio-dispatch/2",
      "hv-lipsync-policy/1", "hv-lipsync-delivery/1"],
    revisionPinningShapes: 15,
    goldenRecordsCarryingARevisionPin: 10,
    additionalRecordsWithoutARevisionPin: ["hv-audio-policy (cartesia)", "hv-audio-policy (azure)"],
    unpinnedReadBackPaths: [
      { path: "validateAudioPolicy", reason: "hv-audio-policy/1..3 pins a model constant, not a capability revision: validateAudioPolicy resolves no capability and re-derives the model from AZURE_AUDIO_MODEL / CARTESIA_MODEL. Two policy records are committed because a model-constant edit is its own hazard, but they are not revision coverage.", coveredBy: "audioTakePlan is where the capability model is compared to the policy model; it needs a job and a screenplay and runs in packages/storage/test/audio-jobs.test.ts against a real PostgreSQL." },
      { path: "hv-audio-line/2", reason: "The retained-direction line discriminant. It shares validateAudioLinePlan and the CARTESIA_AUDIO_CAPABILITY revision with the pinned hv-audio-line/1 record, so the revision is covered even though this discriminant is not.", coveredBy: "packages/planner/test/audio-phrases.test.ts exercises the discriminant; the revision it pins is pinned here by audioLineV1." },
      { path: "hv-audio-policy/3", reason: "The localized policy discriminant. Same reason as validateAudioPolicy above: it pins a model, not a revision.", coveredBy: "packages/planner/test/localized-audio.test.ts." },
      { path: "validateLipSyncPlan", reason: "hv-lipsync-plan/1 embeds a whole retained source including a complete job and dialogue report, so a golden plan fixture is not proportionate here.", coveredBy: "packages/storage/test — the PostgreSQL-backed lip-sync suites exercise it end to end; validateLipSyncPolicy and validateLipSyncDelivery are pinned above and are the two live-comparison sites a plan reaches." },
      { path: "validateAudioTake", reason: "An audio take embeds a job, a policy and a reparsed screenplay; the line plan it carries is pinned individually above.", coveredBy: "packages/storage/test/audio-jobs.test.ts, which runs against a real PostgreSQL in the CI storage lane." },
    ],
    checks: [...checks].sort((a, b) => a.name.localeCompare(b.name)),
    poolAdmitted: false,
    newProviderSpendUsd: 0,
    liveProviderDispatches: 0,
    provesVendorAvailability: false,
    provesVoiceQuality: false,
    provesLipSyncQuality: false,
    provesLivePricing: false,
  };
}

function validatePins(value: unknown): PinsDocument {
  const document = value as PinsDocument;
  if (!document || typeof document !== "object" || document.schema !== "hv-performance-capability-pins/1") throw new Error("Invalid performance capability pins document.");
  if (!/^\d{4}-\d{2}-\d{2}T[\d:.]+Z$/.test(document.recordedAt)) throw new Error("Invalid performance capability pins document.");
  if (!Array.isArray(document.entries) || !document.entries.length) throw new Error("Invalid performance capability pins document.");
  for (const entry of document.entries) {
    if (!/^[a-f0-9]{64}$/.test(entry.capabilityRevision)) throw new Error("Invalid performance capability pins document.");
    if (entry.paid !== true) throw new Error("Invalid performance capability pins document.");
  }
  if (document.schemaIsInsideTheHash !== true || document.videoSchemaIsOutsideTheHash !== true) throw new Error("Invalid performance capability pins document.");
  if (document.poolAdmitted !== false || document.newProviderSpendUsd !== 0 || document.liveProviderDispatches !== 0) throw new Error("Invalid performance capability pins document.");
  for (const field of ["provesVendorAvailability", "provesVoiceQuality", "provesLipSyncQuality", "provesLivePricing"] as const) {
    if (document[field] !== false) throw new Error("Invalid performance capability pins document.");
  }
  if (!Array.isArray(document.unpinnedReadBackPaths) || !document.unpinnedReadBackPaths.length) throw new Error("Invalid performance capability pins document.");
  // The count of pinned shapes must agree with the list, and must not silently claim the whole
  // surface: fifteen record shapes pin a performance revision and ten of them have a golden record.
  if (document.goldenRecordsCarryingARevisionPin !== document.goldenRecords.length
    || document.goldenRecordsCarryingARevisionPin > document.revisionPinningShapes) throw new Error("Invalid performance capability pins document.");
  return document;
}

// ---------------------------------------------------------------------------
// 7. No dispatch, no network, no key, no pool
// ---------------------------------------------------------------------------
test("performance conformance: nothing was dispatched, no key was read, and no pool exists", () => {
  // The whole proof, and it does not depend on the ambient environment: the stub replaces fetch
  // before any test body runs and was never called. An earlier draft also asserted that the three
  // provider key variables were empty, which was theatre — this suite constructs no adapter, so no
  // key is read either way, and the assertion turned a contributor's exported key into a red run
  // for a reason unrelated to their change.
  expect(fetchCalls).toBe(0);
  // There is no performance pool or admitted plan, deliberately: a pool is a failover set, and
  // this lane forbids failover in code — "No automatic retry, alternate voice, or fallback
  // provider may consume a second reservation." Voice selection is by voice id through an
  // hv-audio-policy record, and admitting a pool would break the three single-heldUsd
  // reservation invariants. That work is HV-022's clause (FULL-SCOPE §P7), not this increment's.
  record({ name: "no-dispatch", pairs: 1, passed: 1, skipped: 0 });
});

test("performance conformance: the pins are committed and re-derived on every run", () => {
  const output = process.env.HV_PERFORMANCE_PINS_EVIDENCE?.trim();
  if (output) {
    const document = validatePins(buildPins());
    mkdirSync(dirname(output), { recursive: true });
    const staging = output + ".tmp";
    writeFileSync(staging, JSON.stringify(document, null, 2) + "\n");
    renameSync(staging, output);
  }

  const text = readFileSync(PINS_PATH, "utf8");
  const document = validatePins(JSON.parse(text));
  // The tripwire. Each recorded revision must equal the revision this build produces; an edit to
  // any capability definition breaks here rather than on a restore months later.
  expect(document.entries.map((entry) => `${entry.lane}:${entry.provider}:${entry.schema}:${entry.capabilityRevision}`).sort())
    .toEqual(PERFORMANCE_REGISTRY.map((entry) => `${entry.lane}:${entry.provider}:${entry.schema}:${entry.capabilityRevision}`).sort());
  expect(document.lanes).toEqual([...PERFORMANCE_LANES]);
  expect(document.checks.map((check) => check.name).sort()).toEqual(
    ["audio-modality-unexpressible", "cross-lane-resolver", "golden-records", "hash-shape",
      "moved-revision-refused", "no-dispatch", "registry-derivation", "revision-is-the-key"],
  );
  // No credential, no destination, no host path. The one 64-hex value that is not a revision is
  // lip-sync's pinned OpenAPI digest, which this file does not record — allowed by name, not by
  // loosening the pattern.
  for (const pattern of [/:\/\//, /API_KEY/i, /\/home\//, /\/Users\//, /\/tmp\//]) expect(text).not.toMatch(pattern);
  const known = new Set(PERFORMANCE_REGISTRY.map((entry) => entry.capabilityRevision));
  for (const hex of text.match(/[a-f0-9]{32,}/g) ?? []) expect({ hex, known: known.has(hex) }).toEqual({ hex, known: true });
  expect(text).not.toContain(LIPSYNC_CAPABILITY.openapiSha256);
  record({ name: "pins-evidence", pairs: PERFORMANCE_REGISTRY.length, passed: PERFORMANCE_REGISTRY.length, skipped: 0 });
});

test("performance conformance: every check family reported an outcome", () => {
  const names = checks.map((check) => check.name);
  expect(new Set(names).size).toBe(names.length);
  expect(names.length).toBe(9); // eight check families plus the pins record itself
});
