import {ELEVENLABS_HOST} from "./elevenlabs-capability";
import {audioAbortable} from "./audio-stream";
import {deliverMusicCue, MusicProviderError, validateMusicCueRequest, type MusicCueDelivery, type MusicCueRequest, type MusicProvider} from "./music-provider";

/**
 * HV-024-11: the ElevenLabs Music adapter, on the existing ElevenLabs account and key (G15). No new
 * vendor, account or key: it reads `HV_ELEVENLABS_API_KEY`, which the voice adapter already uses.
 *
 * **The endpoint's shape is unverified until the live proof.** The repository documents no part of
 * ElevenLabs Music's API, and this increment makes no live call. The request below is written
 * against the endpoint as it is publicly described -- `POST /v1/music` with a prompt, a length in
 * milliseconds and a model, answering with the audio bytes -- and the live proof increment either
 * confirms it or changes it, with the operator's evidence.
 *
 * What does not depend on the shape:
 *
 * - **One request, no retry.** A cue is held before it is asked for, and a second request would
 *   be a second charge against one hold.
 * - **The remote body is never echoed** into an error: it can carry the credential or the prompt back.
 * - **The response's own price, if it sends one, is ignored.** The cost is the length asked for at
 *   the declared rate, which is the hold (`musicCueCostUsd`): the vendor bills `music_length_ms`.
 * - **The seed is not sent.** Nothing in the repository says the endpoint takes one; the mock uses it.
 * - **The output is MP3**, which the voice lesson of HV-022-12 recommends for a plan-independent
 *   contract: an uncompressed format may be sold only on a higher plan than the operator's.
 */
export const ELEVENLABS_MUSIC_MODEL = "music_v1";
export const ELEVENLABS_MUSIC_OUTPUT_FORMAT = "mp3_44100_128";
export const ELEVENLABS_MUSIC_URL = `${ELEVENLABS_HOST}/v1/music?output_format=${ELEVENLABS_MUSIC_OUTPUT_FORMAT}`;
/** Ceiling on the bytes read back: 300 s at 128 kbit/s is under 5 MB. */
const MAX_RESPONSE_BYTES = 16 * 1024 * 1024;

export interface ElevenLabsMusicRequest {
  url: string;
  body: {prompt: string; music_length_ms: number; model_id: string; force_instrumental: true};
}

/** The request, from a validated cue request and nothing else. */
export function elevenLabsMusicRequest(input: MusicCueRequest): ElevenLabsMusicRequest {
  const request = validateMusicCueRequest(input);
  return {url: ELEVENLABS_MUSIC_URL, body: {prompt: request.prompt, music_length_ms: request.durationSec * 1000, model_id: ELEVENLABS_MUSIC_MODEL, force_instrumental: true}};
}

async function boundedBytes(response: Response, signal: AbortSignal): Promise<Buffer> {
  if (!response.body) throw new Error("The music provider returned no audio.");
  const reader = response.body.getReader(), parts: Uint8Array[] = [];
  let total = 0;
  for (;;) {
    const {done, value} = await audioAbortable(reader.read(), signal);
    if (done) break;
    total += value.length;
    if (total > MAX_RESPONSE_BYTES) { void reader.cancel().catch(() => {}); throw new Error("The music provider sent more audio than a cue can hold."); }
    parts.push(value);
  }
  return Buffer.concat(parts);
}

export class ElevenLabsMusicProvider implements MusicProvider {
  readonly name = "elevenlabs";
  readonly model = ELEVENLABS_MUSIC_MODEL;
  readonly rights = {basis: "licensed" as const, source: `Generated by ElevenLabs Music (${ELEVENLABS_MUSIC_MODEL}) on the studio operator's account`,
    credit: "Composer (AI crew), generated with ElevenLabs Music",
    terms: "Generated for this film by ElevenLabs Music on the studio operator's ElevenLabs account; its use is governed by that account's terms."};
  private readonly fetchImpl: typeof fetch;
  private readonly timeoutMs: number;
  constructor(private readonly options: {apiKey: string; fetchImpl?: typeof fetch; timeoutMs?: number}) {
    if (typeof options.apiKey !== "string" || !options.apiKey.trim() || options.apiKey.length > 4096 || /\s/.test(options.apiKey))
      throw new Error("Configure the ElevenLabs credential on the studio.");
    this.fetchImpl = options.fetchImpl ?? fetch;
    const timeout = options.timeoutMs ?? 240000;
    if (!Number.isInteger(timeout) || timeout < 1 || timeout > 600000) throw new Error("Use a music request timeout of 1 ms to 10 minutes.");
    this.timeoutMs = timeout;
  }

  async compose(input: MusicCueRequest, signal?: AbortSignal): Promise<MusicCueDelivery> {
    let request: ElevenLabsMusicRequest, cue: MusicCueRequest;
    try { cue = validateMusicCueRequest(input); request = elevenLabsMusicRequest(cue); }
    catch (error) { throw new MusicProviderError((error as Error).message, false); }
    const deadline = AbortSignal.timeout(this.timeoutMs), combined = signal ? AbortSignal.any([signal, deadline]) : deadline;
    if (combined.aborted) throw new MusicProviderError("The music request was cancelled before it was sent.", false);
    // From here the vendor may have been asked, and may bill: every failure says `dispatched`.
    let providerRequestId: string | null = null;
    try {
      const response = await audioAbortable(this.fetchImpl(request.url, {method: "POST", redirect: "manual", signal: combined,
        headers: {"xi-api-key": this.options.apiKey, "content-type": "application/json", accept: "audio/mpeg"},
        body: JSON.stringify(request.body)}), combined, late => { void late.body?.cancel().catch(() => {}); });
      const id = response.headers.get("request-id");
      if (typeof id === "string" && /^[A-Za-z0-9_-]{1,128}$/.test(id)) providerRequestId = id;
      if (!response.ok) {
        void response.body?.cancel().catch(() => {});
        throw new Error("The music provider refused the request (HTTP " + response.status + ").");
      }
      if (response.headers.get("content-type")?.split(";", 1)[0]?.trim().toLowerCase() !== "audio/mpeg") {
        void response.body?.cancel().catch(() => {});
        throw new Error("The music provider did not return MP3 audio.");
      }
      const bytes = await boundedBytes(response, combined);
      return await deliverMusicCue(bytes, cue, {formats: ["mp3"], provider: this.name, model: this.model, providerRequestId}, combined);
    } catch (error) {
      const message = deadline.aborted && !signal?.aborted ? "The music provider did not answer in time."
        : signal?.aborted ? "The music request was cancelled." : (error as Error).message;
      // Our own messages only: none of them carries the response body.
      throw new MusicProviderError(message, true, providerRequestId);
    }
  }
}

/**
 * The studio's music provider, from the operator's environment.
 *
 * Live music is reachable only when the operator asks for it by name -- `HV_MUSIC_PROVIDER=elevenlabs`
 * -- and the key the voice adapter already uses is present, the same two-part gate the voice adapter
 * has (`HV_ELEVENLABS_API_KEY` and the operator's `HV_AUDIO_POLICY_FILE`). The key alone is not
 * enough: it is on the staging host already, for voices. With nothing set there is no music provider
 * and the Composer writes its own score. Any other value fails at startup rather than at the first cue.
 */
export const MUSIC_PROVIDER_ENV = "HV_MUSIC_PROVIDER";
export function musicProviderFromEnvironment(env: Record<string, string | undefined> = process.env, fetchImpl?: typeof fetch): MusicProvider | undefined {
  const value = (env[MUSIC_PROVIDER_ENV] ?? "").trim();
  if (value === "" || value === "none") return undefined;
  if (value !== "elevenlabs") throw new Error("Set " + MUSIC_PROVIDER_ENV + " to elevenlabs, or leave it unset for the Composer's own score.");
  if (!env.HV_ELEVENLABS_API_KEY) throw new Error(MUSIC_PROVIDER_ENV + "=elevenlabs needs the ElevenLabs credential the voice adapter uses.");
  return new ElevenLabsMusicProvider({apiKey: env.HV_ELEVENLABS_API_KEY, ...(fetchImpl ? {fetchImpl} : {})});
}
