import {createHash} from "node:crypto";
import {appendFileSync,closeSync,copyFileSync,existsSync,ftruncateSync,lstatSync,mkdirSync,mkdtempSync,openSync,readFileSync,readSync,readdirSync,realpathSync,rmSync,statSync,writeFileSync,writeSync} from "node:fs";
import {dirname,join,resolve,sep} from "node:path";
import type {Job,JobInput} from "../../queue/src/index";
import type {RenderFile} from "../../planner/src/shot-reuse";
import {soundCueSheet,soundBaseDialogue,soundBaseFrames,soundVoiceWindows,validateSoundJob,validateSoundOutput,type SoundPlan,type SoundMixReport} from "../../planner/src/sound-jobs";
import {SOUND_MIX_RECIPE,SOUND_STEMS,soundCopiedAssetName,soundSessionAssets,type SoundStem} from "../../planner/src/sound-session";
import {SOUND_FRAME_BYTES,soundFail,type SoundAsset} from "../../planner/src/sound-assets";
import {soundWavHeader,verifySoundWav,inspectSoundWav,soundCommand,soundRuntimeRevision} from "./sound-audio";

import {restoreSoundTracks,verifyRestoredTracks} from "./sound-restoration";
import {finishSoundMaster,completeSoundFinishing,measureSound,verifyFinishingRecords} from "./sound-finishing";
import {mixSoundSession} from "./sound-mixer";
import {speechWavHeader} from "./speech";
import {audioPcmHash} from "./audio-delivery";
import {contentHash} from "./capabilities";
import {dialogueSource} from "../../planner/src/dialogue-replacement";
import {retainedDialogueTime} from "../../planner/src/dialogue-jobs";
import {copyDialogueFiles,verifyDialogueMedia,videoIdentity,type DialogueArtifactReader} from "./dialogue-replacement";
import {verifyLipSyncMedia,lipCommand} from "./lipsync-media";
import {validateExport} from "../../assembler/src/index";
import {provenanceMatches} from "../../planner/src/provenance";
export async function soundDigest(path:string,signal?:AbortSignal):Promise<{sha256:string;bytes:number}>{const hash=createHash("sha256");let bytes=0;for await(const part of Bun.file(path).stream()){signal?.throwIfAborted();bytes+=part.length;if(bytes>8*1024**3)soundFail("A sound artifact exceeds its limit.");hash.update(part);}return {sha256:hash.digest("hex"),bytes};}
function local(root:string,key:string):string{if(!/^[A-Za-z0-9._/-]+$/.test(key)||key.split("/").some(p=>!p||p==="."||p===".."))soundFail("Invalid sound media path.");const path=resolve(root,key);if(!path.startsWith(root+sep)||!lstatSync(path).isFile()||lstatSync(path).isSymbolicLink()||!realpathSync(path).startsWith(root+sep))soundFail("Sound media escaped its workspace.");return path;}
function copy(source:string,destination:string):void{mkdirSync(dirname(destination),{recursive:true});copyFileSync(source,destination,1);}
function remove(root:string,directory:string):void{if(!directory.startsWith(root+sep)||realpathSync(directory)!==directory)soundFail("Sound scratch media escaped its workspace.");rmSync(directory,{recursive:true,force:true});}
async function checkBase(plan:SoundPlan,root:string,signal?:AbortSignal):Promise<void>{const base=plan.source.base;
  for(const file of plan.source.baseFiles){const d=await soundDigest(local(root,file.path),signal);if(d.sha256!==file.sha256||d.bytes!==file.bytes)soundFail("The original sound source media changed.");}
  if(base.dialogueReplacement)await verifyDialogueMedia(base,base.output!,root,signal,retainedDialogueTime(base));else if(base.lipSync)await verifyLipSyncMedia(base,base.output!,root,signal);
  else{const path=local(root,base.output!.manifestPath);if(statSync(path).size>32*1024**2)soundFail("Source provenance is too large.");const provenance=JSON.parse(readFileSync(path,"utf8")),video=plan.source.baseFiles.find(f=>f.path===base.output!.mp4Path)!;
    if(!provenanceMatches(provenance,{projectId:base.projectId,sha256:video.sha256})||contentHash(provenance.shots?.map((s:{renderRecord?:unknown})=>s.renderRecord))!==contentHash(dialogueSource(base,Date.parse(base.completedAt!)).shots))soundFail("The picture's original provenance changed.");}
}
/** Rebuild 22050 Hz source voice files without resynthesizing any line. */
export async function retainedSourceVoices(base:Job,root:string,directory:string,access:()=>Promise<void>,signal?:AbortSignal):Promise<{dialogue:string;narration:string}>{
  const dialogue=soundBaseDialogue(base),samples=soundBaseFrames(base)*735,paths={dialogue:join(directory,"source-dialogue.wav"),narration:join(directory,"source-narration.wav")};
  if(dialogue){const wav=base.output!.dialogue?.wavPath??base.output!.lipSync!.wavPath,sourceDirectory=dirname(local(root,wav));copy(dialogue.narration?join(sourceDirectory,"ducked-dialogue.wav"):local(root,wav),paths.dialogue);if(dialogue.narration)copy(join(sourceDirectory,"narration.wav"),paths.narration);}
  else{const fd=openSync(paths.dialogue,"wx");try{writeSync(fd,speechWavHeader(samples));ftruncateSync(fd,44+samples*2);let offset=0;for(const shot of base.output!.shotRenders!){await access();signal?.throwIfAborted();if(shot.clip.speech){const report=shot.clip.speech,wav=readFileSync(local(root,shot.files.audio!.path));if(!wav.subarray(0,44).equals(speechWavHeader(report.totalSamples))||wav.length!==44+report.totalSamples*2)soundFail("The original dialogue WAV format changed.");const pcm=wav.subarray(44);let cursor=0;for(const line of report.lines){if(!pcm.subarray(cursor*2,line.startSample*2).every(b=>b===0)||audioPcmHash(pcm.subarray(line.startSample*2,line.endSample*2))!==line.pcmSha256)soundFail("The original measured dialogue waveform changed.");cursor=line.endSample;}if(!pcm.subarray(cursor*2).every(b=>b===0))soundFail("Original dialogue contains unrecorded sound.");writeSync(fd,pcm,0,pcm.length,44+offset*2);}offset+=Math.round(shot.clip.durationSec*30)*735;}}finally{closeSync(fd);}}
  if(!existsSync(paths.narration)){const fd=openSync(paths.narration,"wx");try{writeSync(fd,speechWavHeader(samples));ftruncateSync(fd,44+samples*2);}finally{closeSync(fd);}}
  for(const path of Object.values(paths)){const header=Buffer.from(await Bun.file(path).slice(0,44).arrayBuffer());if(statSync(path).size!==44+samples*2||!header.equals(speechWavHeader(samples)))soundFail("A retained voice stem changed its timeline.");}return paths;
}
async function convertVoice(source:string,destination:string,frames:number,cwd:string,signal?:AbortSignal):Promise<void>{
  const pcm=destination+".pcm",filter=`pan=stereo|c0=c0|c1=c0,apad=pad_len=128,aresample=48000:resampler=swr:filter_size=64:phase_shift=10:exact_rational=1:dither_method=none,atrim=end_sample=${frames}`;
  await soundCommand(["ffmpeg","-v","error","-nostdin","-protocol_whitelist","file,pipe","-f","wav","-i",source,"-map","0:a:0","-af",filter,"-c:a","pcm_s24le","-f","s24le",pcm],cwd,signal);if(statSync(pcm).size!==frames*SOUND_FRAME_BYTES)soundFail("The voice conversion changed its duration.");writeFileSync(destination,soundWavHeader(frames),{flag:"wx"});for await(const chunk of Bun.file(pcm).stream()){signal?.throwIfAborted();appendFileSync(destination,chunk);}rmSync(pcm);
}
function voiceReader(directory:string):{read:(stem:"dialogue"|"narration",offset:number,frames:number)=>Buffer;close:()=>void}{const fds={dialogue:openSync(join(directory,"dialogue.wav"),"r"),narration:openSync(join(directory,"narration.wav"),"r")};return {read(stem,offset,frames){const bytes=Buffer.alloc(frames*SOUND_FRAME_BYTES);if(readSync(fds[stem],bytes,0,bytes.length,44+offset*SOUND_FRAME_BYTES)!==bytes.length)soundFail("A voice stem changed while mixing.");return bytes;},close(){Object.values(fds).forEach(fd=>closeSync(fd));}};}
async function exportProbe(path:string,cwd:string,frames:number,signal?:AbortSignal):Promise<void>{const p=JSON.parse((await lipCommand(["ffprobe","-v","error","-show_streams","-show_format","-of","json",path],cwd,signal)).toString()),video=p.streams.find((s:any)=>s.codec_type==="video");validateExport(p,{width:video?.width,height:video?.height,fps:30,durationSec:frames/30});const audio=p.streams.filter((s:any)=>s.codec_type==="audio");if(audio.length!==1||audio[0].channels!==2||Number(audio[0].sample_rate)!==48000)soundFail("The sound export must have one stereo 48 kHz AAC soundtrack.");}
export async function renderSoundMix(job:Job|JobInput,root:string,destination:string,readAsset:(asset:SoundAsset,kind:"original"|"audio")=>Promise<Buffer>,access:()=>Promise<void>,signal?:AbortSignal,reader?:DialogueArtifactReader):Promise<SoundMixReport>{
  validateSoundJob(job,Date.now());const plan=job.soundMix!;if(soundRuntimeRevision()!==plan.engineVersion)soundFail("The sound runtime changed after review.");await access();if(existsSync(destination))soundFail("Choose a new destination for the sound version.");mkdirSync(destination,{recursive:true});const workspace=mkdtempSync(join(realpathSync(root),".sound-source-")),incoming=join(workspace,"incoming"),origin=join(workspace,"origin");mkdirSync(incoming);mkdirSync(origin);
  try{
    await copyDialogueFiles({id:plan.source.jobId,projectId:job.projectId},plan.source.files.map(f=>f.file),root,incoming,signal,reader);
    for(const [i,item]of plan.source.files.entries()){copy(local(realpathSync(incoming),item.file.path),join(origin,plan.source.baseFiles[i]!.path));copy(local(realpathSync(incoming),item.file.path),join(destination,item.name));}await checkBase(plan,realpathSync(origin),signal);await access();
    const base=plan.source.base,video=local(realpathSync(origin),base.output!.mp4Path),picture=await videoIdentity(video,workspace,signal);if(picture.frames!==job.totalFrames)soundFail("The selected picture length changed.");
    const source=await retainedSourceVoices(plan.source.base,realpathSync(origin),workspace,access,signal),baseVoiceSourceSha256={dialogue:(await soundDigest(source.dialogue,signal)).sha256,narration:(await soundDigest(source.narration,signal)).sha256},voiceDirectory=join(destination,"voices");mkdirSync(voiceDirectory);
    for(const stem of ["dialogue","narration"] as const){await convertVoice(source[stem],join(voiceDirectory,stem+".wav"),plan.session.totalFrames,workspace,signal);await access();}
    const baseVoiceSha256={dialogue:(await soundDigest(join(voiceDirectory,"dialogue.wav"),signal)).sha256,narration:(await soundDigest(join(voiceDirectory,"narration.wav"),signal)).sha256},recordings=new Map<string,Buffer>();
    for(const asset of soundSessionAssets(plan.session)){for(const kind of ["original","audio"] as const){await access();const bytes=await readAsset(asset,kind);if(bytes.length!==asset[kind].bytes||audioPcmHash(bytes)!==asset[kind].sha256)soundFail("A sound recording changed before mixing.");if(kind==="audio")recordings.set(asset.id,verifySoundWav(bytes,asset.audio.frames,asset.audio.sha256));else inspectSoundWav(bytes);const path=join(destination,soundCopiedAssetName(asset,kind));mkdirSync(dirname(path),{recursive:true});writeFileSync(path,bytes,{flag:"wx",mode:0o600});}}
    const stemDirectory=join(destination,"stems"),rawStemDirectory=plan.session.restoration?join(destination,"restoration/original"):stemDirectory;mkdirSync(rawStemDirectory,{recursive:true});const fds=Object.fromEntries(SOUND_STEMS.map(stem=>{const fd=openSync(join(rawStemDirectory,stem+".wav"),"wx");writeSync(fd,soundWavHeader(plan.session.totalFrames));return [stem,fd];})) as Record<SoundStem,number>,voices=voiceReader(voiceDirectory),voiceWindows=soundVoiceWindows(base);let peaks:Record<SoundStem,number>;
    try{peaks=await mixSoundSession(plan.session,voices.read,recordings,voiceWindows,async(_offset,chunks)=>{for(const stem of SOUND_STEMS)writeSync(fds[stem],chunks[stem]);},access,signal);}finally{voices.close();Object.values(fds).forEach(fd=>closeSync(fd));}
    const restored=plan.session.restoration?await restoreSoundTracks(rawStemDirectory,stemDirectory,join(destination,"restoration"),plan.session.restoration,plan.session.totalFrames,peaks,access,signal):undefined;const restoration=restored?.report;if(restored){peaks=restored.peaks;writeFileSync(join(destination,"restoration/report.json"),JSON.stringify(restoration,null,2)+"\n",{flag:"wx"});}
    const stems=Object.fromEntries(await Promise.all(SOUND_STEMS.map(async stem=>[stem,(await soundDigest(join(stemDirectory,stem+".wav"),signal)).sha256]))) as Record<SoundStem,string>;
    const finishingDirectory=join(destination,"finishing");if(plan.session.finishing)mkdirSync(finishingDirectory);const finished=plan.session.finishing?await finishSoundMaster(join(stemDirectory,"mix.wav"),plan.session.totalFrames,finishingDirectory,plan.session.finishing,access,signal):undefined;
    const mp4=join(destination,"export.mp4");await soundCommand(["ffmpeg","-v","error","-nostdin","-i",video,"-i",finished?join(finishingDirectory,"master.wav"):join(stemDirectory,"mix.wav"),"-map","0:v:0","-map","1:a:0","-c:v","copy","-c:a","aac","-b:a","256k","-ar","48000","-ac","2","-t",String(picture.frames/30),"-map_metadata","-1","-movflags","+faststart",mp4],workspace,signal);
    if(contentHash(await videoIdentity(mp4,workspace,signal))!==contentHash(picture))soundFail("Sound mixing changed the encoded picture.");await exportProbe(mp4,workspace,picture.frames,signal);copy(local(realpathSync(origin),base.output!.captionsPath),join(destination,"captions.vtt"));
    mkdirSync(join(destination,"hls"));await soundCommand(["ffmpeg","-v","error","-nostdin","-i",mp4,"-map","0:v:0","-map","0:a:0","-c","copy","-hls_time","2","-hls_list_size","0","-hls_playlist_type","vod","-hls_segment_filename",join(destination,"hls/segment-%03d.ts"),join(destination,"hls/index.m3u8")],workspace,signal);
    const finishing=finished?completeSoundFinishing(finished,await measureSound(mp4,plan.session.totalFrames,finishingDirectory,"encoded",access,signal)):undefined;if(finishing)writeFileSync(join(finishingDirectory,"report.json"),JSON.stringify(finishing,null,2)+"\n",{flag:"wx"});
    if(soundRuntimeRevision()!==plan.engineVersion)soundFail("The sound runtime changed while mixing.");await access();const report:SoundMixReport={schema:restoration?"hv-sound-result/3":finishing?"hv-sound-result/2":"hv-sound-result/1",...(finishing?{finishing}:{}),...(restoration?{restoration}:{}),plan,recipeRevision:contentHash(SOUND_MIX_RECIPE),videoSha256:(await soundDigest(mp4,signal)).sha256,videoStreamSha256:picture.sha256,totalVideoFrames:picture.frames,voiceWindows,baseVoiceSourceSha256,baseVoiceSha256,stems,peaks};writeFileSync(join(destination,"provenance.json"),JSON.stringify(report,null,2)+"\n",{flag:"wx"});writeFileSync(join(destination,"cue-sheet.json"),JSON.stringify(soundCueSheet(plan,job.id),null,2)+"\n",{flag:"wx"});return report;
  }finally{remove(realpathSync(root),workspace);}
}
export async function sealSoundMix(job:Job|JobInput,directory:string,root:string,report:SoundMixReport,signal?:AbortSignal):Promise<NonNullable<Job["output"]>>{
  const files:RenderFile[]=[];async function visit(path:string):Promise<void>{for(const entry of readdirSync(path,{withFileTypes:true})){if(entry.isSymbolicLink())soundFail("Sound artifacts cannot be symbolic links.");const next=join(path,entry.name);if(entry.isDirectory())await visit(next);else if(entry.isFile())files.push({path:next.slice(root.length+1).split(sep).join("/"),...await soundDigest(next,signal)});else soundFail("Invalid sound artifact.");}}await visit(directory);files.sort((a,b)=>a.path.localeCompare(b.path));const prefix=directory.slice(root.length+1).split(sep).join("/")+"/",data={schema:"hv-sound-output/1" as const,report,files},output={mp4Path:prefix+"export.mp4",captionsPath:prefix+"captions.vtt",manifestPath:prefix+"provenance.json",hlsPlaylistPath:prefix+"hls/index.m3u8",sound:{...data,revision:contentHash(data)}};validateSoundOutput(job,output);return output;
}
/** Rebuild the PCM mix from retained normalized voices and recordings, including after archive restore. */
export async function verifySoundMedia(job:Job|JobInput,output:NonNullable<Job["output"]>,root:string,signal?:AbortSignal):Promise<void>{
  validateSoundOutput(job,output);const plan=job.soundMix!,report=output.sound!.report,canonicalRoot=realpathSync(root),directory=dirname(local(canonicalRoot,output.mp4Path));for(const file of output.sound!.files){const d=await soundDigest(local(canonicalRoot,file.path),signal);if(d.sha256!==file.sha256||d.bytes!==file.bytes)soundFail("A retained sound artifact failed checksum verification.");}
  if(contentHash(JSON.parse(readFileSync(local(canonicalRoot,output.manifestPath),"utf8")))!==contentHash(report))soundFail("The sound provenance changed.");
  if(contentHash(JSON.parse(readFileSync(join(directory,"cue-sheet.json"),"utf8")))!==contentHash(soundCueSheet(plan,job.id)))soundFail("The sound cue sheet differs from its reviewed session.");
  const playlist=readFileSync(local(canonicalRoot,output.hlsPlaylistPath),"utf8"),segments=playlist.split(/\r?\n/).map(line=>line.trim()).filter(line=>line&&!line.startsWith("#")),hlsDirectory=output.hlsPlaylistPath.slice(0,-"index.m3u8".length),ownedSegments=output.sound!.files.filter(file=>file.path.startsWith(hlsDirectory)&&file.path.endsWith(".ts")).map(file=>file.path.slice(hlsDirectory.length)).sort();
  if(!playlist.startsWith("#EXTM3U")||!playlist.includes("#EXT-X-ENDLIST")||!segments.length||segments.some(name=>!/^segment-\d{3,5}\.ts$/.test(name))||new Set(segments).size!==segments.length||contentHash(segments.slice().sort())!==contentHash(ownedSegments))soundFail("The sound HLS playlist differs from its owned segments.");
  const workspace=mkdtempSync(join(canonicalRoot,".sound-verify-")),origin=join(workspace,"origin");mkdirSync(origin);try{
    for(const file of plan.source.baseFiles)copy(join(directory,"source",file.path),join(origin,file.path));await checkBase(plan,realpathSync(origin),signal);const source=await retainedSourceVoices(plan.source.base,realpathSync(origin),workspace,async()=>{},signal);
    for(const stem of ["dialogue","narration"] as const){if((await soundDigest(source[stem],signal)).sha256!==report.baseVoiceSourceSha256[stem])soundFail("The source voice waveform changed.");const path=join(directory,"voices",stem+".wav");if(!Buffer.from(await Bun.file(path).slice(0,44).arrayBuffer()).equals(soundWavHeader(plan.session.totalFrames)))soundFail("The retained voice conversion format changed.");}
    const picture=await videoIdentity(local(canonicalRoot,output.mp4Path),workspace,signal),original=await videoIdentity(local(realpathSync(origin),plan.source.base.output!.mp4Path),workspace,signal);if(contentHash(picture)!==contentHash(original)||picture.sha256!==report.videoStreamSha256||picture.frames!==report.totalVideoFrames)soundFail("The retained sound export changed the picture.");await exportProbe(local(canonicalRoot,output.mp4Path),workspace,job.totalFrames,signal);
    if(!readFileSync(local(canonicalRoot,output.captionsPath)).equals(readFileSync(local(realpathSync(origin),plan.source.base.output!.captionsPath))))soundFail("Sound mixing changed the caption track.");
    const recordings=new Map<string,Buffer>();for(const asset of soundSessionAssets(plan.session)){const original=readFileSync(join(directory,soundCopiedAssetName(asset,"original"))),audio=readFileSync(join(directory,soundCopiedAssetName(asset,"audio")));inspectSoundWav(original);recordings.set(asset.id,verifySoundWav(audio,asset.audio.frames,asset.audio.sha256));}
    const hashes=Object.fromEntries(SOUND_STEMS.map(stem=>[stem,createHash("sha256").update(soundWavHeader(plan.session.totalFrames))])) as Record<SoundStem,ReturnType<typeof createHash>>,voices=voiceReader(join(directory,"voices"));let peaks;
    try{peaks=await mixSoundSession(plan.session,voices.read,recordings,report.voiceWindows,async(_offset,chunks)=>{for(const stem of SOUND_STEMS)hashes[stem].update(chunks[stem]);},async()=>{},signal);}finally{voices.close();}
    if(report.restoration){const r=report.restoration,folder=join(directory,"restoration"),original=join(folder,"original"),processed=join(directory,"stems");if(contentHash(JSON.parse(readFileSync(join(folder,"report.json"),"utf8")))!==contentHash(r))soundFail("The downloadable restoration report changed.");const restoredPeaks=await verifyRestoredTracks(original,processed,folder,r,plan.session.totalFrames,async()=>{},signal);if(contentHash(restoredPeaks)!==contentHash(report.peaks))soundFail("Restored sample peaks changed.");if(soundRuntimeRevision()===r.engineVersion){const repro=join(workspace,"restoration");const check=await restoreSoundTracks(original,join(repro,"stems"),join(repro,"records"),r.settings,plan.session.totalFrames,r.inputPeaks,async()=>{},signal);if(contentHash(check.report)!==contentHash(r)||contentHash(check.peaks)!==contentHash(report.peaks))soundFail("The restored sound differs from its reviewed processing.");}}
    if(report.finishing){const saved=report.finishing,folder=join(directory,"finishing");verifyFinishingRecords(saved,folder);if(contentHash(JSON.parse(readFileSync(join(folder,"report.json"),"utf8")))!==contentHash(saved))soundFail("The downloadable loudness report changed.");
      const probe=join(workspace,"finishing");mkdirSync(probe);for(const [tag,path]of [["after",join(folder,"master.wav")],["encoded",local(canonicalRoot,output.mp4Path)]] as const){const measured=await measureSound(path,plan.session.totalFrames,probe,tag,async()=>{},signal);for(const key of ["integratedLufs","truePeakDbtp","rangeLu","relativeGateLufs","momentaryMaxLufs","shortTermMaxLufs"] as const){const a=measured[key],b=saved[tag][key];if(a===null||b===null?a!==b:Math.abs(a-b)>0.11)soundFail("The delivered waveform differs from its retained loudness measurement.");}}
      if(soundRuntimeRevision()===saved.engineVersion){const reproduced=join(workspace,"reprocessed");mkdirSync(reproduced);const master=await finishSoundMaster(join(directory,"stems/mix.wav"),plan.session.totalFrames,reproduced,saved.settings,async()=>{},signal);if(master.masterSha256!==saved.masterSha256||master.mode!==saved.mode||contentHash(master.before)!==contentHash(saved.before))soundFail("The delivery master differs from its reviewed processing.");}
    }
    if(!SOUND_STEMS.every(stem=>hashes[stem].digest("hex")===(report.restoration?.inputStems??report.stems)[stem])||contentHash(peaks)!==contentHash(report.restoration?.inputPeaks??report.peaks))soundFail("The retained sound mix differs from its reviewed recipe.");
  }finally{remove(canonicalRoot,workspace);}
}
