import {createHash} from "node:crypto";
import {appendFileSync,closeSync,copyFileSync,mkdirSync,mkdtempSync,openSync,readSync,realpathSync,rmSync,statSync,writeFileSync,writeSync} from "node:fs";
import {join,sep} from "node:path";
import {contentHash} from "./capabilities";
import {soundRuntimeRevision,soundWavHeader} from "./sound-audio";
import {soundProcessingCommand} from "./sound-finishing";
import {soundFail} from "../../planner/src/sound-assets";
import {RESTORATION_RECIPE,RESTORATION_TRACKS,RESTORATION_STEMS,restorationFilter,soundRestoration,type SoundRestoration,type RestoredTrack,type RestorationLevels,type RestorationReport} from "../../planner/src/sound-restoration";
type Access=()=>Promise<void>;
type Stem=typeof RESTORATION_STEMS[number];
export function removedWavHeader(frames:number):Buffer{const h=soundWavHeader(frames);h.writeUInt32LE(36+frames*8,4);h.writeUInt16LE(3,20);h.writeUInt32LE(48000*8,28);h.writeUInt16LE(8,32);h.writeUInt16LE(32,34);h.writeUInt32LE(frames*8,40);return h;}
async function digest(path:string,signal?:AbortSignal):Promise<string>{const h=createHash("sha256");for await(const b of Bun.file(path).stream()){signal?.throwIfAborted();h.update(b);}return h.digest("hex");}
async function checkWav(path:string,frames:number,removed=false):Promise<void>{if(statSync(path).size!==44+frames*(removed?8:6)||!Buffer.from(await Bun.file(path).slice(0,44).arrayBuffer()).equals(removed?removedWavHeader(frames):soundWavHeader(frames)))soundFail("A restoration waveform changed its format or duration.");}
function read(fd:number,offset:number,bytes:number):Buffer{const b=Buffer.alloc(bytes);if(readSync(fd,b,0,bytes,offset)!==bytes)soundFail("A sound track changed during restoration.");return b;}
function accumulator(){return {peak:[0,0],square:[0,0]};}
function add(a:ReturnType<typeof accumulator>,value:number,ch:number){a.peak[ch]=Math.max(a.peak[ch]!,Math.abs(value));a.square[ch]!+=value*value;}
function levels(a:ReturnType<typeof accumulator>,frames:number):RestorationLevels{return {peak:a.peak as [number,number],rms:a.square.map(n=>Math.sqrt(n/frames)) as [number,number]};}
/** Float residuals exactly represent the difference of two 24-bit integer samples, including values above full scale. */
export async function restorationLevels(input:string,output:string,removed:string,frames:number,writeRemoved:boolean,access:Access,signal?:AbortSignal){
  await checkWav(input,frames);await checkWav(output,frames);if(!writeRemoved)await checkWav(removed,frames,true);const a=openSync(input,"r"),b=openSync(output,"r"),r=openSync(removed,writeRemoved?"wx":"r"),before=accumulator(),after=accumulator(),difference=accumulator();
  try{if(writeRemoved)writeSync(r,removedWavHeader(frames));for(let offset=0;offset<frames;offset+=65536){signal?.throwIfAborted();await access();const count=Math.min(65536,frames-offset),original=read(a,44+offset*6,count*6),restored=read(b,44+offset*6,count*6),residual=writeRemoved?Buffer.alloc(count*8):read(r,44+offset*8,count*8);
    for(let i=0;i<count*2;i++){const v=original.readIntLE(i*3,3)/8388608,w=restored.readIntLE(i*3,3)/8388608,d=v-w;if(writeRemoved)residual.writeFloatLE(d,i*4);else if(residual.readFloatLE(i*4)!==d)soundFail("The removed signal no longer reconstructs its original track.");add(before,v,i%2);add(after,w,i%2);add(difference,d,i%2);}if(writeRemoved)writeSync(r,residual);
  }}finally{closeSync(a);closeSync(b);closeSync(r);}return {before:levels(before,frames),after:levels(after,frames),removed:levels(difference,frames)};
}
async function referenceLevels(path:string,frames:number):Promise<RestorationLevels>{await checkWav(path,frames);const fd=openSync(path,"r"),values=accumulator();try{for(let offset=0;offset<frames;offset+=65536){const count=Math.min(65536,frames-offset),b=read(fd,44+offset*6,count*6);for(let i=0;i<count*2;i++)add(values,b.readIntLE(i*3,3)/8388608,i%2);}}finally{closeSync(fd);}return levels(values,frames);}
async function quantize(path:string,destination:string,frames:number,access:Access,signal?:AbortSignal):Promise<void>{
  if(statSync(path).size!==frames*16)soundFail("Restoration changed the sound track's sample count.");const input=openSync(path,"r"),output=openSync(destination,"wx");try{writeSync(output,soundWavHeader(frames));for(let offset=0;offset<frames;offset+=65536){await access();signal?.throwIfAborted();const count=Math.min(65536,frames-offset),f=read(input,offset*16,count*16),pcm=Buffer.alloc(count*6);for(let i=0;i<count*2;i++){const sample=f.readDoubleLE(i*8),v=Math.round(sample*8388608);if(!Number.isFinite(sample)||v< -8388608||v>8388607)soundFail("Restoration would overload a track. Reduce its input level or noise reduction, then review again.");pcm.writeIntLE(v,i*3,3);}writeSync(output,pcm);}}finally{closeSync(input);closeSync(output);}
}
/** Recombine the five post-restoration integer stems; no rounding or limiter can hide an overloaded sum. */
export async function sumRestoredStems(directory:string,frames:number,writeMixes:boolean,access:Access,signal?:AbortSignal):Promise<Record<Stem,number>>{
  for(const t of RESTORATION_TRACKS)await checkWav(join(directory,t+".wav"),frames);const fds=RESTORATION_TRACKS.map(t=>openSync(join(directory,t+".wav"),"r")),mixes={me:openSync(join(directory,"me.wav"),writeMixes?"wx":"r"),mix:openSync(join(directory,"mix.wav"),writeMixes?"wx":"r")},peaks=Object.fromEntries(RESTORATION_STEMS.map(t=>[t,0])) as Record<Stem,number>;
  try{for(const fd of Object.values(mixes))if(writeMixes)writeSync(fd,soundWavHeader(frames));for(let offset=0;offset<frames;offset+=65536){await access();signal?.throwIfAborted();const count=Math.min(65536,frames-offset),buffers=fds.map(fd=>read(fd,44+offset*6,count*6)),out={me:Buffer.alloc(count*6),mix:Buffer.alloc(count*6)};
    for(let i=0;i<count*2;i++){const values=buffers.map((b,j)=>{const v=b.readIntLE(i*3,3);peaks[RESTORATION_TRACKS[j]!]=Math.max(peaks[RESTORATION_TRACKS[j]!]!,Math.abs(v));return v;}),me=values[2]!+values[3]!+values[4]!,mix=me+values[0]!+values[1]!;for(const [stem,value]of [["me",me],["mix",mix]] as const){if(value< -8388608||value>8388607)soundFail("The restored sound mix would clip. Reduce the relevant track levels and review again.");out[stem].writeIntLE(value,i*3,3);peaks[stem]=Math.max(peaks[stem],Math.abs(value));}}
    for(const stem of ["me","mix"] as const){if(writeMixes)writeSync(mixes[stem],out[stem]);else if(!read(mixes[stem],44+offset*6,count*6).equals(out[stem]))soundFail("The restored mix differs from its retained track stems.");}
  }}finally{for(const fd of [...fds,...Object.values(mixes)])closeSync(fd);}return peaks;
}
export async function restoreSoundTracks(originalDirectory:string,stemDirectory:string,recordDirectory:string,settings:SoundRestoration,frames:number,inputPeaks:Record<Stem,number>,access:Access,signal?:AbortSignal):Promise<{report:RestorationReport;peaks:Record<Stem,number>}>{
  soundRestoration(settings,frames);const engineVersion=soundRuntimeRevision();mkdirSync(stemDirectory,{recursive:true});mkdirSync(recordDirectory,{recursive:true});mkdirSync(join(recordDirectory,"removed"));mkdirSync(join(recordDirectory,"reference"));const root=realpathSync(recordDirectory),scratch=mkdtempSync(join(root,".processing-")),tracks:RestoredTrack[]=[],inputStems={} as Record<Stem,string>;
  try{for(const stem of RESTORATION_STEMS){await access();await checkWav(join(originalDirectory,stem+".wav"),frames);inputStems[stem]=await digest(join(originalDirectory,stem+".wav"),signal);}
    for(const stem of RESTORATION_TRACKS){const source=join(originalDirectory,stem+".wav"),destination=join(stemDirectory,stem+".wav"),t=settings.tracks.find(t=>t.track===stem);if(!t){copyFileSync(source,destination,1);continue;}let input=source,referenceSha256:string|undefined,noiseLevels:RestorationLevels|undefined;
      if(t.reference){const r=t.reference,reference=join(recordDirectory,"reference",stem+".wav"),fd=openSync(source,"r");let bytes:Buffer;try{bytes=read(fd,44+r.start*6,r.frames*6);}finally{closeSync(fd);}writeFileSync(reference,Buffer.concat([soundWavHeader(r.frames),bytes]),{flag:"wx"});referenceSha256=await digest(reference,signal);noiseLevels=await referenceLevels(reference,r.frames);if(noiseLevels.peak.every(p=>p===0))soundFail("The noise reference is silent. Choose audible unwanted noise or use a fixed floor.");
        input=join(scratch,stem+"-training.wav");writeFileSync(input,Buffer.concat([soundWavHeader(r.frames+2400+frames),bytes,Buffer.alloc(2400*6)]),{flag:"wx"});for await(const part of Bun.file(source).slice(44).stream()){signal?.throwIfAborted();appendFileSync(input,part);}
      }
      const filtered=join(scratch,stem+".f64"),filter=restorationFilter(t,frames);await soundProcessingCommand(["ffmpeg","-hide_banner","-v","error","-nostdin","-protocol_whitelist","file,pipe","-filter_threads","1","-i",input,"-map","0:a:0","-af",filter,"-ar","48000","-ac","2","-c:a","pcm_f64le","-f","f64le",filtered],scratch,access,signal);await quantize(filtered,destination,frames,access,signal);
      const removed=join(recordDirectory,"removed",stem+".wav"),values=await restorationLevels(source,destination,removed,frames,true,access,signal);tracks.push({settings:t,filter,inputSha256:inputStems[stem],outputSha256:await digest(destination,signal),removedSha256:await digest(removed,signal),...(referenceSha256?{referenceSha256,referenceLevels:noiseLevels}:{}),...values});
    }
    const peaks=await sumRestoredStems(stemDirectory,frames,true,access,signal);if(soundRuntimeRevision()!==engineVersion)soundFail("The restoration runtime changed after review.");return {report:{schema:"hv-sound-restoration-result/1",settings,engineVersion,recipeRevision:contentHash(RESTORATION_RECIPE),inputStems,inputPeaks,tracks},peaks};
  }finally{if(!scratch.startsWith(root+sep)||realpathSync(scratch)!==scratch)soundFail("Restoration scratch files escaped their workspace.");rmSync(scratch,{recursive:true,force:true});}
}
export async function verifyRestoredTracks(originalDirectory:string,stemDirectory:string,recordDirectory:string,report:RestorationReport,frames:number,access:Access,signal?:AbortSignal):Promise<Record<Stem,number>>{
  for(const t of report.tracks){const stem=t.settings.track,values=await restorationLevels(join(originalDirectory,stem+".wav"),join(stemDirectory,stem+".wav"),join(recordDirectory,"removed",stem+".wav"),frames,false,access,signal);if(contentHash(values)!==contentHash({before:t.before,after:t.after,removed:t.removed}))soundFail("The restoration meters differ from the retained waveforms.");if(t.settings.reference){const r=t.settings.reference,path=join(recordDirectory,"reference",stem+".wav"),fd=openSync(join(originalDirectory,stem+".wav"),"r");try{const expected=Buffer.concat([soundWavHeader(r.frames),read(fd,44+r.start*6,r.frames*6)]);if(createHash("sha256").update(expected).digest("hex")!==t.referenceSha256||contentHash(await referenceLevels(path,r.frames))!==contentHash(t.referenceLevels))soundFail("The retained noise reference changed its original sample range.");}finally{closeSync(fd);}}}
  return sumRestoredStems(stemDirectory,frames,false,access,signal);
}
