import {mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync} from "node:fs";
import {join,sep} from "node:path";
import {contentHash} from "./capabilities";
import {audioPcmHash} from "./audio-delivery";
import {MAX_SOUND_SECONDS,MAX_SOUND_UPLOAD_BYTES,SOUND_RATE,SOUND_FRAME_BYTES,soundFail,soundRights,soundText,validateSoundAsset,type SoundAsset} from "../../planner/src/sound-assets";
export const SOUND_CONVERSION_RECIPE={schema:"hv-sound-conversion/1",sampleRate:48000,channels:2,encoding:"pcm_s24le",mono:"duplicate-both-channels",resampler:"swr",filterSize:64,phaseShift:10,exactRational:true,dither:"none",frames:"nearest-rational",flushPaddingFrames:128} as const;
export function soundRuntimeRevision():string{const result=Bun.spawnSync(["ffmpeg","-version"],{stdin:"ignore",stdout:"pipe",stderr:"pipe",timeout:10000});if(result.exitCode!==0||!result.stdout.toString().startsWith("ffmpeg version "))soundFail("Install the FFmpeg sound runtime before importing or mixing recordings.");return "ffmpeg-sound-"+contentHash({runtime:result.stdout.toString().replace(/\r\n/g,"\n"),recipe:SOUND_CONVERSION_RECIPE});}
/** Validate the RIFF envelope before passing any bytes to the local WAV decoder. */
export function inspectSoundWav(bytes:Buffer):{sampleRate:number;channels:number;frames:number;encoding:string;dataOffset:number;dataBytes:number}{
  if(bytes.length<44||bytes.length>MAX_SOUND_UPLOAD_BYTES||bytes.toString("ascii",0,4)!=="RIFF"||bytes.toString("ascii",8,12)!=="WAVE"||bytes.readUInt32LE(4)!==bytes.length-8)soundFail("Choose a complete little-endian WAV recording up to 128 MiB.");
  let format:Buffer|undefined,dataOffset=0,dataBytes=0,cursor=12;
  while(cursor+8<=bytes.length){const name=bytes.toString("ascii",cursor,cursor+4),length=bytes.readUInt32LE(cursor+4),start=cursor+8,end=start+length;if(end>bytes.length)soundFail("A WAV chunk exceeds the recording.");if(name==="fmt "){if(format)soundFail("A WAV must have one format header.");format=bytes.subarray(start,end);}if(name==="data"){if(dataOffset)soundFail("A WAV must have one audio data chunk.");dataOffset=start;dataBytes=length;}cursor=end+(length%2);}
  if(cursor!==bytes.length||!format||format.length<16||!dataOffset||!dataBytes)soundFail("The WAV format or audio data is incomplete.");
  let tag=format.readUInt16LE(0);const channels=format.readUInt16LE(2),sampleRate=format.readUInt32LE(4),byteRate=format.readUInt32LE(8),align=format.readUInt16LE(12),bits=format.readUInt16LE(14);
  if(tag===65534){if(format.length<40||format.readUInt16LE(16)!==22||format.readUInt16LE(18)!==bits||!format.subarray(26,40).equals(Buffer.from("000000001000800000aa00389b71","hex")))soundFail("Use a PCM or floating-point WAV with matching container and valid bit depth.");tag=format.readUInt16LE(24);}
  const encoding=tag===1?({8:"pcm_u8",16:"pcm_s16le",24:"pcm_s24le",32:"pcm_s32le"} as Record<number,string>)[bits]:tag===3?({32:"pcm_f32le",64:"pcm_f64le"} as Record<number,string>)[bits]:undefined;
  if(!encoding||![1,2].includes(channels)||sampleRate<8000||sampleRate>192000||align!==channels*bits/8||byteRate!==sampleRate*align||dataBytes%align||dataBytes/align>sampleRate*MAX_SOUND_SECONDS)soundFail("Use mono or stereo uncompressed WAV audio, 8–192 kHz, up to ten minutes.");
  if(tag===3)for(let pos=dataOffset;pos<dataOffset+dataBytes;pos+=bits/8){const sample=bits===32?bytes.readFloatLE(pos):bytes.readDoubleLE(pos);if(!Number.isFinite(sample)||Math.abs(sample)>1)soundFail("Export floating-point audio with finite samples within full scale before importing it.");}
  return {sampleRate,channels,frames:dataBytes/align,encoding,dataOffset,dataBytes};
}
export function soundWavHeader(frames:number):Buffer{if(!Number.isSafeInteger(frames)||frames<1||frames*SOUND_FRAME_BYTES>0xffffffff-36)soundFail("Invalid stereo 24-bit PCM length.");const bytes=frames*SOUND_FRAME_BYTES,h=Buffer.alloc(44);h.write("RIFF");h.writeUInt32LE(36+bytes,4);h.write("WAVEfmt ",8);h.writeUInt32LE(16,16);h.writeUInt16LE(1,20);h.writeUInt16LE(2,22);h.writeUInt32LE(SOUND_RATE,24);h.writeUInt32LE(SOUND_RATE*SOUND_FRAME_BYTES,28);h.writeUInt16LE(SOUND_FRAME_BYTES,32);h.writeUInt16LE(24,34);h.write("data",36);h.writeUInt32LE(bytes,40);return h;}
export function soundWav(pcm:Buffer):Buffer{return Buffer.concat([soundWavHeader(pcm.length/SOUND_FRAME_BYTES),pcm]);}
export function verifySoundWav(wav:Buffer,frames:number,sha256?:string):Buffer{if(wav.length!==44+frames*SOUND_FRAME_BYTES||!wav.subarray(0,44).equals(soundWavHeader(frames))||sha256&&audioPcmHash(wav)!==sha256)soundFail("The normalized sound waveform changed.");return wav.subarray(44);}
export async function soundCommand(args:string[],cwd:string,signal?:AbortSignal):Promise<void>{signal?.throwIfAborted();const child=Bun.spawn(args,{cwd,stdin:"ignore",stdout:"ignore",stderr:"pipe"});let timedOut=false;const abort=()=>child.kill("SIGKILL"),timer=setTimeout(()=>{timedOut=true;abort();},120000);signal?.addEventListener("abort",abort,{once:true});try{if(signal?.aborted)abort();const [code,error]=await Promise.all([child.exited,new Response(child.stderr).text()]);signal?.throwIfAborted();if(code!==0||timedOut)soundFail(timedOut?"Sound processing timed out.":"Sound processing failed: "+error.slice(-700));}finally{clearTimeout(timer);signal?.removeEventListener("abort",abort);}}
/** Conversion preserves the original upload separately; it does not qualify loudness or rights. */
export async function normalizeSoundUpload(original:Buffer,projectId:string,label:string,rightsInput:unknown,cwd:string,assertAccess:()=>Promise<void>,signal?:AbortSignal,now=Date.now()):Promise<{asset:SoundAsset;audio:Buffer}>{
  const rights=soundRights(rightsInput,now),name=soundText(label,"a sound label",120),metadata=inspectSoundWav(original),engineVersion=soundRuntimeRevision(),frames=Math.round(metadata.frames*SOUND_RATE/metadata.sampleRate),root=realpathSync(cwd),scratch=mkdtempSync(join(root,".sound-import-"));
  try{await assertAccess();signal?.throwIfAborted();writeFileSync(join(scratch,"original.wav"),original,{flag:"wx",mode:0o600});const filter=(metadata.channels===1?"pan=stereo|c0=c0|c1=c0,":"")+`apad=pad_len=128,aresample=48000:resampler=swr:filter_size=64:phase_shift=10:exact_rational=1:dither_method=none,atrim=end_sample=${frames}`;
    await soundCommand(["ffmpeg","-v","error","-nostdin","-max_alloc","268435456","-protocol_whitelist","file,pipe","-f","wav","-i","original.wav","-map","0:a:0","-af",filter,"-c:a","pcm_s24le","-f","s24le","audio.pcm"],scratch,signal);
    const pcm=readFileSync(join(scratch,"audio.pcm"));if(pcm.length!==frames*SOUND_FRAME_BYTES||soundRuntimeRevision()!==engineVersion)soundFail("The sound conversion runtime or sample count changed.");const audio=soundWav(pcm),{dataOffset:_offset,dataBytes:_bytes,...source}=metadata;
    const data={schema:"hv-sound-asset/1" as const,id:crypto.randomUUID(),projectId,label:name,createdAt:new Date(now).toISOString(),rights,original:{sha256:audioPcmHash(original),bytes:original.length,...source},audio:{sha256:audioPcmHash(audio),bytes:audio.length,frames},engineVersion};const asset=validateSoundAsset({...data,revision:contentHash(data)},projectId);await assertAccess();signal?.throwIfAborted();return {asset,audio};
  }finally{if(!scratch.startsWith(root+sep)||realpathSync(scratch)!==scratch)soundFail("The sound import scratch directory escaped its workspace.");rmSync(scratch,{recursive:true,force:true});}
}
