import {expect,test} from "bun:test";
import {contentHash} from "../../generator/src/capabilities";
import {applyEditOperation,editTimeline,type EditClip,type EditLane,type EditSource} from "../src/edit-timeline";
import {EditTime} from "../src/edit-time";
import {projectEditScriptNavigation} from "../src/edit-script-projection";
import {EDIT_SCRIPT_LIMITS,type EditScriptEntry,type EditScriptSourceIndex,type EditScriptWindow} from "../src/edit-script-types";

const S=1600,history=contentHash("history"),source:EditSource={id:"original",revision:contentHash("source"),label:"Original",frames:120,width:64,height:48,audio:["mix","dialogue"],captions:[],voices:[],unmeasuredAudio:false};
const clip=(id:string,lane:EditLane="picture",at=0,from=0,frames=30,layer=0):EditClip=>({id,sourceId:source.id,lane,layer,at,from,frames,link:null,gainDb:0,opacity:1,crop:null,envelope:{from,frames,fadeIn:0,fadeOut:0}});
const timeline=(clips:EditClip[],sources=[source])=>editTimeline({schema:"hv-edit-timeline/1",width:64,height:48,frames:100,sources,clips,markers:[]});
const window=(startSample:number,endSample:number,lanes:EditLane[]=["picture","mix","dialogue"]):EditScriptWindow=>({startSample,endSample,lanes,evidence:"measured-speech"});
const entry=(id:string,windows:EditScriptWindow[]):EditScriptEntry=>({id,kind:"dialogue",sceneIndex:0,startLine:3,endLine:4,text:"Welcome home.",character:"SPUD",windows});
const index=(entries:EditScriptEntry[],facts=source):EditScriptSourceIndex=>{const scriptText="INT. HOME - DAY\n\nSPUD\nWelcome home.",data={schema:"hv-edit-script-source/1" as const,sourceId:facts.id,sourceRevision:facts.revision,receiptRevision:contentHash("receipt-"+facts.id),label:facts.label,language:"en",scriptRevision:contentHash({scriptVersion:1,scriptText}),scriptText,entries,warnings:[]};return {...data,revision:contentHash(data)};};
const project=(t:ReturnType<typeof timeline>,entries:EditScriptEntry[])=>projectEditScriptNavigation("sequence",history,t,[index(entries)]);

test("script navigation keeps duplicate occurrences, sample trims/slips and independent L/J lanes without claiming picture visibility",()=>{
  const t=timeline([clip("picture","picture",5,10,20),clip("duplicate","picture",40,10,20,1),clip("j-sound","mix",2,12,20),clip("l-dialogue","dialogue",8,10,20)]),entries=[entry("line",[window(12*S+100,14*S+200)])],before=JSON.stringify({t,entries}),result=project(t,entries);
  const byId=Object.fromEntries(result.occurrences.map(o=>[o.clipId,o]));expect(result.occurrences).toHaveLength(4);expect(byId.picture).toMatchObject({startSample:7*S+100,endSample:9*S+200,startFrame:7,endFrame:10,sourceStartSample:12*S+100,sourceEndSample:14*S+200,held:false,muted:false,transition:false});expect(byId.duplicate!.startSample).toBe(42*S+100);expect(byId["j-sound"]!.startSample).toBe(2*S+100);expect(byId["l-dialogue"]!.startSample).toBe(10*S+100);expect(new Set(result.occurrences.map(o=>o.id)).size).toBe(4);
  const slipped=applyEditOperation(t,{kind:"slip",clipId:"picture",linked:false,delta:3}),mapped=project(slipped,entries).occurrences.find(o=>o.clipId==="picture")!;expect(mapped).toMatchObject({startSample:5*S,endSample:6*S+200,sourceStartSample:13*S});
  const masked=applyEditOperation(t,{kind:"composite",clipId:"picture",composite:{schema:"hv-edit-composite/1",masks:[{id:"mask",label:"Mask",kind:"rectangle",sourceRevision:source.revision,combine:"replace",invert:false,featherQ8:0,keyframes:[{sourceFrame:0,interpolation:"hold",geometry:{xQ16:0,yQ16:0,widthQ16:1,heightQ16:1}}]}]}});expect(project(masked,entries).occurrences).toEqual(result.occurrences);expect(result.warnings.join(" ")).toContain("not guaranteed visible");expect(JSON.stringify({t,entries})).toBe(before);
});

test("ramp projection matches enumerated half-open sample membership and preserves fractional original positions",()=>{
  const c={...clip("ramp","dialogue",4,20,20),timing:{from:20,offset:0,points:[{frame:0,rate:500},{frame:20,rate:2000}]}},t=timeline([c]),time=new EditTime(c),w=window(20*S+4001,20*S+16003,["dialogue"]),actual=project(t,[entry("line",[w])]).occurrences;
  const members:number[]=[];for(let at=c.at*S;at<(c.at+c.frames)*S;at++){const s=time.source(at);if(s>=w.startSample&&s<w.endSample)members.push(at);}expect(actual).toHaveLength(1);expect(actual[0]!.startSample).toBe(members[0]!);expect(actual[0]!.endSample).toBe(members.at(-1)!+1);expect(actual[0]!.sourceStartSample).toBe(time.source(members[0]!));expect(actual[0]!.sourceStartSample%1).not.toBe(0);expect(actual[0]!.sourceEndSample).toBe(w.endSample);expect(actual[0]!.held).toBe(false);
  const split=applyEditOperation(t,{kind:"split",clipId:"ramp",linked:false,at:12,rightIds:{ramp:"right"},rightLink:null}),parts=project(split,[entry("line",[w])]).occurrences;expect(parts.reduce((n,o)=>n+o.endSample-o.startSample,0)).toBe(members.length);expect(parts[0]!.startSample).toBe(members[0]!);expect(parts.at(-1)!.endSample).toBe(members.at(-1)!+1);
});

test("holds retain a single source position and mute audio only, with half-open cue edges and isolated zero-rate ramp samples",()=>{
  const hold=(id:string,lane:EditLane)=>({...clip(id,lane,10,40,30),timing:{from:40,offset:0,points:[{frame:0,rate:0},{frame:30,rate:0}]}}),t=timeline([hold("picture","picture"),hold("sound","mix")]),result=project(t,[entry("held",[window(40*S,41*S)]),entry("before",[window(39*S,40*S)]),entry("after",[window(40*S+1,41*S)])]);
  expect(result.occurrences).toHaveLength(2);for(const o of result.occurrences){expect(o).toMatchObject({entryId:"held",startSample:10*S,endSample:40*S,sourceStartSample:40*S,sourceEndSample:40*S,held:true});expect(o.muted).toBe(o.lane==="mix");}
  const c={...clip("ramp-hold","mix",0,30,30),timing:{from:30,offset:0,points:[{frame:0,rate:1000},{frame:10,rate:0},{frame:20,rate:0},{frame:30,rate:1000}]}},parts=project(timeline([c]),[entry("whole",[window(0,120*S,["mix"])])]).occurrences;
  expect(parts.map(o=>[o.startSample,o.endSample,o.held,o.muted])).toEqual([[0,10*S,false,false],[10*S,20*S+1,true,true],[20*S+1,30*S,false,false]]);expect(parts[1]!.sourceStartSample).toBe(35*S);expect(parts[1]!.sourceEndSample).toBe(35*S);
});

test("borrowed dissolve handles include picture, separate sound and linked captions while preserving duplicated evidence windows",()=>{
  const clips=(["picture","mix","captions"] as const).flatMap((lane,i)=>[{...clip("left-"+i,lane,0,10,20),link:"left"},{...clip("right-"+i,lane,20,40,20),link:"right"}]),t=applyEditOperation(timeline(clips),{kind:"crossfade",leftId:"left-0",rightId:"right-0",linked:true,frames:6,alignment:"center",ids:{"left-0":"picture-fade","left-1":"mix-fade"}}),left=window(31*S,32*S,["picture","mix","captions"]),right=window(38*S,39*S,["picture","mix","captions"]),result=project(t,[entry("left-handle",[left,left]),entry("right-handle",[right])]);
  expect(result.occurrences).toHaveLength(9);expect(new Set(result.occurrences.map(o=>o.id)).size).toBe(9);for(const o of result.occurrences){expect(o.transition).toBe(true);expect([o.startSample,o.endSample]).toEqual(o.entryId==="left-handle"?[21*S,22*S]:[18*S,19*S]);}expect(project(timeline(clips),[entry("left-handle",[left]),entry("right-handle",[right])]).occurrences).toEqual([]);
});

test("script projection is sealed and input-order deterministic and rejects altered identities, malformed evidence and UTF-8/entry/output overflow",()=>{
  const other={...source,id:"other",revision:contentHash("other"),label:"Other"},t=timeline([clip("picture"),{...clip("other-picture","picture",40,5,30,1),sourceId:other.id}],[source,other]),a=index([entry("line",[window(0,S)])]),{revision:_otherRevision,...otherData}=index([entry("line",[window(6*S,8*S)])],other),scriptText="INT. HOME - NIGHT\n\nSPUD\nWelcome home.\n\nThe porch light fades.",otherScript={...otherData,scriptText,scriptRevision:contentHash({scriptVersion:2,scriptText})},b={...otherScript,revision:contentHash(otherScript)},result=projectEditScriptNavigation("sequence",history,t,[a,b]);
  expect(projectEditScriptNavigation("sequence",history,t,[b,a])).toEqual(result);expect(result.sources.map(s=>s.scriptText)).toEqual(t.sources.map(s=>s.id===source.id?a.scriptText:b.scriptText));expect(result.sources[0]!.scriptRevision).not.toBe(result.sources[1]!.scriptRevision);expect(result.sources.every(s=>s.entries[0]!.id==="line"&&s.entries[0]!.text==="Welcome home.")).toBe(true);
  expect(result.occurrences.map(o=>[o.sourceId,o.entryId,o.clipId,o.startSample,o.endSample])).toEqual([[source.id,"line","picture",0,S],[other.id,"line","other-picture",41*S,43*S]]);expect(new Set(result.occurrences.map(o=>o.id)).size).toBe(2);const {revision,...data}=result;expect(revision).toBe(contentHash(data));expect(projectEditScriptNavigation("sequence",contentHash("next"),t,[a,b]).revision).not.toBe(revision);
  const single=timeline([clip("picture")]);for(const change of [(x:any)=>x.sourceRevision=contentHash("wrong"),(x:any)=>x.entries[0].windows[0].endSample=0,(x:any)=>x.entries[0].windows[0].startSample=.5,(x:any)=>x.entries[0].windows[0].lanes=["music"],(x:any)=>x.entries[0].windows[0].evidence="guessed",(x:any)=>x.entries.push(x.entries[0]),(x:any)=>x.job={path:"secret"},(x:any)=>x.entries[0].character=undefined]){const bad=structuredClone(a);change(bad);expect(()=>projectEditScriptNavigation("sequence",history,single,[bad])).toThrow();}
  expect(()=>projectEditScriptNavigation("sequence","stale",single,[a])).toThrow("revision");expect(()=>projectEditScriptNavigation("sequence",history,{...single,frames:99},[a])).toThrow("changed");expect(()=>projectEditScriptNavigation("sequence",history,single,[])).toThrow("every original");
  expect(()=>project(single,Array.from({length:EDIT_SCRIPT_LIMITS.entriesPerSource+1},(_,i)=>entry("e"+i,[])))).toThrow("bounded script index");const unicode=index([{...entry("large",[]),text:"界".repeat(3*1024**2)}]);expect(()=>projectEditScriptNavigation("sequence",history,single,[unicode])).toThrow("8 MiB");
  const dense=timeline(Array.from({length:256},(_,i)=>clip("clip-"+i))),many=Array.from({length:128},(_,i)=>entry("entry-"+i,[window(0,S,["picture"])]));expect(()=>project(dense,many)).toThrow("8 MiB");
});
