import {describe,expect,test} from "bun:test";
import {AMBIENCE_MIX,AMBIENCE_PRESETS,AMBIENCE_RECIPE,ambienceCues,ambienceForHeading,ambienceRights,ambienceScenes} from "../src/sound-ambience";
import {soundSession} from "../src/sound-session";
import {soundFixture} from "../../../test/fixtures/sound";

// HV-024-12: the studio's ambience beds. The catalogue is small and fixed, a scene's bed comes from
// its heading, the creator can override any scene, and the cues sit under a cut's scenes with fades
// where the bed changes.
const S=48000;
const SCRIPT=["INT. KITCHEN - DAY","Ana pours tea.","","EXT. BEACH - SUNSET","Waves.","","EXT. MOUNTAIN PASS - NIGHT","Wind howls.","","EXT. BACK GARDEN - NIGHT","Crickets.","","INT. BAR - NIGHT","Glasses clink."].join("\n");
const SHOTS=[{shotId:"shot-1-1",frames:2*S},{shotId:"shot-1-2",frames:S},{shotId:"shot-2-1",frames:4*S},{shotId:"shot-3-1",frames:2*S},{shotId:"shot-4-1",frames:2*S},{shotId:"shot-5-1",frames:3*S}];
const TOTAL=14*S;

describe("the studio's ambience catalogue", () => {
  /** Five to eight named presets, each a fixed seed and filter, none of them silence. */
  test("is a small fixed catalogue of named, seeded presets", () => {
    expect(AMBIENCE_PRESETS.map(preset=>preset.id)).toEqual(["room-tone","wind","rain","traffic","surf","crowd","night"]);
    expect(new Set(AMBIENCE_PRESETS.map(preset=>preset.seed)).size).toBe(AMBIENCE_PRESETS.length);
    for(const preset of AMBIENCE_PRESETS){expect(Number.isSafeInteger(preset.seed)).toBe(true);expect(preset.label.length).toBeGreaterThan(0);expect(preset.channel).not.toContain(";");expect(preset.trimDb).toBeLessThanOrEqual(0);}
    expect(AMBIENCE_RECIPE).toMatchObject({schema:"hv-ambience/1",sampleRate:48000,channels:2,loopFrames:20*48000});
  });

  /** Every periodic part completes whole cycles in the loop, which is what lets the seam join in phase. */
  test("every periodic part of a preset completes whole cycles in the loop", () => {
    const seconds=AMBIENCE_RECIPE.loopFrames/AMBIENCE_RECIPE.sampleRate;
    for(const preset of AMBIENCE_PRESETS){const rates=[...(preset.bed+","+(preset.tone?.filter??"")).matchAll(/tremolo=f=([0-9.]+)/g)].map(match=>Number(match[1]));if(preset.tone)rates.push(preset.tone.hz);
      for(const rate of rates)expect(Math.abs(rate*seconds-Math.round(rate*seconds))).toBeLessThan(1e-9);}
  });

  /** The rights record says the studio generated the bed, and nothing else. */
  test("a bed's rights record says the studio generated it", () => {
    const rights=ambienceRights(AMBIENCE_PRESETS[4]!);
    expect(rights).toEqual({basis:"original",attested:true,credit:"Ambience generated by the studio",source:"Generated by this studio from ambience preset surf (recipe hv-ambience/1, seed 5503)",terms:expect.stringContaining("no third-party recording, sample, vendor or model output")});
  });
});

describe("choosing a scene's bed from its heading", () => {
  /** INT is room tone; EXT … BEACH is surf; weather and busy places win; EXT … NIGHT with no telling word is night air. */
  test("the heading's INT/EXT, location words and time of day choose the bed", () => {
    const cases:[string,string][]=[
      ["INT. KITCHEN - DAY","room-tone"],["INT. OFFICE - NIGHT","room-tone"],["EXT. BEACH - DAY","surf"],["EXT. PIER - NIGHT","surf"],
      ["EXT. CITY STREET - NIGHT","traffic"],["INT. CAR - MOVING - DAY","traffic"],["INT. BAR - NIGHT","crowd"],["INT. TRAIN STATION - DAY","crowd"],
      ["EXT. STREET - NIGHT (RAIN)","rain"],["INT. ATTIC - STORMY NIGHT","rain"],["EXT. FOREST - DAY","wind"],["EXT. MOUNTAIN PASS - NIGHT","wind"],
      ["EXT. BACK GARDEN - NIGHT","night"],["EXT. BACK GARDEN - DAY","wind"],["INT./EXT. FARMHOUSE PORCH - DAY","room-tone"],["I/E. CANYON ROAD - DAY","traffic"],
      ["INT. FOREST CABIN - DAY","room-tone"],["FLASHBACK","room-tone"],["","room-tone"],
    ];
    for(const [heading,preset]of cases)expect([heading,ambienceForHeading(heading).id]).toEqual([heading,preset]);
  });

  /** Location words match whole words only: SEASIDE is not SEA, CARPET is not CAR. */
  test("location words match whole words only", () => {
    expect(ambienceForHeading("INT. CARPET SHOP - DAY").id).toBe("room-tone");
    expect(ambienceForHeading("EXT. BARN - DAY").id).toBe("wind");
  });
});

describe("a cut's scenes and their beds", () => {
  /** Consecutive shots of a scene make one span; each span gets its heading's bed. */
  test("the cut's shots become scene spans, each with its heading's bed", () => {
    expect(ambienceScenes(SCRIPT,SHOTS,TOTAL)).toEqual([
      {sceneNumber:1,heading:"INT. KITCHEN - DAY",start:0,frames:3*S,preset:"room-tone",chosenBy:"heading"},
      {sceneNumber:2,heading:"EXT. BEACH - SUNSET",start:3*S,frames:4*S,preset:"surf",chosenBy:"heading"},
      {sceneNumber:3,heading:"EXT. MOUNTAIN PASS - NIGHT",start:7*S,frames:2*S,preset:"wind",chosenBy:"heading"},
      {sceneNumber:4,heading:"EXT. BACK GARDEN - NIGHT",start:9*S,frames:2*S,preset:"night",chosenBy:"heading"},
      {sceneNumber:5,heading:"INT. BAR - NIGHT",start:11*S,frames:3*S,preset:"crowd",chosenBy:"heading"},
    ]);
  });

  /** The creator's choice for a scene replaces the heading's, "none" silences it, and other scenes keep theirs. */
  test("a creator's override replaces one scene's bed, and none silences it", () => {
    const scenes=ambienceScenes(SCRIPT,SHOTS,TOTAL,{"2":"rain","5":"none"});
    expect(scenes.map(scene=>[scene.sceneNumber,scene.preset,scene.chosenBy])).toEqual([[1,"room-tone","heading"],[2,"rain","creator"],[3,"wind","heading"],[4,"night","heading"],[5,null,"creator"]]);
  });

  /** An override naming a scene not in the cut, or a preset not in the catalogue, is refused, not ignored. */
  test("an override for an unknown scene or preset is refused", () => {
    expect(()=>ambienceScenes(SCRIPT,SHOTS,TOTAL,{"9":"rain"})).toThrow("Scene 9 is not in this cut");
    expect(()=>ambienceScenes(SCRIPT,SHOTS,TOTAL,{"2":"thunder"})).toThrow("Choose an ambience from the studio's catalogue");
    expect(()=>ambienceScenes(SCRIPT,SHOTS,TOTAL,{"0":"rain"})).toThrow("is not in this cut");
    expect(()=>ambienceScenes(SCRIPT,SHOTS,TOTAL,["rain"])).toThrow("scene numbers mapped");
  });

  /** Shots that do not add up to the cut, or do not name a scene, give one span under the first heading. */
  test("a cut whose shots cannot be read as scenes is one span under the first heading", () => {
    for(const shots of [[],SHOTS.slice(1),[{shotId:"opening",frames:TOTAL}]])
      expect(ambienceScenes(SCRIPT,shots,TOTAL)).toEqual([{sceneNumber:1,heading:"INT. KITCHEN - DAY",start:0,frames:TOTAL,preset:"room-tone",chosenBy:"heading"}]);
  });
});

describe("ambience cues under a cut", () => {
  const assets=new Map(AMBIENCE_PRESETS.map((preset,index)=>[preset.id,{id:`0000000${index}-0000-4000-8000-000000000000`,revision:String(index).repeat(64),frames:AMBIENCE_RECIPE.loopFrames}]));
  const seed="11111111-2222-4333-8444-555555555555";

  /** One looping ambience cue per run of the same bed: a second's fade at the film's ends, a quarter-second where the bed changes. */
  test("each run of a bed is one looping cue, faded at the film's ends and at scene boundaries", () => {
    const scenes=ambienceScenes(SCRIPT,SHOTS,TOTAL,{"2":"room-tone"}),cues=ambienceCues(scenes,assets,TOTAL,seed);
    expect(cues.map(cue=>[cue.assetId,cue.start,cue.frames,cue.fadeIn,cue.fadeOut])).toEqual([
      [assets.get("room-tone")!.id,0,7*S,S,S/4],[assets.get("wind")!.id,7*S,2*S,S/4,S/4],[assets.get("night")!.id,9*S,2*S,S/4,S/4],[assets.get("crowd")!.id,11*S,3*S,S/4,3*S/4],
    ]);
    for(const cue of cues)expect(cue).toMatchObject({role:"ambience",loop:true,trimIn:0,trimOut:AMBIENCE_RECIPE.loopFrames,gainDb:AMBIENCE_MIX.gainDb,duckDb:AMBIENCE_MIX.duckDb,balance:0});
    expect(new Set(cues.map(cue=>cue.id)).size).toBe(cues.length);expect(ambienceCues(scenes,assets,TOTAL,seed)).toEqual(cues);
  });

  /** A silenced scene leaves a gap; no fade is longer than a quarter of its cue. */
  test("a silenced scene leaves a gap, and short cues get short fades", () => {
    const cues=ambienceCues(ambienceScenes(SCRIPT,SHOTS,TOTAL,{"1":"none","3":"none","4":"none","5":"none"}),assets,TOTAL,seed);
    expect(cues).toHaveLength(1);expect(cues[0]).toMatchObject({start:3*S,frames:4*S,fadeIn:S/4,fadeOut:S/4});
    const short=ambienceCues([{sceneNumber:1,heading:"",start:0,frames:1000,preset:"wind",chosenBy:"heading"}],assets,1000,seed);expect(short[0]).toMatchObject({fadeIn:250,fadeOut:250});
  });

  /** The cues are a valid sound session as they stand, once their assets are bound. */
  test("the cues are accepted by the sound session as they stand", () => {
    const projectId=crypto.randomUUID(),{asset}=soundFixture(projectId,AMBIENCE_RECIPE.loopFrames),refs=new Map(AMBIENCE_PRESETS.map(preset=>[preset.id,{id:asset.id,revision:asset.revision,frames:asset.audio.frames}]));
    const cues=ambienceCues(ambienceScenes(SCRIPT,SHOTS,TOTAL),refs,TOTAL,seed).map(({assetId:_id,assetRevision:_revision,...cue})=>({...cue,asset}));
    const session=soundSession({reviewed:true,dialogueGainDb:0,narrationGainDb:0,cues},projectId,TOTAL);
    expect(session.cues.map(cue=>[cue.role,cue.start,cue.frames])).toEqual([["ambience",0,3*S],["ambience",3*S,4*S],["ambience",7*S,2*S],["ambience",9*S,2*S],["ambience",11*S,3*S]]);
  });
});
